### DISCUSSION TITLE
[paperless.auth] Login failed for user `a2epfq5ugq0u` from private IP `172.18.0.1`

### DISCUSSION THREAD

**Discussion by tomihbk** [paperless-ngx/paperless-ngx#10002] [Support] [answered]
Hi y'all,

Just finished upgrading my Postgre v13 to v17. The migration went well. I also took the opportunity to update to v2.16.1. The home page statistic page is loading infinitely : 
![image](https://github.com/user-attachments/assets/0c023f54-c05d-4a03-99ca-044b5826b7dc)

After looking at the webserver logs : 
```log
2025-05-22 19:58:14 [2025-05-22 19:58:14,249] [INFO] [paperless.auth] Login failed for user `a2epfq5ugq0u` from private IP `172.18.0.1`.
2025-05-22 19:58:14 [2025-05-22 19:58:14,254] [WARNING] [django.request] Unauthorized: /api/statistics/
2025-05-22 19:58:14 [2025-05-22 19:58:14,971] [INFO] [paperless.auth] Login failed for user `a2epfq5ugq0u` from private IP `172.18.0.1`.
2025-05-22 19:58:14 [2025-05-22 19:58:14,977] [WARNING] [django.request] Unauthorized: /api/statistics/
2025-05-22 19:58:15 [2025-05-22 19:58:15,382] [INFO] [paperless.auth] Login failed for user `a2epfq5ugq0u` from private IP `172.18.0.1`.
2025-05-22 19:58:15 [2025-05-22 19:58:15,389] [WARNING] [django.request] Unauthorized: /api/statistics/
```

Is there something I can do to resolve this ?

Thanks in advance

What my yml looks like  : 
```yml
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    volumes:
      - D:/Archive/pgdata-17:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8010:8000
    healthcheck:
      test: [ "CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - D:/Archive/data:/usr/src/paperless/data
      - D:/Archive/media:/usr/src/paperless/media
      - D:/Archive/./export:/usr/src/paperless/export
      - D:/Archive/./consume:/usr/src/paperless/consume
      - D:/Archive/Trash:/usr/src/paperless/media/trash
    environment:
      COMPOSE_PROJECT_NAME: paperless
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      # The UID and GID of the user used to run paperless in the container. Set this
      # to your UID and GID on the host so that you have write access to the
      # consumption directory.
      USERMAP_UID: 1000
      USERMAP_GID: 100
      # This will wait for 50 seconds to check new file is unused
      PAPERLESS_CONSUMER_POLLING_RETRY_COUNT: 20 # If 4 consecutive checks detect no changes to the file, it will be consumed
      PAPERLESS_CONSUMER_POLLING_DELAY: 30 # If a new file is detected, it will be checked for changes every 30 seconds
      PAPERLESS_CONSUMER_ENABLE_BARCODES: "true"
      PAPERLESS_CONSUMER_BARCODE_STRING: PATCHT
      PAPERLESS_TRASH_DIR: /usr/src/paperless/media/trash

```
