### DISCUSSION TITLE
Docker Secrets in version 15+

### DISCUSSION THREAD

**Discussion by ms-schaefer** [paperless-ngx/paperless-ngx#10051] [Support] [answered]
Hello,

I was trying to update from version 14.x to 15/16. My setup is running on a Docker stack using Docker secrets for the database credentials. The relevant parts of the Docker compose file look like this:

```
services: 
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.16
    container_name: paperless
    ...
    environment:
	  ...
      PAPERLESS_DBUSER_FILE: /run/secrets/paperless_db_user
      PAPERLESS_DBPASS_FILE: /run/secrets/paperless_db_password
      PAPERLESS_DBNAME_FILE: /run/secrets/paperless_db_name
    secrets:
      - paperless_db_user
      - paperless_db_password
      - paperless_db_name
```

I simply stopped the containers, pulled the new version and tried to restart the container. This worked fine in version 14 but failes in 15 and 16. The essential error message looks like this (after many lines of Python messages):

```
django.db.utils.OperationalError: (1045, "Access denied for user 'paperless_db_user\n'@'paperless.proxy_host' (using password: YES)")
```

Putting all the credentials into variables in the environment file of Docker works fine. But whenever I try to switch to the Docker secrets things fail. Was anything changed regarding the Docker secret support from 14 to 15 that I missed? In the [manual](https://docs.paperless-ngx.com/setup/) nothing specific is mentioned.

I can see the `\n` after the user name in the error message. Might this be a problem? For sure this is not in the secret file on my disk. The file was not touched when I tried to update the version. I even recreated the file to make sure it is clean (no line break etc. but just a single line with the username). When I plugged in the username directly to the Docker compose setup but left the password in the secret file, things still failed. So whatever causes the issues with the username might affect the password as well?

For now I can live with the `.env` approach. Still, using Docker secrets would be my prefered workflow. 

Any hint what I might have missed would be appreciated!
