### DISCUSSION TITLE
HTTPS Setup on Paperless-NGX

### DISCUSSION THREAD

**Discussion by kenrmayfield** [paperless-ngx/paperless-ngx#10108] [Support] [answered]
How would you Setup Paperless-NGX to use HTTPS?

**Comment by virtadpt** [comment]
Honestly?  I'd run certbot (probably with the --nginx switch, because that's what I use) and let it do the heavy lifting.

Unless you're asking about putting a web server in front of Paperless-NGX and setting up proxying so that this is possible?

**Comment by kenrmayfield** [comment]


**Reply by stumpylog** [reply]
If you insist on using a self-signed cert, you can try the options for SSL here: https://github.com/emmett-framework/granian?tab=readme-ov-file#options

**Comment by knebb** [comment]
If you are using your own setup you have to configure your webserver to use https://. If you are able to use your own setup you should be able to configure your webserver.

In case you use the docker  based setup there is no option to use https:// because the certificate of the answering paperless system is different from the IP address your are using. And this is only a single issue when thinking of doing this. So: with docker you do not have an option to use https:// at all.

BUT you can always install a proxy in front of your docker based paperless setup which provides certificates and https://. That is the way I have it here.
I use NGINX (based on OPNSense) who provides security and protection to my paperless instance. So I am able to access myy Paperless system even from outside of my LAN.

**Reply by kenrmayfield** [reply]
@knebb 

Thank You.

**Comment by kenrmayfield** [comment]


**Reply by gi0baro** [reply]
You don't need to. Just point Granian to the generated certificate and change the listening port.

**Comment by kenrmayfield** [comment]


**Reply by gi0baro** [reply, marked as answer]
It depends on how you run it. With compose it should be enough to mount the folder where you have your certificate and key and add the relevant env vars, eg:

```yaml
services:
  webserver:
    volumes:
      - ./ssl:/usr/src/paperless/sslconf
    environment:
      GRANIAN_SSL_CERTIFICATE: /usr/src/paperless/sslconf/cert.pem
      GRANIAN_SSL_KEYFILE: /usr/src/paperless/sslconf/key.pem
```
