### DISCUSSION TITLE
OCR Inconsistencies for 7-Digit Order Numbers (Mass Scanning Project)

### DISCUSSION THREAD

**Discussion by federicotravaini** [paperless-ngx/paperless-ngx#10166] [Support] [answered]
I'm starting a project to scan ~1 million documents. Our main challenge is searching for 7-digit order numbers (e.g., `1234567`) that often get broken by OCR: `12 3 4 5 6 7`, `1 2 3 4 5 6 7`, `123 456 7`, etc.

The canonical (no-space) `1234567` is our required search key. Trying all spacing combinations is unfeasible.

* **Wildcard Search** (query="1*2*3*4*5*6*7"): This is the logical approach for "any characters in between." However, the behavior with OCR-introduced spaces is uncertain. Even with correct query= syntax, it's not consistently matching.
* **Post-processing Script** to De-space OCR: My idea was to create a script to remove all spaces from the OCR text and append it to document content. This would allow searching `1234567 `directly. It tried but not able to do it.
* **API search**: not working as intended (might be my issue) but also not very user friendly. I would like to stick with the GUI.
* **Advanced search**: using `*1*2*3*4*5*6*7*` doesnt' work. Should it?

What are the best practices or built-in solutions for this in Paperless-ngx?

* How to robustly search for numbers with inconsistent OCR-introduced spaces?
* Are there OCRmyPDF/Tesseract configurations to prevent this spacing for numeric sequences?
* If a post-processing script is the way, how do I ensure it reliably modifies?

Any help or insights are greatly appreciated!

**Comment by federicotravaini** [comment]
Another option would be to generate a note containing the entire OCR’d PDF text with all spaces removed. Is this achievable via a post-process script, or would you recommend another approach?

**Reply by marcelbrueckner** [reply, marked as answer]
I use the post-consumption script to extract invoice data and store it in custom fields: https://paperless.sh/post-consumption/content-matching/.

Data is extracted using [organize](https://github.com/tfeldmann/organize), which allows to match PDF content with regular expressions. So if your documents always contain 7-digit order numbers, maybe with a few spaces in-between, you can easily strip them out before pushing the information back to Paperless-ngx.

Similar to the link above, a rule for your use-case could look like the following:

```yaml
rules:
  - name: "Order number"
    locations: *current_document
    filters:
      # Test this regular expression: https://regex101.com/r/bvajqQ/1
      - filecontent: '(?P<order_number>(?:\d\s*){6}\d)'
      # Remove spaces
      - python: |
          return {
            "order_number": filecontent['order_number'].replace(' ',''),
          }
    actions:
      - shell: "pngx edit {env.DOCUMENT_ID} --custom-fields 1={python.order_number}"
```
