### DISCUSSION TITLE
Documents Disappeared after update

### DISCUSSION THREAD

**Discussion by AgentRatty** [paperless-ngx/paperless-ngx#10178] [Support]
Installed PaperlessNGX at home under ubuntu, worked great. Thought I could do the same with docs at work using WSL2 using docker. Everything was peachy. Loaded a bunch of documents, created tags, etc. Performed a docker update a couple of weeks later and no documents show in web ui. I can see the documents on the HD, but queried the Postgres db directly and no documents, no tags. :-( it appears all data went poof! Meanwhile, my linux at home (same version) is going strong. The biggest difference is WSL2 vs Native Ubuntu.
At this point, the couple of hours I spent organizing are probably gone, but the docs are there. How can I get these to be reindexed?

Compose:
```yaml
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 6677:8000
    volumes:
      - /home/luis/paperless/data:/usr/src/paperless/data
      - /home/luis/paperless/dox:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/luis/paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*
  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
volumes:
  data: null
  media: null
  pgdata: null
  redisdata: null
```
...orphaned files
[2025-03-24 18:07:48,956] [WARNING] [ocrmypdf._metadata] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.

[2025-03-24 18:07:50,371] [INFO] [ocrmypdf.optimize] Image optimization did not improve the file - optimizations will not be used

[2025-03-24 18:07:51,149] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 0.97 savings: -3.6%

[2025-03-24 18:07:51,149] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.09 savings: 7.8%

[2025-03-24 18:07:51,219] [WARNING] [ocrmypdf._pipelines._common] Output file is a valid PDF, but conversion to PDF/A did not succeed (issue: No PDF/A metadata in XMP)

[2025-03-24 18:07:51,225] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2025-03-24 18:07:56,558] [INFO] [paperless.parsing.tesseract] pdftotext exited 0

[2025-03-24 18:07:56,643] [DEBUG] [paperless.consumer] Generating thumbnail for athenaIDX v7.1 EDI Toolkit Reference Guide.pdf...

[2025-03-24 18:07:56,650] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-y1zwhqjc/archive.pdf[0] /tmp/paperless/paperless-y1zwhqjc/convert.webp

[2025-03-24 18:07:57,362] [INFO] [paperless.parsing] convert exited 0

[2025-03-24 18:07:58,137] [DEBUG] [paperless.consumer] Saving record to database

[2025-03-24 18:07:58,137] [DEBUG] [paperless.consumer] Creation date from parse_date: 2020-06-01 00:00:00-07:00

[2025-03-24 18:07:59,476] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxpjby458m/athenaIDX v7.1 EDI Toolkit Reference Guide.pdf

[2025-03-24 18:07:59,483] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-y1zwhqjc

[2025-03-24 18:07:59,484] [INFO] [paperless.consumer] Document 2020-06-01 athenaIDX v7.1 EDI Toolkit Reference Guide consumption finished

[2025-03-24 18:07:59,495] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 1 created

[2025-03-24 18:08:06,595] [INFO] [paperless.tasks] Emptying trash of all expired documents

[2025-03-24 18:08:06,601] [INFO] [paperless.tasks] Deleted 0 documents from trash

[2025-03-24 18:08:07,449] [WARNING] [paperless.sanity_checker] Orphaned file in media dir: /usr/src/paperless/media/documents/originals/0000053.pdf

[2025-03-24 18:08:07,450] [WARNING] [paperless.sanity_checker] Orphaned file in media dir: /usr/src/paperless/media/documents/originals/0000094.docx
.
.
.
Apoliogies if this is a FAQ, but I did not find anything pertinent
