### DISCUSSION TITLE
Build the main branch in a docker container

### DISCUSSION THREAD

**Discussion by Tockra** [paperless-ngx/paperless-ngx#1024] [Support]
Hi Guys,

I was looking for a guide to build your main branch in a docker container, but I found nothing.
Normaly I have no problems to build project if there is a `Dockerfile` but I have/had multiple problems with paperless-ngx now and before.
I created a docker-compose file and in the same folder is the build directory which contains the git repo:
```yml
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: some-pw

  webserver:
    build: ./build
    restart: unless-stopped
    depends_on:
      - db
      - broker
    expose:
        - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      - JBIG2ENC_VERSION=latest
      - QPDF_VERSION=latest
      - PIKEPDF_VERSION=latest
      - PSYCOPG2_VERSION=latest
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db
      - VIRTUAL_HOST=<my-domain>
      - LETSENCRYPT_HOST=<my-domain>
      - LETSENCRYPT_EMAIL=<my-mail>
      - VIRTUAL_PORT=8000
      - HTTPS_METHOD=redirect
    networks:
      - proxy-tier
      - default

networks:
    proxy-tier:
        external:
            name: proxy-tier
```

Now I have 2 problems:
1. The Dockerfile of the paperless-ngx is basing on :
```dockerfile
FROM ghcr.io/paperless-ngx/paperless-ngx/builder/jbig2enc as jbig2enc-builder
FROM ghcr.io/paperless-ngx/paperless-ngx/builder/qpdf as qpdf-builder
FROM ghcr.io/paperless-ngx/paperless-ngx/builder/pikepdf as pikepdf-builder
FROM ghcr.io/paperless-ngx/paperless-ngx/builder/psycopg2 as psycopg2-builder
```
This is not perfect, because I'm building my own docker image because I don't want to trust some Dockerhub or similar repo.
But okay...

2. I get always the following error message:
![grafik](https://user-images.githubusercontent.com/1353859/170062849-7581ef48-6133-4da3-a80b-6cf890b9c0bf.png)

Hopefully somebody can help me with problem 2 ;)

T
