### DISCUSSION TITLE
HEALTHCHECK FAILING: curl: (7) Failed to connect to localhost port 8000: Connection refused

### DISCUSSION THREAD

**Discussion by Ro4cHii** [paperless-ngx/paperless-ngx#1143] [Support] [answered]
Hello everyone,

I try to setup paperless-ngx by using the following yaml in portainer (add stack):

```
services:
  broker:
    container_name: paperless-redis
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperedis:/data

  db:
    container_name: paperless-db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8124:8000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'localhost:8000']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /volume1/docker/paperlessngx/data:/usr/src/paperless/data
      - /volume1/docker/paperlessngx/media:/usr/src/paperless/media
      - /volume1/docker/paperlessngx/export:/usr/src/paperless/export
      - /volume1/docker/paperlessngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: username
      PAPERLESS_ADMIN_PASSWORD: supersecurepassword
      PAPERLESS_URL: https://pl.username.synology.me
      PAPERLESS_OCR_LANGUAGES: eng deu
      PAPERLESS_SECRET_KEY: pa6lHUuc1W8PQWdsP6wXViH1cJoKV38zj9ixRkDeTadQ0iX8O9pNdq9GVXIqH6gilf4uV18vVy5KTfLAvghbkBbZz9ZsF9g5jmx5
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_FILENAME_FORMAT: '{created_year}/{correspondent}/{title}'
      

  gotenberg:
    container_name: paperless-gotenberg
    image: gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    container_name: paperless-tika
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

However, the webserver container refuses to start giving me the following container health output:

% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 curl: (7) **Failed to connect to localhost port 8000: Connection refused**

I tried several user UIDs/GIDs (normal user, admin user, root) and also omitting PAPERLESS_URL.
When omitting the healthcheck option, the webserver container starts normally but port 8124 is unreachable.

What am I doing wrong? :(
