### DISCUSSION TITLE
mail_fetcher isn't executed automatically

### DISCUSSION THREAD

**Discussion by nosebeggar** [paperless-ngx/paperless-ngx#1258] [Support]
Hi all,

when I run mail_fetcher inside the container manually everything works absolutely fine and as expected, but the mail.log shows me that it hasn't run in 4 days and in fact there are a few mails in my inbox that should have been imported. 

The redis broker is running and the webserver has the necessary variables in the yml like this:
```
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

```

Any ideas?
