### DISCUSSION TITLE
/usr/src/paperless/data/migration_lock: Permission denied

### DISCUSSION THREAD

**Discussion by Belgadon** [paperless-ngx/paperless-ngx#1490] [Support] [answered]
Goal:
Install paperless-ngx with an folder structure outside of /docker on my Synology NAS using portainer.

I did it with this:
```
version: "3.6"
services:
  broker:
    image: redis:6.2
    restart: always
    volumes:
      - /volume1/docker/paperedis:/data

  db:
    image: postgres:14
    restart: always
    volumes:
      - /volume1/docker/paperdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - 8777:8000
    volumes:
      - /volume1/paperlessngx/data:/usr/src/paperless/data
      - /volume1/paperlessngx/documents:/usr/src/paperless/media
      - /volume1/paperlessngx/export:/usr/src/paperless/export
      - /volume1/paperlessngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: ****
      PAPERLESS_ADMIN_PASSWORD: ****
      PAPERLESS_OCR_LANGUAGE: deu+eng
volumes:
  data:
  media:
  pgdata:
  redisdata:
```

Unfortunatly the webserver restarts permanently with this error in the logs:
`/sbin/docker-prepare.sh: line 47: /usr/src/paperless/data/migration_lock: Permission denied
`

I have no idea what or even where that folder is nor what user needs access to it?

Bonus question:
I tried to add
`PAPERLESS_FILENAME_FORMAT: {title]
`but that has not worked. Is ist the {} that are wrong?

Edit:
I change the path of _data_ and _export_, because I am not very much interessted in them.
```
      - /volume1/docker/paperlessngx/data:/usr/src/paperless/data
      - /volume1/paperlessngx/media:/usr/src/paperless/media
      - /volume1/docker/paperlessngx/export:/usr/src/paperless/export
      - /volume1/paperlessngx/consume:/usr/src/paperless/consume
```
Now I get the following error:

```
?: PAPERLESS_CONSUMPTION_DIR is not writeable
	HINT: Set the permissions of 
d--------- /usr/src/paperless/consume
 to be writeable by the user running the Paperless services
```

I think I dont really get how the user from Synology, the users from Portainer and the users from paperless-ngx work together.
Is it one user, multiple users?
