### DISCUSSION TITLE
"added on" and "created on" filter does not work

### DISCUSSION THREAD

**Discussion by benderweb** [paperless-ngx/paperless-ngx#1734] [Support] [answered]
When I use these filters, documents are no longer displayed.
Based on the screenshots, some documents should be visible per filter. 
Other filters were not set at that moment and i use not both filters (added / created) at the same time.

I use Paperless 1.9.2 with mariadb on a Synology NAS. For the paperless installation, i use the existing mariadb 10.3.32 from the synology NAS. I´ve tested this with Chrome and Edge Browser with the same result.

Does the filter work for you?
Can anybody help me?

Before (without any filtering)
![image](https://user-images.githubusercontent.com/103854073/193656739-dfdd75e6-82c1-4746-b648-f7a536b267b1.png)

After use filter "added on" (standalone)
![image](https://user-images.githubusercontent.com/103854073/193656836-b5003d01-7b94-459d-bcec-ad6e1a858bf5.png)

After use filter "created on" (standalone)
![image](https://user-images.githubusercontent.com/103854073/193657015-2c940f33-4e5a-4c91-82cf-c94bfb7067c1.png)

**Comment by shamoon** [comment]
Hmm yea I cannot reproduce this but I wonder if theres something specific going on? See screenshot below I just tested the demo site (in German just in case)

<img width="478" alt="Screen Shot 2022-10-03 at 5 14 30 PM" src="https://user-images.githubusercontent.com/4887959/193707877-27e797b1-7c9d-4791-bd1d-2ef3d3b044c8.png">

**Comment by benderweb** [comment]
I have now been able to reproduce the problem.
The problem does not occur when I install the Mariadb directly via the compose file (docker-compose.mariadb.yml) - with minimal changes.

However, I am using the already existing MariaDB of the Synology NAS. The syno Maria DB has the version 10.3.32.

**With this Stack, i have the descriped problem ....**


```
version: "3.4"
services:
  redis:
    image: redis:7
    container_name: paperless-t-redis
    restart: unless-stopped
  
#  db:
#    image: docker.io/library/mariadb:10
#    container_name: paperless-t-mariadb
#    restart: unless-stopped
#    volumes:
#      - /volume1/docker/paperless_t_ngx/dbdata:/var/lib/mysql
#    environment:
#      MARIADB_HOST: paperless
#      MARIADB_DATABASE: paperless
#      MARIADB_USER: paperless
#      MARIADB_PASSWORD: paperless
#      MARIADB_ROOT_PASSWORD: paperless
#    ports:
#      - "3306:3306"
  
  webserver:
    image: paperlessngx/paperless-ngx:latest
    container_name: paperless-t-ngx
    restart: unless-stopped
    depends_on:
#      - db
      - redis
    ports:
      - 16600:8000
    volumes:
      - /volume1/docker/paperless_t_ngx/data:/usr/src/paperless/data
      - /volume1/docker/paperless_t_ngx/media:/usr/src/paperless/media
      - /volume1/docker/paperless_t_ngx/export:/usr/src/paperless/export
      - /volume1/docker/paperless_t_ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBNAME: paperless_t
      PAPERLESS_DBHOST: 192.168.***.**
      PAPERLESS_DBUSER: ***
      PAPERLESS_DBPASS: ***
      PAPERLESS_DBPORT: 3307
      USERMAP_UID: 1026
      USERMAP_GID: 101
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: ***
      PAPERLESS_ADMIN_PASSWORD: ***
      PAPERLESS_ADMIN_MAIL: paperless_admin@***.de
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_ENABLE_UPDATE_CHECK: TRUE
```



**With this Stack, i have not the descriped problem.... Why?**
```
version: "3.4"
services:
  redis:
    image: redis:7
    container_name: paperless-t-redis
    restart: unless-stopped
  
  db:
    image: docker.io/library/mariadb:10
    container_name: paperless-t-mariadb
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless_t_ngx/dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
    ports:
      - "3306:3306"
  
  webserver:
    image: paperlessngx/paperless-ngx:latest
    container_name: paperless-t-ngx
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - 16600:8000
    volumes:
      - /volume1/docker/paperless_t_ngx/data:/usr/src/paperless/data
      - /volume1/docker/paperless_t_ngx/media:/usr/src/paperless/media
      - /volume1/docker/paperless_t_ngx/export:/usr/src/paperless/export
      - /volume1/docker/paperless_t_ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBNAME: paperless_t
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBPORT: 3306
      USERMAP_UID: 1026
      USERMAP_GID: 101
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: ***
      PAPERLESS_ADMIN_PASSWORD: ***
      PAPERLESS_ADMIN_MAIL: paperless_admin@***.de
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_ENABLE_UPDATE_CHECK: TRUE
```
