### DISCUSSION TITLE
Account lost on restart

### DISCUSSION THREAD

**Discussion by ronstone2000** [paperless-ngx/paperless-ngx#1978] [General]
I'm currently assessing Paperless NGX 1.9.2. I am mostly very impressed and appreciate all the effort that goes into this project but have the following issue, which is likely my own misunderstanding.

I installed on a Pi 4 with 8GB memory using the manual docker instructions here: https://paperless-ngx.readthedocs.io/en/latest/setup.html#install-paperless-from-docker-hub

I chose to use sqlite due to resource limitations

Volumes are bound to the host:

...

    volumes:
      - /media/me/tv-cont1/paperless/data:/usr/src/paperless/data
      - /media/me/tv-cont1/paperless/media:/usr/src/paperless/media
      - /media/me/NAS/paperless_backups:/usr/src/paperless/export
      - /media/me/tv-cont1/paperless/consume:/usr/src/paperless/consume
      - /home/me/paperless-tika/scripts:/scripts
... 

After initial set-up I created an admin user, logged in and all was fine.

But if I restart the host running docker I cannot log back in. The username and password chosen during set-up are not accepted. I need to rerun `docker-compose run --rm webserver createsuperuser` to recreate the same username+password combo, and upon login, the document count is 0. I keep exports via cron, so I can recover. The only way I have found to avoid this is setting `PAPERLESS_ADMIN_USER`, `PAPERLESS_ADMIN_EMAIL`, and `PAPERLESS_ADMIN_PASSWORD`, but I don't think I should have to do that, and I'm not crazy about having the password exposed as plain text.

Any suggestions appreciated.

**Comment by shamoon** [comment]
Do you retain all docs and just lose the user? 

Have you made sure your database (whatever type) is being persisted? With out configs etc it’s hard to be too specific but sounds a bit like that

**Reply by ronstone2000** [reply]
That may be the issue. I do not have `PAPERLESS_DATA_DIR` set, but I do have the data directory mapped:

```
ls -l /media/me/tv-cont1/paperless/data/
total 81512
-rw-r--r-- 1 py py 79993622 Nov 14 10:50 classification_model.pickle
-rw-r--r-- 1 py py  3461120 Nov 14 11:43 db.sqlite3
drwxr-xr-x 2 py py     4096 Nov 14 11:43 index
drwxr-xr-x 2 py py     4096 Nov 13 08:59 log
-rw-r--r-- 1 py py        0 Nov 14 09:02 migration_lock
```

Will this not persist?

**Reply by ronstone2000** [reply]
I did not notice if docs were lost when it happened. They were missing from the UI and I ran an import based on that. And here are the env and yml settings. 

```
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
#USERMAP_UID=1000
#USERMAP_GID=1000

# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
PAPERLESS_OCR_LANGUAGES=spa

###############################################################################
# Paperless-specific settings                                                 #
###############################################################################

# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.

# This is required if you will be exposing Paperless-ngx on a public domain
# (if doing so please consider security measures such as reverse proxy)
#PAPERLESS_URL=https://paperless.example.com

# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
#PAPERLESS_SECRET_KEY=change-me

# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=America/Boston

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=eng

# Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx
#PAPERLESS_FORCE_SCRIPT_NAME=/PATHPREFIX
#PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # trailing slash required

PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=True
PAPERLESS_ENABLE_UPDATE_CHECK=True
PAPERLESS_PRE_CONSUME_SCRIPT="/scripts/pre-consume.sh"
PAPERLESS_POST_CONSUME_SCRIPT="/scripts/post-consume.sh"
PAPERLESS_CONSUMER_ENABLE_BARCODES=True
PAPERLESS_CONSUMER_RECURSIVE=True
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=True
PAPERLESS_CONSUMER_INOTIFY_DELAY=3
PAPERLESS_ADMIN_PASSWORD=xxxxxxxxxxx
PAPERLESS_ADMIN_USER=yyyyyyyyyyyyy
```

```
And here are the env settings. 
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8282:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /media/me/tv-cont1/paperless/data:/usr/src/paperless/data
      - /media/me/tv-cont1/paperless/media:/usr/src/paperless/media
      - /media/me/NAS/paperless_backups:/usr/src/paperless/export
      - /media/me/tv-cont1/paperless/consume:/usr/src/paperless/consume
      - /home/me/paperless-tika/scripts:/scripts
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998


  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  redisdata:
```
