### DISCUSSION TITLE
Enhancements to email fetcher

### DISCUSSION THREAD

**Discussion by AaronSeibert** [paperless-ngx/paperless-ngx#2022] [Feature Requests] [answered]
Not sure if this is worth merging in to the main application - but I get a lot of emails from providers that don't contain attachments, and the information I need is in the body of the email. Since paperless-ng (and I believe paperless-ngx) only archive documents, I created a container that fetches a specific folder, pulls unread emails and saves the email body as a pdf directly to the consume directory for paperless. 

Check out the source for it here:

https://github.com/AaronSeibert/paperless-imap-to-pdf

I just add to the paperless docker-compose with the following:

```
  imapfetcher:
    image: binaryitsystems/paperless-imap-to-pdf:latest
    restart: unless-stopped
    volumes:
      - /var/docker_services/paperless-ngx/consume:/output
    environment:
      IMAP_SERVER: REDACTED
      IMAP_USER: REDACTED
      IMAP_PASSWORD: REDACTED
      IMAP_FOLDER: Convert
      SAVE_DIRECTORY: /output
      PULL_FREQUENCY: 600
```
      
Then I have a rule in my provider that filters on known senders of information I want to save, and if it has an attachment it goes to a Paperless folder that's configured direclty in Paperless, and if no PDF attachments exist then it goes to the Convert folder and drops other attachments. YMMV with the last filter, it worked for me though for what I get.
