### DISCUSSION TITLE
How best to add Lua programming capability to Paperless-ngx ?

### DISCUSSION THREAD

**Discussion by nodecentral** [paperless-ngx/paperless-ngx#2034] [Support] [answered]
I have some good (albeit basic) ability with the Lua programming language and was wondering the best way in which I could make it part of my Paperless-ngx set up ?

Should I access my existing Paperless container command line, and run the relevant apt-get install commands , or should I go a little deeper and add it to the Dockerfile ? Not that I’ve ever done the latter before, but I came across this -> https://github.com/mhndev/docker-lua/blob/master/Dockerfile and wondered if it was a straightforward thing to combine that with the paperless one - > https://github.com/paperless-ngx/paperless-ngx/blob/main/Dockerfile

If I can achieve this, it’ll hopefully allow me to do my post/pre consumption scripting using  something like `#!/usr/local/bin/lua` ?

**Comment by stumpylog** [comment, marked as answer]
With custom container init commands, you can install any tool or language you'd like, so scripts can be written with Bash, Python, etc.  I don't see why Lua couldn't work.

https://paperless-ngx.readthedocs.io/en/beta/advanced_usage.html#custom-container-initialization

**Reply by nodecentral** [reply]
Thanks @stumpylog ,

I’ve never done anything like that before, but I’m hoping I can use much of what’s in the dockerfile I shared earlier ? And I can see there is a warning message too on your link - `This is an advanced functionality with which you could break functionality or lose data.`

Naming the file a specific way `custom-cont-init.d` , and place it in a mapped volume location seems straight forward, my challenge is the scripting itself…

Leveraging that earlier Lua dockerfile example, here’s my first attempt (untested) , can you tell me if I’m in the right ball park ?

````
#!/bin/bash

# build lua

wget https://www.lua.org/ftp/lua-5.1.5.tar.gz && \
tar xf lua-5.1.5.tar.gz && \
cd lua-5.1.5 && \
#./configure --prefix=/opt/apps/lua/lua-5.1.5 && \
make linux && \
ln -s /lua-5.1.5/src/lua /usr/bin/lua

# build luarocks

wget https://luarocks.github.io/luarocks/releases/luarocks-2.4.4.tar.gz && \
tar zxpf luarocks-2.4.4.tar.gz  && \
cd luarocks-2.4.4  && \
./configure --with-lua-include=/lua-5.1.5/src/ ; make bootstrap   && \
luarocks install luasocket
````

**Reply by stumpylog** [reply]
I don't think there's any need to install from source.  Both lua and luarocks are available in the Debian repos.

**Reply by nodecentral** [reply]
Thanks @stumpylog , I assumed that route would install the latest version, where as I need a specific version installed.

Other than that, having never created `custom container init commands ` before does the above look right ?

**Reply by stumpylog** [reply]
It looks like a valid Bash script to me

**Reply by nodecentral** [reply]
Hi @stumpylog 

I thought I’d give it a go, so I added the required line into my paperless Docker compose (extract below)
````
….
volumes:
      - /share/Container/paperless/data:/usr/src/paperless/data
      - /share/Container/paperless/media:/usr/src/paperless/media
      - /share/Container/paperless/export:/usr/src/paperless/export
      - /share/Container/paperless/consume:/usr/src/paperless/consume
      - /share/Container/paperless/scripts:/usr/src/paperless/scripts
      - /share/Container/paperless/scripts:/custom-cont-init.d:ro
    environment:
      PAPERLESS_REDIS: redis://redis:6379
….
````
unfortunately that didn’t seem to do anything, so I accessed the root of the container and did a few checks, which showed me the following..
````
[/] # docker exec -it paperlessngx /bin/sh
# ls
Pipfile       docker     locale     paperless       paperless_tesseract  paperless_tika  src
Pipfile.lock  documents  manage.py  paperless_mail  paperless_text       setup.cfg
# cd /
# ls
bin  boot  custom-cont-init.d  dev  etc  home  lib  lib64  media  mnt  opt  pikepdf  proc  psycopg2  qpdf  root  run  sbin  srv  sys  tmp  usr  var
# cd custom-cont-init.d
# ls -la
total 12
drwxr-xr-x 2 root root 4096 Nov 28 21:38 .
drwxr-xr-x 1 root root 4096 Nov 28 21:43 ..
-rwxr--r-- 1 root root  470 Nov 28 21:38 custom-cont-init.d
#
````
If i try and execute it from here it tells me `wget` and `make` dont exist ? So it seems I need to use specific commands ? 

By any chance do you have any examples of working `custom-cont-init.d` files i can learn from ?
