### DISCUSSION TITLE
Where to check for things breaking consumption?

### DISCUSSION THREAD

**Discussion by DeltaTangoLima** [paperless-ngx/paperless-ngx#2198] [Support] [answered]
I've had a working paperless-ngx setup for quite some time now, and have never really had much in the way of issues. But, a couple of days ago we had a power outage, which exceeded my UPS battery's capacity, and everything dropped.

Since then, my paperless-ngx has stubbornly refused to consume any new documents. I also cannot modify the tags or other metadata on any existing docs (eg. can't untag an item that was in the inbox at the time of power loss).

All perms are fine. My docker compose setup has the paperless container running everything under UID 1000, and I've confirmed I can add/delete files in all the consume and media directories from within the running container. I've even blown away the postgres database and reimported from a nightly backup, to no avail.

Turning on debug logging has turned up nothing at all. There's no useful log entries in the database container. When I check the  paperless logs as well as the tasks section in the admin interface, all signs are that it's successfully consumed and tagged the new documents.

But they never appear in the inbox, they're never moved from the consume directory, and they never appear under the media directory (last files there are the last ones that were consumed prior to the power loss).

I'm at a loss at what else to check, and have been tearing my hair out for a couple of days now. Any suggestion as to what else I can look for/at?

Thanks in advance.

**Comment by shamoon** [comment]
Odd indeed. So the new files don’t show in the database and aren’t actually moved? Both of those things should throw an error AFAIK. Not being able to untag something also makes me think of the db. The requests in the browser work fine? How about consuming via email or consume directory?

**Reply by DeltaTangoLima** [reply]
Good questions - new files introduced via mail and web browser also do not work.

I just remembered, this did happen to me once before, but it turned out the lack of UID and GID mappings were the fix (even though users, groups and perms hadn't changed).

I figured it was a layer 8 issue at the time - can't shake the feeling I'm missing something this time too.

In case it helps, here's my compose file:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /home/pi/docker/paper/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    user: "1000"
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/pi/docker/paper/backups:/backups
      - /home/pi/docker/paper/data:/usr/src/paperless/data
      - /storage/docs/paperless-ng/media:/usr/src/paperless/media
      - /home/pi/docker/paper/export:/usr/src/paperless/export
      - /home/pi/docker/paper/consume:/usr/src/paperless/consume
    environment:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DEBUG: false
      PAPERLESS_DBHOST: db
      PAPERLESS_OCR_PAGES: 0   # set to 1 if ingesting large scans, and don't want OCR run over all pages
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://[redacted_url]
      PAPERLESS_CORS_ALLOWED_HOSTS: http://192.168.254.8:8000

volumes:
  pgdata:
```

Edit: just tried completely nuking my DB container and restoring from the nightly backup that was taken *before* the power outage. No dice.

Is there any more verbose logging I can enable/access somewhere?
