### DISCUSSION TITLE
Documents missing ? Where did they go ?

### DISCUSSION THREAD

**Discussion by nodecentral** [paperless-ngx/paperless-ngx#2224] [Support] [answered]
Hi

I must admit you start to second guess yourself when you can’t find things, but I’m unable to find a load of school documents I’m sure I imported a while ago.  

I know I did not intentionally delete them , but that’s not to say i might not have done accidentally ?  
Is there an easy way I can check? I know there’s  lots of files in the log folder, (mine go up to paperless.log.19), is it a case of working through each one, or is there a consolidated view somewhere

**Comment by nodecentral** [comment]
Another thing I’ve noticed, is that the trash directory environment option (https://github.com/paperless-ngx/paperless-ngx/pull/24 ) doesn’t seem to be working (for me) - see extract of set up below.. ??
````
    volumes:
      - /share/Container/paperless/data:/usr/src/paperless/data
      - /share/Container/paperless/media:/usr/src/paperless/media
      - /share/Container/paperless/export:/usr/src/paperless/export
      - /share/Container/paperless/consume:/usr/src/paperless/consume
      - /share/Container/paperless/scripts:/usr/src/paperless/scripts
      - /share/Container/paperless/trash:/usr/src/paperless/trash
    environment:
       PAPERLESS_TRASH_DIR: /usr/src/paperless/trash/
`````
FYI - I’ve just done a couple of test deletions, and can’t seem to see anything being recorded in the logs for either paperless, paperless_db and paperless_redis ? Does that sound right ?
