### DISCUSSION TITLE
How to add allowed URLs?

### DISCUSSION THREAD

**Discussion by DimitriDR** [paperless-ngx/paperless-ngx#2317] [Support] [answered]
I tried 10 variants, always the kind of error:

`?: (corsheaders.E014) Origin 'https://paperless.domain.tld, http://localhost, localhost, paperless.domain.tld' in CORS_ALLOWED_ORIGINS should not have path`

Here my Docker-Compose:

```
webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8010:8000
    environment:
      PAPERLESS_DBHOST: db
      PAPERLESS_OCR_LANGUAGE: fra
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIME_ZONE: Europe/Paris
      PAPERLESS_URL: "https://paperless.domain.tld, http://localhost, localhost, paperless.domain.tld"
      USERMAP_GID: 100
      USERMAP_UID: 1027
    volumes:
      - /volume1/docker/paperless-ngx/core/data/:/usr/src/paperless/data
      - /volume1/docker/paperless-ngx/core/media/:/usr/src/paperless/media
      - /volume1/docker/paperless-ngx/core/export/:/usr/src/paperless/export
      - /volume1/docker/paperless-ngx/core/consume/:/usr/src/paperless/consume
    networks:
      - paperless-ngx-network
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
```

I tried without quotes, in brackets, etc. Nothings works. 
How can I achieve that??

Thanks.
