### DISCUSSION TITLE
Adding tika and gotenberg to helm chart

### DISCUSSION THREAD

**Discussion by tarioch** [paperless-ngx/paperless-ngx#2357] [Feature Requests]
What do you think about adding tika and gotenberg by default to the helm chart? Especially with the new email integration it's often needed.

At the moment I did it manually by adding this to my values

```yaml

env:
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://localhost:3000"
  PAPERLESS_TIKA_ENDPOINT: "http://localhost:9998"

additionalContainers:
  tika:
    name: "tika"
    image: "ghcr.io/paperless-ngx/tika:latest"
  gotenberg:
    name: "gotenberg"
    image: "docker.io/gotenberg/gotenberg:7.6"
```
