### DISCUSSION TITLE
Users cannot be restricted

### DISCUSSION THREAD

**Discussion by Gortosch** [paperless-ngx/paperless-ngx#2466] [Support] [answered]
Hello all,

I have installed paperless-ngx in Docker. When I create a user via Django and give it only all view permissions, it also has all modify permissions. If I don't give the user any rights at all, he can still do everything. Is this a bug or am I doing something wrong. Attached the compose file. 

```
version: "3"
services:
  paperless_broker:
    image: library/redis:7
    container_name: 'paperless_redis'
    restart: unless-stopped
    volumes:
      - paperless_redisdata:/data

  paperless_db:
    image: library/mariadb:10
    container_name: 'paperless_mariadb'
    restart: unless-stopped
    volumes:
      - paperless_dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  paperless_webserver:
    image: paperlessngx/paperless-ngx:latest
    container_name: 'paperless'
    restart: unless-stopped
    depends_on:
      - paperless_db
      - paperless_broker
    ports:
      - 8099:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      #USERMAP_UID=1000
      #USERMAP_GID=1000
      PAPERLESS_OCR_LANGUAGES: deu eng
      PAPERLESS_URL: 'https://paperless.local.xy.de'
      PAPERLESS_SECRET_KEY: ThisIsTheSecredKey
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_REDIS: redis://paperless_broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: paperless_db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBPORT: 3306

volumes:
  paperless_data:
  paperless_media:
  paperless_dbdata:
  paperless_redisdata:

networks:
  default:
    external: true
    name: nginx_proxy_default
```

Thank you very much.

Greetings
Sven
