### DISCUSSION TITLE
Docker can't connect to db

### DISCUSSION THREAD

**Discussion by andreapx** [paperless-ngx/paperless-ngx#2484] [Support]
I'm trying to install paperless-ngx with docker, but i get the error
`django.db.utils.OperationalError: (1045, "Access denied for user 'paperless'@'172.20.0.61' (using password: YES)")`
Here is my docker-compose:
````
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-ngx-redis
    restart: unless-stopped
    volumes:
      - /var/docker/paperless-ngx/redisdata:/data
    networks:
      internal_bridge:
          ipv4_address: "172.20.0.63"

  db:
    image: docker.io/library/mariadb:10
    container_name: paperless-ngx-db
    restart: unless-stopped
    volumes:
      - /var/docker/paperless-ngx/dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
    networks:
      internal_bridge:
          ipv4_address: "172.20.0.62"

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx-app
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "127.0.0.1:8004:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /var/docker/paperless-ngx/data:/usr/src/paperless/data
      - /var/docker/paperless-ngx/media:/usr/src/paperless/media
      - /var/docker/paperless-ngx/export:/usr/src/paperless/export
      - /var/docker/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
    networks:
      internal_bridge:
          ipv4_address: "172.20.0.61"

networks:
  internal_bridge:
    external: true
````
If I try to connect to the db it works
````
mysql -u paperless -h 172.20.0.62 -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
````
What could I have possibly done wrong?
Thanks!
