### DISCUSSION TITLE
docker data-dir on external mount - trouble with network (?!)

### DISCUSSION THREAD

**Discussion by lobochrome** [paperless-ngx/paperless-ngx#2500] [Support] [answered]
Hi,

I've moved my data-dir to a new mount point, since I'm running of an RPi4 CM module with limited onboard storage. 

I've configured the daemon.json file in /etc/docker accordingly and can run hello-world. However, the paperless-ngx docker compose runs into an issue where paperless-broker-1 comes up seemingly okay, but the webserver cannot reach it. In fact the webserver can't resolve anything and seems to be unable to connect to the network.

I'm using a standard docker-compose.yml:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 80:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/lobsta/docstore/incoming:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379


volumes:
  data:
  media:
  redisdata:
```

Any thoughts what could be wrong?

```
lobsta@pibox /m/r/paperless-ngx> docker compose up
[+] Running 3/3
 ⠿ Network paperless_default        Created                                                                                                                                                                                                                               0.1s
 ⠿ Container paperless-broker-1     Created                                                                                                                                                                                                                               0.1s
 ⠿ Container paperless-webserver-1  Created                                                                                                                                                                                                                               0.1s
Attaching to paperless-broker-1, paperless-webserver-1
paperless-broker-1     | 1:C 24 Jan 2023 12:08:51.882 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
paperless-broker-1     | 1:C 24 Jan 2023 12:08:51.882 # Redis version=6.0.17, bits=64, commit=00000000, modified=0, pid=1, just started
paperless-broker-1     | 1:C 24 Jan 2023 12:08:51.882 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
paperless-broker-1     | 1:M 24 Jan 2023 12:08:51.886 * Running mode=standalone, port=6379.
paperless-broker-1     | 1:M 24 Jan 2023 12:08:51.886 # Server initialized
paperless-broker-1     | 1:M 24 Jan 2023 12:08:51.886 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
paperless-broker-1     | 1:M 24 Jan 2023 12:08:51.892 * Loading RDB produced by version 6.0.17
paperless-broker-1     | 1:M 24 Jan 2023 12:08:51.892 * RDB age 827 seconds
paperless-broker-1     | 1:M 24 Jan 2023 12:08:51.892 * RDB memory usage when created 0.80 Mb
paperless-broker-1     | 1:M 24 Jan 2023 12:08:51.892 * DB loaded from disk: 0.000 seconds
paperless-broker-1     | 1:M 24 Jan 2023 12:08:51.892 * Ready to accept connections
paperless-webserver-1  | Paperless-ngx docker container starting...
paperless-webserver-1  | Installing languages...
paperless-webserver-1  | Err:1 http://deb.debian.org/debian bullseye InRelease
paperless-webserver-1  |   Temporary failure resolving 'deb.debian.org'
paperless-webserver-1  | Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
paperless-webserver-1  |   Temporary failure resolving 'deb.debian.org'
paperless-webserver-1  | Err:3 http://deb.debian.org/debian bullseye-updates InRelease
paperless-webserver-1  |   Temporary failure resolving 'deb.debian.org'
paperless-webserver-1  | Reading package lists...
paperless-webserver-1  | W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
paperless-webserver-1  | W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
paperless-webserver-1  | W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
paperless-webserver-1  | W: Some index files failed to download. They have been ignored, or old ones used instead.
paperless-webserver-1  | Package tesseract-ocr-deu already installed!
paperless-webserver-1  | Package tesseract-ocr-eng already installed!
paperless-webserver-1  | Package tesseract-ocr-jpn not found! :(
paperless-webserver-1  | Creating directory /tmp/paperless
paperless-webserver-1  | Adjusting permissions of paperless files. This may take a while.
paperless-webserver-1  | Waiting for Redis...
paperless-webserver-1  | Redis ping #0 failed.
paperless-webserver-1  | Error: Error -3 connecting to broker:6379. Temporary failure in name resolution..
paperless-webserver-1  | Waiting 5s
paperless-webserver-1  | Redis ping #1 failed.
paperless-webserver-1  | Error: Error -3 connecting to broker:6379. Temporary failure in name resolution..
paperless-webserver-1  | Waiting 5s
paperless-webserver-1  | Redis ping #2 failed.
paperless-webserver-1  | Error: Error -3 connecting to broker:6379. Temporary failure in name resolution..
paperless-webserver-1  | Waiting 5s
paperless-webserver-1  | Redis ping #3 failed.
paperless-webserver-1  | Error: Error -3 connecting to broker:6379. Temporary failure in name resolution..
paperless-webserver-1  | Waiting 5s
paperless-webserver-1  | Redis ping #4 failed.
paperless-webserver-1  | Error: Error -3 connecting to broker:6379. Temporary failure in name resolution..
paperless-webserver-1  | Waiting 5s
paperless-webserver-1  | Failed to connect to redis using environment variable PAPERLESS_REDIS.
paperless-webserver-1 exited with code 1
```
