### DISCUSSION TITLE
[Docker] Volumes vs. Mounts

### DISCUSSION THREAD

**Discussion by henfri** [paperless-ngx/paperless-ngx#2653] [Feature Requests] [answered]
Hello,

to be honest, I do not understand why docker volumes are a good concept for data that needs to be persistent. It is somewhere hidden where I don't know and I am not aware of...

I have -except for paperless- not one single container that has persistent&important data in a docker volume.

Can you explain, why this choice is made for paperless (at least according to the documentation, these volumes should be backed up)?

I.e.  in this line https://github.com/paperless-ngx/paperless-ngx/blob/bdf9b2453fcd8ef14045463bc90779f977ce5ed8/docker/compose/docker-compose.postgres-tika.yml#L45
I think it would be a lot user-friendly to have
```
    volumes:
      - ./pgdata:/var/lib/postgresql/data
```

However, I am willing to learn. Are there any dis-advantages by this?

My current docker-compose.yml looks like this:
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-id-ata-Micron_1100_MTFDDAV256TBN-part3/dockerconfig/paperless/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
#    image: jonaswinkler/paperless-ng:latest
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /srv/dev-disk-by-id-ata-Micron_1100_MTFDDAV256TBN_17501A32891E-part3/dockerconfig/paperless/data:/usr/src/paperless/data
      - /srv/dev-disk-by-label-DataPool1/Paperless/paperless_ng_media:/usr/src/paperless/media
      - /srv/dev-disk-by-label-DataPool1/Paperless/export:/usr/src/paperless/export
      - /srv/dev-disk-by-label-DataPool1/Paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:

```
I would like to update to the latest standard and would ask for your guidance.
Firstly, I think, I can remove the three, volumes here.
Then, current docker-compose.yaml uses different versions of the containers:
docker.io/library/redis:7
docker.io/library/postgres:13
image: docker.io/gotenberg/gotenberg:7.8
image: ghcr.io/paperless-ngx/tika:latest

Is it safe to just replace these, or are any steps required to upgrade?

Regards,
Hendrik

**Comment by stumpylog** [comment, marked as answer]
For most beginners to Docker, volumes are much simpler, since they are managed by Docker.  If you're a more advanced user, bind mounts will function just fine.  I use them myself as I have my own management system.

I'm not sure what image versions you're using, but it's generally fine to upgrade.  For the database at least, you should refer to the Postgres documentation for upgrades between major versions

**Comment by mjh2901** [comment]
I recommend figuring out enough about docker to use mounts and not volumes.  Most backup services will specifically skip volumes, I just got screwed by this.  With mounts the files are there for the OS to backup and copy.  While a lot of stuff we are screwing around with backup is not a big deal.  If you are going to use paperless for your actual life you need to be able to confidently practice 3-2-1 backup and doing that properly with volumes is immensely more difficult than standard mounts in the Computers file system.

**Reply by n00b12345** [reply]
> I recommend figuring out enough about docker to use mounts and not volumes.  Most backup services will specifically skip volumes, I just got screwed by this.  With mounts the files are there for the OS to backup and copy.  While a lot of stuff we are screwing around with backup is not a big deal.  If you are going to use paperless for your actual life you need to be able to confidently practice 3-2-1 backup and doing that properly with volumes is immensely more difficult than standard mounts in the Computers file system.

Thank you, that was very insightful.

**Comment by henfri** [comment]
Volumes are easy to use. But then -especially not so profficient- users will not know that they need to back them up. 
Thus, I do not thik that this is a good design choice...
@mjh2901: I agree. I know enough to use mounts and to do backups... - and in fact the paperless docker-compose.yaml use volumes anyway. So, I do not see any reason to use both here.

**Comment by henfri** [comment]
I am going to update to the latest docker-compose.yml
Now, in this one, it says:
```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
```

Before, I had no volumes here. Thus, all redis data is in the docker-container. 
Do I still need this data?

Best regards,
Hendrik

**Reply by kaechele** [reply]
Containers specify mount points within their `Dockerfile`. If you do not either mount something into the container at that location or put a named volume against it an anonymous volume will be created. You can recognize them by looking for any volumes in `docker volume ls` that simply have hashes as their names.
Those volumes are not deleted automatically when the container goes away (you could delete all the unused anonymous volumes with `docker volume prune` if you wanted). But they will also not be re-attached if the container is recreated. So if you did not have volumes for redis before the redis store would be recreated every time you recreate the container. For redis I don't think that's dramatic, but for other stuff you'd probably want to make sure your volumes are well-defined.

**Comment by kaechele** [comment]
Here's a pointer for you from the Docker documentation as to why volumes are used, and not bind mounts:
> Bind mounts have been around since the early days of Docker. Bind mounts have limited functionality compared to [volumes](https://docs.docker.com/storage/volumes/). When you use a bind mount, a file or directory on the host machine is mounted into a container. The file or directory is referenced by its absolute path on the host machine. By contrast, when you use a volume, a new directory is created within Docker’s storage directory on the host machine, and Docker manages that directory’s contents.

Source: https://docs.docker.com/storage/bind-mounts/

You can make a named volume behave like a bind mount like so:
```
volumes:
  pgdata:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/pdgata"
```

I have some of my volumes on NFS drives, for example:
```
volumes:
  pgdata:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.10,nolock,soft,rw"
      device: ":/srv/paperless/pgdata"
```

With bind mounts you would not have the flexibility to do that. You would have to manually mount the NFS directory to a local mount path and then point the bind mount to it, instead of having the Docker engine do the heavy lifting for me.
Another benefit is that you could move the data from a local directory to an NFS share and only need to update the volume definition once.
