### DISCUSSION TITLE
Can't connect to custom Database Server

### DISCUSSION THREAD

**Discussion by as149** [paperless-ngx/paperless-ngx#2656] [Support]
### Description

New Dockercompose Installation of Paperlessngx just connects to localy installed Databases.
Even I describe "PAPERLESS_DBHOST=192.168..." in docker-compose.yml the initial Installation will connect to Databases 
at localhost.

### Steps to reproduce

```yaml
version: "3.4"
networks:
  vlan3:
    external: true
    name: vlan3

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    networks:
      vlan3:
        ipv4_address: "192.168.111.21"
    volumes:
      - .../redisdata:/data

  paperless-ngx:
    container_name: paperless-ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    networks:
      vlan3:
        ipv4_address: "192.168.111.20"
    ports:
      - "8000:8000"
    hostname: paperless
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ".../data:/usr/src/paperless/data"
      - ".../media:/usr/src/paperless/media"
      - ".../export:/usr/src/paperless/export"
      - ".../consume:/usr/src/paperless/consume"
    environment:
      - USERMAP_UID=1001
      - USERMAP_GID=1000
      - PAPERLESS_OCR_LANGUAGES=deu eng
      - PAPERLESS_TIME_ZONE=Europe/Berlin
      - PAPERLESS_OCR_LANGUAGE=deu
      - PAPERLESS_REDIS=redis://192.168.111.21:6379
      - PAPERLESS_DBENGINE=mariadb
      - PAPERLESS_DBHOST=192.168.111.12
      - PAPERLESS_DBPORT=3306
      - PAPERLESS_DBNAME=paperless
      - PAPERLESS_DBUSER=paperless
      - PAPERLESS_DBPASS=paperless
```

### Webserver logs

```bash
connection = Database.connect(**conn_params)
File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 123, in Connect return Connection(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
super().__init__(*args, **kwargs2)                                                                                                                                                                                django.db.utils.OperationalError: (1045, "Access denied for user 'paperless'@'192.168.111.20' (using password: YES)")
```

### Paperless-ngx version

latest

### Host OS

linux

### Installation method

Docker - official image

### Browser

Chrome

### Other

In "paperless-ngx/docker/docker-prepare.sh" the connection Parameters are configured to localhost.
