### DISCUSSION TITLE
Default User/Pass

### DISCUSSION THREAD

**Discussion by comod** [paperless-ngx/paperless-ngx#2658] [Feature Requests] [answered]
Hi,

new to paperless. I just want to tell you, that the setup is a little bit stressful if you want to do this with portainer which should in theory everything make easier. I was forced to google around, because documentation do not cover portainer. I was able to find a config file which promise: _"This file contains everything paperless needs to run."_ - Cool - Lets Go! Everything seems to work... Login...Hmm do not know... Google again... find other people also run into this issue and someone (of you) points to the docs #7 . What in the end worked for me was to open the shell of the webserver via portainer and pick a command from https://docs.paperless-ngx.com/setup/#bare_metal
`python3 manage.py createsuperuser`

TL/DR: Why not make this easier and let the user create a user the first time when paperless is visited or create a default user root/root or admin/admin?

**Comment by shamoon** [comment, marked as answer]
Well, step 7 of the docker method is explicitly to create a superuser, I’m not convinced that’s harder than a default one that needs to be changed anyway…

Not sure where that was confusing for you, docs are always a work-in-progress of course

**Reply by comod** [reply]
For anyone  who also ran into this. This way you can configure your admin user directly in the docker-compose.yml:
  
```
webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    // ...
    environment:
      // ...
      PAPERLESS_ADMIN_USER: root
      PAPERLESS_AUTO_LOGIN_USERNAME: root
      PAPERLESS_ADMIN_PASSWORD: mypassword
```
