### DISCUSSION TITLE
Gotenburg failures

### DISCUSSION THREAD

**Discussion by smseidl** [paperless-ngx/paperless-ngx#2665] [Support] [answered]
My gotenberg instance is giving me problems over the last couple weeks.  I'm not really sure when it started as I don't process many non-pdf files.  I have upgraded to the latest instance in the docker-compose examples and am still getting the errors.  Has anyone solved this?

`msg=convert to PDF: lock long-running LibreOffice listener: start long-running LibreOffice listener: LibreOffice listener socket not available: context deadline exceeded`

```
Version: 7.8.0
-------------------------------------------------------
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook 
[SYSTEM] prometheus: collecting metrics
[SYSTEM] uno: long-running LibreOffice listener ready to start
[SYSTEM] gc: application started
[SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
[SYSTEM] api: server listening on port 3000
ERR undefined | ts=1676295476.3484282 logger=api msg=convert to PDF: lock long-running LibreOffice listener: start long-running LibreOffice listener: LibreOffice listener socket not available: context deadline exceeded trace=941aa978-f4fc-45c2-8e3a-9764772d266b remote_ip=172.19.0.7 host=gotenberg:3000 uri=/forms/libreoffice/convert method=POST path=/forms/libreoffice/convert referer= user_agent=python-requests/2.28.1 status=503 latency=10087110960 latency_human=10.08711096s bytes_in=43265 bytes_out=19 
```

```
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8002:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /mnt/paperless_export:/usr/src/paperless/export
      - /mnt/paperless_consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{document_type}/{title}"
      PAPERLESS_CONSUMER_POLLING: 90
      PAPERLESS_OCR_ROTATE_PAGES: 'true'
      PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD: 9
      PAPERLESS_DATE_ORDER: MDY
      PAPERLESS_ENABLE_UPDATE_CHECK: 1
      PAPERLESS_CONSUMER_ENABLE_BARCODES: 1
      PAPERLESS_CONSUMER_BARCODE_STRING: PATCHT

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
```
