### DISCUSSION TITLE
Integrate document translation

### DISCUSSION THREAD

**Discussion by landcraft** [paperless-ngx/paperless-ngx#269] [Feature Requests]
Wouldn't it be great to have the ability to translate a document from one language to another, by somehow using Google Translate (or another free online translation service), maybe with the OCR'd text?

**Comment by GooRoo** [comment]
Translation is my main use-case for OCR'd documents. I even bought a scanner specifically for this.

**Reply by landcraft** [reply]
but this is not built into paperless is the point. Would be great to do this within paperless

**Comment by CyberSardinha** [comment]
I get a lot of correspondence in German that isn't my main language. Even though I can read it it's quite hard and takes me a lot of time and use of a translator to get some of the words.

It would be really great if we could automate that.

My idea is having a translated tab and use a tool like Deep Translator (https://github.com/nidhaloff/deep-translator) and translate the text on the content tab.

It would really help my daily live and I'm sure of a lot of people on my situation.

**Reply by BitBeaver-182** [reply]
I'm on the same boat as you are. I was thinking to search for a text in english and if the content of the letter is in German in this case, translate it.

**Comment by MarcelRobitaille** [comment]
This would change my life. I would donate to have this implemented.

**Reply by jamess60** [reply]
+1 - Temporary job overseas so tonnes of French language invoices/crap to deal with. 
This really would be a take my wallet moment

**Comment by MarcelRobitaille** [comment]
It would be even better if it could be some privacy-respecting self-hosted translation service

**Comment by MarcelRobitaille** [comment]
What about integrating the libretranslate api? If you also self-host libretranslate, you could point paperless
at your instance

**Reply by CyberSardinha** [reply]
Maybe we can integrate it with a post consumption script.

Is there a way to get the content from the file?

**Comment by CyberSardinha** [comment]
So I did a post consumption script that translates the documents using deepl (https://www.deepl.com/).
I've tried with argos-translator that is self hosted but it doesn't seem to accept pdf files.

I just quickly posted it on Github if anyone wants to have a look: https://github.com/CyberSardinha/paperless-ngx-deppl

This script substitutes the archived files but keeps the original file so you can still refer to the original.

I'll write more instructions later.

**Comment by jamess60** [comment]
Maybe a temporary solution for Firefox users - I use this google translate powered browser extension that can do pretty performant real time web page translation. It seems to work within paperless *reasonably* well. 

https://addons.mozilla.org/en-GB/firefox/addon/traduzir-paginas-web/

**Comment by CAFxX** [comment]
If I can add one thing: even more important than the translation *per se*, it's the integration of the translated data with the search/categorization features: i.e. it is crucial for the original document (and its translation) to be retrieved also when I search for that document in a different language (e.g. if I search for "tax returns" (in English) I should get documents related to tax returns regardless of which language the original document is in).

**Comment by bjesus** [comment]
I need this feature too as I'm living abroad. Just created a very rudimentary working draft here: https://github.com/paperless-ngx/paperless-ngx/commit/4665667978d424c4ba8196690be477c77a421cbd . It's my first time working on Paperless-ngx and I gotta say everything is laid out very logically, it was pretty easy to get things working. It uses DeepL for the translations currently. One needs to set two new keys in the config:

```
PAPERLESS_TRANSLATION_TARGET=EN
PAPERLESS_DEEPL_TOKEN=***
```

Currently it will auto-translate documents to the specified target language and will let you search in the translations too. I'll do some code refactoring and fixing and then let's see if we can get this upstream.

If anyone has other ideas regarding the backend - I'd be happy to hear. Haven't tried running libretranslate locally but I guess that's also an option.

**Reply by MarcelRobitaille** [reply]
Hi @bjesus. That's really cool! Looking at the code, in only shows the translated text in the website, not on the PDF. Is that correct?

**Reply by charlesnagy** [reply]
Hi @bjesus ! You say it's rudimentary but looks pretty neat to me. :) Also covers what the majority of the commenters seem to want here. Great job and thanks! Are you planning to open a PR with this? Would be great to have this incorporated in the main branch.

**Reply by bjesus** [reply]
hey, @MarcelRobitaille  - that's correct, the OCR spits out the text but without positions, so I'm currently unable to place the translated text over the PDF.

@charlesnagy  - thanks! I'm currently a little swamped with other things but hoping to get back to this in a month or so.

**Reply by ok-kenji** [reply]
This sounds amazing! I'm a little new to paperless and wondering how to implement this? Or is it not actually out in 'the wild' yet? In any case, thanks for working on this, I'm another that would kill to have this functionality!

**Reply by charlesvestal** [reply]
This is awesome! I'd suggest starting with trying to abstract it to N backend providers, even if only DeepL is the first one; libretranslate, google translate, locally hosted whisper ai, all could be viable backends. I tried rolling this with libretranslate and post processing scripts but found it to be a little fragile. Would love to help support getting this to the main release!

**Comment by kavishdahekar** [comment]
Unfortunately it seems @bjesus 's PR was not merged https://github.com/paperless-ngx/paperless-ngx/pull/6386

An easier solution that requires no source-code changes is to write a post consume script that uses the paperless API to read the "content" of the document that's generated via OCR, then translate it and append the translation to the content itself, thus making it searchable.

I managed to get passable german to english translations using an ollama mistral model that runs locally.

If anybody's interested, drop me a response here and I'll put it up somewhere for you to replicate.

**Reply by charlesvestal** [reply]
I'd love to see it, thanks!

**Reply by kavishdahekar** [reply]
You will need the following changes:
1. To run a python post consumption script with its dependencies, we need a venv. I achieved this by extending the paperless docker image and then having docker compose build it.

```Dockerfile
# Dockerfile

# Use the official Paperless-ngx image as the base image
FROM ghcr.io/paperless-ngx/paperless-ngx:latest

# Install dependencies
RUN apt-get update && apt-get install -y jq python3-venv

# Create venv
RUN mkdir -p /usr/venvs/post_consume
RUN python3 -m venv /usr/venvs/post_consume

# Install python requirements
RUN /usr/venvs/post_consume/bin/pip install requests ollama
```

Modify your docker-compose.yaml to build this Dockerfile instead of pulling the paperless image
```yaml
# docker-compose.yaml
  webserver:
    # image: ghcr.io/paperless-ngx/paperless-ngx:latest
    build: .
    volumes:
      # add a volume pointing to the directory containing your post consumption script
      - <path to the directory containing your post consumption script>:/usr/src/scripts
```

2. Here's the `post_consume_script.py`. It's very messy, didn't get a chance to cleanup yet.

```python
#!/usr/venvs/post_consume/bin/python

import os
import requests
from ollama import chat
from ollama import Client
from ollama import ChatResponse

def debug_print(variable_name, value):
    print("*" * 100)
    print(f"{variable_name}: {value}")
    print("*" * 100)

def translate_text(text, lang_source, lang_target):
    # Set the URL for your Ollama model running on localhost
     url = "http://host.docker.internal:11434/api/generate"  # Adjust the URL if needed

     # Define the prompt you want to send
     prompt = f"Translate the following text from {lang_source} to {lang_target}:\n\n{text}"
     
     client = Client(host='http://host.docker.internal:11434')

     try:
          response = client.chat(
               model='mistral',
               messages=[
                    {
                         'role': 'user',
                         'content': prompt,
                    },
          ])

          return response.message.content
     except Exception as e:
          return "Translation failed : " + str(e)

# Paperless API details
API_URL = 'http://host.docker.internal:8777/api/documents'
DOC_ID = os.environ.get('DOCUMENT_ID')
API_TOKEN = '<your token>'

# Prepare headers and data for the PATCH request
headers = {
    'Authorization': f'Token {API_TOKEN}',
    'Content-Type': 'application/json'
}

# Fetch document
response = requests.get(f"{API_URL}/{DOC_ID}/", headers=headers)

# Modify OCR content
OCR_CONTENT = response.json()['content']

TRANSLATED_CONTENT = translate_text(OCR_CONTENT, "German", "English")
MODIFIED_CONTENT = f"{OCR_CONTENT}\n\n-----------------\n\n{TRANSLATED_CONTENT}"

# Print modified content for debugging
debug_print("Modified content", MODIFIED_CONTENT)

# Update the document's content to include the translated text
response = requests.patch(f"{API_URL}/{DOC_ID}/", headers=headers, json={'content': MODIFIED_CONTENT})

# Print response for debugging
debug_print("Response status code", response.status_code)
debug_print("Response content", response.text)
```

3. Add the following env for the webserver service `PAPERLESS_POST_CONSUME_SCRIPT=<path>/post_consume_script.py`
4. Finally, make sure you have ollama running with a model already loaded. In my case I'm using mistral.
```bash
$ curl http://127.0.0.1:11434/api/tags | jq '.models[].name'

"dolphin-mistral:v2.8"
"deepseek-r1:latest"
"mistral:latest"

```

Result looks like this:
<img width="1161" alt="image" src="https://github.com/user-attachments/assets/63bb71eb-9dc6-4e0c-95e5-ee57e5d6865d" />

**Reply by anoff** [reply]
elegant patch and great explanation, thanks Kavish!

**Reply by charlesvestal** [reply]
Coming back here to say thank you and that this works great! I may try to make a separate queue for translation so it can process multiple docs then go back and add content later, but this is a huge start. Thank you!

**Reply by charlesvestal** [reply]
I took this and implemented it slightly differently. Adding here in case it helps someone! 

1. This uses a flask app to act as a queuing agent. This way paperless can process documents and ship off the translations, and they'll come back whenever they're done. on my mac, the LLMs were so slow it would take an hour for a batch of documents to show up after scanning.
2. I moved to libretranslate for the timing issues, but the concept should work with an LLM based solution as well
3. Moved to a bash script with curl to avoid needing a Dockerfile and having to build. This way we can use the base image and don't need to build anything
4. Additional improvements:
  - Language detection - Automatically skips documents already in English
  - OCR text cleanup - Handles common OCR errors before translation
  - Volume mounts - Scripts are externally mounted, so code changes just need a service restart
  - Status endpoint - Can monitor queue size and translation stats at /status
  - Error handling - Translation failures don't break document processing

Here are the relevant files:

 
docker-compose.yml
``` yaml
# Docker Compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      - ./scripts:/usr/src/paperless/scripts
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_POST_CONSUME_SCRIPT: "/usr/src/paperless/scripts/post_consume_script.sh"

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

  translator:
    image: python:3.12-slim
    restart: unless-stopped
    depends_on:
      - broker
      - webserver
      - libretranslate
    ports:
      - "5000:5000"
    volumes:
      - ./scripts:/app
    working_dir: /app
    command: >
      sh -c "pip install flask requests redis langdetect &&
             python translator-queue.py"
    environment:
      - FLASK_ENV=production

  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    environment:
      LT_DISABLE_WEB_UI: true
      LT_LOAD_ONLY: de,en
    volumes:
      - lt_data:/app/db

volumes:
  data:
  media:
  pgdata:
  redisdata:
  lt_data:
```

scripts/post_consume_script.sh (make executable; `chmod +x scripts/post_consume_script.sh`)

``` bash
#!/bin/bash

# Get document ID from environment
DOC_ID="${DOCUMENT_ID}"

if [ -z "$DOC_ID" ]; then
    echo "Error: DOCUMENT_ID not found in environment"
    exit 1
fi

echo "****************************************************************************************************"
echo "Post-consume script starting for document: $DOC_ID"
echo "****************************************************************************************************"

# Translator service URL (will be in same Docker network)
TRANSLATOR_URL="http://translator:5000"

# Send translation request to translator service (non-blocking)
response=$(curl -s -w "%{http_code}" -X POST \
    "$TRANSLATOR_URL/translate" \
    -H "Content-Type: application/json" \
    -d "{\"document_id\": \"$DOC_ID\"}" \
    --max-time 5 \
    -o /tmp/translate_response.txt)

http_code="${response: -3}"

if [ "$http_code" = "202" ]; then
    echo "Document $DOC_ID queued for translation"
    echo "****************************************************************************************************"
    echo "Translation queued: Document $DOC_ID added to translation queue"
    echo "****************************************************************************************************"
else
    echo "Failed to queue translation: HTTP $http_code"
    cat /tmp/translate_response.txt 2>/dev/null || true
    echo "Document processing will continue without translation"
fi

echo "Post-consume script completed"
```

translator-queue.py
``` python
from flask import Flask, request, jsonify
import os, requests, sys
import traceback
import threading
import time
import redis
import json
import re
from queue import Queue
from langdetect import detect
from langdetect.lang_detect_exception import LangDetectException

app = Flask(__name__)

API_URL = "http://webserver:8000"
TOKEN   = "[your token]"
LIBRETRANSLATE_URL = "http://libretranslate:5000"

# Redis connection for job queue
redis_client = redis.Redis(host='broker', port=6379, db=0, decode_responses=True)

# In-memory queue for processing
translation_queue = Queue()
processing_stats = {"total": 0, "completed": 0, "failed": 0}

def clean_ocr_text(text):
    """Clean up common OCR errors before translation"""
    # Common OCR character substitutions
    ocr_fixes = {
        # Common character misreads
        'rn': 'm',  # rn often misread as m
        '|': 'l',   # pipe often misread as l
        
        # German-specific fixes
        'ü': 'ü', 'ä': 'ä', 'ö': 'ö', 'ß': 'ß',  # Ensure proper encoding
    }
    
    cleaned = text
    
    # Fix obvious OCR errors
    for wrong, right in ocr_fixes.items():
        cleaned = cleaned.replace(wrong, right)
    
    # Fix common quote marks
    cleaned = cleaned.replace('„', '"')  # German opening quote
    cleaned = cleaned.replace('"', '"')  # German closing quote
    
    # Smart paragraph handling for better translation
    # First clean up spaces and tabs
    cleaned = re.sub(r'[ \t]+', ' ', cleaned)
    cleaned = re.sub(r'\n[ \t]+', '\n', cleaned)  # Remove leading spaces
    cleaned = re.sub(r'[ \t]+\n', '\n', cleaned)  # Remove trailing spaces
    
    # Preserve paragraph breaks (double newlines) but merge lines within paragraphs
    paragraphs = re.split(r'\n\s*\n', cleaned)  # Split on paragraph breaks
    
    processed_paragraphs = []
    for paragraph in paragraphs:
        if paragraph.strip():
            # Within each paragraph, merge lines that don't end with sentence terminators
            lines = paragraph.strip().split('\n')
            merged_paragraph = []
            current_sentence = ""
            
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                    
                if current_sentence:
                    # Check if previous line ended with sentence terminator
                    if current_sentence[-1] in '.!?:':
                        merged_paragraph.append(current_sentence)
                        current_sentence = line
                    else:
                        # Merge with previous line
                        current_sentence += " " + line
                else:
                    current_sentence = line
            
            # Add the last sentence
            if current_sentence:
                merged_paragraph.append(current_sentence)
                
            processed_paragraphs.append('\n'.join(merged_paragraph))
    
    cleaned = '\n\n'.join(processed_paragraphs)
    
    # Fix common word boundaries
    cleaned = re.sub(r'(\w)([A-Z])', r'\1 \2', cleaned)  # Add space before caps
    
    return cleaned.strip()

def process_translation_job(doc_id):
    """Process a single translation job"""
    print(f"[translator] Processing translation for document {doc_id}", flush=True)
    try:
        # Fetch OCR text
        r = requests.get(
            f"{API_URL}/api/documents/{doc_id}/",
            headers={"Authorization": f"Token {TOKEN}"}
        )
        r.raise_for_status()
        text = r.json().get("content", "")
        
        if not text.strip():
            print(f"[translator] No content found for document {doc_id}", flush=True)
            return
            
        # Clean up common OCR errors before translation
        cleaned_text = clean_ocr_text(text)
        
        # Detect language - skip translation if already English
        try:
            detected_lang = detect(cleaned_text)
            print(f"[translator] Detected language: {detected_lang} for document {doc_id}", flush=True)
            
            if detected_lang == 'en':
                print(f"[translator] Document {doc_id} is already in English, skipping translation", flush=True)
                processing_stats["completed"] += 1
                return
                
        except LangDetectException as e:
            print(f"[translator] Language detection failed for document {doc_id}: {e}, proceeding with translation", flush=True)
        
        # Request translation from LibreTranslate
        resp = requests.post(
            f"{LIBRETRANSLATE_URL}/translate",
            json={
                "q": cleaned_text,
                "source": "de",
                "target": "en",
                "format": "text"
            },
            timeout=60  # LibreTranslate is much faster
        )
        resp.raise_for_status()
        translation = resp.json().get("translatedText", "")
        
        # Patch back to Paperless
        new_content = f"{text}\n\n-----------------\n\n{translation}"
        patch = requests.patch(
            f"{API_URL}/api/documents/{doc_id}/",
            headers={"Authorization": f"Token {TOKEN}"},
            json={"content": new_content}
        )
        patch.raise_for_status()
        
        processing_stats["completed"] += 1
        print(f"[translator] Successfully translated document {doc_id}", flush=True)
        
    except Exception as e:
        processing_stats["failed"] += 1
        print(f"[translator] Error translating document {doc_id}: {str(e)}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)

def queue_worker():
    """Background worker that processes translation jobs serially"""
    print("[translator] Queue worker started", flush=True)
    while True:
        try:
            # Get job from queue (blocks until available)
            doc_id = translation_queue.get(timeout=1)
            process_translation_job(doc_id)
            translation_queue.task_done()
        except:
            # Timeout or other error, continue
            time.sleep(0.1)

# Start background worker thread
worker_thread = threading.Thread(target=queue_worker, daemon=True)
worker_thread.start()

@app.route("/", methods=["GET"])
def health():
    return "OK", 200

@app.route("/status", methods=["GET"])
def status():
    """Return queue status"""
    return jsonify({
        "queue_size": translation_queue.qsize(),
        "stats": processing_stats
    })

@app.route("/translate", methods=["POST"])
def queue_translation():
    """Queue a translation job (non-blocking)"""
    print("[translator] /translate endpoint hit", flush=True)
    try:
        data = request.json
        if not data or "document_id" not in data:
            return "Missing document_id", 400
            
        doc_id = data["document_id"]
        
        # Add to queue
        translation_queue.put(doc_id)
        processing_stats["total"] += 1
        
        print(f"[translator] Queued translation for document {doc_id}", flush=True)
        return jsonify({"status": "queued", "document_id": doc_id}), 202
        
    except Exception as e:
        print("[translator] Error in queue_translation:", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return str(e), 500

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
```
