### DISCUSSION TITLE
Paperless NGX - Import Office Dokumente - Error while converting document to PDF: 503 Server Error

### DISCUSSION THREAD

**Discussion by mdangst** [paperless-ngx/paperless-ngx#2753] [Support]
### Description

It does not work with any gotenberg version as shown in the list below:

7
7.4
7.6
7.7.2

Paperless example.docx
Error while converting document to PDF: ![503 Server Error](https://user-images.githubusercontent.com/118683900/221372954-1eacd624-b875-442e-98d5-66fc2e51a0d1.PNG) Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert#/forms/libreoffice/convert

### Steps to reproduce

1. Upload MS Word document (.docx)
2. After a while the error message is triggered

### Webserver logs

```bash
[2023-02-25 19:06:55,007] [INFO] [paperless.tasks] Saving updated classifier model to /usr/src/paperless/data/classification_model.pickle...

[2023-02-25 19:07:22,054] [INFO] [paperless.consumer] Consuming Paperless example.docx

[2023-02-25 19:07:22,288] [DEBUG] [paperless.consumer] Detected mime type: application/vnd.openxmlformats-officedocument.wordprocessingml.document

[2023-02-25 19:07:22,430] [DEBUG] [paperless.consumer] Parser: TikaDocumentParser

[2023-02-25 19:07:22,436] [DEBUG] [paperless.consumer] Parsing Paperless example.docx...

[2023-02-25 19:07:22,437] [INFO] [paperless.parsing.tika] Sending /tmp/paperless/paperless-ngxbfu5ec42/Paperless example.docx to Tika server

[2023-02-25 19:07:30,135] [WARNING] [paperless.parsing.tika] Unable to extract date for document /tmp/paperless/paperless-ngxbfu5ec42/Paperless example.docx: 'Creation-Date'

[2023-02-25 19:07:30,136] [INFO] [paperless.parsing.tika] Converting /tmp/paperless/paperless-ngxbfu5ec42/Paperless example.docx to PDF as /tmp/paperless/paperless-t6ryhpl2/convert.pdf

[2023-02-25 19:08:01,251] [DEBUG] [paperless.parsing.tika] Deleting directory /tmp/paperless/paperless-t6ryhpl2

[2023-02-25 19:08:02,168] [ERROR] [paperless.consumer] Error while consuming document Paperless example.docx: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert#/forms/libreoffice/convert

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 111, in convert_to_pdf

    response.raise_for_status()  # ensure we notice bad responses

  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert#/forms/libreoffice/convert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 385, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 82, in parse

    self.archive_path = self.convert_to_pdf(document_path, file_name)

  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 113, in convert_to_pdf

    raise ParseError(

documents.parsers.ParseError: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert#/forms/libreoffice/convert
```

### Paperless-ngx version

1.13.0

### Host OS

DSM 7.1.1-42962 Update 4 (Synology DS420+)

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Please have a look through existing issues before opening a new one, this does work in general but setup can be a little finicky
https://github.com/paperless-ngx/paperless-ngx/search?q=Service+Unavailable+for+url&type=discussions
https://github.com/paperless-ngx/paperless-ngx/search?q=Service+Unavailable+for+url&type=issues

**Comment by JamieHeather** [comment]
I'm also having the same issue with basically the same setup as OP: none of the proposals in the recent issues fixed it, nor did any combination that I could find.

**Comment by shamoon** [comment]
Gotenberg is completely separate software, of course we use it here but if you think you’ve found a bug or a document that won’t process with it perhaps searching / opening an issue there would be helpful, but again, don’t think this is broken generally and don’t think on the -ngx side of things

If you do figure it out please post back any resolution, indeed it seems the cause can vary

**Comment by denispol** [comment]
I am running gotenberg:7.8 and can confirm that this is also happening, in my case with different file formats (.xls or .doc for instance)

**Reply by CamelT0E** [reply]
same here

**Comment by titro** [comment]
same here. some documents are fine, others not. having trouble with one .eml which is pulled from my gmail inbox. others are fine

i saw in gotenberg logs

```gotenberg convert to pdf: chromium pdf: print to pdf: context deadline exceeded```
i added as a gotenberg command in my compose:

```      - "--api-timeout=400s"```

now it's fine :-)

**Reply by fergbrain** [reply]
This solved my issue as well.

**Reply by Triarii1** [reply]
This fixed it!. Was driving me insane. Cheers mate

**Comment by CamelT0E** [comment]
There are always problems with gotenberg versions.
The latest versions are not running on my Synology DiskStation.

Versions that work:
7.4, 7.8.0, 7.8.1

Versions with problems:
latest, 7.5, 7.6, 7.7, 7.8, 7.8.2, 7.8.3

I find it problematic that the version 7.8 is specified in the compose-file. This can trigger the proven error 503 for a current installation. I test every version! The latest version for me is 7.8.1 on Synology Diskstation. I hope it helps other users.

**Comment by hannibal85** [comment]
I'm also on Synology (DSM7.1) and still have this Bug.. Even with above mentioned measures like increasing timeouts.
I was on 7.8.2 and downgraded today to 7.8.1. Unfortunately no luck. At least with the 2 test files I tried up to now. Sometimes I have the feeling it is just luck if it is working or not

**Comment by CamelT0E** [comment]
according to which instructions did you install paperless?
Did you restart the DS?
I am currently using the gotenberg:latest (7.8.3). 
Works without problems now.

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/59985723/f398b8f8-acf3-48b5-994c-96bc4eda2eda)

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/59985723/c1d282fe-fb89-4597-9886-ae71033b26d7)

**Comment by hannibal85** [comment]
I installed according the official docker-compose template
[docker/compose/docker-compose.postgres-tika.yml](https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml)

But modified the compose file a little bit according my needs (different logger etc.)

**Comment by Vyerni** [comment]
I've done clean brand new installs and still face this issue. Can't seem to solve it at all

**Comment by alex-schmitt** [comment]
I was getting this issue too.  I found that it was because the Synology NAS doesn't have enough resources to process the gotenberg request within the default 30s timeout. You can increase the time out, I set mine to 5 minutes.

https://gotenberg.dev/docs/troubleshooting#timeouts-chromium
https://gotenberg.dev/docs/configuration#api

example:
~~~
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--api-timeout=300s"
~~~

**Comment by tradexsrl** [comment]
for future users: i have solved reading the gotenberg documentation by passing these parameters:
enviroment:
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/
command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
      - "--chromium-restart-after=5"
      - "--chromium-auto-start=true"
      - "--libreoffice-disable-routes=false"
      - "--libreoffice-auto-start=true"
      - "--libreoffice-restart-after=5"
      - "--chromium-ignore-certificate-errors=true"
      - "--chromium-disable-web-security=true"
      - "--chromium-allow-insecure-localhost=true"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--chromium-start-timeout=30s"
      - "--api-timeout=600s"

The most important are: 
- "--libreoffice-disable-routes=false"
-  - "--api-timeout=600s"

the endpoint in enviroment section is the correct one and not the one found in other discussion (PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/forms/libreoffice/convert#)

**Reply by Limerick-gh** [reply]
This helped to get Gotenberg back working in my environment, too!
Thanks for sharing @tradexsrl!!

**Reply by Vyerni** [reply]
I still unfortunately couldn't get it to work. 

Any chance you could post your entire compose file so I can spin up another instance on the Synology to see if maybe just somewhere I've done something wrong?

**Reply by hannibal85** [reply]
I also tried most of the above mentioned settings (esp. the long timeout) on different Gotenberg versions and never could get it working.
Then I moved the exact some setup (same docker-compose and same mounts) from my Synology to an ubuntu server VM and everything works like a charm. So for my understanding the issue seems Synology related even I have no clue if it is the weaker hardware or something in the Synology software stack.

**Reply by tradexsrl** [reply]
What type of symbology do you have?
My docker installation runs on an rs2421rp+ with 16gb of ram ands latest dsm version but even before with just 4gb of ram works with no problem and on the same nas I have 25 containers running with a total of 3-4 gb of ram used.
Problem was the endpoint that in many blog post on internet were not the correct one
Can you post the entire portainer configuration?
Maybe is just a problem of docker networking that do not see the gotenberg container or this container are not able to go to internet

**Reply by hannibal85** [reply]
I had it running on a Synology DS916+. Means 8GB memory and Intel N3710 4core CPU. Normally approx. 6GB of memory where used.
Relevant part of the config that works now on my VM:

```yaml
paperless:
    container_name: paperless
    image: "ghcr.io/paperless-ngx/paperless-ngx:2.4.2"
    [...]
    environment:
      [...]
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

gotenberg:
    container_name: paperless_gotenberg
    image: "gotenberg/gotenberg:7.10.2"
    [...]
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

tika:
    container_name: paperless_tika
    image: "ghcr.io/paperless-ngx/tika:2.9.0-minimal"
    [...]
```

Note: I removed all the timeout tweaks after migration as it was not needed on the VM

**Reply by tradexsrl** [reply]
mine is like this:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx
    container_name: paperlessNGX
[....]
    environment:
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TASK_WORKERS: 2

  gotenberg:
    image: gotenberg/gotenberg
    restart: always
    container_name: PaperlessNGX-GOTENBERG
    ports:
      - 3000:3000

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
      - "--chromium-restart-after=5"
      - "--chromium-auto-start=true"
      - "--libreoffice-disable-routes=false"
      - "--libreoffice-auto-start=true"
      - "--libreoffice-restart-after=5"
      - "--chromium-ignore-certificate-errors=true"
      - "--chromium-disable-web-security=true"
      - "--chromium-allow-insecure-localhost=true"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--chromium-start-timeout=30s"
      - "--api-timeout=600s"


  tika:
    image: ghcr.io/paperless-ngx/tika
    container_name: PaperlessNGX-TIKA
    ports:
      - 9998:9998
    restart: always

**Comment by Vyerni** [comment]
> What type of symbology do you have? My docker installation runs on an rs2421rp+ with 16gb of ram ands latest dsm version but even before with just 4gb of ram works with no problem and on the same nas I have 25 containers running with a total of 3-4 gb of ram used. Problem was the endpoint that in many blog post on internet were not the correct one Can you post the entire portainer configuration? Maybe is just a problem of docker networking that do not see the gotenberg container or this container are not able to go to internet

Ahh, see that could be it. I've noticed the same thing, that reverting the exact same config to a beefier VM, it works a treat, but once it's attached to my Synology DS420+, it fails.

**Reply by tradexsrl** [reply]
i saw the cpu is an intel celeron and have 2gb or ram standard. if you do not expand the ram i think it doesn't work
at home i have the same nas but i have expanded to the maximum the ram and added an ssd cache and it works

**Comment by Spoker** [comment]
After trying about every option I found in this thread (and others) I said 'f*** it' and just went for gotenberg:latest (now 8.2.1) and the options below, and guess what. It worked! Running on a synology ds918+ with 8GB of ram.
I don't know if it will stay this way, but I'm pretty happy right now.

```
command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--libreoffice-disable-routes=false"
      - "--api-timeout=300s"
```

**Reply by Vyerni** [reply]
Oddly similar. After seeing your post, went through and re-confirmed everything in my compose file, made it as is here, and it DIDNT work. 

However, I just checked that instance now, and noticed it has been consuming Office files. I definitely haven't made any config changes since, nor do I believe anything else has changed. 

So i'll currently take it as a win, until it breaks again

**Comment by Ambrotos** [comment]
I know it's been a few months, but for anyone still struggling with this issue I may have a solution. Initially I tried many of the suggestions above with no success. Eventually, I noticed that upon consuming a new .docx the gotenberg container's CPU utilization would spike for 20 seconds before receiving the 503 unavailable error we're all complaining about. I noticed in the gotenberg documentation that 20 seconds happens to be gotenberg's default LibreOffice startup timeout. So I was finally able to fix this problem on my setup (running on a Synology DS1821+) by adding the following two additional commands to the gotenberg service in my compose.yaml file:
```
      - "--libreoffice-auto-start=true"
      - "--libreoffice-start-timeout=300s"
```

**Reply by grosejon** [reply]
Mind posting your compose file? I'm also on a DS but cannot seem to get it to process anything. I would love to see what your setup looks like.

**Comment by schnillerman** [comment]
This seems to work for me on a DS918+, Gotenberg 8.7:

```
gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    container_name: cloud-paperless-ngx-gotenberg
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      #added according to https://github.com/paperless-ngx/paperless-ngx/discussions/2753#discussioncomment-7748479 and https://github.com/paperless-ngx/paperless-ngx/discussions/2753#discussioncomment-8404513:
      #- "--chromium-disable-routes=true"
      #- "--chromium-restart-after=5"
      #- "--chromium-auto-start=true"
      #- "--libreoffice-disable-routes=false"
      - "--libreoffice-auto-start=true"
      - "--libreoffice-start-timeout=300s"
      - "--libreoffice-restart-after=5"
      #- "--chromium-ignore-certificate-errors=true"
      #- "--chromium-disable-web-security=true"
      #- "--chromium-allow-insecure-localhost=true"
      - "--chromium-start-timeout=30s"
      - "--api-timeout=300s"
```

The `--libreoffice-restart-after=5` seems to be important, too.
