### DISCUSSION TITLE
Paperless 1.13 does not recognize barcodes

### DISCUSSION THREAD

**Discussion by torbengb** [paperless-ngx/paperless-ngx#2766] [Support] [answered]
I'm running Paperless-ngx v1.13 and I want to try out the [clever use of barcodes as described in this pull request](https://github.com/paperless-ngx/paperless-ngx/pull/2554). However, I can't even get the basic barcode recognition to work. How can I troubleshoot this?

**What I have:**
- Paperless-ngx v1.13,
- running on Docker on Linux,
- `docker-compose.yml` contains the `environment` parameters `PAPERLESS_CONSUMER_ENABLE_BARCODES: 1` and `PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: 1`,
- scanning at 300dpi using a Brother ADS-1700W.

**Testing:**
My simple testing fails with the standard PATCHT separator page, using [this testing file](https://github.com/paperless-ngx/paperless-ngx/blob/main/src/documents/tests/samples/barcodes/patch-code-t-middle.pdf). 
- ACTUAL: Paperless saves it as one multi-page document with the separator page in the middle. 
- EXPECTED: Paperless should save two single-page documents, and the PATCHT separator page is not saved.

**Comment by mtettke123** [comment]
really strange. Just tested, works in my docker install, but I get:
![grafik](https://user-images.githubusercontent.com/82048170/221597351-dc2d7814-4243-47ad-8fb4-946713f49727.png)

edit: Could you paste or send your complete compose-file?

**Reply by les-les** [reply]
with the testfile [Link to Testfile ](https://github.com/paperless-ngx/paperless-ngx/blob/main/src/documents/tests/samples/barcodes/patch-code-t-middle.pdf)

i got the 1st page working and the rest got rejected cuz marked as a duplicate 

error: message: 
patch-code-t-middle_document_0.pdf: Not consuming patch-code-t-middle_document_0.pdf: It is a duplicate of patch-code-t-middle_document_1 (#271)

**Comment by torbengb** [comment]
My `docker-compose.env` does not contain anything, so it is omitted.
Here is my `docker-compose.yml`:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - /home/hunter/docker/paperless/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: (secret)
      POSTGRES_USER: (secret)
      POSTGRES_PASSWORD: (secret)

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8019:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/hunter/docker/paperless/data:/usr/src/paperless/data
      - /home/hunter/docker/paperless/media:/usr/src/paperless/media
      - /home/hunter/docker/paperless/export:/usr/src/paperless/export
      - /home/hunter/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_ENABLE_BARCODES: 1
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: 1

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.6
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
```
