### DISCUSSION TITLE
[DOCKER/Portainer] - NFS for both media and consume volumes

### DISCUSSION THREAD

**Discussion by bTYUw1z3GJ** [paperless-ngx/paperless-ngx#2952] [Support] [answered]
I am somewhat new to docker, portainer, (and paperless-ngx for that matter), but have enough knowledge to be able to pick it up pretty quickly now that I am getting into it. So far, it is somewhat straightforward and I do have a portainer stack running paperless perfectly and have learned a bunch about the workflow and features of paperless. 

Now, I'd like to move to a more production environment and want to tweak a few settings. I'd like to continue to use volumes (as opposed to bind mounts), but am unsure of the syntax and methods of mapping an NFS share as a volume. 

I'd like to have both the consume volume and the media volume pointed to an NFS share (two different shares, of course). 

I came across another post referencing using an NFS for the pgdata volume, like so:

```
volumes:
  pgdata:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.10,nolock,soft,rw"
      device: ":/srv/paperless/pgdata"
``` 
I understand this for the most part, but unsure where in my portainer docker compose I should reference this. Would it go inline under the webserver, or at the bottom under volumes. 

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
      USERMAP_UID: 1000
      USERMAP_GID: 100
# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
      #PAPERLESS_OCR_LANGUAGES: tur ces
# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
      #PAPERLESS_SECRET_KEY: change-me
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
      #PAPERLESS_TIME_ZONE: America/Los_Angeles
# The default language to use for OCR. Set this to the language most of your
# documents are written in.
      #PAPERLESS_OCR_LANGUAGE: eng

volumes:
  data:
  media:
  pgdata:
  redisdata:
``` 

Or should I take care of this by way of the Portainer Container Advance Container Settings --> Volumes?

**Comment by stumpylog** [comment]
You would add the options where the volumes are defined, the `volumes:` key.  I'm not sure about Portainer and it's own settings or options

**Comment by bTYUw1z3GJ** [comment, marked as answer]
Using Portainer's in-built volume mapping through the GUI was a bit elusive (in terms of making it actually work). 

However, I was able to figure out exactly how to use the docker compose file in Portainer to get it working. I was way overthinking it simply due to lack of much experience using volume mapping like this. 

Here is what I had to do. Works great. 

```
volumes:
  data:
  media:
     name: media
     driver_opts:
        type: nfs
        o: addr=192.168.10.11,rw,nolock,soft
        device: :/paperless-media
  pgdata:
  consume:
     name: consume
     driver_opts:
        type: nfs
        o: addr=192.168.10.11,rw,nolock,soft
        device: :/Scans/Personal
  redisdata:
``` 

Then, for the webserver mapping:

```
webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
```
