### DISCUSSION TITLE
Paperless on RaspberryPi, Documents on SynologyNAS

### DISCUSSION THREAD

**Discussion by elbruti** [paperless-ngx/paperless-ngx#2961] [General]
I have a general question: I would like to use Paperless-ngx in our office with three employees. Unfortunately, we have a SynologyNAS which is not capable of visualization, meaning it does not support Docker. Therefore, installation is not possible on this device. My idea was to install Paperless-ngx using Portainer on my Raspberry Pi 4 (4GB) located in the network. However, the PDFs to be managed, or rather the Paperless database, should be located on the SynologyNAS. So, the Pi should only host the Paperless server. Is this possible? What do I need to consider? I look forward to your feedback.

**Comment by Ben-Bitdiddle-DE** [comment]
This could be straightforward. Install Paperless dockerized on the RPI and make the relevant paths from the NAS available via SMB or NFS (so mount these NAS drives into your RPI). Paperless paths can be configured/directed to use these.

DB performance via NAS/SMB could be an issue (DB file access over network), for the PDFs (transfer to paperless for OCR/indexing and for storage/retrieval onto/from archive) this might also hold, but normally you will not access these files too often.

I have some huge PDFs (>100MB), there is some noticeable delay in the webfrontend while working with such documents, though having them on a local drive; over network this will be even worse.

**Reply by elbruti** [reply]
Thank you for your quick response. I changed the paths in the Docker Compose for Portainer and added an NFS path. Unfortunately, I can't run the stack now and I'm getting an error message. NFS access is set up on the NAS. I checked the permissions using an SSH command and it seems I have access. Can you send me the text from your Compose file?

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /volume1/docker/paperless-ngx/export:/usr/scr/paperless/export
      - /volume1/docker/paperless-ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_SECRET_KEY: secret
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: passwort
      PAPERLESS_OCR_LANGUAGE: deu

      USERMAP_UID: 0
      USERMAP_GID: 0

volumes:
  data:
  media:
     name: media
     driver_opts:
        type: nfs
        o: addr=192.168.198.68,rw,nolock,soft
        device: :/paperless-media
  pgdata:
  consume:
     name: consume
     driver_opts:
        type: nfs
        o: addr=192.168.198.68,rw,nolock,soft
        device: :/import
  redisdata:
```

**Reply by Ben-Bitdiddle-DE** [reply]
I don't use NFS shares, all my drives are local (RPi as file server), but they are nevertheless mounted locally as logical LVM drives. I'm not sure if this compose-file-NFS-mount is supposed to work; I would have mounted the directories outside docker and just used them inside as local dirs. So you can also double-check the correct permissions outside paperless.

**Reply by Ben-Bitdiddle-DE** [reply]
As far I can see my compose file looks quite the same beside that, beside that I use SQLite instead of PostgreSQL.

**Reply by elbruti** [reply]
This version is working right now :)

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_SECRET_KEY: secret
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: passwort
      PAPERLESS_OCR_LANGUAGE: deu
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
      USERMAP_UID: 0
      USERMAP_GID: 0
# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
      #PAPERLESS_OCR_LANGUAGES: tur ces
# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
      #PAPERLESS_SECRET_KEY: change-me
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
      #PAPERLESS_TIME_ZONE: America/Los_Angeles
# The default language to use for OCR. Set this to the language most of your
# documents are written in.
      #PAPERLESS_OCR_LANGUAGE: eng

volumes:
  data:
  media:
     name: media
     driver_opts:
        type: nfs
        o: addr=192.168.198.68,rw,nolock,soft
        device: :/volume1/portainer_nfs/paperless/media
  pgdata:
  consume:
     name: consume
     driver_opts:
        type: nfs
        o: addr=192.168.198.68,rw,nolock,soft
        device: :/volume1/portainer_nfs/paperless/import
  redisdata:
```
