### DISCUSSION TITLE
User interface for gotenberg to convert/create pdfs

### DISCUSSION THREAD

**Discussion by nodecentral** [paperless-ngx/paperless-ngx#2996] [Support]
Hi

I came across the follow container on GitHub, which looked like it could be a good addition to my Paperless-ngx stack; but so far I’ve been unable to get it to work with the gotenberg container already running with Paperless. 

Here,is a link https://github.com/t0mer/gotenberg-ui. Has anyone seen or used this docker container before and got it working ? If not if anyone fancies giving it a go, and are prepared to share their success or failure , I’d appreciate it?

**Comment by titro** [comment]
why a seperate gotenberg ui? put gotenberg and tika in your compose and you'll see the result (and errors) in paperless.

**Reply by nodecentral** [reply]
Hi @titro, 

I already have gotenberg included within my compose file, this particular route was to allow me to use it directly, and do some other bits to like webpages to pdf etc.

**Comment by titro** [comment]
No problems with gotenberg. Just point it to your gotenberg instance with the correct IP/Port:

```
version: "3.7"

services:
  gotenbergui:
    image: techblog/gotenbergui
    container_name: gotenbergui
    restart: always
    environment:
      - GOTENBERG_API_ADDRESS=http://<ip>:3000
    ports:
      - "8044:8080"
```
