### DISCUSSION TITLE
Mounting NFS share to consume returns an permission error

### DISCUSSION THREAD

**Discussion by holzfelix** [paperless-ngx/paperless-ngx#3106] [Support]
Hi I try tu run paperless-ngx in a docker container in a debian VM on da proxmos host.

In the debian VM I added a mount to a qnap NAS. Mountppoint ist /media/dataarchieve
The NAS user is called "paperless" and has R/W access to the whole directory with all sub directories. 

In my dy docker Compose I setted the path to this mountpoint for the consume and the export dirs. I also changed the uid and guid  for the docker user in docker-compose. 

Now I got this error on paperless-ngx webserver:
```
SystemCheckError: System check identified some issues:
ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is not writeable
	HINT: Set the permissions of 
drwxr-xr-x root root /usr/src/paperless/consume
 to be writeable by the user running the Paperless services
System check identified 1 issue (0 silenced).
```

Ma docker-compose file looks like this:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /media/dataarchive/export:/usr/src/paperless/export
      - /media/dataarchive/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
      USERMAP_UID: 1000
      USERMAP_GID: 100
# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
      #PAPERLESS_OCR_LANGUAGES: tur ces
# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
      #PAPERLESS_SECRET_KEY: change-me
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
      #PAPERLESS_TIME_ZONE: America/Los_Angeles
# The default language to use for OCR. Set this to the language most of your
# documents are written in.
      #PAPERLESS_OCR_LANGUAGE: eng
      
volumes:
  data:
  media:
  pgdata:
  redisdata:
```

What is my mistake in this config? 

Thanks in advance
