### DISCUSSION TITLE
Adding “ organize - The file management automation” into Paperless

### DISCUSSION THREAD

**Discussion by nodecentral** [paperless-ngx/paperless-ngx#3137] [General]
Hi all

I’ve logged this as a “show and tell”,  even though I’ve only just started to play around with it, plus I’m sharing it here more to see if anyone’s interested in testing this tool and integration out with me.. (https://organize.readthedocs.io/en/latest/). 

My goal by incorporating organize into Paperless, is to greatly enhance the pre and post consume capabilities, so it can do much more, and most importantly a little easier for those not able to write scripts etc.  (well that’s the hope anyway).

**INSTALLATION.**

One approach to do this is to use the the advanced container facility (https://docs.paperless-ngx.com/advanced_usage/#custom-container-initialization ) and make the installation part of your paperless build.  But before I do that, I’m going to do it manually first by accessing the command line of my test/development Paperless-ngx docker instance (not my live one) and do the following..

Access the command line via 
````
docker exec -it paperlessngx /bin/sh
````
Then install organize, I’m doing the one with ocr, as a test but you don’t have to - `pip3 install -U organize-tool` is the other
````
pip3 install -U "organize-tool[textract]"
````
Once installed I’ll check the location of the organize config.yaml
````
organize reveal --path
````
Which tells me the following..
````
/root/.config/organize/config.yaml
````
Which i will copy over to my paperless script folder to see and customise, here’s what it looks like 
````
# organize configuration file
# https://organize.readthedocs.io

rules:
  - name: "The name of this rule"
    locations:
      - # your locations here
    filters:
      - # your filters here
    actions:
      - # your actions here
````

**CONFIGURATION**

From here it’s going to be about what scripts I want organize to run, and they provide some useful examples on their website (shared earlier). As my initial goal is to have a pre-consume folder (or folders), where i can automate checks for files that meet a certain criteria to be consumed by paperless. 

To create a preconsume folder and a location where its easier for me to edit, create my organize config.yaml, i updated my paperless-ngx docker_compose with the following two mapped volumes.
````
      - /share/Container/paperless/preconsume:/usr/src/paperless/preconsume
      - /share/Container/paperless/organize:/root/.config/organize
````

From there, each time Organize runs, if a rule is met, it move the files into the consume folder for paperless to then work its magic.  An example script would be something like this..
````
rules:
  - name: "Sort my invoices and receipts"
    locations: /usr/src/paperless/preconsume/
    subfolders: true
    filters:
      - extension: pdf
      - name:
          contains:
            - Invoice
            - Order
            - Purchase
          case_sensitive: false
    actions:
      - move: /usr/src/paperless/consume/
````
 
More updates to come when i can, but if anyone reading this is interested to follow me (or even take the lead more) and contribute , please add any thoughts/comments/concerns below..
