### DISCUSSION TITLE
Initial setup behind traefik - Gateway Time-Out

### DISCUSSION THREAD

**Discussion by azuravian** [paperless-ngx/paperless-ngx#3224] [Support]
I'm setting up paperless for the first time, running behind Traefik.  Logs show apps worker as ready.  Traefik seems to have picked everything up from labels with no issues, but I keep getting a Gateway Time-Out when going to my paperless subdomain.

Compose File:
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /docker/paperless/redisdata:/data

  ngx-db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - /docker/paperless/dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - ngx-db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /docker/paperless/data:/usr/src/paperless/data
      - /mounteddrive/paperless/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: ngx-db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    labels:
      - "traefik.enable=true"
      ## Authentication
      - traefik.http.routers.paperless-https.entrypoints=websecure
      - traefik.http.routers.paperless-https.tls=true
      - traefik.http.routers.paperless-https.priority=99
      - traefik.http.routers.paperless-https.rule=Host(`paperless.example.com`)
      - traefik.http.routers.paperless-https.tls.certresolver=letsencrypt
      ## Middlewares
      - traefik.http.routers.paperless-https.middlewares=chain-oauth@file
      ## Services
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      - traefik.http.routers.paperless-https.service=paperless
      

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
```

**Comment by shamoon** [comment]
I run it behind Traefik, setup looks pretty darn similar. Is `PAPERLESS_URL` set in your .env ?

**Reply by azuravian** [reply]
I do.  I have the following in my .env:
USERMAP_UID
USERMAP_GID
PAPERLESS_URL
PAPERLESS_SECRET_KEY
PAPERLESS_TIME_ZONE
PAPERLESS_OCR_LANGUAGE

**Comment by stumpylog** [comment]
One thing I don't see is any sort of network information.  Your Traefik container will need to be able to see the paperless container on a network.  For example, I use a network named `reverse-proxy` with containers I want to access connection to it.  You could do the reverse, connecting a `paperless-net` to the Traefik container.

**Reply by azuravian** [reply]
Tried this with no success.  Still getting gateway timeout.  I've seen some comments on paperless-ng that there may be some http headers required.  Is that the case with ngx as well?

**Comment by dakky** [comment]
did you fix that issue? I have the same problem

**Reply by azuravian** [reply]
I never did, unfortunately.

**Comment by schorschebob** [comment]
I had the same problems. After some back and forth, I got it to work by specifying the network label:
`- "traefik.docker.network=proxy-manager"`.

Of course, replace `proxy-manager` with the name of your external proxy network.

**Comment by dakky** [comment]
i fixed it too. it was indeed an issue with the docker networks. I made a coyp/paste error. Basically the traefik container and the paperless container need to share the same network.

**Comment by morphrv** [comment]
I don't know if the OP managed to solve this or not but, here's how I've got paperless-ngx running with Traefik v2:

```
networks:
  proxy_net:
    external: true
  backend:
    external: true
```

The network 'proxy_net' is home to the paperless-ngx webserver service and Traefik. The paperless-ngx broker, db (Postgres in my instance), gotenberg and tika services live on the backend network. The only service to sit on both is the paperless-ngx webserver service.

I tend to use the file provider for Traefik (no particular reason why, just a personal preference over Docker labels):

```
http:
  routers:
    paperless-ngx:
      rule: Host(`edms.domain.net`)
      service: paperless-webserver-1
      middlewares:
        - chain-no-auth@file

  services:
    paperless-webserver-1:
      loadBalancer:
        servers:
          - url: http://paperless-webserver-1:8000
```

For the middleware chain, I have:

```
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-https-redirectscheme
          - middlewares-secure-headers
          - middlewares-compress
          - middlewares-traefik-real-ip
```

Are they all strictly necessary? Probably not, as they've been lifted from my production Traefik instance (because I'm lazy) which runs a variety of services. The important header, I've found, is the referrerPolicy:

`referrerPolicy: "strict-origin-when-cross-origin"`

Here's my secure-headers middleware for reference:
```
  middlewares-secure-headers:
    # General Security Headers (added to response/requests)
    # Includes HSTS
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
          - "X-Forwarded-For"
          - "X-Real-IP"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: false
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
          X-Forwarded-Proto: "https"
```

(Not to mention adding the PAPERLESS_URL environment setting)

**Comment by github-actions** [comment]
This discussion has been automatically closed due to inactivity.

**Comment by Qubitza** [comment]
Thanks @schorschebob and @morphrv I was struggling for hours to start two instances on the same port but with different subpaths.
With you help I finally got it working using this docker-compose file:
```
version: "3.4"
services:
  traefik:
    image: traefik:v2.0
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - paperless-traefik

  broker-one:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata-one:/data
    networks:
      - paperless-redis-one

  webserver-one:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker-one
    volumes:
      - ./one/data:/usr/src/paperless/data
      - ./one/media:/usr/src/paperless/media
      - ./one/export:/usr/src/paperless/export
      - ./one/consume:/usr/src/paperless/consume
    expose:
      - 8000
    environment:
      PAPERLESS_REDIS: redis://broker-one:6379
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_SECRET_KEY: <please change me>
      PAPERLESS_STATIC_URL: /one/static/
      PAPERLESS_FORCE_SCRIPT_NAME: /one
    labels:
      - traefik.enable=true
      - traefik.docker.network=paperless-traefik
      - traefik.http.routers.paperless-ngx-one.rule=PathPrefix(`/one`)
      - traefik.http.services.paperless-ngx-one.loadbalancer.server.port=8000
    networks:
      - paperless-traefik
      - paperless-redis-one

  broker-two:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata-two:/data
    networks:
      - paperless-redis-two

  webserver-two:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker-two
    volumes:
      - ./two/data:/usr/src/paperless/data
      - ./two/media:/usr/src/paperless/media
      - ./two/export:/usr/src/paperless/export
      - ./two/consume:/usr/src/paperless/consume
    expose:
      - 8000
    environment:
      PAPERLESS_REDIS: redis://broker-two:6379
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_SECRET_KEY: <please change me>
      PAPERLESS_STATIC_URL: /two/static/
      PAPERLESS_FORCE_SCRIPT_NAME: /two
    labels:
      - traefik.enable=true
      - traefik.docker.network=paperless-traefik
      - traefik.http.routers.paperless-ngx-two.rule=PathPrefix(`/two`)
      - traefik.http.services.paperless-ngx-two.loadbalancer.server.port=8000
    networks:
      - paperless-traefik
      - paperless-redis-two

volumes:
  redisdata-one:
  redisdata-two:

networks:
  paperless-traefik:
    name: paperless-traefik
  paperless-redis-one:
    name: paperless-redis-one
  paperless-redis-two:
    name: paperless-redis-two

```
