### DISCUSSION TITLE
No documents after Synology crash and reinstall from backup

### DISCUSSION THREAD

**Discussion by zmeel** [paperless-ngx/paperless-ngx#3323] [Support] [answered]
Yesterday, my Synology NAS experienced a volume crash because of 1 faulty drive and incorrect shut down. I had to setup everything from scratch but luckily could do this from a local backup.  However, restoring my paperless-ngx data (docker setup) does not show any documents. I'm a long time user of paperless-ngx (started with paperless) and using docker-compose:

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: <removed>

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
        - /volume1/docker/paperless/data:/usr/src/paperless/data
        - /volume1/docker/paperless/media:/usr/src/paperless/media
        - /volume1/docker/paperless/export:/usr/src/paperless/export
        - /volume1/homes/erik/Drive/Scans:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  data:
  media:
  pgdata:
``` 
My Synology NAS made a daily backup of my docker folder (/volume1/docker/) where the paperless data is. I can see all the imported files in de media folder (0000001.pdf etc.) but nothing in paperless itself. 

I'm starting to think that this backup strategy was not really the way to go...

 I could use some help from the community!
