### DISCUSSION TITLE
Weird error with the TIKA container since updating to 1.14.5 from 1.13.0

### DISCUSSION THREAD

**Discussion by nosebeggar** [paperless-ngx/paperless-ngx#3440] [Support] [answered]
Hi all, I just upgraded (of course I have a backup) but I'd like to resolve this rather than roll back.

Since upgrading the tika container won't start, it spams my log with this over and over:
`tika_1       | [0.015s][warning][os,thread] Failed to start thread "VM Thread" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
tika_1       | Error occurred during initialization of VM
tika_1       | Cannot create VM thread. Out of system resources.
`

This is my docker-compose.yml:
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - ./redisdata:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./databasefolder:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: XXX

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    privileged: true
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 127.0.0.1:8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./datafolder:/usr/src/paperless/data
      - ./mediafolder:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    environment:
      CHROMIUM_DISABLE_ROUTES: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:

```

It's weird, because the host system has plenty of resources left:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/944111/1930fdd6-deb7-40f5-8c1a-cac7db91c06d)

Any ideas what I could do? I already deleted the container and had it rebuilt, still no dice.
