### DISCUSSION TITLE
No data after migration

### DISCUSSION THREAD

**Discussion by lockheed** [paperless-ngx/paperless-ngx#3464] [Support]
I just migrated from paperless-ng linuxserve.io to -ngx using the guide on the page. I am using  sqlite.
After migration,  paperless is empty: no users, no data. Why?

Here's my portainer stack:
```
---
version: "2.1"
services:
   broker:
     container_name: paperless-redis
     image: docker.io/library/redis:7
     restart: unless-stopped
     volumes:
      - /z/data/paperless_redis:/data
     networks:
      - paperless-net
      
   paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    depends_on:
      - broker
    environment:
      USERMAP_UID: 1000
      PGID: 1000
      PAPERLESS_OCR_LANGUAGES: eng deu fre pol
      PAPERLESS_TIME_ZONE: Europe/Warsaw
      PAPERLESS_OCR_LANGUAGE: pol
      DOCKER_MODS: linuxserver/mods:papermerge-multilangocr
      OCRLANG: pol
      PAPERLESS_URL: https://my.url
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DATA_ROOT: /config
      PAPERLESS_MEDIA_ROOT: /data/media
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /etc/localtime:/etc/localtime
      - /z/docker/_configs/paperless:/config
      - /z/data/paperless_docs:/data
    restart: unless-stopped
    networks:
      - frontend
      - paperless-net

networks:
  paperless-net:
    driver: bridge
  frontend:
    external: true
```
