### DISCUSSION TITLE
Email consumption stopped working

### DISCUSSION THREAD

**Discussion by ronstone2000** [paperless-ngx/paperless-ngx#3519] [Support]
This had been working in earlier versions, now cannot consume emails.

Paperless-NGX 1.14.5 on Docker

Log error:
`Error while consuming document Periodic Information Certificate (PIC) for Q3-2023.eml: Error while converting document to PDF: 400 Client Error: Bad Request for url: http://gotenberg:3000/forms/chromium/convert/html`

docker-compose.yml:
```
<snip>
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - 'gotenberg'
      - '--chromium-disable-javascript=true'
      - '--chromium-allow-list=file:///tmp/.*'

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
```

Have I missed a required config update? I didn't see anything recent relates to Gotenburg in the changelings.
