### DISCUSSION TITLE
User law on a document not updated by API

### DISCUSSION THREAD

**Discussion by Philippe-M** [paperless-ngx/paperless-ngx#3694] [Support] [answered]
### Description

Hi, 

I would like to use the API to modify reading / writing authorizations on documents after adding a recovered file from an e-mail address by Paperless-Ngx.

I was inspired by the code of this page https://github.com/paperless-ngx/paperless-ngx/wiki/post-consume-crcript-examples.I transformed it to achieve this:

```
#!/usr/bin/env python3

import os
import requests

def _set_auth_tokens(paperless_url: str, timeout: float, session: requests.Session):
    credentials = {"username": "myuser", "password": "mypassword"}
    response = sess.get(paperless_url, timeout=timeout)
    response.raise_for_status()
    csrf_token = response.cookies["csrftoken"]

    response = sess.post(
        paperless_url + "/api/token/",
        data=credentials,
        headers={"X-CSRFToken": csrf_token},
        timeout=timeout,
    )
    response.raise_for_status()

    api_token = response.json()["token"]

    session.headers.update(
        {"Authorization": f"Token {api_token}", f"X-CSRFToken": csrf_token}
    )

if __name__ == "__main__":
    paperless_url = "http://localhost:8000"
    timeout = 5.0

    with requests.Session() as sess:
        _set_auth_tokens(paperless_url, timeout, sess)

        #doc_pk = int(os.environ["DOCUMENT_ID"])
        doc_pk = 62

        doc_info_resp = sess.get(
            paperless_url + f"/api/documents/{doc_pk}/", timeout=timeout
        )
        doc_info_resp.raise_for_status()
        doc_info = doc_info_resp.json()

        correspondent = doc_info["correspondent"]
        doc_type = doc_info["document_type"]
        doc_original_name = doc_info["original_file_name"]
        doc_owner = doc_info["owner"]

        print('correspondent : ' + str(correspondent))
        print('doc_type : ' + str(doc_type))
        print('doc_original_name : ' + str(doc_original_name))
        print('owner : ' + str(doc_owner))

        print('----------------')

        print('Ajout des droits')
        # Admin groupe : 1
        # Direction groupe : 2
        # ADV groupe : 3
        try:
            resp = sess.patch(
                paperless_url + f"/api/documents/{doc_pk}/",
                data=
                    {
                        "owner": 3,
                        "view": {
                            "users": ["myuser"], 
                            "groups":["administrators"]
                        },
                        "change": {
                            "users": ["myuser"],
                            "groups": ["administrators"]
                        }
                    },
                timeout=timeout,
            )
        except Exception as err:
            print('Erreur : ' + str(err.args()))
        else:
            resp.raise_for_status()
```

When I launch it manually by defining an ID of document manually (it exists in my instance Paperless-Ngx), I manage to change the owner but not the values for View or Change.I have no execution errors and nothing in the logs of the container.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/a2f80e7a-8f24-450d-bd5b-f101a842de8a)

The user defined in the script is superuser and owner of the document.

### Steps to reproduce

Launch the script from the Paperless_webserver container

### Webserver logs

```bash
Nothing
```

### Paperless-ngx version

1.16.3

### Host OS

Linux Fedora 37 

### Installation method

Docker - official image

### Browser

CLI

### Configuration changes

docker-compose.yml

**Comment by shamoon** [comment]
Groups and users should be passed as ID numbers

**Reply by Philippe-M** [reply]
Hi, 

I tested this code : 

```
        try:
            resp = sess.patch(
                paperless_url + f"/api/documents/{doc_pk}/",
                data=
                    {
                        "owner": 3,
                        "view": {
                            "users": ["3"], 
                            "groups":["3"]
                        },
                        "change": {
                            "users": ["3"],
                            "groups": ["1"]
                        }
                    },
                timeout=timeout,
            )
```

Or that one

```
        try:
            resp = sess.patch(
                paperless_url + f"/api/documents/{doc_pk}/",
                data=
                    {
                        "owner": 3,
                        "view": {
                            "users": [3], 
                            "groups":[3]
                        },
                        "change": {
                            "users": [3],
                            "groups": [1]
                        }
                    },
                timeout=timeout,
            )
```

Or

```
        try:
            resp = sess.patch(
                paperless_url + f"/api/documents/{doc_pk}/",
                data =
                    {
                        "owner": 3,
                        "view": {
                            "users": "3", 
                            "groups": "3"
                        },
                        "change": {
                            "users": "3",
                            "groups": "1"
                        }
                    },
                timeout = timeout,
            )
```

Or 

```
        try:
            resp = sess.patch(
                paperless_url + f"/api/documents/{doc_pk}/",
                data =
                    {
                        "owner": 3,
                        "view": {
                            "users": 3, 
                            "groups": 3
                        },
                        "change": {
                            "users": 3,
                            "groups": 1
                        }
                    },
                timeout = timeout,
            )
```

In both cases the rights are not updated. I spent this morning, before testing again, on version 1.16.4

No trace of change in the administration of Django. For my tests I am on a docker content in sqlite

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/41acfcc7-e627-4fd6-95a9-0ed61c63e435)

My custom docker-compose.yml for integrate Tabula.

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./consume:/usr/src/paperless/consume
      - ./scripts/custom-cont-init.d:/custom-cont-init.d:ro
      # Use for PAPERLESS_POST_CONSUME_SCRIPT
      - ./export:/usr/src/paperless/export      
      - ./scripts:/usr/src/paperless/scripts
      # -------------------------------------
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless/scripts/post_script.py
      PAPERLESS_OCR_LANGUAGE: fra
      PAPERLESS_TIME_ZONE: Europe/Paris
      PAPERLESS_URL: http://localhost:8000
      CSRF_TRUSTED_ORIGINS: http://localhost:8000

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

  tabula:
    build: ./
    volumes:
    # Same source of PAPERLESS_POST_CONSUME_SCRIPT
      - ./export:/export
      - ./scripts:/scripts
      
volumes:
  data:
  media:
  redisdata:
```

scripts/custom-cont-init.d/install-requests.sh
```
echo "Installation de requests"
pip install requests
```
