### DISCUSSION TITLE
Looking for a good RPi 3B+ Config (Docker)

### DISCUSSION THREAD

**Discussion by DoinStuff35** [paperless-ngx/paperless-ngx#3804] [General]
Hi!

I´m looking for a lean Docker-Configuration to get paperless ngx running as smooth as possible on my RPi 3B+.

Here´s my try:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_OCR_Mode: skip
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_WEBSERVER_WORKERS: 1
      PAPERLESS_ENABLE_NLTK: false
      PAPERLESS_SECRET_KEY: stuff
      PAPERLESS_ADMIN_USER: login
      PAPERLESS_ADMIN_PASSWORD: 12345

volumes:
  data:
  media:
  pgdata:
  redisdata:

```

Is working, but the Import is pretty slow. OCR is still working, which i do not understand: Doesn´t "PAPERLESS_OCR_Mode: skip" turns OCR off?

Help and further Optimization welcome!

Ah...using portainer.

Thanks!

**Comment by DoinStuff35** [comment]
Ended with this one:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /media/ssd1/data:/usr/src/paperless/data
      - /media/ssd1/media:/usr/src/paperless/media
      - /media/ssd1/export:/usr/src/paperless/export
      - /media/ssd1/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGES: deu
      PAPERLESS_OCR_Mode: skip
      PAPERLESS_OCR_PAGES: 1
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_THREADS_PER_WORKER: 1
      PAPERLESS_WEBSERVER_WORKERS: 1
      PAPERLESS_ENABLE_NLTK: false
      PAPERLESS_SECRET_KEY: secret
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: pw

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

Not stable at all, have to restart Pi often :( 

Help appreciated.
