### DISCUSSION TITLE
importer not working

### DISCUSSION THREAD

**Discussion by SB97** [paperless-ngx/paperless-ngx#3817] [Support]
Hello,
im running 1.16.5 and today my documents went suddenly missing.
I rested the filters in the frontend and confirmed that the files are present in the docker volume.

As i have a current export, i just pruned everything and reinstalled paperless, but i cant get the import to work:
```
root@p-paperless:/home/paperless-ngx# docker-compose exec -T webserver document_importer ../export
Checking the manifest
Installed 2 object(s) from 1 fixture(s)
Copy files into paperless...
0it [00:00, ?it/s]
Updating search index...
0it [00:00, ?it/s]
```
i don´t see a message about the import in the paperless.log in the frontend

**Comment by BoBBer446** [comment]
Wie hast du paperless-ngx installiert?
Docker compose?
Wie sieht deine config aus?

**Reply by SB97** [reply]
I host in docker. Here is the docker-compose.yml
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  data:
  media:
  pgdata:
  redisdata:

```

Was hat mich als Deutscher enttarnt? :)
