### DISCUSSION TITLE
Lost all Data

### DISCUSSION THREAD

**Discussion by DoinStuff35** [paperless-ngx/paperless-ngx#3846] [Support] [answered]
**Setup:**
RPi 4 (Pi OS Lite)
Portainer 2.18.4
Paperless ngx 1.16.5

All paperless-Folders on portable SSD connected to Pi. SSD configured as SMB-Share to access files from Network/Windows.

**Docker Compose YML:**

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /media/ssd1/data:/usr/src/paperless/data
      - /media/ssd1/media:/usr/src/paperless/media
      - /media/ssd1/export:/usr/src/paperless/export
      - /media/ssd1/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGES: deu
      PAPERLESS_OCR_Mode: skip
      PAPERLESS_OCR_PAGES: 1
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_THREADS_PER_WORKER: 1
      PAPERLESS_WEBSERVER_WORKERS: 1
      PAPERLESS_ENABLE_NLTK: false
      PAPERLESS_SECRET_KEY: ***********************************
      PAPERLESS_ADMIN_USER: *********
      PAPERLESS_ADMIN_PASSWORD: ********

volumes:
  data:
  media:
  pgdata:
  redisdata:

```

**Problem:** First Login, System running smooth. Imported about 120 Documents. Created Tags, Document-Types, correspondents and indexed some files. Shutdown Pi by console command and went to sleep. Today: All Data gone! No more Documents, no types, no tags, just nothing! Media Folder is empty. Log File in "Data" empty too.

I´m scared to death! Using a DMS first time and lost all data! Had a Backup...but all the work was all in vain. :(
