### DISCUSSION TITLE
[Feature Request] OAuth2/OIDC support

### DISCUSSION THREAD

**Discussion by madduck** [paperless-ngx/paperless-ngx#4006] [Feature Requests] [answered]
### Description

The ability to authenticate to Paperless NGX with OAuth2/OIDC would be amazing. The ability to manage this in the UI, as well as setting like limiting users to domains and sharing etc. could allow for tighter integration with Nextcloud, WikiJS, and other tools that are getting more traction in home and small business networks.

### Other

OAuth2 can presumably be added to Django with something like [django-allauth](https://django-allauth.readthedocs.io/en/latest/), and at least [one person has managed to get oauth2 for paperless working](https://ciphermenial.github.io/posts/adding-oauth-to-paperless/), but it needs tigther integration with the app, and if only on the login screen.

**Comment by Vyerni** [comment]
Would definitely look forward to this

**Comment by stumpylog** [comment]
There's been several attempts (#3773 and #1746 at least), but the authors seem to go AFK and not finish the work up.  If someone would like to attempt it again, there's some prior work to start from.

**Reply by mpflanzer** [reply]
Could you outline a bit what kind of solution would be preferred by you? For instance
- do local users and OIDC users need to be automatically merged based on something or is it a manual step via the UI?
- can OIDC automatically create new users or do all users need to be manually created first in the UI?
- is it ok to limit the integration to just the login? Or do you also want to make use of groups, roles and permissions from the OIDC provider?

**Comment by ternium1** [comment]
Hello,

I found a way to authenticate using an OIDC provider.
My setup is the following:
 - Traefik as reverse proxy
 - Paperless in a docker container without exposing its port
 - ADFS as Oauth provider
 
This was done by using Traefik and a forwardauth middleware that adds the X-Forwarded-User header. Paperless allows using this method of authentication.

Here are the paperless env variables required for this to work:

```
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: true
      PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_FORWARDED_USER
````
and here are the paperless labels for traefik:

```
    labels:
      - "traefik.http.routers.paperless.rule=Host(`paperless.example.com`)"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.middlewares=traefik-auth@file"
      - "traefik.http.routers.paperless.entrypoints=websecure"
```

Here is the traefik-forward-auth docker-compose:

```yml
  traefik-forward-auth:
    image: "mesosphere/traefik-forward-auth:3.1.0"
    container_name: "traefik-forward-auth"
    environment:
      #LOG_LEVEL: "debug"
      CLIENT_ID: "xxx"
      CLIENT_SECRET: "xxx"
      ENCRYPTION_KEY: "xxx"
      PROVIDER_URI: "xxx"
      SECRET: "xxx"
      AUTH_HOST: "xxx"
      COOKIE_DOMAIN: "xxx"
    depends_on:
      - traefik
    volumes:
     - /path/for/custom_certs:/etc/ssl/certs
    labels:
      - "traefik.port=4181"
      - "traefik.http.routers.traefik-forward-auth.entrypoints=websecure"
      - "traefik.http.routers.traefik-forward-auth.middlewares=traefik-auth@file"
      - "traefik.http.routers.traefik-forward-auth.rule=Path(`/_oauth`)"
  ```

and here is the traefik middleware config inside dynamic.yml

```yml
http:
  middlewares:
    traefik-auth:
      forwardAuth:
        address: "http://traefik-forward-auth:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"

```
