### DISCUSSION TITLE
Rootless container throws permission error

### DISCUSSION THREAD

**Discussion by chris-fj** [paperless-ngx/paperless-ngx#4019] [Support]
### Description

I can't setup the container as rootless. Following the docs instructions to set up the user inside the containr provokes a permissions error that dissapears when I uncomment the `user` key so the problem is in the key. Am I misunderstanding the usage of the key `user`? I have to admit that the docs could benefit of having the rootless section explained a little better

### Steps to reproduce

I'm using docker compose and my `docker-compose.yml` file looks like this

```yaml
# docker-compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: redis:7
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - redisdata:/data

  db:
    image: postgres:15
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: 'REDACTED'

  webserver:
    image: paperlessngx/paperless-ngx:1.17
    user: 1000:100
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    networks:
      - internal

  gotenberg:
    image: gotenberg/gotenberg:7.8
    restart: unless-stopped

    networks:
      - internal
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    networks:
      - internal
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  internal:
```

My `docker-compose.env` file looks like this

```yaml
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=1000
USERMAP_GID=100

# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
#PAPERLESS_OCR_LANGUAGES=tur ces

###############################################################################
# Paperless-specific settings                                                 #
###############################################################################

# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.

# This is required if you will be exposing Paperless-ngx on a public domain
# (if doing so please consider security measures such as reverse proxy)
#PAPERLESS_URL=https://paperless.example.com

# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
#PAPERLESS_SECRET_KEY=change-me

# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=UTC

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=eng

# Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx
#PAPERLESS_FORCE_SCRIPT_NAME=/PATHPREFIX
#PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # trailing slash required
#
PAPERLESS_DBNAME=paperless
PAPERLESS_DBUSER=paperless
PAPERLESS_DBPASS=REDACTED
```

and uid/gid information:

```bash
id $(whoami)
uid=1000(<my-user>) gid=100(users) groups=473(docker),100(users)
```

I want to run the container in rootless mode so I added `user: 1000:100` under `webserver`, which is the uid/gid of the user running the container, as per [the docs](https://docs.paperless-ngx.com/configuration/#docker):

> Rootless
> 
> If you want to run Paperless as a rootless container, you will need to do the following in your docker-compose.yml:
> 
> set the user running the container to map to the paperless user in the container. This value (user_id below), should be the same id that USERMAP_UID and USERMAP_GID are set to in the next step. See USERMAP_UID and USERMAP_GID [here](https://docs.paperless-ngx.com/configuration#docker).

### Webserver logs

```bash
Adding the `user` key provokes the following error:


paperless-webserver-1  | Paperless-ngx docker container starting...
paperless-webserver-1  | Mapping UID and GID for paperless:paperless to 1000:100
paperless-webserver-1  | usermod: no changes
paperless-webserver-1  | groupmod: Permission denied.
paperless-webserver-1  | groupmod: cannot lock /etc/group; try again later.
```

that loops indefinitely
```


### Browser logs

_No response_

### Paperless-ngx version

1.17.1

### Host OS

arm64 openSUSE 15.4

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

I think the only changes respect with the original compose file is that I used docker hub for the source of the images, changed the volumes to have them all in the same folder and added an internal network

### Other

_No response_
