### DISCUSSION TITLE
[Feature Request]  Allow running container with read only root file system

### DISCUSSION THREAD

**Discussion by YurNaybor** [paperless-ngx/paperless-ngx#4020] [Feature Requests] [answered]
### Description

Hi,

I am currently implementing paperless-ngx in my Homelab. I try to secure my containers pretty tightly and one part of that it, to run them with read only root file system (e.g. "read_only: true" on the service in Docker Compose). as well as with a non root user. Unfortunately, the paperless-ngx container opts to write supervisord files into the working directory (/usr/src/paperless/src/), when run non root (e.g. [here](https://github.com/paperless-ngx/paperless-ngx/blob/ce36c2d0eaa90a7912d4e200328bcb58e1f1e54e/docker/paperless_cmd.sh#L9)).

I worked around this by setting a custom command in my compose file and write the supervisord files in a tmpfs mount. I believe this change could be incorporated into the cmd of paperless easily:

```
[...]
  paperless-ngx:
    [...]
    command:
      - /usr/local/bin/supervisord
      - -c
      - /etc/supervisord.conf
      - --user
      - paperless
      - --logfile
      - /tmp/supervisord.log
      - --pidfile
      - /tmp/supervisord.pid
    environment:
      - "USERMAP_UID=1000"
      - "USERMAP_GID=1000"
      [...]
    user: 1000:1000
    volumes:
      - type: tmpfs
        target: /tmp
```
