### DISCUSSION TITLE
Backup with Document Importer including MariaDB dump?

### DISCUSSION THREAD

**Discussion by NetRat88** [paperless-ngx/paperless-ngx#4140] [Support]
Hey folks,

I have recently worked extensively with Paperless-ngx on my RaspberryPi 4 in docker and I am now ready to use the system productively.
The question of a backup and restore process arose here, which I have also tested as far as possible.
I still wanted to make sure that I didn't incur any losses as the data grew.

I installed Paperless via a docker-compose.yaml with stack.env via Portainer (upload file and stack.env). All of my directories (except redisdata) are stored on my QNAP NAS and were mapped with NFS in the compose file.

For the backup, I used the command `sudo docker exec -d paperless-webserver-1 document_exporter ../export` 
Then the stack and directory contents were deleted and completely reinstalled. The data was then restored using the command `sudo docker exec -d paperless-webserver-1 document_import ../export`
All documents, users, tags, etc. seem to be there.

Since I use a MariaDB, I wanted to make sure whether I would also have to take a database dump and restore it, or whether this would all be covered via the document importer?

This is my docker-compose.yaml I use to install via Portainer web GUI over add stack and upload file

```
version: "1.0"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - stack.env

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8810:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume

    env_file:
      - stack.env

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
  dbdata:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/docker/volumes/paperless/dbdata"
  data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/docker/volumes/paperless/data"
  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/docker/volumes/paperless/media"
  export:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/docker/volumes/paperless/export"
  consume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/ScannedDocuments/consume"
```

Thanks and Greetings
NetRat
