### DISCUSSION TITLE
What should you consider when operating paperless on NFS volumes (with nightly nas shutdown)

### DISCUSSION THREAD

**Discussion by NetRat88** [paperless-ngx/paperless-ngx#4141] [Support]
Hey folks,

please excuse my second question within a short time!

Are there any concerns when storing the paperless-ngx volumes data, dbdata (mariadb), media, export and consume on my QNAP NAS, which will be always shut down at night from 1-8 am? The volumes are mapped by NFS in the compose file.

Do you need to pay attention to anything here? Should the docker stack automatically be shut down before switching off the NAS or something else?
I used the soft attribute when mapping the drives, which hopefully prevents the Docker container from crashing. Test still pending.

This I am currently using to map the volumes in the compose file:

```
volumes:
  redisdata:
  dbdata:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/docker/volumes/paperless/dbdata"
  data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/docker/volumes/paperless/data"
  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/docker/volumes/paperless/media"
  export:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/docker/volumes/paperless/export"
  consume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.100,nolock,soft,rw"
      device: ":/ScannedDocuments/consume"
```

My current paperless-ngx is running with docker compose on my raspberry pi 4 (redisdata, mariadb, goetenburg and tiki) and the complete docker-compose.yaml and stack.env you can find in this post:

https://github.com/paperless-ngx/paperless-ngx/discussions/4140

Many thanks in advance and best regards
Tim
