### DISCUSSION TITLE
Updating paperless-ngx with docker-compose

### DISCUSSION THREAD

**Discussion by olegkron** [paperless-ngx/paperless-ngx#4240] [Support] [answered]
Hi everyone! 

Is there a _reliable_ way to update your paperless-ngx running on docker with docker-compose ?

After updating with docker-compose I have lost both my configuration (correspondents, tags, etc) and my data (0 documents in the GUI, luckily still available in the old docker volume directory). 
Ideally I'd like to upgrade while keeping the data and the configuration intact.

Please let me know if there is a better way to upgrade your paperless-ngx without going through such a headache. 

Many thanks! 

Commands run: 
```
docker-compose down
docker-compose pull
docker-compose up
```

docker-compose file: 
```

version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/srv/dev-disk-by-uuid-abcd/paperless/data
      - media:/srv/dev-disk-by-uuid-abcd/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_ADMIN_USER: ***
      PAPERLESS_ADMIN_PASSWORD: ***

  gotenberg:
    image: gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  redisdata:
```
