### DISCUSSION TITLE
Best way to backup data

### DISCUSSION THREAD

**Discussion by nsauter** [paperless-ngx/paperless-ngx#4450] [Support] [answered]
Hi!

I have seen many backup diskussions here but non that really explains how to backup paperless-ngx data properly. I plan to use paperless-ngx as docker deployment and before i scan all my documents and shred them i wanto to make sure that i have a good backup. So: Whats the best way to backup data and how to restore them in case of loss? I mean... Im Sysadmin but nerver really worked with docker so im a bit afraid im doing something wrong an end up losing all docs.

Paperless Documentation tells that files are stored in docker volume paperless_media on the host. Is it okay to just backup this folder? What to do with the database?

Thanks in advance

**Comment by stumpylog** [comment, marked as answer]
Use the export tool

**Reply by nsauter** [reply]
I didnt find anythin in the documentation. Can i just put this in a cronjob or do i have to invoke it with a ui click? How to import then? Is there a import tool too?

**Reply by stumpylog** [reply]
https://docs.paperless-ngx.com/administration/#exporter

**Reply by smseidl** [reply]
I use this in Docker to have a cron like scheduler
```
 # Scheduler Service
  scheduler:
    image: mcuadros/ofelia:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ofelia.ini:/etc/ofelia/config.ini
    depends_on:
      - webserver
    restart: unless-stopped
```
ofelia.ini
```
[job-exec "Document Exporter"]
schedule = @midnight
container = paperlessngx-portainer-webserver-1
command = document_exporter ../export -f
run-on-startup = true
```

Note 1 - I am running a forked version of mcuadros/ofelia to pull in a PR that was not merged yet.  So the `@midnight` or the `run-on-startup` may not work.  

Note 2: My `../export` folder is mapped to a nas volume, so every night when the backups occur it's backed up to my NAS not local drive.
