### DISCUSSION TITLE
Yet another native iOS app for paperless-ngx

### DISCUSSION THREAD

**Discussion by plu** [paperless-ngx/paperless-ngx#4553] [General]
Unfortunately I've not come across @paulgessinger's [post](https://github.com/paperless-ngx/paperless-ngx/discussions/3283) when I started working on yet another native iOS app for paperless-ngx. If I had found Paul's app a few months ago, I'd probably not even have started working on another one, because his app is really great! But now that I have invested a significant amount of time already, I'm going to continue and I'd like to show how far I've come:

## Less Paper - Client for Paperless-ngx

The app is [available for free on the App Store](https://apps.apple.com/app/apple-store/id6464425056?pt=118988044&ct=ghd&mt=8), it supports iPhone, iPad and macOS.

If you have any feedback or if you're missing some features that you'd like to see in the app, don't hesitate and tell me! I've recently implemented bulk edit of tags and importing documents. Next on my list is bulk edit for document type, correspondent and storage paths.

Even though the app is available for iOS and macOS, my main focus is and will be on iOS. The macOS version might be a little behind in the feature set, but also usability wise not yet very optimised for macOS.

### iPhone

<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/521e7cbd-960a-4604-8eb0-2e7dac1d817f" width=200>

<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/7fc34cd9-c035-4fe4-a8a6-03a72957a031" width=200>

<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/60ead03d-4a72-4dd1-8459-c443be594a49" width=200>

<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/f228c8f7-71da-4113-9187-1d21a2384ba3" width=200>

### iPad

<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/1e62fd60-680a-42f7-ace8-8d037619b882" width=600>

<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/8d783702-7514-48de-9846-90f1d4fd5100" width=600>

**Comment by thegodfatherrelish** [comment]
Thanks for your time and work on this, I will definitely install it and try it out alongside Paul's app.

**Comment by paulgessinger** [comment]
I've already tried it out a bit and it works really well!

Is the code public, or are you planning to make it public?

**Reply by plu** [reply]
Thank you, Paul! The code is not yet public, but I don't see a reason to keep it private forever. I'll clean a few things up and try to release it over the next few weeks.

**Reply by tooomm** [reply]
Did you managed to polish it a bit and put it out in the meantime? :)

**Comment by plu** [comment]
I've just released another update:

- support forward auth systems like Authelia
- import password protected documents

Feedback, especially for Authelia, is highly appreciated!

<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/4f82a011-1fcd-4b01-a1f1-2bc4490ca8e5" width=150>

<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/373843cb-6573-4dbc-aacd-622fb1245b63" width=150>

**Reply by aroberts** [reply]
I'm very interested in this, but unable to get it to recognize my authelia-based forward auth. I saw from your post in Paul's thread that you're capturing any redirects and assuming they're auth related; this should be working for me, but all I get is either "invalid credentials" when I enter credentials, or "unknown error" when I don't. 

peeking my access logs, it looks like it's POSTing to /api/token, which is returning 400 rather than getting redirected to authelia (running v4.37.5). Is there anything else I can try? or a better place to leave a bug report?

**Reply by plu** [reply]
Hm, on top of my head I have no idea yet what might be the problem. Is that 400 bad request coming from Authelia, or from Paperless-ngx?

**Reply by aroberts** [reply]
~Ok, this is really mysterious- it's the paperless container itself that's rendering the 400. I don't understand how it could be bypassing authelia- I went ahead and logged out of authelia on my phone browser, in case it was somehow sharing cookies, but still the same effect. I confirmed that GET and POST to paperless.my.domain/api/token produce 302 and 303, respectively, from the CLI. There aren't any exceptions or additional routes in my traefik config, and the traefik dashboard also reports that the authelia middleware is attached to my paperless service.~

~paperless is configured with PAPERLESS_ENABLE_HTTP_REMOTE_USER_API and PAPERLESS_ENABLE_HTTP_REMOTE_USER set to true, but that shouldn't impact this bypass behavior. I'm totally at a loss for what could be causing the app to reach past my authentication layer.~

~This definitely sounds like something wrong with my system, but do you have any advice for how I can analyze the request the app is making?~

Edit: reinstalled the app and I saw the redirect handled properly. I'm still unable to add the server due to a "method not allowed" error on /api/token, but at least that's not such a mystery.

Another edit: I'm not a Django expert, but I think the 400 error with that styling may indicate my CORS or CSRF settings are off? I am running in debug mode and passing ALLOWED_HOSTS="*", but still not getting in with the app, and it's challenging to debug without a window into the request on the app side. Any advice?

Relevant paperless env config (ansible/jinja templating):
```
      PAPERLESS_DEBUG: "true"
      PAPERLESS_URL: https://paperless.{{ toplevel_domain }}
      PAPERLESS_ALLOWED_HOSTS: "*"
      PAPERLESS_CORS_ALLOWED_HOSTS: "http://127.0.0.1,http://::1,https://*.{{ toplevel_domain }},http://authelia:9091"
      PAPERLESS_CSRF_TRUSTED_ORIGINS: "http://127.0.0.1,http://::1,https://*.{{ toplevel_domain }},http://authelia:9091"
      PAPERLESS_USE_X_FORWARD_HOST: "true"
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
      PAPERLESS_ENABLE_HTTP_REMOTE_USER_API: "true"

```
paperless logs when I click "add server" in the app (with the URL filled in):
```
Bad Request: /api/token/
[2024-03-18 17:56:08,825] [WARNING] [django.request] Bad Request: /api/token/
```

**Reply by plu** [reply]
Which version of Paperless-ngx are you running there? I've tried to reproduce your setup (without Authelia currently), but with no luck so far.

```yaml
version: "3.4"
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.6.3
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      PAPERLESS_ADMIN_MAIL: plu@aptumtek.com
      PAPERLESS_ADMIN_PASSWORD: secret
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_TIME_ZONE: Europe/Berlin

      PAPERLESS_DEBUG: "true"
      PAPERLESS_ALLOWED_HOSTS: "*"
      PAPERLESS_CORS_ALLOWED_HOSTS: "http://127.0.0.1,http://::1,http://authelia:9091"
      PAPERLESS_CSRF_TRUSTED_ORIGINS: "http://127.0.0.1,http://::1,http://authelia:9091"
      PAPERLESS_USE_X_FORWARD_HOST: "true"
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
      PAPERLESS_ENABLE_HTTP_REMOTE_USER_API: "true"

    healthcheck:
      test: ["CMD", "/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 30
    ports:
      - "8000:8000"
    volumes:
      - ./consume:/usr/src/paperless/consume
      - ./healthcheck/paperless:/healthcheck
  redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 30
    volumes:
      - ./healthcheck/redis:/healthcheck
```

![Screenshot 2024-03-19 at 09 43 51](https://github.com/paperless-ngx/paperless-ngx/assets/31597/eff0ae05-a537-47ab-bf00-c0e198af5e06)
