### DISCUSSION TITLE
Possible bug? Consumer not recognizing PATCH-T paper.

### DISCUSSION THREAD

**Discussion by jschwalbe** [paperless-ngx/paperless-ngx#4632] [Support] [answered]
Running 1.17.4 via docker.

docker-compose.yml
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - /home/user/docker-configs/paperless-ngx/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: [snip]
      POSTGRES_PASSWORD: [snip]

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "5832:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/user/docker-configs/paperless-ngx/data:/usr/src/paperless/data
      - /home/user/docker-configs/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/scans/paperless/consume:/usr/src/paperless/consume

    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_ENABLE_BARCODES: true
      PAPERLESS_CONSUMER_POLLING: 60
      USERMAP_UID: 1000
      USERMAP_GID: 1001

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
```

logfile during a consume:
```
paperless-ngx-webserver-1  | [2023-11-18 17:33:32,012] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/2023-11-18 11182023172628.pdf to the task queue.
paperless-ngx-webserver-1  | [2023-11-18 17:33:32,037] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[b4552851-4fce-4c30-a06e-2518c59dba9d] received
paperless-ngx-webserver-1  | [2023-11-18 17:33:34,008] [WARNING] [paperless.barcodes] No pages to split on!
paperless-ngx-webserver-1  | [2023-11-18 17:33:34,049] [INFO] [paperless.consumer] Consuming 2023-11-18 11182023172628.pdf
paperless-ngx-webserver-1  | [2023-11-18 17:33:34,434] [INFO] [ocrmypdf._sync] Start processing 3 pages concurrently
paperless-ngx-webserver-1  | [2023-11-18 17:33:34,438] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
paperless-ngx-webserver-1  | [2023-11-18 17:33:34,438] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
paperless-ngx-webserver-1  | [2023-11-18 17:33:34,439] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
paperless-ngx-webserver-1  | [2023-11-18 17:33:34,444] [INFO] [ocrmypdf._sync] Postprocessing...
paperless-ngx-webserver-1  | [2023-11-18 17:33:34,893] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
paperless-ngx-webserver-1  | [2023-11-18 17:33:36,103] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.05 savings: 4.7%
paperless-ngx-webserver-1  | [2023-11-18 17:33:36,103] [INFO] [ocrmypdf._pipeline] Total file size ratio: 0.95 savings: -5.4%
paperless-ngx-webserver-1  | [2023-11-18 17:33:36,113] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
paperless-ngx-webserver-1  | [2023-11-18 17:33:38,265] [INFO] [paperless.consumer] Document 2023-11-18 2023-11-18 11182023172628 consumption finished
paperless-ngx-webserver-1  | [2023-11-18 17:33:38,279] [INFO] [celery.app.trace] Task documents.tasks.consume_file[b4552851-4fce-4c30-a06e-2518c59dba9d] succeeded in 6.238036611001007s: 'Success. New document id 25 created'
```

PDF: 
[2023-11-18 11182023172626.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13401631/2023-11-18.11182023172626.pdf)
