### DISCUSSION TITLE
docker-compose on ubuntu with existing mysql database

### DISCUSSION THREAD

**Discussion by mthome1** [paperless-ngx/paperless-ngx#4643] [Support] [answered]
Hello, 

I recently installed paperless-ngx with the docker-compose install script on my Ubuntu Server (which has mysql running for my fhem installation).

Setup of paperless-ngx went without any problems, however, when I check my filesystem on the db-directory which i use for paperless-ngx, it shows a different user.

Here is the relevant part of my yaml:
```
db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - /opt/paperless-ngx/db:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
```

But when I do a ls -l on /opt/paperless-ngx I see the following:
```
mthome@hermine:/opt/paperless-ngx$ ls -l
total 24
drwxr-xr-x 2 mthome mthome 4096 Nov 17 18:53 consume
drwxr-xr-x 4 mthome mthome 4096 Nov 19 15:05 data
drwxr-xr-x 6 fhem      999 4096 Nov 17 18:52 db
-rw-rw-r-- 1 mthome mthome  147 Nov 16 17:06 docker-compose.env
-rw-rw-r-- 1 mthome mthome 2503 Nov 16 17:06 docker-compose.yml
drwxr-xr-x 2 mthome mthome 4096 Nov 16 17:07 export
lrwxrwxrwx 1 mthome mthome   30 Nov 17 18:52 media -> /mnt/Data/paperless-ngx_media/
```

My docker-compose ps shows that the db is running as container:

```
mthome@hermine:/opt/paperless-ngx$ docker-compose ps
        Name                       Command                  State                        Ports
----------------------------------------------------------------------------------------------------------------
paperless_broker_1      docker-entrypoint.sh redis ...   Up             6379/tcp
paperless_db_1          docker-entrypoint.sh mariadbd    Up             3306/tcp
paperless_webserver_1   /sbin/docker-entrypoint.sh ...   Up (healthy)   0.0.0.0:8000->8000/tcp,:::8000->8000/tcp

```
Any idea, what I am doing wrong that the db-files in /opt/paperless-ngx/db  use the fhem user? My expectation would be that db has the same user/group as the other files.

**Comment by stumpylog** [comment]
You created a container for the databsae and pointed paperless to it.  I'm not sure why you think that would use an existing database instance/container instead.  You would need to provide the host for your database at a minimum, and probably different, pre-configured password/username, depending on what you have created in that database

**Reply by mthome1** [reply]
I think you got me wrong. I expect that the docker database is used and the files that are written belong to the same user as the docker user.
However, what I see ist that the files are written by the fhem user  and not mthome.

**Reply by stumpylog** [reply]
Then you would need to configure your MariaDB container with a user.  In a compose file, that's the `user:` key.  If may take additional setup, such as mapping `/etc/passwd`.  They don't provide documentation that I can find for it (like Postgres does), so you'll probably need to do more research if you encounter errors.

**Reply by mthome1** [reply]
Ok, thanks very much. One more question as I guess I do not really understand (maybe you know). Why does docker use the user mthome for consume, data, media and export and the user fhem for the database?

Has it something todo with the container/image docker.io/library/mariadb:10 itself?

I startet the docker-compose with the user mthome. So what makes docker use the user fhem?

Here my yaml:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - /opt/paperless-ngx/db:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /opt/paperless-ngx/data:/usr/src/paperless/data
      - /opt/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /opt/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306


volumes:
  redisdata:

```
