### DISCUSSION TITLE
chmod: changing permissions of '/var/run/postgresql': Operation not permitted

### DISCUSSION THREAD

**Discussion by steakhutzeee** [paperless-ngx/paperless-ngx#4662] [Support] [answered]
Hi, starting my database container noted this in the logs:

`chmod: changing permissions of '/var/run/postgresql': Operation not permitted`

After this the container starts without issues. 

In the database section of the compose I'm using `user: 1000:100
`
This could be the problem? 
Thanks!

**Comment by stumpylog** [comment, marked as answer]
You would probably find more help looking at the Postgres discussions and issues, not the paperless ones

**Reply by woessmich** [reply]
Hi
I agree, and then I don‘t.

@steakhutzeee : Did you solve it?

Getting postgres to run seems either to require some advanced knowledge, or it is just luck.
How it looks, there are many variables at play depending on the host system, some strange user and permission situations, if volumes are mounted ad NFS or CIFS and maybe more.

But, if paperless-ngx is supposed to become THE document archive system for the masses, and I believe it has the potential to do so, there needs to be a robust way to get it up and running. I am wondering how many potential users gave up frustrated because of such errors.

I have my system running on a NUC with a Synology hosting the persistent volumes, and it works.
And I love it!
But it runs only just so and only if I use NFS shares (a least for some folders, I did not check all combinations).

I am currently trying to run it with the volumes on an Unraid storage, and can‘t even get the most simple postgres example to run.
I admit, this is in no way a problem of paperless-ngx, but I believe there must be ways to address these very common postgres problems and have it included in the docs.
Actually, is a problem of paperless-ngx as postgres was selected as a database.

If even this below gives the following error in the log, how would we expect paperless to get going?

`initdb: error: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data ...  `

Why is the operation not permitted?
Is something wrong with permissions? What? Where?
Wrong user? What user, where, what to change, what to put?
People just do not know and many „solutions“ I found are not applicable, incorrect or outright nonsense.
There must be ways…

```
 # Use postgres/example user/password credentials
version: '3.1'

volumes:
  pgdata:
    driver_opts:
      #type: "nfs"
      #o: "addr=192.168.1.189,rw,nfsvers=4"
      #device: ":/mnt/user/dockerdata/postgrestest"
      type: "cifs"
      o: "username=docker-rw,password=.docker."      
      device: "//192.168.1.189/dockerdata/postgrestest"

services:

  db:
    image: postgres
    restart: always
    #user: 100:99
    environment:
      POSTGRES_PASSWORD: example
      #PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

``` 

i left in the commented out options that do not work also.
