### DISCUSSION TITLE
restoring from backup

### DISCUSSION THREAD

**Discussion by swdit** [paperless-ngx/paperless-ngx#4677] [Support]
Hi, i need help please.
I had paperless-ngx running on a rasperry pip in docker, initially set up via the quickinstall sh.
Now I crashed it on a rebuild when trying to do some speed optimizations.

Should not be a problem I backuped the 4 main folder (data, consume/drop, media, export)

The thing is that after "docker compose up" it openens up a fresh empty database even without a superuser instead of using the sqlite db i pushed into the folder path spcified in the docker-compose.yml

What am I doing wrong?

YML:
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data


  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/admin/paperless-ngx/data:/usr/src/paperless/data
      - /home/admin/paperless-ngx/media:/usr/src/paperless/media
      - /home/admin/paperless-ngx/export:/usr/src/paperless/export
      - /home/admin/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  redisdata:
```

ENV:
```

APERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_SECRET_KEY=xxxxxxxxx....
PAPERLESS_CONSUMER_POLLING=60
PAPERLESS_TASK_WORKERS=2

```
