### DISCUSSION TITLE
Error connecting to redis in docker swarm

### DISCUSSION THREAD

**Discussion by felix-exon** [paperless-ngx/paperless-ngx#4686] [Support]
I get the following error, starting up the webserver image:
`Error: Error 99 connecting to localhost:6379. Cannot assign requested address..`

I am in a docker swarm environment with the following compose file:

```yml
version: "3.0"
services:
  
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - internal
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped 
    depends_on:
      - broker
      - databases_mariadb
    ports:
      - "8766:8000"
    networks:
      - cloudflare_network
      - databases_network
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume1/docker/paperless-ngx/data:/usr/src/paperless/data
      - /volume1/docker/paperless-ngx/media:/usr/src/paperless/media
      - /volume1/docker/paperless-ngx/export:/usr/src/paperless/export
      - /volume1/docker/paperless-ngx/consume:/usr/src/paperless/consume    
    environment:
      - PAPERLESS_URL=https://paperless.mydomain.com
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_REDIS_PREFIX=paperless
      - USERMAP_UID=1026
      - USERMAP_GID=100
      - PAPERLESS_TIME_ZONE=Europe/Berlin
      - PAPERLESS_OCR_LANGUAGE=deu
      - PAPERLESS_SECRET_KEY=<some-key>
      - PAPERLESS_ADMIN_USER=adm_xxxxx
      - PAPERLESS_ADMIN_PASSWORD=xxxxx      
      - PAPERLESS_DBENGINE=mariadb
      - PAPERLESS_DBHOST=databases_mariadb
      - PAPERLESS_DBUSER=paperless
      - PAPERLESS_DBPASS=xxxxxxxx
      - PAPERLESS_DBPORT=3306
      - PAPERLESS_EMAIL_TASK_CRON="*/5 * * * *"
  
networks:
  internal:
    driver: overlay
  cloudflare_network:
    external: true  
  databases_network:
    external: true
    
volumes:
  redisdata:
```

to my understanding the redis used should be `redis://broker:6379` but the logs suggest it is using `localhost:6379`.

Any idea, how to fix that?
