### DISCUSSION TITLE
Can't login after update to 2.0.1

### DISCUSSION THREAD

**Discussion by Man-in-Black** [paperless-ngx/paperless-ngx#4755] [Support] [answered]
### Description

I just wanted to update my installation from 1.14.5 to 2.0.1 via docker.
The update itself works fine, but I'm not able to login anymore with my exisiting users.
I got the following error on the web
<img width="295" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9048534/d74261d0-f6d8-446d-8187-2eb33ed3908e">
and the following entry in the logfile:
`paperless    | [2023-12-01 22:09:29,743] [INFO] [paperless.auth] Login failed for user `xxx` from ip....`

### Steps to reproduce

1. Update docker via the official guide (https://docs.paperless-ngx.com/administration/#docker-updating)
2. try to login

### Webserver logs

```bash
paperless    | [2023-12-01 22:09:29,743] [INFO] [paperless.auth] Login failed for user `xxx` from ip....
```

### Paperless-ngx version

2.0.1

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Edge

**Comment by stumpylog** [comment]
The LSIO image is not supported here.  And no longer updated

**Comment by Man-in-Black** [comment]
Oh man, that was my mistake, I'm using the official docker image, must be accidentaly changed the field...
I couldn't have done the update if it was a linuxserver.io image to version 2.0.1

**Comment by stumpylog** [comment]
Either way, I can't reproduce this, going from any version to another.  I can't read the error message, but I would suspect it's something about a password being wrong?  Not something that changes version to version

**Comment by trevon88** [comment]
maybe same probleme like me: try paperless and paperless

Because when i updatet, login dosnt work, so i try it like this, and see there, it works. BUT i Lost the full Index then.... not shure whats diffrent to 2.0.1......

**Comment by Man-in-Black** [comment]
I did the following:
`docker-compose down; docker-compose pull; docker-compose up -d; docker-compose logs -f`
Nothing more.
How can it be that the login did not work anymore?
The password is definitly correct, I logged in with it right before the update.

These are the logs related to it:
```
paperless    | 2023-12-01 21:49:00,526 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
paperless    | 2023-12-01 21:49:00,526 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
paperless    | 2023-12-01 21:49:00,526 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
paperless    | 2023-12-01 21:49:00,526 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
paperless    | [2023-12-01 22:49:00,572] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
paperless    | [2023-12-01 22:49:00,587] [INFO] [celery.apps.worker] celery@847bf08e951b ready.
paperless    | [2023-12-01 22:49:00,597] [INFO] [celery.beat] beat: Starting...
paperless    | /usr/local/lib/python3.11/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
paperless    |   warnings.warn(
paperless    | [2023-12-01 22:49:33,904] [INFO] [paperless.auth] Login failed for user `xxx` from IP `2a02:810d:4b3f:e5a8:...`.
paperless    | [2023-12-01 22:49:37,973] [INFO] [paperless.auth] Login failed for user `yyy` from IP `2a02:810d:4b3f:e5a8:...`.
paperless    | [2023-12-01 22:49:45,705] [INFO] [paperless.auth] Login failed for user `zzz` from IP `2a02:810d:4b3f:e5a8:...`.
paperless    | [2023-12-01 22:50:00,001] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
paperless    | [2023-12-01 22:50:00,007] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[39e62370-5b9a-48b0-a8e7-2d92e7a03f31] received
paperless    | [2023-12-01 22:50:00,043] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[39e62370-5b9a-48b0-a8e7-2d92e7a03f31] succeeded in 0.03490096516907215s: 'No new documents were added.'
```

paperless / paperless also didn't work.

**Comment by Man-in-Black** [comment]
I hope someone have a hint, I'd love to use the new version because I want to make use of the new custom fields.

**Reply by shamoon** [reply]
create a superuser and then login, edit the other user

**Reply by Man-in-Black** [reply]
I've done it, but now all other users are gone.
I followed the instructions in the docs, but after I created a new superuser all existing data is gone.

**Reply by shamoon** [reply]
My guess is the data mount wasnt correctly created, for example it was in a way that didnt actually persist after recreating the container.

**Reply by Man-in-Black** [reply]
Thank you for this hint.
Indeed, the content of the mountpoint within the docker looks different as from outside the docker container.
inside:
<img width="548" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9048534/c6431146-74db-40d0-9341-93e197357b32">
outisde:
<img width="548" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9048534/0fd17b2f-d54d-4cd3-bb1a-43c7f5851fce">

The part in the compose file looks like this:
```yml
  webserver:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8012:8000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume1/docker/paperless/data:/usr/src/paperless/data
      - /volume1/docker/paperless/media:/usr/src/paperless/media
      - /volume1/docker/paperless/export:/usr/src/paperless/export
      - /volume1/docker/paperless/Inbox:/usr/src/paperless/consume
    environment:
```

any idea why this happens?
