### DISCUSSION TITLE
Losing Data / Index after Update "Stack" from 1.17.4

### DISCUSSION THREAD

**Discussion by trevon88** [paperless-ngx/paperless-ngx#4788] [Support] [answered]
Hello, I want to update Paperless. I use Portainer and stacks. My settings look like this. Currently, I am on version: 1.17.4 Here is the stack:

```
services:
  redis:
    image: redis:6.2
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
      - ./redis:/data

  db:
    image: postgres:14
    container_name: paperless-db
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $PGDB
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPW

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperlessngx
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - gotenberg
      - tika
    ports:
      - 8777:8000
    volumes:
      - /mnt/data:/usr/src/paperless/data
      - /mnt/media:/usr/src/paperless/media
      - /mnt/export:/usr/src/paperless/export
      - /mntscan:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: $PUID 
      USERMAP_GID: $PGID 
      PAPERLESS_TIME_ZONE: $TZ
      PAPERLESS_ADMIN_USER: $ADMINUSER
      PAPERLESS_ADMIN_PASSWORD: $ADMINPW
      PAPERLESS_OCR_LANGUAGE: deu+eng #change as necessary, read the documentation for more info
      PAPERLESS_FILENAME_FORMAT: '{created_year}/{correspondent}/{title}'

      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000 #don't change
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998 #don't change
      PAPERLESS_CONSUMER_POLLING: 60
      
    networks:
      - default
#uncomment the following line and change the network name as necessary to add the webserver to your reverse proxy network
      #- proxy

  gotenberg:
    image: gotenberg/gotenberg:7.4
    restart: unless-stopped
    container_name: gotenberg
    ports:
      - 3000:3000 # change the port mapping if you need
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
  
  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: tika
    ports:
      - 9998:9998 # change the port mapping if you need
    restart: unless-stopped    

networks:
  default:
    name: paperless
    ipam:
      config:
        - subnet: 172.18.0.0/16 #change the subnet as necessary
#uncomment the following lines and change the network name as necessary to add your reverse proxy network
  #proxy: 
    #external: true
```

When I update, Paperless loses its current user, as well as all data (indexing) -> Paperless shows 0 data. What am I doing wrong? Are there possibly versions incompatible with each other? I ask especially since the small version jumps worked without problems with the update. (Simply pull the new versions)

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/74497490/28565b8c-3f5b-46a1-8a18-d0fadb63e937)
