### DISCUSSION TITLE
function consume from directory is not installed (docker)

### DISCUSSION THREAD

**Discussion by paulsommer** [paperless-ngx/paperless-ngx#4808] [Support] [answered]
Hello,
I am still struggeling with the setup of paperless-ngx.

After executing enstall-paperless-ngx.sh I got the following  docker-compose.yml:
```
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - /home/paperless/DB:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/paperless/data:/usr/src/paperless/data
      - /home/paperless/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/paperless_consume:/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:

```
I don't see any entry for a consumer. Shouldn't there be one.
Some further infos:
```
$ docker image ls
REPOSITORY                            TAG       IMAGE ID       CREATED        SIZE
mariadb                               10        cc28c72eefe7   2 days ago     404MB
ghcr.io/paperless-ngx/tika            latest    2a81de987ac5   3 days ago     359MB
ghcr.io/paperless-ngx/paperless-ngx   latest    5a46a33687ff   4 days ago     1.4GB
redis                                 7         961dda256baa   3 weeks ago    138MB
gotenberg/gotenberg                   7.8       436e3cc07c4c   6 months ago   1.54GB
```
```
$ docker compose ps
NAME                    IMAGE                                        COMMAND                  SERVICE             CREATED             STATUS                    PORTS
paperless-broker-1      docker.io/library/redis:7                    "docker-entrypoint.s…"   broker              20 hours ago        Up 22 minutes             6379/tcp
paperless-db-1          docker.io/library/mariadb:10                 "docker-entrypoint.s…"   db                  20 hours ago        Up 22 minutes             3306/tcp
paperless-gotenberg-1   docker.io/gotenberg/gotenberg:7.8            "/usr/bin/tini -- go…"   gotenberg           20 hours ago        Up 22 minutes             3000/tcp
paperless-tika-1        ghcr.io/paperless-ngx/tika:latest            "/bin/sh -c 'exec ja…"   tika                20 hours ago        Up 22 minutes             9998/tcp
paperless-webserver-1   ghcr.io/paperless-ngx/paperless-ngx:latest   "/sbin/docker-entryp…"   webserver           20 hours ago        Up 22 minutes (healthy)   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp
````

Shouldn't there be a **paperless_consumer_1** ? The documentation suggests that.

How can I include the consume part here?
