### DISCUSSION TITLE
How to move the Media folder to my Synology NAS?

### DISCUSSION THREAD

**Discussion by JClishe** [paperless-ngx/paperless-ngx#4843] [Support] [answered]
I'm running Paperless on a Docker container on a Raspberry Pi. I've successfully moved the Consume folder to my NAS; When I drop files in the Synology consume folder, Paperless imports them. But when I point the Media volume at my Synology, new documents never end up there and the Synology's media folder remains empty.

Here's my folder structure on the Synology: 

![image](https://github.com/paperless-ngx/paperless-ngx/assets/32135828/c6abc3d0-e0c1-45ce-a0c3-a8021dc3738b)

And the full path:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/32135828/a9ba5dcd-ec46-40b3-999b-a4878d3f55da)

Here are the relevant pieces of my Docker compose file. Any ideas why documents aren't being saved to the media folder on my Synology?
```yaml
version: "3.4"
services:
  ...

  webserver:
    ...
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
    env_file: docker-compose.env

volumes:
  data:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=10.118.97.11,nolock,soft,rw,nfsvers=4"
      device: ":/volume1/containers/paperless/media/"
  pgdata:
  redisdata:
  consume:
    driver_opts:
      type: "nfs"
      o: "addr=10.118.97.11,nolock,soft,rw,nfsvers=4"
      device: ":/volume1/containers/paperless/consume/"
```
