### DISCUSSION TITLE
Browser slowdown with many correspondents

### DISCUSSION THREAD

**Discussion by Philippe-M** [paperless-ngx/paperless-ngx#4872] [General]
Hello everyone,

I am currently testing paperless v2.1 with data similar to a production version. My test configuration is based on Docker with the minimum number of programs running on this PC. I retrieved the docker-compose-mariadb.yml with a few minor adaptations in order to access the database from outside the container to import data (corresponding).

Before importing the data, I perform the basic setup and then import a document. Everything goes well and it works. Afterward, I directly import my data into the 'documents_correspondant' table, which represents 13190 records. Once the import is finished, I return to the paperless UI, load the correspondents' page to ensure that everything is okay. It works fine.

I return to the documents page, and the issues begin. The page loading time is slow, to the extent that GNOME informs me that Firefox is not responding and suggests closing it or waiting. A few seconds later, I can use Firefox again. My initially added document is visible, and I want to filter by correspondent. I click on the "Correspondent" button, and once again, Firefox becomes slow.

I launch the Firefox debugger in the network tab and realize that the loading of the selected_correspondents[] table is slowing down Firefox.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/9933d90f-1613-48bb-9101-5f6edffb2bcb)

I try to understand the benefit of loading this entire list when no filter has been requested yet. Since it's a field intended for filtering, it would be better to trigger the query when the user has entered, for example, 3 characters, perhaps by adding an index on the 'name' field in the database.

**docker-compose.yml**

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped 
    volumes:
      - redisdata:/data
    networks:
      - backend      

  db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
    ports:
      - "3306:3306"      
    networks:
      - backend        

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.1
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika      
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./consume:/usr/src/paperless/consume
      - ./scripts/custom-cont-init.d:/custom-cont-init.d:ro      
      - ./export:/usr/src/paperless/export      
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      # with database
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      # --------    
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998      
      #PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless/scripts/post_script.py
    networks:
      - backend

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    networks:
      - backend    
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
    networks:
      - backend  
             
volumes:
  data:
  media:
  dbdata:
  redisdata:

networks:
  backend:
    name: paperless_ngx
```

**CPU usage when loading the documents page**
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/a7fac632-ed14-4a79-b418-7e9f3e09cc6b)

One of the CPU cores reaches 100% (red) and then drops back down once the loading of the 'selected_correspondent' table is completed

Config :
- OS : Fedora 39
- Firefox 120
- Gnome 45.2
- Processeur : 11th Gen Intel® Core™ i7-1165G7 × 8
- RAM : 32G
