### DISCUSSION TITLE
Synology NFS mount, paperless-ngx on raspberry-pi-like computer, chown impossible

### DISCUSSION THREAD

**Discussion by pedrom34** [paperless-ngx/paperless-ngx#4896] [Support]
Hey guys,

I've got a problem I can't solve
My paperless-ngx is throwing chown errors at startup if I set UID and GID to 1000:1000. But it's working anyway...
If I change that the UID/GID to 1024:100, paperless-ngx doesn't start at all.

My instance is on docker-compose (via portainer) on a SBC (not a rapsberry pi, but a Rock64).
The documents are on a distant NFS share served by a synology nas.

My LAN is 192.168.0.X.

I can't find a way to resolve this...
Can you help me?

Here's my docker compose :
```
version: "3.4"
services:
  broker:
    container_name: redis-broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    container_name: paperless-ngx
    image: paperlessngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/dietpi_userdata/containers/paperless/custom-cont-init.d:/custom-cont-init.d:ro
      - /mnt/dietpi_userdata/containers/paperless/data:/usr/src/paperless/data
      - /mnt/docs/Paperless/media:/usr/src/paperless/media
      - /mnt/docs/Paperless/export:/usr/src/paperless/export
      - /mnt/docs/Paperless/00.consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      #PAPERLESS_DBHOST: db
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
      USERMAP_UID: 1000
      USERMAP_GID: 1000
# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
      PAPERLESS_SECRET_KEY: 
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
      PAPERLESS_TIME_ZONE: Europe/Paris
# The default language to use for OCR. Set this to the language most of your
# documents are written in.
      PAPERLESS_OCR_LANGUAGE: fra
      PAPERLESS_CONSUMER_POLLING: 3600
      PAPERLESS_ALLOWED_HOSTS: 'localhost,192.168.0.11,https://paperless.domain'
      PAPERLESS_URL: "https://paperless.domain"
      PAPERLESS_CONSUMER_IGNORE_PATTERNS: '[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini", "@eaDir/*", "@eaDir/*", "@eaDir/SYNO@.fileindexdb/term/**","@eaDir/SYNO@.fileindexdb/**","@eaDir/cloud.tmp.dir/**"]'
      PAPERLESS_OCR_MODE: skip
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: always
      PAPERLESS_WEBSERVER_WORKERS: 1
      PAPERLESS_ENABLE_NLTK: false
      
volumes:
  data:
  media:
  redisdata:
```

Here's my synology nas export:
```
/volume2/docs	10.8.0.0/24(rw,async,no_wdelay,insecure,all_squash,insecure_locks,sec=sys,anonuid=1024,anongid=100)	192.168.0.0/24(rw,async,no_wdelay,insecure,all_squash,insecure_locks,sec=sys,anonuid=1024,anongid=100)
```

Here's my SBC fstab:
```
192.168.0.4:/volume2/docs /mnt/nas/volume2/docs nfs nofail,noauto,x-systemd.automount
```

Here's my SBC passwd:
```
root:x:0:0:root:/root:/bin/bash
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
dietpi:x:1000:1000::/home/dietpi:/bin/bash
```
