### DISCUSSION TITLE
Tags auto assignment not working

### DISCUSSION THREAD

**Discussion by M1scer** [paperless-ngx/paperless-ngx#5038] [Support] [answered]
Hi all,

i am using paperless since a while and have already uploaded more than 500 files.
All my tags, document types, ... do have the auto rule.

But until now it have not yet set on tag by itself.

i am running the docker container behind a traefik proxy on a raspberry pi.
These are my settings in the compose.yml file:

```
paperlessApp:
        container_name: paperlessApp
        hostname: paperlessApp
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        restart: unless-stopped
        depends_on:
          - paperlessDb
          - paperlessRedis
        labels:
          - "traefik.http.routers.paperlessApp.entrypoints=websecure"
          - "traefik.http.routers.paperlessApp.rule=Host(`paperless.xxxx.de`)"
          - "traefik.http.services.paperlessApp.loadbalancer.server.port=8000"
          - "traefik.http.routers.paperlessApp.tls=true"
          - "traefik.http.routers.paperlessApp.tls.certresolver=myresolver"
          - "traefik.http.middlewares.paperlessApp.headers.sslProxyHeaders.X-Forwarded-Proto=https"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8000"]
          interval: 30s
          timeout: 10s
          retries: 5
        volumes:
          - ./paperless/data:/usr/src/paperless/data
          - ./paperless/media:/usr/src/paperless/media
          - ./paperless/export:/usr/src/paperless/export
          - ./paperless/consume:/usr/src/paperless/consume
        
          # Set Timezone
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        environment:
          - "PAPERLESS_URL=https://paperless.xxxx.de"
          - "PAPERLESS_REDIS=redis://paperlessRedis:6379"
          - "PAPERLESS_DBENGINE=mariadb"
          - "PAPERLESS_DBHOST=paperlessDb"
          - "PAPERLESS_DBUSER=paperless" # only needed if non-default username
          - "PAPERLESS_DBPASS=xxxxx" # only needed if non-default password
          - "PAPERLESS_DBPORT=3306"
          
          - "PAPERLESS_OCR_LANGUAGE=deu"
          - "PAPERLESS_OCR_OUTPUT_TYPE=pdf"
          - "PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{title}"
          - "PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true"
          - "PAPERLESS_CONSUMER_ENABLE_BARCODES=true"
          - "PAPERLESS_CONSUMER_RECURSIVE=true"
          - "PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true"
          - "PAPERLESS_TASK_WORKERS=1"
          - "PAPERLESS_THREADS_PER_WORKER=2"
          - "PAPERLESS_WORKER_TIMEOUT=10000"
          - "PAPERLESS_WEBSERVER_WORKERS=1"
          - "PAPERLESS_CONVERT_MEMORY_LIMIT=32"
        networks:
          - traefik
        logging:
          driver: "json-file"
          options:
            max-size: "200k"
            max-file: "5"
```

Any ideas how to debug this?
