### DISCUSSION TITLE
Docker stack not starting the webserver

### DISCUSSION THREAD

**Discussion by braberli** [paperless-ngx/paperless-ngx#5086] [Support]
I use Paperless-ngx in a Docker stack now sucessfully for several month on a Debian 11 host (amd64). For several days I try to move the stack into another Docker environment on a Debian 12 host (arm64). The webserver container does not start successfully. After fixing the user rights issues (volumes could not be mounted), it still stops at this point (and then it is restarted after 6 minutes):
     
```
Paperless-ngx docker container starting...
Installing languages...
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main arm64 Packages [8685 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [11.1 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [127 kB]
Fetched 9075 kB in 6s (1505 kB/s)
Reading package lists...
Package tesseract-ocr-deu already installed!
Package tesseract-ocr-eng already installed!
Package tesseract-ocr-fra already installed!
Mapping UID and GID for paperless:paperless to 139:145
```

In an old documentation, I found PAPERLESS_DEBUG as env, but setting it to true/1 does not give me any other information. Looking into the container (as long as it is running) shows me, that the access to consume and media works well.

Where could I find / enable any sort of logging giving me a hint to find the problem?

What happens in the webserver initialization after Mapping UID and GID for paperless:paperless?
Broker, Tika and Gotenberg start without any problem.

**Comment by stumpylog** [comment]
The next step with output is creating necessary directories if they don't exist.  I would assume that is failing somehow, perhaps permissions?

**Reply by braberli** [reply]
Entering the container, I can see that all volumes are created and for consume and media I can see their content (they are nfs shares).  The user paperless (139) and group paperless (145) exist on the docker host on the nfs server and all directories that are mounted as nfs share (rw in /etc/export on the nfs server) as volume in docker are at the moment writable for everybody (chmod 777). 

I started with the docker compose file from Github and modified the type of volumes which is working for several other stacks in the same environment (and using the same nfs server with same user/group and base directory for rw access).


```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - tika
      - gotenberg	  
    ports:
      - 82:8000
    volumes:
      - type: volume
        source: data
        target: /usr/src/paperless/data
        volume:
            nocopy: true
      - type: volume
        source: media
        target: /usr/src/paperless/media
        volume:
            nocopy: true
      - type: volume
        source: export
        target: /usr/src/paperless/export
        volume:
            nocopy: true
      - type: volume
        source: consume
        target: /usr/src/paperless/consume
        volume:
            nocopy: true
    deploy:  
      replicas: 1

    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: ####MYVALUE####
      PAPERLESS_DBUSER: ####MYVALUE####
      PAPERLESS_DBPASS: ####MYVALUE####
      PAPERLESS_DBNAME: ####MYVALUE####
      PAPERLESS_DBPORT: 3306
      USERMAP_UID: 139
      USERMAP_GID: 145
      PAPERLESS_OCR_LANGUAGES: deu eng fra
      PAPERLESS_SECRET_KEY: ####MYVALUE####
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_TASK_WORKERS: 1
      PAPERLESS_ENABLE_UPDATE_CHECK: 1      
      PAPERLESS_DEBUG: 1
      PAPERLESS_WEBSERVER_WORKERS: 4

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"	  

volumes:
  data:
     driver: local
     driver_opts:
      type: nfs
      o: "addr=####MYVALUE####,nolock,soft,rw"
      device: ":/media/software/docker/paperless/config"
  media:
     driver: local
     driver_opts:
      type: nfs
      o: "addr=####MYVALUE####,nolock,soft,rw"
      device: ":/media/dokumente/paperless"
  export:
     driver: local
     driver_opts:
      type: nfs
      o: "addr=####MYVALUE####,nolock,soft,rw"
      device: ":/media/software/docker/paperless/export"
  consume:
     driver: local
     driver_opts:
      type: nfs
      o: "addr=####MYVALUE####,nolock,soft,rw"
      device: ":/media/dokumente/_posteingang"
  redisdata:
```



Where could I increase the log level and get any output? As written, PAPERLESS_DEBUG doesn't do anything.

**Reply by stumpylog** [reply]
Debug has no effect in the bash startup scripts.  I would suspect the problem is the NFS setup

**Reply by braberli** [reply]
I use exact the same NFS setup for paperless on my former docker host and I use it on the new docker host for a grafana stack where grafana is storing there some persistent data (written by the container). To be sure to avoid user right differences, I started with grafana using the paperless user and group. The grafana directory uses the same nfs export (and another subdirectory).

What is paperless in the startup scripts doing? Which script is running there?

**Reply by braberli** [reply]
I had the chance to log in the webserver's container today and having a look around.

I noticed that the UID/GID settings were not consistent inside the container (started with the docker compose above):

```
me@containerid:/usr/src/paperless# ls -all
total 48
drwxr-xr-x 1      1000 paperless  4096 Dec 16 01:17 .
drwxr-xr-x 1 root      root       4096 Dec  6 03:17 ..
drwxrwxrwx 3 paperless       145 16384 Dec 27 22:14 consume
drwxrwxrwx 2 paperless       145  4096 Dec 27 22:21 data
drwxrwxrwx 2 paperless       145  4096 Dec 23 16:30 export
-rw-r--r-- 1      1000 paperless  1369 Dec  6 03:12 gunicorn.conf.py
drwxrwxrwx 3 paperless       145  4096 Dec 27 21:27 media
drwxr-xr-x 1      1000 paperless  4096 Dec 16 01:15 src
drwxr-xr-x 8      1000 paperless  4096 Dec 16 01:17 static

me@containerid:/usr/src/paperless# id paperless
uid=139(paperless) gid=1000(paperless) groups=1000(paperless)

```

consume, data, export and media are NFS shares and I set paperless to UID 139 and GID 145. **Why is here still UID/GID=1000?** 
`Mapping UID and GID for paperless:paperless to 139:145`
was the last message in the log up to now. 

I could look into the NFS shares from inside the container, but without having the right UID/GID, paperless will not be able to do anything there.

**Reply by braberli** [reply]
Progress:

In an old discussion on paperless (without NGX), I found a thread about leaving out the UID. So, I tried to only set the GID (to 145) and left out the environment value for UID. On the NFS share, I set the owner to 1000 and the group to 145 and paperless webserver in the new docker container could start:

Unfortunately, it hangs now at the creation of the search index (takes a while and the docker container is restarted without any further information).

`Search index out of date. Updating...`

**Reply by braberli** [reply]
Additionally, the creation of the document_classifier seems to fail as it is repeated every hour.
There are no hints to reasons in the logfile (available in the running container).

What do you suggest to analyze to find the problem? Where should I search for problems? Paperless does not tell me too much (even in debug mode there is no hint in the log file).

**Reply by croemmich** [reply]
I'm having the same issue. It appears either the usermod or groupmod is hanging forever. 

```
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 3000:3000
```

Exec-ing into the container and running `id paperless` reveals the uid has been updated, but not the group:
```
uid=3000(paperless) gid=1000(paperless) groups=1000(paperless)
```

**Reply by croemmich** [reply]
I added a custom entrypoint and strace-ed the usermod. It appears usermod is chown-ing everything in `/usr/src/paperless` which is extremely slow on my TrueNAS Scale instance.

**Comment by croemmich** [comment]
I was able to work around the issue with a custom entrypoint:
```
#!/usr/bin/env bash
set -x

chown root:root /usr/src/paperless

usermod -o -u "$USERMAP_UID" paperless
groupmod -o -g "$USERMAP_GID" paperless

chown paperless:paperless /usr/src/paperless

/usr/sbin/docker-entrypoint.sh /usr/local/bin/paperless_cmd.sh
```

The workaround here is the change the ownership of the paperless home directory to root so usermod doesn't chown everything. From the chown man:
>   The change of the user ownership of files inside of the user's home directory is also
   not done if the home dir owner uid is different from the current or new user id. This
   is a safety measure for special home directories such as /.
  
  So far it doesn't seem to be causing any issues.

**Reply by ported-pw** [reply]
If you want to do the same thing with the TrueCharts app version (GUI), just enable "Show advanced settings" and use 3 arguments to build the same command as the script above:
```
/bin/bash
-c
chown root:root /usr/src/paperless; usermod -o -u "$USERMAP_UID" paperless; groupmod -o -g "$USERMAP_GID" paperless; chown paperless:paperless /usr/src/paperless; /usr/sbin/docker-entrypoint.sh /usr/local/bin/paperless_cmd.sh
```
It should look like this:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/34283054/7ed592da-d5b1-4f7a-ba2f-2413699bced2)

**Reply by hanjo** [reply]
Thank you, this seems to have fixed my issue as well. I'm a little bit concerned about side effects though, due to the discussion in the pull request mentioned below...

**Comment by faan11** [comment]
I've added a new pull request https://github.com/paperless-ngx/paperless-ngx/pull/7244 concerning this issue

**Reply by bjoernwuest** [reply]
Any update on this? Also face this problem with a larger paperless installation. Startup takes approx. 8-9 hours! Interstingly, I/O on disks are nearly non-measurable, sometimes going up to 700k/s RW for docker paperless process, but mostly idleing at 0k/s . BTW: fileystem is ZFS, with 128k block size on seven disk RAIDZ3 SAS 15krpm array. RAM is used to 25% only, so this seems not being the issue.
One more addition: counting the files in /usr/src/paperless:
```
.:      10523
./data: 53
./static:       1315
./.gnupg:       0
./export:       0
./src:  914
./consume:      0
./media:        8240
```

**Comment by Merinorus** [comment]
Indeed, as soon as you set the [environment variables](https://docs.paperless-ngx.com/configuration/) `USERMAP_UID` and `USERMAP_GID`, the [map_uidgid()](https://github.com/paperless-ngx/paperless-ngx/blob/a9b7965dcf7129399242858fa29c0462e1100709/docker/docker-entrypoint.sh#L6-L16) function is run at each container start. And that may take a lot of time.

Here is the workaround I did personally: I wrote a new Dockerfile that changes the `paperless` user's UID and GID:

```Dockerfile
FROM ghcr.io/paperless-ngx/paperless-ngx:2.14

ARG PUID=1000
ARG PGID=1000
RUN usermod --non-unique --uid "${PUID}" paperless && groupmod --non-unique --gid "${PGID}" paperless
```

Here is an extract of my `docker-compose.yml`:
```yaml
  ...
  paperless:
    container_name: paperless
    build:
      context: ./
      dockerfile: ../dockerfiles/paperless/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      USERMAP_UID: ${PUID}
      USERMAP_GID: ${PGID}
```

This way, the `usermod` command is applied at the end of the container build and the `map_uidgid()` function above won't change anything, because your PUID and PGID already match the built container's user.
It will still take a lot of time during the container build, but at least it will accelerate the container start and may reduce downtime.

Note that build args `PUID` and `PGID` are passed for the container build step, then `USERMAP_UID` and `USERMAP_GID` are passed as environment variables when the container starts. Also, make sure to rebuild your container image.

From what I remember, linuxserver.io has a handy way to change the PUID/PGID while also being rootless, with the S6 overlay scripts. I didn't take the time to investigate more, sorry.
