### DISCUSSION TITLE
automaticly run comand document_exporter  for backups

### DISCUSSION THREAD

**Discussion by boernie77** [paperless-ngx/paperless-ngx#5137] [Support] [answered]
Hi. I installed Paperless-NGX as a docker container in Unraid. Now i want to make automaticly backups. I want to run the command "document_exporter /path/to/export" every day. I tried to make a script via "vim". But vim does not work... and when i don´t use the shell inside the docker, instead using my Terminal on my Mac via ssh, the command "document_exporter /pat/to/export" does not work.

How can i run the command via ssh from my Terminal or how can i run the command automaticly every day inside the docker?

Intersesting is also, that via ssh i don´t see the same folder as inside the docker...

**Comment by stumpylog** [comment, marked as answer]
The command only exists inside the container.  You can execute commands inside a container via script using `docker exec`, for example `docker exec --tty <container-name> document_exporter /export`.  Then trigger the script either manually or via timer.

**Reply by boernie77** [reply]
Thanks! That helps. I now use docker exec -it <container id> document_exporter /usr/src/paperless/export. I got the docker id with "docker ps -a"

**Comment by smseidl** [comment]
@boernie77  - I use the `ofelia` container to schedule my backups.  The official GitHub link is here: https://github.com/mcuadros/ofelia, but I use my own personal built version based on a PR pending there (https://github.com/mcuadros/ofelia/pull/184) to at some additional scheduling options (`@midnight` or the `run-on-startup`) that have yet to be merged into the main one.

*Compose*
```
  # Scheduler Service
  scheduler:
    image: ghcr.io/smseidl/ofelia:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/scott/ofelia/paperless_ofelia.ini:/etc/ofelia/config.ini
    depends_on:
      - webserver
    restart: unless-stopped
```

*INI File used by container*    
```
[job-exec "Document Exporter"]
schedule = @midnight
#container = paperlessngx-portainer-webserver-1
container = paperless-webserver-1
command = document_exporter ../export -f
run-on-startup = true
```
