### DISCUSSION TITLE
Consume directory not working on Docker-compose install

### DISCUSSION THREAD

**Discussion by ThisisErm** [paperless-ngx/paperless-ngx#5198] [Support] [answered]
###Any file added to consume directory is ignored and not processed by Paperless

This is my docker-compose.yml file:
```
`version: '3'

services:

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    ports:
      - "8010:8000"
    environment:
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_DBENGINE=django.db.backends.postgresql
      - PAPERLESS_DBHOST=postgres
      - PAPERLESS_DBPORT=5432
      - PAPERLESS_DBUSER=paperless
      - PAPERLESS_DBPASS=paperless
      - PAPERLESS_DBNAME=paperless
      - PAPERLESS_CONSUMPTION_DIR=/consume
      - PAPERLESS_ADMIN_USER=admin
      - PAPERLESS_ADMIN_PASSWORD=pass
    depends_on:
      - redis
      - postgres
   
  redis:
    image: redis:alpine

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_DB: paperless`

```
I'm not specifically devlaring volumes because Paperless seems to create it's own by default and I end up with duplicates. With this compose file paperless creates 4 volumes (consume, data, export, and media).

The consume volume is mapped to the container as `/usr/src/paperless/consume`

I can navigate to this container via the command line and manually add files to it or create test files on it but none of these files appear to be noticed by Paperless.

The logs show no errors and do not appear to show any action at all when a file is added to this directory, and the file does not show in the Paperless web ui.

I have checked the directory permissions and they match the permissions of the Docker user. I have also tried as the root user.

###Steps to Reproduce:
1. `touch docker-compose.yml`
2. `nano docker-compose.yml`
3. configure file, crtl+0 , crtl+x
4. `docker-compose up`
5. inspect container configuration via Portainer to get the volumes and identify "consume" volume.
6. cd into consume volume
7. Add test file either by moving, copying, or creating a new file
8. Monitor the app's running terminal for any action.[None]
9. Review the Paperless logs for any errors.[None]

**Comment by shamoon** [comment]
Did you leave off the volume mapping from your copy paste above? Because I don’t see any. I’d make sure they’re working from inside the paperless container

**Comment by ThisisErm** [comment]
Sorry. I did leave them out. Here's the volume config:

```
   volumes:
      - consume:/usr/src/paperless/consume
      - export:/usr/src/paperless/export
      - media:/usr/src/paperless/media
      - data:/usr/src/paperless/data
```

And they are declared at the top level at the end of the file:

```
volumes:
  consume:
  export:
  media:
  data:
```
With this configuration, Paperless is using 4 local volumes I created for the app with this setup

```
Host/volume      |   Path in container
paperless_media  |  /usr/src/paperless/media
paperless_export |  /usr/src/paperless/export
paperless_consume|  /usr/src/paperless/consume
paperless_data   |  /usr/src/paperless/data
```

The volumes seem to be working properly. When I upload a file via the Paperless web ui, I immediately see the action in the logs (e.g. file name, procesing, documents.tasks.consume, success, etc.)

Then I navigate to the media/original directory and see my file there, as well as see the file on the Paperless web ui, but when I add a file to the consume directory nothing happens. Do you think its something with my volumes?
