### DISCUSSION TITLE
scan_06.01.2024_02:43:43.pdf [Errno 13] Permission denied: '/usr/src/paperless/media/media.lock

### DISCUSSION THREAD

**Discussion by Dvalin21** [paperless-ngx/paperless-ngx#5265] [Support]
Hey guys.

This is not a bug, more of a need of advice. So I'm using the following docker container with Paperless-ngx

https://github.com/manuc66/node-hp-scan-to

and the compose is 

```
  node-hp-scan-to:
    image: manuc66/node-hp-scan-to:latest
    container_name: PaperlessNGX-HP-Scanner
    hostname: HPrinter
    environment:
      - IP=address
      - PATTERN="scan"_dd.mm.yyyy_hh:MM:ss
      - PGID=1026
      - PUID=100
      - TZ=America/Chicago
    volumes:
      - /volume1/docker/paperlessngx/consume:/scan:rw
    restart: always
```
I finally got it to work with my printer, HP Officejet Pro 8020 Series  flawless,
however, the issue I'm having is that when scanning to the consume folder as you can see I mounted, I get from error

scan_06.01.2024_02:43:43.pdf [Errno 13] Permission denied: '/usr/src/paperless/media/media.lock

Paperless is recognizing that its being saved, but the moment its finished it denies it and then deletes it. It even shows up in Paperless as being processed or scanned. Anyway, point being, how do I give the hp-scanner docker permission to scan documents into the consume folder?  Thanks.

**Comment by stumpylog** [comment]
That's a permissions error with your media folder, not the scanner (yet).  You should confirm paperless owns the folder and can create files there.

**Reply by Dvalin21** [reply]
it does own the folder. However, I switched to the consume folder since it would seem all files process through this folder before going over to the documents folder. But still I get -13 permission error there as well. This tool would be great if I can figure out why the permission are locked down. 
For more information, Im using the install config from marius hosting 
https://mariushosting.com/synology-install-paperless-ngx-with-office-files-support/

```
version: "3.9"
services:
  redis:
    image: redis:7
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    container_name: PaperlessNGX-REDIS
    hostname: paper-redis
    mem_limit: 512m
    mem_reservation: 256m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/paperlessngx/redis:/data:rw
    environment:
      TZ: Europe/Bucharest
    restart: on-failure:5

  db:
    image: postgres:16
    container_name: PaperlessNGX-DB
    hostname: paper-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "paperless", "-U", "paperlessuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/paperlessngx/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperlessuser
      POSTGRES_PASSWORD: paperlesspass
    restart: on-failure:5

  gotenberg:
    image: gotenberg/gotenberg:latest
    container_name: PaperlessNGX-GOTENBERG
    hostname: gotenberg
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-disable-routes=true"
      - "--chromium-allow-list=file:///tmp/.*"
    restart: on-failure:5

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: PaperlessNGX-TIKA
    hostname: tika
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    restart: on-failure:5

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: PaperlessNGX
    hostname: paperless-ngx
    mem_limit: 6g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8777:8000
    volumes:
      - /volume1/docker/paperlessngx/data:/usr/src/paperless/data:rw
      - /volume1/docker/paperlessngx/media:/usr/src/paperless/media:rw
      - /volume1/docker/paperlessngx/export:/usr/src/paperless/export:rw
      - /volume1/docker/paperlessngx/consume:/usr/src/paperless/consume:rw
      - /volume1/docker/paperlessngx/trash:/usr/src/paperless/trash:rw
    environment:
      PAPERLESS_REDIS: redis://:redispass@paper-redis:6379
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBHOST: paper-db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperlessuser
      PAPERLESS_DBPASS: paperlesspass
      PAPERLESS_TRASH_DIR: ../trash
      PAPERLESS_FILENAME_FORMAT: '{created_year}/{correspondent}/{document_type}/{title}'
      PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD: 6
      PAPERLESS_TASK_WORKERS: 1
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Bucharest
      PAPERLESS_ADMIN_USER: marius
      PAPERLESS_ADMIN_PASSWORD: mariushosting
      PAPERLESS_URL: https://paperlessngx.yourname.synology.me
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperlessngx.yourname.synology.me
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      tika:
        condition: service_started
      gotenberg:
        condition: service_started
```

Tried changing up the docker compose for hp-tool 

```
  node-hp-scan-to:
    image: manuc66/node-hp-scan-to:latest
    container_name: PaperlessNGX-HP-Scanner
    hostname: HPrinter
    volumes:
      - /volume1/docker/paperlessngx/consume:/scan:rw
      - /volume1/docker/paperlessngx/config:/app/config:rw
      - /volume1/docker/paperlessngx/hp-scan:/hp-scan:rw
    environment:
      - DIR=/scan
      - TEMP-DIR=/hp-scan
      - IP=10.0.0.33
      - RESOLUTION=300
      - PATTERN="scan"_dd.mm.yyyy_hh:MM:ss
      - TZ=America/Chicago
      - USERMAP_UID=1026
      - USERMAP_GID=100
    restart: always
```
After I restart the docker, it may or may not find the documents that I've tried to scan.
