### DISCUSSION TITLE
Paperless has noting after restore

### DISCUSSION THREAD

**Discussion by alephtaph** [paperless-ngx/paperless-ngx#5294] [Support]
Hi everyone

I had Paperless_ngx installed as a docker installation on my Synology NAS where it worked flawlessly. During the replacement of my NAS one drive got corrupted and I needed load the new NAS with a full restore from a backup.

I got now everything back working besides Paperless_ngx. I just can't get it to work. I had a previous case here when I got the error that the DB is corrupt. But even with a different restore from the volume folder it is not working.

Now I use this compose:

```yaml
version: "2.1"
services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    environment:
      - PUID=1000
      - PGID=100

      - PAPERLESS_OCR_LANGUAGE=deu
      - PAPERLESS_URL=https://dms.xxx.ch
      - PAPERLESS_SECRET_KEY=xxx
      - PAPERLESS_FILENAME_FORMAT={created_year}/{title}
      - PAPERLESS_ADMIN_USER=xxx
      - PAPERLESS_ADMIN_PASSWORD=xxx
      - PAPERLESS_OCR_MODE=skip
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_MEDIA_ROOT=/media
      - PAPERLESS_DATA_DIR=/data
      - PAPERLESS_CONSUMPTION_DIR=/consume
      - PAPERLESS_TIME_ZONE=CET
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://10.0.0.12:3000
      - PAPERLESS_TIKA_ENDPOINT=http://10.0.0.12:9998
    volumes:

      - /volume1/docker/paperless_ngx/data:/usr/src/paperless/data
      - /volume1/docker/paperless_ngx/media:/usr/src/paperless/media
      - /volume1/docker/paperless_ngx/export:/usr/src/paperless/export
      - /volume1/docker/paperless_ngx/consume:/usr/src/paperless/consume 
      
    ports:
      - 8066:8000
    restart: unless-stopped
    depends_on:
      - broker

  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless_ngx/redisdata:/data
```

My files where in different locations, so I moved it so that it is according to the compose file and the container starts, but I have no documents and no settings.

Is there a way I can import everything again with the document importer or is there a different way to reload. I have tried the sanity check which resulted in - No issue
And also document_index reindex gave me 0it
![image](https://github.com/paperless-ngx/paperless-ngx/assets/82863225/12e82a02-bced-4a7a-a490-7b2423e8a03f)

So thank you for any suggestion and help.

Have a great day.

Marco
