### DISCUSSION TITLE
Possible Celery Handling Bug and/or iNotify?

### DISCUSSION THREAD

**Discussion by Snify89** [paperless-ngx/paperless-ngx#5354] [Support]
I have to admit I am not familiar with the celery and task worker(s) architecture... 
But anyway, I have a lot of documents (over 5000) in my consume folder (and a lot of other small metadata files from another export).
After starting paperless with the consume folder, I think it scanned the entire folder(s) first, puts them in a "queue" and then does its OCR/archiving work.
If the "work" was successfull, it deletes the file in the consume folder, just as expected...
The paperless "queue" seems not be related to celery at all?!

Now, I had to restart my server and so I had to restart paperless (docker) also (I use docker compose down and then up again).
This was done while working (e.g. OCRMYPDF and/or unpaper).
I use 1 Task Worker only and 1 Thread.

After restarting paperless again, I had an additional celery worker added (so 2 in total, though I have configured just 1).
The queue amount seems also to have doubled. (Edit: This might not be the case. )

Doing this again, I can confirm, that another task worker has been added.

Good thing though, I can see really just 1 process doing the OCR/archiving work.

Am I doing someting wrong maybe or is this a bug?

Edit:
My compose file

```yaml
version: "3.4"
services:
broker:
image: docker.io/library/redis:7
restart: unless-stopped
volumes:
- ./redisdata:/data

db:
image: docker.io/library/postgres:15
restart: unless-stopped
volumes:
- ./pgdata:/var/lib/postgresql/data
env_file: postgresconfig.env

webserver:
image: ghcr.io/paperless-ngx/paperless-ngx:latest
restart: unless-stopped
depends_on:
- db
- broker
- gotenberg
- tika
ports:
- "8000:8000"
healthcheck:
test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
interval: 30s
timeout: 10s
retries: 5
volumes:
- ./data:/usr/src/paperless/data
- ./media:/usr/src/paperless/media
- ./export:/usr/src/paperless/export
- /mycustomconsumefolder:/usr/src/paperless/consume
- ./trash:/usr/src/paperless/trash
env_file: paperlessconfig.env

gotenberg:
image: docker.io/gotenberg/gotenberg:7.10
restart: unless-stopped

command:
- "gotenberg"
- "--chromium-disable-javascript=true"
- "--chromium-allow-list=file:///tmp/.*"

tika:
image: ghcr.io/paperless-ngx/tika:latest
restart: unless-stopped
```

These are my settings:

> PAPERLESS_REDIS=redis://broker:6379
> PAPERLESS_DBENGINE=postgresql
> PAPERLESS_DBHOST=db
> PAPERLESS_DBPORT=5432
> PAPERLESS_DBNAME=paperless
> PAPERLESS_DBUSER=paperless
> PAPERLESS_DBPASS=somedbpass
> PAPERLESS_TIKA_ENABLED=true
> PAPERLESS_TIKA_ENDPOINT=http://tika:9998
> PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
> PAPERLESS_TRASH_DIR=/usr/src/paperless/trash
> PAPERLESS_LOGROTATE_MAX_BACKUPS=100
> PAPERLESS_SECRET_KEY=somesecret
> PAPERLESS_ADMIN_USER=someadminuser
> PAPERLESS_ADMIN_MAIL=somemail
> PAPERLESS_ADMIN_PASSWORD=somepassword
> PAPERLESS_OCR_LANGUAGE=deu+eng
> PAPERLESS_OCR_MODE=force
> PAPERLESS_OCR_MAX_IMAGE_PIXELS=9999999999
> PAPERLESS_TASK_WORKERS=1
> PAPERLESS_THREADS_PER_WORKER=1
> PAPERLESS_WORKER_TIMEOUT=999999
> PAPERLESS_TIME_ZONE=Europe/Berlin
> PAPERLESS_CONVERT_TMPDIR=/tmp
> PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
> PAPERLESS_CONSUMER_RECURSIVE=true
> PAPERLESS_NUMBER_OF_SUGGESTED_DATES=5
> PAPERLESS_WEBSERVER_WORKERS=2

Edit: docker compose down deletes also the /tmp folder.
Would this be an issue?

Edit:
I have 3 tasks now which only 1 is actually running.
The other 2 are just "stuck" and might never be consumed or later, when all other documents are consumed (not sure)
