### DISCUSSION TITLE
Attempting to use hp-scan docker with paperless-ngx

### DISCUSSION THREAD

**Discussion by Dvalin21** [paperless-ngx/paperless-ngx#5455] [Support] [answered]
So, I'm able to get paperless-ngx and [hp-scan-to](https://github.com/manuc66/node-hp-scan-to) running. Both in docker.

Here is my docker compose

```
version: "3.9"
services:
  redis:
    image: redis:7
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    container_name: PaperlessNGX-REDIS
    hostname: paper-redis
    mem_limit: 512m
    mem_reservation: 256m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping || exit 1
    volumes:
      - /volume1/docker/paperlessngx/redis:/data:rw
    environment:
      TZ: America/Chicago
    restart: on-failure:5
  db:
    image: postgres:16
    container_name: PaperlessNGX-DB
    hostname: paper-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -q
        - -d
        - paperless
        - -U
        - paperlessuser
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/paperlessngx/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperlessuser
      POSTGRES_PASSWORD: 
    restart: on-failure:5
  gotenberg:
    image: gotenberg/gotenberg:latest
    container_name: PaperlessNGX-GOTENBERG
    hostname: gotenberg
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-disable-routes=true
      - --chromium-allow-list=file:///tmp/.*
    restart: on-failure:5
  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: PaperlessNGX-TIKA
    hostname: tika
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    restart: on-failure:5
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: PaperlessNGX
    hostname: paperless-ngx
    mem_limit: 6g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        - CMD
        - curl
        - -fs
        - -S
        - --max-time
        - "2"
        - http://localhost:8000
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8777:8000
    volumes:
      - /volume1/docker/paperlessngx/data:/usr/src/paperless/data:rw
      - /volume1/docker/paperlessngx/media:/usr/src/paperless/media:rw
      - /volume1/docker/paperlessngx/export:/usr/src/paperless/export:rw
      - /volume1/docker/paperlessngx/consume:/usr/src/paperless/consume:rw
      - /volume1/docker/paperlessngx/trash:/usr/src/paperless/trash:rw
    environment:
      PAPERLESS_REDIS: redis://:redispass@paper-redis:6379
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBHOST: paper-db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperlessuser
      PAPERLESS_DBPASS: 
      PAPERLESS_TRASH_DIR: ../trash
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{document_type}/{title}"
      PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD: 6
      PAPERLESS_TASK_WORKERS: 1
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: America/Chicago
      PAPERLESS_ADMIN_USER: 
      PAPERLESS_ADMIN_PASSWORD: 
      PAPERLESS_URL: https://
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      tika:
        condition: service_started
      gotenberg:
        condition: service_started
  node-hp-scan-to:
    image: manuc66/node-hp-scan-to:latest
    container_name: PaperlessNGX-HP-Scanner
    hostname: HPrinter
    volumes:
      - /volume1/docker/paperlessngx/consume:/scan:rw
      - /volume1/docker/paperlessngx/hp-scan:/tmp/scan-to-hp-scan:rw
      - /volume1/docker/paperlessngx/media/documents:/usr/src/paperless/media/documents:rw
    environment:
      - DIR=/scan
      - TEMP-DIR=/hp-scan
      - IP=10.0.0.33
      - RESOLUTION=300
      - PATTERN="scan"_dd.mm.yyyy_hh:MM:ss
      - TZ=America/Chicago
      - USERMAP_UID=1026
      - USERMAP_GID=100
    restart: always
```
I'm able to scan directly from my printer HP Officeject 8020 series MFP to the tmp folder then to scan (which is mounted to consume on the host side)
When I scan and send something over I get the following permission errors

```
PaperlessNGX-HP-Scanner  | Scan event captured, saving scan #0
PaperlessNGX-HP-Scanner  | Waiting user input: 1/50
PaperlessNGX-HP-Scanner  | Waiting user input: 2/50
PaperlessNGX-HP-Scanner  | Waiting user input: 3/50
PaperlessNGX-HP-Scanner  | Selected shortcut: SavePDF
PaperlessNGX-HP-Scanner  | Scan will be converted to pdf, using /tmp/scan-to-pcCCPaKH as temp scan output directory for individual pages
PaperlessNGX-HP-Scanner  | ScanPlexMode is : Simplex
PaperlessNGX-HP-Scanner  | Afd is : Loaded
PaperlessNGX-HP-Scanner  | New job created: http://10.0.0.33:8080/Jobs/JobList/5
PaperlessNGX-HP-Scanner  | Ready to download page job page 1 at: /Scan/Jobs/5/Pages/1
PaperlessNGX-HP-Scanner  | Page downloaded to: /tmp/scan-to-pcCCPaKH/scan_18.01.2024_10:44:02.jpg
PaperlessNGX-HP-Scanner  | Job state: Completed, totalPages: 1:
PaperlessNGX-HP-Scanner  | Scan of page(s) completed totalPages: 1:
PaperlessNGX-HP-Scanner  | The following page(s) have been rendered inside '/scan/scan_18.01.2024_10:44:01.pdf': 
PaperlessNGX-HP-Scanner  |      - page   1 - 2481x3329
PaperlessNGX             | [2024-01-18 22:44:37,952] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/scan_18.01.2024_10:44:01.pdf to the task queue.
PaperlessNGX-HP-Scanner  | Running iteration: 0 - errorCount: 0
PaperlessNGX-HP-Scanner  | Host destinations fetched: HPrinter
PaperlessNGX-HP-Scanner  | Re-using existing destination: HPrinter - /WalkupScanToComp/WalkupScanToCompDestinations/a299e96b-8cf7-435d-988b-aeff569a246d
PaperlessNGX-HP-Scanner  | Using: HPrinter
PaperlessNGX-HP-Scanner  | Waiting scan event for: /WalkupScanToComp/WalkupScanToCompDestinations/a299e96b-8cf7-435d-988b-aeff569a246d
PaperlessNGX-HP-Scanner  | Start listening for new ScanEvent
PaperlessNGX             | [2024-01-18 22:44:38,638] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[9c21fbf0-81ac-4ead-b51d-c6395055c37e] received
PaperlessNGX             | [2024-01-18 22:44:39,338] [INFO] [paperless.consumer] Consuming scan_18.01.2024_10:44:01.pdf
PaperlessNGX             | [2024-01-18 22:44:53,234] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 27.85 - rotation appears correct
PaperlessNGX             | [2024-01-18 22:45:07,562] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
PaperlessNGX             | [2024-01-18 22:45:08,877] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.12 savings: 11.0%
PaperlessNGX             | [2024-01-18 22:45:08,877] [INFO] [ocrmypdf._pipeline] Total file size ratio: 0.88 savings: -14.2%
PaperlessNGX             | [2024-01-18 22:45:08,879] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
PaperlessNGX             | [2024-01-18 22:45:12,970] [ERROR] [paperless.consumer] The following error occurred while storing document scan_18.01.2024_10:44:01.pdf after parsing: [Errno 13] Permission denied: '/usr/src/paperless/consume/scan_18.01.2024_10:44:01.pdf'
PaperlessNGX             | Traceback (most recent call last):
PaperlessNGX             |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
PaperlessNGX             |     raise exc_info[1]
PaperlessNGX             |   File "/usr/src/paperless/src/documents/consumer.py", line 563, in try_consume_file
PaperlessNGX             |     self.original_path.unlink()
PaperlessNGX             |   File "/usr/local/lib/python3.11/pathlib.py", line 1147, in unlink
PaperlessNGX             |     os.unlink(self)
PaperlessNGX             | PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/consume/scan_18.01.2024_10:44:01.pdf'
PaperlessNGX             | [2024-01-18 22:45:14,088] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[9c21fbf0-81ac-4ead-b51d-c6395055c37e] raised unexpected: ConsumerError("scan_18.01.2024_10:44:01.pdf: The following error occurred while storing document scan_18.01.2024_10:44:01.pdf after parsing: [Errno 13] Permission denied: '/usr/src/paperless/consume/scan_18.01.2024_10:44:01.pdf'")
PaperlessNGX             | Traceback (most recent call last):
PaperlessNGX             |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
PaperlessNGX             |     raise exc_info[1]
PaperlessNGX             |   File "/usr/src/paperless/src/documents/consumer.py", line 563, in try_consume_file
PaperlessNGX             |     self.original_path.unlink()
PaperlessNGX             |   File "/usr/local/lib/python3.11/pathlib.py", line 1147, in unlink
PaperlessNGX             |     os.unlink(self)
PaperlessNGX             | PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/consume/scan_18.01.2024_10:44:01.pdf'
PaperlessNGX             | 
PaperlessNGX             | The above exception was the direct cause of the following exception:
PaperlessNGX             | 
PaperlessNGX             | Traceback (most recent call last):
PaperlessNGX             |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
PaperlessNGX             |     R = retval = fun(*args, **kwargs)
PaperlessNGX             |                  ^^^^^^^^^^^^^^^^^^^^
PaperlessNGX             |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
PaperlessNGX             |     return self.run(*args, **kwargs)
PaperlessNGX             |            ^^^^^^^^^^^^^^^^^^^^^^^^^
PaperlessNGX             |   File "/usr/src/paperless/src/documents/tasks.py", line 171, in consume_file
PaperlessNGX             |     document = Consumer().try_consume_file(
PaperlessNGX             |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PaperlessNGX             |   File "/usr/src/paperless/src/documents/consumer.py", line 577, in try_consume_file
PaperlessNGX             |     self._fail(
PaperlessNGX             |   File "/usr/src/paperless/src/documents/consumer.py", line 116, in _fail
PaperlessNGX             |     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
PaperlessNGX             | documents.consumer.ConsumerError: scan_18.01.2024_10:44:01.pdf: The following error occurred while storing document scan_18.01.2024_10:44:01.pdf after parsing: [Errno 13] Permission denied: '/usr/src/paperless/consume/scan_18.01.2024_10:44:01.pdf'
```
Now, even though it says permission denied from docker logs and logs in paperless, the moment I restart the stack, then paperless is able to detect the pdf and process it or transfer it as normal. Any ideas how I can get this done from start to finish without having to restart the stack each time?  Thanks.
