### DISCUSSION TITLE
Stuck with document_importer when changing from Postgre to MariaDB

### DISCUSSION THREAD

**Discussion by seemedFilm** [paperless-ngx/paperless-ngx#5506] [Support] [answered]
Hi folks,

I'm running on the Export Docker 2.4.0

I've spend now more then 8h on trying and I'm stuck. I was trying this approach: https://www.youtube.com/watch?v=F-NtIbxF6oc
I have a paperless-ngx with Postgre under Portainer (Proxmox) and want to change to use my MariaDB. ((Is the following approach the best one? I couldnt find any better to be honest))

My approach is to document_exporter the docs (which I have now under the folder export and in export.tgz) and then use the document_importer on the new "paperless-ngx-neu" Dockercontainer. 
But any try, the document import with:  `docker-compose exec -T webserverneu document_importer ../export` fails or better nothing happen without any messages.

This is the old stack with Postgre

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    container_name: paperlessngx
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /Paperless-ngx/scripts:/usr/src/paperless/scripts
      - /Paperless-ngx/export:/usr/src/paperless/export
      - /Paperless-ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_SECRET_KEY: PAPERLESS_SECRET_KEY
      #PAPERLESS_ADMIN_USER: admin
      #PAPERLESS_ADMIN_PASSWORD: admin
      PAPERLESS_OCR_LANGUAGE: deu
      #PAPERLESS_PRE_CONSUME_SCRIPT: /usr/src/paperless/scripts/pre-consume.sh
      PAPERLESS_CONSUMER_POLLING: 1
      PAPERLESS_OCR_MODE: skip
      PAPERLESS_URL: PAPERLESS_URL
      USERMAP_UID: 0
      USERMAP_GID: 0

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

This is the new stack with MariaDB:
```
version: "3.4"
services:
  redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /Paperless-ngx-neu/redisdata:/data

  webserverneu:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    container_name: paperlessngxneu
    depends_on:
      - redis
    ports:
      - "8020:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /Paperless-ngx-neu/data:/usr/src/paperless/data
      - /Paperless-ngx-neu/media:/usr/src/paperless/media
      - /Paperless-ngx-neu/scripts:/usr/src/paperless/scripts
      - /Paperless-ngx-neu/export:/usr/src/paperless/export
      - /Paperless-ngx-neu/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: 192.168.1.xx
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBSSLMODE: DISABLED 
      PAPERLESS_SECRET_KEY: PAPERLESS_SECRET_KEY
      #PAPERLESS_ADMIN_USER: admin
      #PAPERLESS_ADMIN_PASSWORD: admin
      PAPERLESS_OCR_LANGUAGE: deu
      #PAPERLESS_PRE_CONSUME_SCRIPT: /usr/src/paperless/scripts/pre-consume.sh
      PAPERLESS_CONSUMER_POLLING: 1
      PAPERLESS_OCR_MODE: skip
      PAPERLESS_URL: PAPERLESS_URL

      USERMAP_UID: 0
      USERMAP_GID: 0


volumes:
  data:
  media:
  pgdata:
  redisdata:
```

The same content is in the docker-compose.yml file (as I understood in the YT
