### DISCUSSION TITLE
OAuth 2.x authentication behind Caddy and oauth2-proxy including REST API support

### DISCUSSION THREAD

**Discussion by hansmi** [paperless-ngx/paperless-ngx#5558] [Feature Requests] [answered]
I was very happy to see remote user support for (unsafe) API endpoints in #5386, but I understand the reasoning for rolling back in #5534.

I'm using Paperless-ngx 2.4.2 behind Caddy and [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) for OAuth2/OIDC authentication[^1]. The authenticated user is sent to Paperless-ngx via an HTTP header. Here's how I re-implemented support for external authentication for unsafe API operations by using a custom settings module:

```python
from django.contrib import auth
from rest_framework import authentication

from .settings import *


class RemoteUserAuthentication(authentication.RemoteUserAuthentication):
  header = HTTP_REMOTE_USER_HEADER_NAME


_REST_DEFAULT_AUTHENTICATION_CLASSES = REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"]
_REST_DEFAULT_AUTHENTICATION_CLASSES.remove("rest_framework.authentication.RemoteUserAuthentication")
_REST_DEFAULT_AUTHENTICATION_CLASSES.insert(0, "paperless.settings_custom.RemoteUserAuthentication")
```

Docker Compose configuration (only the relevant bits):

```yaml
paperless:
  image: ghcr.io/paperless-ngx/paperless-ngx:2.4
  environment:
    - DJANGO_SETTINGS_MODULE=paperless.settings_custom
    - PAPERLESS_ENABLE_HTTP_REMOTE_USER=true
    - PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME=HTTP_X_FORWARDED_EMAIL
  volumes:
    - ./etc/paperless/settings_custom.py:/usr/src/paperless/src/paperless/settings_custom.py:ro
```

Caddy:

```
reverse_proxy http://oauth2:4180 {
  header_up -Remote-*
  header_up -X-Forwarded-*
}
```

[^1]: My [`paperhooks` library](https://github.com/hansmi/paperhooks/) supports OIDC ID tokens using Google Cloud Platform service account keys ([`GCPServiceAccountKeyAuth`](https://pkg.go.dev/github.com/hansmi/paperhooks/pkg/client#GCPServiceAccountKeyAuth)).
