### DISCUSSION TITLE
rclone mount, paperless consume folder not working anymore

### DISCUSSION THREAD

**Discussion by janreinhardt** [paperless-ngx/paperless-ngx#5577] [Support]
My scanner does not scan directly to a drive in my home network. But it does scan documents to Dropbox cloud storage. So I set up an rclone service that mounts my Dropbox account into my paperless-ngx consume folder. Everything looks fine then, the Dropbox files are listed by ls -l inside the consume folder.
But this somehow breaks the consume function? Paperless-ngx does not consume any document anymore after the mount. No Dropbox document but also no document directly copied to the consumer folder by me.
(both services Paperless-ngx and rclone are running in separate Docker containers on a Raspberry Pi 5 using the latest RaspiOS / Debian Bookworm)

When I reverse the order of starting the containers, i.e. first rclone then paperless-ngx, this is the log / error:

```
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Running Django checks
SystemCheckError: System check identified some issues:
ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is set but doesn't exist.
	HINT: Create a directory at /usr/src/paperless/consume
```

Please, is there any solution to this?

**Comment by stumpylog** [comment]
I mean, that's a really clear error message.

**Reply by janreinhardt** [reply]
Sadly, not to me. The consumption directory **does** exist.

**Reply by stumpylog** [reply]
The OS says it does not, and I would generally think it knows what exists on the filesystem.  You haven't shared your compose setup at all, but perhaps you are confusing internal paths with external paths.

**Reply by janreinhardt** [reply]
No, it's not about internal / external paths of the containers. I have got a perfectly working Paperless-ngx install. When I combine it with an Rclone mount into the consume directory -which is also providing the desired results- Paperless stops consuming.
This has got smth to do with the filesystem of my machine I assume, but its more difficult than a missing directory or a confused path.

**Reply by janreinhardt** [reply]
This is the docker compose:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:6.0
    networks:
      - paperless_network
    restart: unless-stopped
    volumes:
      - /home/jan_reinhardt/paperless-ngx/redis/data:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: ${PUID}
      USERMAP_GID: ${PGID}
      PAPERLESS_TIME_ZONE: ${TZ}
      PAPERLESS_URL: ${PAPERLESSURL}
      PAPERLESS_SECRET_KEY: ${RANDOMKEY}
      PAPERLESS_OCR_LANGUAGE: ${LANG}
      PAPERLESS_ADMIN_USER: ${ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${ADMIN_PASS}
    networks:
      - paperless_network
    volumes:
      - /home/jan_reinhardt/paperless-ngx/data:/usr/src/paperless/data
      - /home/jan_reinhardt/paperless-ngx/media:/usr/src/paperless/media
      - /home/jan_reinhardt/paperless-ngx/export:/usr/src/paperless/export
      - /home/jan_reinhardt/paperless-ngx/consume:/usr/src/paperless/consume

networks:
  paperless_network:
```
