### DISCUSSION TITLE
paperlessngx-mariadb on Synology NAS with Docker: django.db.utils.OperationalError: (1130, "Host '192.168.112.6' is not allowed to connect to this MariaDB server")

### DISCUSSION THREAD

**Discussion by trailcafe** [paperless-ngx/paperless-ngx#5616] [Support]
Dear all,

I install paperlessngx with Maria DB on my Synology NAS via portainer with the following compose file:

```yaml
version: "3.4"
services:
  redis:
    image: redis:7
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    container_name: PaperlessNGX-MDB-REDIS
    hostname: paper-redis
    mem_limit: 512m
    mem_reservation: 256m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    volumes:
      - /volume1/docker/paperlessngxmdb/redis:/data:rw
    environment:
      TZ: Europe/Berlin
    restart: on-failure:5

  db:
    image: docker.io/library/mariadb:10
    container_name: PaperlessNGX-MDB-MariaDB
    hostname: paperlessngx-mdb-mariadb
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperlessngxmdb/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
      
  gotenberg:
    image: gotenberg/gotenberg:latest
    container_name: PaperlessNGX-MDB-GOTENBERG
    hostname: gotenberg
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-disable-routes=true"
      - "--chromium-allow-list=file:///tmp/.*"
    restart: on-failure:5
    
  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: PaperlessNGX-MDB-TIKA
    hostname: tika
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    restart: on-failure:5
  
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: PaperlessNGX-MDB
    hostname: paperlessngx-mdb
    mem_limit: 6g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8778:8000"
    volumes:
      - /volume1/docker/paperlessngxmdb/data:/usr/src/paperless/data:rw
      - /volume1/docker/paperlessngxmdb/media:/usr/src/paperless/media:rw
      - /volume1/docker/paperlessngxmdb/export:/usr/src/paperless/export:rw
      - /volume1/docker/paperlessngxmdb/consume:/usr/src/paperless/consume:rw
    environment:
      PAPERLESS_REDIS: redis://:redispass@paper-redis:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: paperlessngx-mdb-mariadb
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TRASH_DIR: ../trash
      PAPERLESS_FILENAME_FORMAT: '{created_year}/{correspondent}/{title} - {tag_list}'
      PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD: 6
      PAPERLESS_TASK_WORKERS: 1
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: paperless
      PAPERLESS_ADMIN_PASSWORD: paperless
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    restart: on-failure:5
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      tika:
        condition: service_started
      gotenberg:
        condition: service_started
```        

Everything is starting but MariaDB gives me the following error:
"django.db.utils.OperationalError: (1130, "Host '192.168.112.6' is not allowed to connect to this MariaDB server")"

The IP address is strange because I am in the range 192.168.178.xxx

Maybe someone has an idea how to solve it. 
Thanks in advance.
