### DISCUSSION TITLE
Help with

### DISCUSSION THREAD

**Discussion by dbathlon** [paperless-ngx/paperless-ngx#5650] [Support]
Hi,

i installed paperless-ngx on proxmox with data, consume, etc folders mounted in my sinology nas. Everything worked fine until I got fsck errors on my proxmox machine. I couldn't get it fixed. So I thought I clone the VM and install paperless-ngx there. Data wouldn't get lost, because I had the mount points on NAS.

So I installed it and changed the folders in the docker-compose.yml, I have access to the NAS but there are no documents in paperless. Have I missed anything? The only problem could be is that I couldn't outsource the database to the nas (I can't remember 100%, because that was 1,5 years ago or so).

Here's the docker-compose.yml

 ```yaml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/datadb:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - - broker
    ports:
      - "8888:8000"
    volumes:
      - /mnt/nas/data:/usr/src/paperless/data
      - /mnt/nas/media:/usr/src/paperless/media
      - /mnt/nas/export:/usr/src/paperless/export
      - /mnt/nas/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

Help appreciated, thanks in advance.
