### DISCUSSION TITLE
Consumer polling stops after a few hours and doesn't consume new content

### DISCUSSION THREAD

**Discussion by oberdon** [paperless-ngx/paperless-ngx#5713] [Support] [answered]
Hi all,
I have installed paperless-ngx in docker on a Raspberry Pi 5 with the installation script. I love the tool!
I host the consume folder and media folder on a Synology NAS that I mounted via cifs. This all works well, and I changed consumption to polling and recursive. It consumes all the files correctly within the first few hours of restart. After running several hours, at some point it stops consuming. I didn't see any obvious error in the log. The NAS folders are still correctly mounted, and restarting the docker images or restarting the PI brings the functionality back. Any idea where the problem could lie? Many thanks for your help!

See my docker-compose.yml:

```yaml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
     - tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - /mnt/PaperlessMedia:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/PaperlessCollector:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      #PAPERLESS_FILENAME_FORMAT: "{title}"
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: 1
      PAPERLESS_CONSUMER_RECURSIVE: 1
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: 1
      #PAPERLESS_OCR_USER_ARGS='{"invalidate_digital_signatures": true}'
      PAPERLESS_CONSUMER_ENABLE_BARCODES: 1

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  pgdata:
  redisdata:
```
