### DISCUSSION TITLE
ODIC: Authelia SSO

### DISCUSSION THREAD

**Discussion by RefineryX** [paperless-ngx/paperless-ngx#5799] [Support] [answered]
Following the enablement of OIDC in the last release https://github.com/paperless-ngx/paperless-ngx/pull/5190, wondering has anyone managed to get this to work with Authelia yet? If so, would you mind sharing your config?

Thinking about implementing however, keen to completely skip the legacy login process in favour of the OIDC provider _(discussed at the end of https://github.com/paperless-ngx/paperless-ngx/pull/5190)_

**Comment by shamoon** [comment, marked as answer]
Yes, it does work.

My compose (or .env or .conf or whatever) changes:

```
PAPERLESS_SOCIALACCOUNT_PROVIDERS: {"openid_connect": {"APPS": [{"provider_id": "authelia","name": "Authelia","client_id": "paperless-ngx","secret": "***","settings": { "server_url": "https://login.domain.com"}}]}}
PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
```

And my Authelia config, which I had setup already but added a new client entry for looks like:

```yaml
identity_providers:
  oidc:
    hmac_secret: ***
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      ***
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 24h
    enable_client_debug_messages: false
    clients:
      ...
      - id: paperless-ngx
        description: Paperless-ngx
        secret: ***
        public: false
        authorization_policy: two_factor
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://paperless.domain.com/accounts/oidc/authelia/login/callback/
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
```

Obviously some of the particulars above can be changed to your needs
