### DISCUSSION TITLE
[Feature Request] Getting EasyOCR to work with paperless-ngx

### DISCUSSION THREAD

**Discussion by deajan** [paperless-ngx/paperless-ngx#6056] [Feature Requests]
### Description

So, tesseract has some pretty terrible results compared to EasyOCR.
Would love to see EasyOCR engine supported.

There's already a more generic discussion about alternative OCR plugins going on at https://github.com/paperless-ngx/paperless-ngx/discussions/5128, but this one is EasyOCR specific.

Since EasyOCR is already supported by a OCRMyPDF plugin, I begun diving into the code in hope to get the plugin to work.

### Here's how far I came:

As long as the ocrmypdf-easyocr plugin is installed, it will be used by ocrmypdf
There are a couple of issues with using the ocrmypdf-easyocr plugin in paperless, of which a couple can be resolved:
- The dependencies are wrong for headless machines (made a PR at https://github.com/ocrmypdf/OCRmyPDF-EasyOCR/pull/6)
- There is no PyPI release yet (created an issue https://github.com/ocrmypdf/OCRmyPDF-EasyOCR/issues/8 and workaround at https://github.com/paperless-ngx/paperless-ngx/compare/dev...netinvent:paperless-ngx:switch-to-easyocr)

There's one big problem that must be solved between paperless-ngx and OCRMyPDF developpers I think...
Perhaps more on the OCRMyPDF side since tesseract integration already works.

When using paperless-ngx with EasyOCR plugin, OCR fails with `AssertionError: daemonic processes are not allowed to have children` error message, since both products use multiprocessing pools (and threading).
I've opened an issue at https://github.com/ocrmypdf/OCRmyPDF-EasyOCR/issues/7 in hope for the OCRMyPDF developper to make the plugin compatible with paperless-ngx

### What's next ?

Hopefully the project developpers can comment on this issue.

**Comment by deajan** [comment]
So I am working on a (stupid) attempt to check whether EasyOCR can be used in paperless-ngx.
So far, I can run the "plugin" and the tool, which will be stuck at the end since I didn't implement an ending condition, but it looks promising since it should get the work done.
https://github.com/netinvent/OCRmyPDF-EasyOCR/blob/nodeamon/ocrmypdf_easyocr/__init__.py

So the idea now is to get rid of the multiprocessing module in the plugin.

The only drawback is that there will be no parallelism, but since paperless-ngx already handles this, there are chances that the ocrmypdf-easyocr plugin will get to work.

**Reply by deajan** [reply]
Some news.
I think I found a quite elegant way to get rid of the multiprocessing recursion problem using celery's version of the mutliprocessing module.

Next step: easyocr does not produce hocr output which is required for OCRMyPDF (see https://github.com/JaidedAI/EasyOCR/discussions/1090 and https://github.com/ocrmypdf/OCRmyPDF/issues/595)

As far as I understand, it would be quite simple to write a "easyocr2hocr" parser.
I've found some code for azure output to hocr which seems to confirm the idea that it's "that simple", see https://github.com/nnashiki/azv2hocr/blob/main/azv2hocr/core.py

I'll try to write something that I could include directly into the ocrmypdf-easyocr plugin.

Some other caveats I found:

- EasyOcr is a CPU / memory hog (unless using GPU, which is rare on servers). My actual test setup freezed a couple of times until I added more RAM
- EasyOCR downloads training models on first run. We'd need to pre-download them and put them in the docker image
- OCRMyPDF will default to EasyOCR if present. We would need to build two separate docker images, or make a feature request at OCRMyPDF for a new `--no-use-plugin` parameter which would allow paperless-ngx setups to choose between both Tesseract and EasyOCR engines

[EDIT] Using this balantly as my notes ^^

Instructions to setup current EasyOCR plugin (still will default to Tesseract)

```
docker exec -it paperless-webserver bash
#curl -OL http://ftp.us.debian.org/debian/pool/main/n/nano/nano_7.2-2_amd64.deb
#dpkg -i nano

python -m pip install easyocr imagecodecs
#python -m pip uninstall -y opencv-python
#python -m pip install opencv-python-headless
python -m pip install --upgrade ocrmypdf
python -m pip install https://github.com/netinvent/OCRmyPDF-EasyOCR/archive/refs/heads/recursive-daemon-allowed.zip
```
[/EDIT]

**Reply by lukeaust** [reply]
I could hardly agree more. 
I just made a prototype of the page and found that easyorc's detection works very well. 
My idea is to automatically determine the editable pdf or picture pdf or picture according to the uploaded file, and then use easyorc to identify keywords to extract metadata, and classified storage.

**Comment by UltraSalem** [comment]
So interestingly, I had done some hackety hack 'I have no idea what i am doing.gif' type stuff to get my paperless-ngx working with easyOCR back in January. It was slow and borked itself a few times (and the model downloading was painful), but I got there in the end.

However I hadn't touched my paperless instance since January. I had rebooted the server a few times since then though, so docker-compose likely did some rebuilding? Today, I get the "AssertionError: daemonic processes are not allowed to have children" message when trying to OCR a new document, which I did not encounter in the 200 previous files I had OCR'd back in Jan. So I googled the error, and found this thread. :) I'll attach my gubbins in the hope it proves useful to someone.

/zdata/containers/ is a ZFS storage pool on a NAS, but mounted locally to my server with NFS.

OS: Ubuntu 22.04.4 LTS x86_64 
Host: HP Z640 Workstation 
Kernel: 6.5.0-25-generic 
CPU: Intel Xeon E5-1650 v3 (12) @ 3.500GHz 
GPU: NVIDIA Quadro M6000 
Memory: 32Gb 

$ nvidia-smi
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro M6000                   On  | 00000000:02:00.0 Off |                  Off |
| 25%   46C    P8              29W / 250W |    709MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2512      C   /usr/bin/python3                            705MiB |
+---------------------------------------------------------------------------------------+
```
/zdata/containers/paperless-ngx/ $ ls
EasyOCR   consume          custom-cont-init.d  docker-compose.env  export  pgdata    redisdata
aptcache   data                docker-compose.yml  media   pipcache

/zdata/containers/paperless-ngx/docker-compose.yml
```
# Docker Compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /zdata/containers/paperless-ngx/redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - /zdata/containers/paperless-ngx/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: [redacted]
      POSTGRES_PASSWORD: [redacted]

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
#      - gotenberg
#      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /zdata/containers/paperless-ngx/data:/usr/src/paperless/data
      - /zdata/containers/paperless-ngx/media:/usr/src/paperless/media
      - /zdata/containers/paperless-ngx/export:/usr/src/paperless/export
      - /zdata/containers/paperless-ngx/consume:/usr/src/paperless/consume

# bunch of stuff in here as part of switch to ocrmypdf backend to easyocr with GPU
      - /zdata/containers/paperless-ngx/custom-cont-init.d:/custom-cont-init.d:ro

# needed for GPU bits - make sure these are owned by root:root and remove write permissions for group and other
      - /zdata/containers/paperless-ngx/pipcache:/root/.cache/pip
      - /zdata/containers/paperless-ngx/aptcache:/var/cache/apt

# predownload the english v2 and craft easyocr models, and extract into EasyOCR/model. or let the first run do it for you
      - /zdata/containers/paperless-ngx/EasyOCR:/usr/src/paperless/.EasyOCR

    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 0
#      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
#      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

# doing a GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
/zdata/containers/paperless-ngx/custom-cont-init.d/easyocrwithgpubackend.sh
```
#!/bin/sh

# install dependencies
/usr/bin/apt-get update -y
/usr/bin/apt-get install libgl1 -y
/usr/bin/apt-get install git -y
/usr/bin/apt-get install pip3 -y

# install pytorch
pip install torch torchvision

# install EasyOCR https://github.com/ocrmypdf/OCRmyPDF-EasyOCR
pip install git+https://github.com/ocrmypdf/OCRmyPDF-EasyOCR.git
```

my docker-compose env. I wasn't 100% clear on the effect of threads vs workers re: system RAM and GPU RAM, so...I iterated. Comments ended up in my file below.
docker-compose.env
```
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=1000
USERMAP_GID=1000

###############################################################################
# Paperless-specific settings                                                 #
###############################################################################

# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.

# This is required if you will be exposing Paperless-ngx on a public domain
# (if doing so please consider security measures such as reverse proxy)
PAPERLESS_URL=[redacted]

# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
PAPERLESS_SECRET_KEY=[redacted]

# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=Australia/Sydney

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=eng

# my settings

# NFS shares don't send inotifiy to local server when it modifies files, so any file actions 
# not local to the host won't get picked up by the consumer, so we have to do some manual polling.
# let us start with 5 mins (units are in seconds, so 300)
PAPERLESS_CONSUMER_POLLING=300

# stop leaving duplicate trash lying around in the consumer directory. defaults to false
PAPERLESS_CONSUMER_DELETE_DUPLICATES=true

#undo this once we have multi-user support? IF WE WANT THAT?
# well dumb thing is you can't logout to change user once auto login is enabled
#PAPERLESS_AUTO_LOGIN_USERNAME=guest

# u got mail
PAPERLESS_ADMIN_MAIL=[redaced]

# work harder, not smater - CPU version
#PAPERLESS_TASK_WORKERS=3
#PAPERLESS_THREADS_PER_WORKER=3

# work less hard, GPU shat itself at 3x3. try 1 worker, 100 threads - 100 pages on gpu? who knows.
# GPU settings 
# - now trying 2 and 20 - 2024-01-11 - it was bad - run out of GPU memory
# - now trying 1 and 128 - 2024-01-13 - i think we just want one head process so the GPU
# can do smart stuff? or pytorch can, without having to fight with another instance
# - now trying 1 and 64 - 2024-01-16 - getting errors with 128 that google suggest are out of memory related
# eg: RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
PAPERLESS_TASK_WORKERS=1
PAPERLESS_THREADS_PER_WORKER=64

# CPU settings
# - 2 and 5 - 2024-01-12
#PAPERLESS_TASK_WORKERS=2
#PAPERLESS_THREADS_PER_WORKER=5

#webUI workers or something - default is 1, more should mean faster UI
PAPERLESS_WEBSERVER_WORKERS=2
```

let me know if you need anything else. This was several late nights of stuffing around, I'm not actually any kind of actual dev.
