### DISCUSSION TITLE
Dockerized Paperless slows down after time, fast after container reboot

### DISCUSSION THREAD

**Discussion by nosebeggar** [paperless-ngx/paperless-ngx#6109] [Support]
Everytime I open paperless on a new day, the container is extremely slow and will take minutes before running properly.
Whenever I restart the container, performance is as expected for hours on end. I really want to avoid something dirty like a cronjob restarting the container every night. Does anyone have any idea why this might be?

The host system is not the issue, it is basically idle at 5% all day. It runs quite some other containers as well, but none are really demanding, except for maybe jellyfin.

**Comment by deajan** [comment]
Do you have any monitoring software you could plug on your system ? Perhaps a memory leak ? Would be easier identified with monitoring.

**Reply by nosebeggar** [reply]
Hi, thanks for the reply, like I said, my host system is unaffected, otherwise I'd at least see it swapping. I do not have monitoring.

**Reply by deajan** [reply]
Perhaps you could setup a quick prometheus + node_exporter, which will give some insights about what happens (ie processses, forks, io stats, mem stats...)
What do the container logs say ?

Also, you might post more details about your system (os, container manager used and versions).

**Comment by Bond246** [comment]
I want to join in here because i have the exact same problem.
In my case it looks like that only a complete host reboot helps to solve the issue. Even rebooting the container(s) or restarting the hole stack doesn't help. 

This is an example of my dev-console in firefox for requesting /documents?
![grafik](https://github.com/user-attachments/assets/610e5d66-dc6c-4138-b02b-0620d15346de)
It took nearly 3min to load this page.

Logs of the app-container:
```log
[2024-07-25 15:34:20,274] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[d1016593-3978-49e2-ad0d-8d4060282978] received
[2024-07-25 15:34:20,275] [INFO] [celery.worker.request] Discarding revoked task: paperless_mail.tasks.process_mail_accounts[d1016593-3978-49e2-ad0d-8d4060282978]
[2024-07-25 15:36:57,910] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[b8c3a3e4-6570-47b3-9694-5474944526bd] received
[2024-07-25 15:36:57,911] [INFO] [celery.worker.request] Discarding revoked task: paperless_mail.tasks.process_mail_accounts[b8c3a3e4-6570-47b3-9694-5474944526bd]
```
db-container
```log
2024-07-25 13:36:39.475 UTC [27] LOG:  checkpoint starting: time
2024-07-25 13:36:40.821 UTC [27] LOG:  checkpoint complete: wrote 16 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.311 s, sync=0.019 s, total=1.346 s; sync files=15, longest=0.011 s, average=0.002 s; distance=66 kB, estimate=66 kB
```
in redis are no logs to be found in that time. Last log is `Ready to accept connections tcp` 

My compose-file for portainer.
It was made already at the beginning of p-ngx or maybe some weeks before:
```yaml
version: "3.4"
services:
  paperless-redis:
    image: redis:alpine
    container_name: paperless-redis
    restart: unless-stopped
    networks:
      - my-bridge
    volumes:
      - paperless-redis_data:/data

  paperless-db:
    image: postgres:15-alpine
    container_name: paperless-db
    restart: unless-stopped
    networks:
      - my-bridge
    volumes:
      - paperless-db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ***
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***

  paperless-app:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-app
    restart: unless-stopped
    depends_on:
      - paperless-redis
      - paperless-db
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my-bridge
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      #- paperless_export:/usr/src/paperless/export    ##
      - paperless_incoming:/usr/src/paperless/consume 
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-db
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_SECRET_KEY: ***
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{created}_{title}"
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_CONSUMER_POLLING_DELAY: 30
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

volumes:
  paperless_data:
    external: true
  paperless_media:
    external: true
  paperless_incoming:
    external: true
  paperless_export:
    external: true
  paperless-db_data:
    external: true
  paperless-redis_data:
    external: true

networks:
  my-bridge:
    external: true
```

Last year or so i migrated from postgres 13 to 15. But that was smoothly.
The problem is not new... Could be months but i always thought that i've done something wrong or it will solve in future versions.

Do monitor the system i'm using grafana and telegraf. If there are any logs that would help or metrics that would help please tell me.

The docker is is a Intel NUC10i5 with 16GB RAM and NVMe-SSD.
The OS is Ubuntu 22.04.4 actually.
The media and incoming volume is a docker cifs-mount.

Thanks so far.
