### DISCUSSION TITLE
Auto consume directory does not work

### DISCUSSION THREAD

**Discussion by thechinese** [paperless-ngx/paperless-ngx#6155] [Support] [answered]
**My setup:**
I'm running paperless ngx through portainer on my QNAP NAS.
The normal stuff works, I upload files through the web ui and organize them.

**Problem:** 
When I'm trying to use the auto consume functionality, the logs just tell me that paperless is watching (or polling) the folder, but nothing happens.
I wanted to have a shared folder on the network so I can just move files there automatically.

The folder in File Station:
![nff3x9J](https://github.com/paperless-ngx/paperless-ngx/assets/12871346/3c5fe004-93d7-44c4-ba5f-208204e8db8a)

I'm kinda new to this whole NAS thing, and I'm not sure what path I have to specify for the folder on my NAS.

I've tried different variations for the consume folder:  
- /share/ChenghisKhan/paperless/consume 
- /share/paperless/consume
- /ChenghisKhan/share/paperless/consume

I also tried with and without the `PAPERLESS_CONSUMER_POLLING`  Option

This is my docker-compose
``` 
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 18980:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./config:/config
      - ./data:/data
      - ./export:/export
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: 0815admin
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_FILENAME_FORMAT: "{document_type}/{correspondent}/{created_year}{created_month}{created_day}_{correspondent}_{title}"
      PAPERLESS_MEDIA_ROOT: /data/media
      PAPERLESS_CONSUMPTION_DIR: /share/paperless/consume
      PAPERLESS_EXPORT_DIR: /export
      PAPERLESS_DATA_DIR: /config
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_POLLING: 60 

  gotenberg:
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    environment:
      CHROMIUM_DISABLE_ROUTES: 1

  tika:
    image: apache/tika
    restart: unless-stopped
      
volumes:
  data:
  media:
  pgdata:
  redisdata:
```
