### DISCUSSION TITLE
Need assistance with Paperless Docker-Compose Setup on Proxmox Container

### DISCUSSION THREAD

**Discussion by 4s4ml** [paperless-ngx/paperless-ngx#6158] [Support] [answered]
Hello everyone,
I'm currently facing a perplexing issue with my Paperless setup running in a Proxmox container using Docker-compose. Everything was running smoothly until yesterday when I encountered a disk space shortage. To address this, I shut down the instance, resized the disk, and rebooted it. However, since then, I've been unable to start Paperless.

The root of the problem appears to be related to PostgreSQL. Below is an excerpt from the failure log:

```
paperless-ngx_db_1  | /usr/lib/postgresql/15/bin/postgres: error while loading shared libraries: /lib/x86_64-linux-gnu/libpam.so.0: invalid ELF header
paperless-ngx_db_1  | no data was returned by command ""/usr/lib/postgresql/15/bin/postgres" -V"
paperless-ngx_db_1  | initdb: error: program "postgres" is needed by initdb but was not found in the same directory as "/usr/lib/postgresql/15/bin/initdb"
```

Unfortunately, I'm at a loss regarding how this issue occurred and how to rectify it. I'm reaching out to the community for any insights or suggestions you may have.

Your help would be greatly appreciated. Thank you in advance for your time and assistance!

`Docker Compose version v2.25.0`
`Docker Engine - Version:  26.0.0`

Docker-Compose:
```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - ./export:/usr/src/paperless/export
      - /mnt/paperless/data:/usr/src/paperless/data
      - /mnt/paperless/media:/usr/src/paperless/media
      - /mnt/paperless/import:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PUID: 0
      PGID: 0

volumes:
  data:
  media:
  pgdata:
  redisdata:
```
Best regards,
Peter

**Comment by stumpylog** [comment]
> invalid ELF header

I would re-pull and re-create the container.  That's a very odd error to have

**Reply by 4s4ml** [reply, marked as answer]
Appreciate your assistance, @stumpylog! Unfortunately, trying your suggestion didn't yield any changes.

Upon further investigation, it seems the issue might be inherent to my system. Even when attempting a basic PostgreSQL Docker Compose setup:

```
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./pgdata:/var/lib/postgresql/data
```

I encounter the same error as previously mentioned, namely, the `invalid ELF header`.
