### DISCUSSION TITLE
Export / document_exporter does not work in my environment

### DISCUSSION THREAD

**Discussion by endrei** [paperless-ngx/paperless-ngx#6206] [Support] [answered]
Hi community,

first of all: I am relatively new to the whole docker/paperless stuff. So dont judge me, if something is not so clear for me, as for you :-).

Nevermind, paperless is working fine so far, after I have installed it via portainer into my docker-instance. I was using --> ghcr.io/paperless-ngx/paperless-ngx:latest

So now I would like to backup my data with paperless tools using the document_exporter. 

Therfore I executed: 
`docker exec paperless-ngx-webserver-1 document_exporter ../export`

The prompt was doing something....
`100%|██████████|` 395/395 [00:00<00:00, 830.62it/s]`

Unfortunately I have no glue, where the data / export was stored?! So I decided to search for something like "export"

```
root@docker:/# find / -name export
/var/snap/docker/common/var-lib-docker/overlay2/b245f643dd19e8152fb6fba6b6029b9c81e3ae820f8b95d1304833691698ed2e/diff/usr/lib/libreoffice/share/xslt/export
/var/snap/docker/common/var-lib-docker/overlay2/6bd326e564ac072658ba5a36ad659cc2ac4545907a74736b89ebc142a7d1213b/diff/usr/src/paperless/export
/var/snap/docker/common/var-lib-docker/overlay2/fbe5028b3be9464062b369da37680ac1318201281409a69c857364b1204a6a00/diff/command/export
/var/snap/docker/common/var-lib-docker/overlay2/fbe5028b3be9464062b369da37680ac1318201281409a69c857364b1204a6a00/diff/package/admin/execline-2.9.3.0/command/export
/sys/class/gpio/export
/snap/core22/1122/usr/share/bash-completion/completions/export
/snap/core22/1033/usr/share/bash-completion/completions/export
/snap/core20/2105/usr/share/bash-completion/completions/export
/snap/core20/2182/usr/share/bash-completion/completions/export
/usr/share/bash-completion/completions/export
```

a couple of "export" entries was found in my filesystem... unfortunately all were empty...
e.g.

```
root@docker:/# cd /var/snap/docker/common/var-lib-docker/overlay2/6bd326e564ac072658ba5a36ad659cc2ac4545907a74736b89ebc142a7d1213b/diff/usr/src/paperless/export
root@docker:/var/snap/docker/common/var-lib-docker/overlay2/6bd326e564ac072658ba5a36ad659cc2ac4545907a74736b89ebc142a7d1213b/diff/usr/src/paperless/export# ls -l
total 0
```

I guess I have done something wrong during the installation/deployment of my paperless container. 
Paperless was deployed as a stack:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless-db-username *changed 
      POSTGRES_PASSWORD: paperless-db-password *changed 

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_SECRET_KEY: *changed 
      PAPERLESS_ADMIN_USER: *changed 
      PAPERLESS_ADMIN_PASSWORD: *changed 
      PAPERLESS_OCR_LANGUAGE: deu
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
      USERMAP_UID: 1000
      USERMAP_GID: 100
# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
      #PAPERLESS_OCR_LANGUAGES: tur ces
# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
      #PAPERLESS_SECRET_KEY: change-me
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
      #PAPERLESS_TIME_ZONE: America/Los_Angeles
# The default language to use for OCR. Set this to the language most of your
# documents are written in.
      #PAPERLESS_OCR_LANGUAGE: eng

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

what I have done wrong, that I cant find this export on my disk? 

I guess it is more a docker related problem as a paperless?

Thanks in advance and best regards!
