### DISCUSSION TITLE
Docker container not starting - permission denied

### DISCUSSION THREAD

**Discussion by jaydhary14** [paperless-ngx/paperless-ngx#6241] [Support]
### Description

Digest: sha256:101f3cbfd1e15f9dc3303f2eeb64dd4a9489f121accb31612c9ff8be93ba8094
Status: Downloaded newer image for ghcr.io/paperless-ngx/paperless-ngx:latest
Creating paperless-ngx_broker_1 ... done
Creating paperless-ngx_db_1     ... done
Creating paperless-ngx_webserver_1 ... error

ERROR: for paperless-ngx_webserver_1  Cannot create container for service webserver: failed to chmod on /home/docker_volumes/volumes/paperless-ngx_Export/_data: chmod /home/docker_volumes/volumes/paperless-ngx_Export/_data: permission denied

ERROR: for webserver  Cannot create container for service webserver: failed to chmod on /home/docker_volumes/volumes/paperless-ngx_Export/_data: chmod /home/docker_volumes/volumes/paperless-ngx_Export/_data: permission denied

### Steps to reproduce

I have even created entirely new volumes location 
root@ubuntu001:/home/docker_volumes# cd /etc/docker/
root@ubuntu001:/etc/docker# ls
daemon.json
root@ubuntu001:/etc/docker# cat daemon.json
{
  "data-root": "/home/docker_volumes"
}

### Webserver logs

```bash
No logs
```

### Browser logs

```bash
No logs
```

### Paperless-ngx version

2.6.3

### Host OS

Linux ubuntu001 5.15.0-101-generic #111-Ubuntu (ProxMox VM)

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

docker-compose.yaml

### Other

none

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is most definitely something particular to your setup and system, not something affecting all users of Paperless.  As such, I've converted it to a support discussion.

Having not provided your Docker Compose file or the command you were running, I'm going to guess you are using Docker Volumes, not bind mounts for the volumes of the container.  The existence and permissions of those are managed by Docker.  Changing their location is possible, but complicated, as I don't believe Docker moves any existing data to the new location, nor does it try to change permissions.

So I would suggest not changing the location and ensuring things under `/var/lib/docker/volumes/` are owned by the correct user, which is probably root.

**Comment by jaydhary14** [comment]
```yaml
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /home/paperless/paperless-ngx/Database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_FOLDER: /media/PaperlessDocs/Database

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - type: bind
        source: /home/paperless/paperless-ngx/Data
        target: /usr/src/paperless/data
      - type: volume
        source: Media
        target: /usr/src/paperless/media
      - type: volume
        source: Export
        target: /usr/src/paperless/export
      - type: volume
        source: Consume
        target: /usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{document_type}/{created_year}-{created_month}_{correspondent}_{title}"
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true, "continue_on_soft_render_error" :true}'
      PAPERLESS_CONSUMER_POLLING: "60"
      PAPERLESS_CONSUMER_ENABLE_BARCODES: "true"
      PAPERLESS_CONSUMER_ENABLE_TAG_BARCODE: "true"
      USERMAP_UID: "1000"
      USERMAP_GID: "1000"

volumes:
  redisdata:
  Media:
    driver_opts:
      type: "cifs"
      o: "username=paperless,password=xxxxxx,uid=1000,gid=1000,vers=1.0,rw"
      device: "//192.168.0.xxx/PaperlessDocs/Media"
  Export:
    driver_opts:
      type: "cifs"
      o: "username=paperless,password=xxxxxx,uid=1000,gid=1000,vers=1.0,rw"
      device: "//192.168.0.xxx/PaperlessDocs/Export"
  Consume:
    driver_opts:
      type: "cifs"
      o: "username=paperless,password=xxxxxx,uid=1000,gid=1000,vers=1.0,rw"
      device: "//192.168.0.xxx/PaperlessDocs/Consume"
```
