### DISCUSSION TITLE
Find "actuallly failed" imports in File Tasks?

### DISCUSSION THREAD

**Discussion by kvoit** [paperless-ngx/paperless-ngx#6245] [Support]
I just added  a pile of documents  into my instance, some of which were already in the archive. So I expected to see some import  fails. Only by coincidence I hovered over  a message and found that the import didn't fail because the document was already present,  but because redoing OCR was omitted to avoid breaking a signature.

I see two issues here:
a) I see "failed because the document is already there" very different from "failed because I refuse to import this and it will not be in the archive afterwards". Should this be very clearly distinguished?
a) I don't  see a  reason to not import the document if  OCR fails at all, to be honest. Without actual numbers, I would guess that 99.9% of signed documents do not need OCR, because they are  already text. There would be no harm in just adding them to the archive. At least a lot less harm than having them denied undetectedly.

**Comment by wookiefriseur** [comment]
Yeah, some filter for types of fails would be nice. Or a tab for warnings, with duplicate fails showing up in warnings only.

Regarding the signatures, you can allow invalidation:

```yaml
  webserver:
    container_name: paperless-webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
 ...
    environment:
      ...
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
```

It is fine, because the original file won't be touched. (see #5683 )
