### DISCUSSION TITLE
When setting UID different from 1000: cannot lock /etc/passwd

### DISCUSSION THREAD

**Discussion by kingp0dd** [paperless-ngx/paperless-ngx#6384] [Support]
### Description

Trying to run as non-root, but when setting a different UID (other than 1000), it fails to start.

### Steps to reproduce

```

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    user: "3002"

# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=3002
USERMAP_GID=3002
```

### Webserver logs

```bash
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 3002:3002
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
```

### Paperless-ngx version

2.7.2

### Host OS

Debian 12

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Did you search? https://github.com/paperless-ngx/paperless-ngx/discussions/2460

**Comment by kingp0dd** [comment]
> Did you search? https://github.com/paperless-ngx/paperless-ngx/discussions/2460

Yes, the one that looks similar to my issue was: https://github.com/paperless-ngx/paperless-ngx/issues/4531 but it is closed already with no solutions.

I check the one you linked (https://github.com/paperless-ngx/paperless-ngx/discussions/2460), but his solution was already what I did as stated in my first post. Anything else from the logs that I might need to check to solve this?

additional info:

when I change the UID and GID to 1000 in the config I mentioned in my first post:

```
docker-compose.yml

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    user: "1000"

---
paperless.env

# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=1000
USERMAP_GID=1000
```

It works without changing anything else. 
Is it intended that only 1000 can be used?

**Comment by stumpylog** [comment]
I really don't understand the fascination with rootless.  It seems like nothing but an issue generator.

Anyway, presumably some people have been able to run the container with rootless, but I don't and don't have experience with it.  If you find anything out that can be documented, let us know or open a PR for it.

**Comment by kingp0dd** [comment]
If you can point me to the right direction of debugging this, I can provide more info. So far, this is what I know:

Non-root works only if using UID:GID 1000:1000. 

```
Non-root (using 3002)

compose:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    user: "3002"

paperless.env:
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=3002
USERMAP_GID=3002

docker logs:
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 3002:3002
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
```

```
Non-root (using 1000)

compose:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    user: "1000"

paperless.env:
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=1000
USERMAP_GID=1000

docker logs:
this starts the container successfully

```
