### DISCUSSION TITLE
Can’t connect to external mariadb server

### DISCUSSION THREAD

**Discussion by sbach89** [paperless-ngx/paperless-ngx#6477] [Support] [answered]
### Description

Paperless only tries connect to localhost despite setting env variable to point to a different mariadb server

### Steps to reproduce

`docker-compose.yaml`

```
services:
  broker:
    image: redis:7
    restart: unless-stopped
    volumes:
      - /paperless/broker:/data
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /paperless/data:/usr/src/paperless/data
      - /paperless/media:/usr/src/paperless/media
      - /paperless/export:/usr/src/paperless/export
      - /paperless/consume/:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: 10.3.54.24
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: password
```
`.env`
```
USERMAP_UID=1000
USERMAP_GID=1000
PAPERLESS_URL=https://paperless.DOMAIN
PAPERLESS_SECRET_KEY=lol
PAPERLESS_TIME_ZONE=America/New_York
PAPERLESS_OCR_LANGUAGE=eng
```
`log`
```
 django.db.utils.OperationalError: (1045, "Access denied for user 'paperless'@'paperless01' (using password: YES)")
```

`paperless01` is hostname of the server running docker, it is not running maridb. 10.3.54.24 is running mariadb, which is a completely separate VM.

### Webserver logs

```bash
django.db.utils.OperationalError: (1045, "Access denied for user 'paperless'@'paperless01' (using password: YES)")
```

### Paperless-ngx version

Latest

### Host OS

Debian 12 AMD64

### Installation method

Other (please describe above)

### Other

ghcr.io/paperless-ngx/paperless-ngx:latest

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
