### DISCUSSION TITLE
Use mounted OneDrive folder for consume and media folder

### DISCUSSION THREAD

**Discussion by henrik-sc** [paperless-ngx/paperless-ngx#6507] [Support]
Hi all!
I would like to mount OneDrive folders via rclone and use that folders as consume and media folder. However, it do not get it to work. Once the consume folder ist mounted, Paperless does not notice the files therein, does not consume them if I upload new ones. If I upload a file via the web interface it is stored but not visible in the media folder. Only after I restart the machine (and the OneDrive folders are not mounted anymore, I can see the media directory and subdirectories.

Does anyone know, how I can use my local Paperless-ngx with OneDrive directories mounted via rclone?

Many thanks in advance!

I have attached my config files und the command I use for mounting the OneDrive directories ("consume" as example)

```
paperless@paperless:/HDD/paperless/paperless-ngx$ cat docker-compose.env 
USERMAP_UID=1001
USERMAP_GID=1001
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY='$`mykey

```

```
paperless@paperless:/HDD/paperless/paperless-ngx$ cat docker-compose.yml 
# Docker Compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - /HDD/paperless/paperless-ngx/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: mypsswd

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /HDD/paperless/paperless-ngx/data:/usr/src/paperless/data
      - /HDD/paperless/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /HDD/paperless/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:

```

And here is the command for mounting the folder:

`paperless@paperless:/HDD/paperless/paperless-ngx$ rclone --vfs-cache-mode writes mount onedrive:/paperless/consume/ /HDD/paperless/paperless-ngx/consume &`

I run paperless in a Proxmox VM with Ubuntu Server installed. Paperless was installed via the script from the website's setup section.

BR
Henrik
