### DISCUSSION TITLE
Docker compose seems to change ownership of /custom-cont-init.d

### DISCUSSION THREAD

**Discussion by Blumenkind111** [paperless-ngx/paperless-ngx#6533] [Support] [answered]
Hi all,

I am a novice to docker so it may be that I am overlooking something simple, but: 

I want to install zxing-cpp with the solution proposed here: https://github.com/paperless-ngx/paperless-ngx/discussions/5351

I have created the install script in a folder scripts/custom-cont-init.d and changed rights and ownerships to this: 
ls -la scripts/custom-cont-init.d/ 
```
drwxr-xr-x 2 root root 4096 Apr 30 13:55 .
drwxr-xr-x 3 root root 4096 Apr 30 14:22 ..
-rwxr-xr-x 1 root root   89 Apr 30 13:25 install_zxing.sh
```

My docker-compose.yml
```
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - /home/blumenkind/paperless-ngx:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/blumenkind/paperless-ngx/consume:/usr/src/paperless/consume
      - /home/blumenkind/paperless-ngx/scripts/custom-cont-init.d:/custom-cont-init.d:ro
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
```

The when i run docker compose up, it starts normally, but mentions: 
```
...
webserver-1  | Adjusting permissions of paperless files. This may take a while.  # I dont know if this is related
...
webserver-1  | **** Potential tampering with custom scripts detected ****
webserver-1  | **** The folder '/custom-cont-init.d' must be owned by root ****
```
Everything works like before, but zxing-cpp is not installed (e.g. the script is not executed successfully). After ending the container (with strg+c) the file permissions look like this: 

ls -la scripts/custom-cont-init.d/ 
```
drwxr-xr-x 2 blumenkind blumenkind 4096 Apr 30 13:55 .
drwxr-xr-x 3 blumenkind blumenkind 4096 Apr 30 14:22 ..
-rwxr-xr-x 1 blumenkind blumenkind   89 Apr 30 13:25 install_zxing.sh
```

I do not suppose that this is a bug, but with my limited knowledge of docker I am not even able to google this problem. What am I missing?
