### DISCUSSION TITLE
Mail: Unsupported authentication mechanism

### DISCUSSION THREAD

**Discussion by Zipper5004** [paperless-ngx/paperless-ngx#6557] [Support]
Hi,

I'm using paperless ngx with docker container. My docker-compose.yml looks like:
```yaml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /data/paperless-ngx/data:/usr/src/paperless/data
      - /data/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /data/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
```

Now I wanted to set up an email connection:
Name: My_Account
Username: My_User
IMAP: smtp.my-server.de
Password: ****
IMAP Port: 143
IMAP Security: STARTTLS
Character Set: UTF-8

The mail.log says:
[2024-05-03 15:43:51,202] [ERROR] [paperless_mail] Error while authenticating account 2024-05-03T15:43:50.965761: Response status "OK" expected, but "NO" received. Data: [b'[ALERT] Unsupported authentication mechanism.']

on my-server.de I cannot see any auth-request in dovecot-logs.

Does anyone have a clue, what this error means?
