### DISCUSSION TITLE
using existing volumes via OMV on paperless-ngx causing error

### DISCUSSION THREAD

**Discussion by benh9110** [paperless-ngx/paperless-ngx#6565] [Support]
Hello,

I need help with my papaerless-ngx installation on portainer. Here I want to access volumes I have created. The volumes are mounted via CIFS from an OMV share. Here is my stack:

```yaml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8010:8000
    volumes:
      - paperless-ngx_data:/usr/src/paperless/data
      - paperless-ngx_media:/usr/src/paperless/media
      - paperless-ngx_export:/usr/src/paperless/export
      - paperless-ngx_consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_BIND_ADDR: 0.0.0.0
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGES: deu eng
      PAPERLESS_FILENAME_FORMAT: ={created_year}/{created_month}/{created_day}/{correspondent}/{title}
      PAPERLESS_SECRET_KEY: ***
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: ***

volumes:
  paperless-ngx_data:
    external: true
  paperless-ngx_media:
    external: true
  paperless-ngx_export:
    external: true
  paperless-ngx_consume:
    external: true
  pgdata:
  redisdata:
```

Unfortunately, I always get the error message:
```
failed to deploy a stack: Network paperless-ngx_default 
Creating Network paperless-ngx_default 
Created Container paperless-ngx-db-1 
Creating Container paperless-ngx-broker-1 
Creating Container paperless-ngx-db-1 
Created Container paperless-ngx-broker-1 
Created Container paperless-ngx-webserver-1 
Creating Error response from daemon: failed to populate volume: error while mounting volume '/var/lib/docker/volumes/paperless-ngx_media/_data': failed to mount local volume: mount //192.168.178.101/ssd/paperless-ngx/media/:/var/lib/docker/volumes/paperless-ngx_media/_data, data: addr=192.168.178.101,username=***,password=********,vers=3.0: connection refused
```

I already access another OMV share via Plex with a set up in the same way. Access itself should therefore work. Can anyone help me for set up?

- Docker with portainer, running on ubuntu 24.04 LTS
