### DISCUSSION TITLE
help: not recognizing new files in consume folder

### DISCUSSION THREAD

**Discussion by gdh123** [paperless-ngx/paperless-ngx#661] [Support]
Hi folks,

I have installed paperless via the script on docker.
consume folder is on a CIFS/SMB share

for some reason inotify is not working, so I added `PAPERLESS_CONSUMER_POLLING=10` within  `docker-compose.env` file.
Still it is not processing documents.

once I startup docker, it consumes the files.

any workaround known?

**Comment by gdh123** [comment]
could maybe someone post the docker.env or .yml file with activated polling?

I tried different spellings with : and = and with spaces and without, it still does not consume added files after boot.

**Comment by slrzo** [comment]
Did you check the paperless.log for any errors?
I use `PAPERLESS_CONSUMER_POLLING=1800` (=30 Minutes) while having the consume dir on a folder on the docker host (Windows Machine atm).
.yml uses this volume: `- /n/paperless/consume:/usr/src/paperless/consume` (Points to the drive N:\ on Windows machine).
Everything is working fine for me.

**Comment by gdh123** [comment]
user/home/config/docker-compose.env
`PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY=BxN3CG92lIRCg8avMs0dPglS5duZ5uwWDf0i5RQpZdMpfdLANvbacNyqfH$
PAPERLESS_OCR_MODE=skip_noarchive
PAPERLESS_TASK_WORKERS=2
PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{title}
PAPERLESS_CONSUMER_POLLING=1800
`

user/home/config/docker-compose.yml

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /home/debian/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/debian/data:/usr/src/paperless/data
      - /mnt/paperless/Paperless_output:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/paperless/Paperless_input:/usr/src/paperless/consume
- /home/debian/scripts:/usr/src/paperless/scripts
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
  media:
  pgdata:
  redisdata
```


/etc/fstab
`//192.168.0.119/Qnap/3-Files/01-Papierkram/Scan_Ordner /mnt/paperless cifs rw,uid=1000,gid=1000,vers=3.0,file_mode=0660,credentials=/root/.smbcredentials,_netdev 0 0`


installed on debian via docker and install script

any idea?
