### DISCUSSION TITLE
Change Postgres version from 15 to 16

### DISCUSSION THREAD

**Discussion by schroeer** [paperless-ngx/paperless-ngx#6669] [Support] [answered]
In the latest release, the recommended Postgres version for new Docker installations has been raised from 15 to 16. I think it makes sense to replicate this change in existing installations in order to prevent a deviation from the norm. If this is correct, I and probably others would very much welcome advice on the correct procedure.

**Comment by OverDodo** [comment]
Theres official documentation from postgres on how to upgrade to a new major version:

https://www.postgresql.org/docs/current/upgrading.html

**Comment by p33k** [comment]
What about just using the document exporter and importer? 
I did this with my synology docker install:
1. Backup everything
2. run Document exporter
3. Fresh Docker Container with postgres and everything in latest versions
4. document importer

**Comment by github-actions** [comment]
This discussion has been automatically closed because it was marked as answered. Please see our [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/dev/CONTRIBUTING.md#automatic-repository-maintenance) for more details.

**Comment by schroeer** [comment, marked as answer]
# Upgrade the Postgres database from version 15 to 16

This is how I did it. Please use at your own risk.

## `docker-compose.yml` before
```yaml
  db:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
```

## Shutdown Paperless
```ShellSession
docker compose down
```

## Start only Postgres container (version 15)
```ShellSession
docker compose up -d db
```

## Dump database
```ShellSession
docker compose exec db pg_dumpall -U paperless > dump.sql
```

You can check that the file `dump.sql` looks reasonable.

## Shutdown Postgres container
```ShellSession
docker compose down db
```

## Remove database volume
```ShellSession
docker volume rm paperless_pgdata
```

# Update `docker-compose.yml`
```yaml
  db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
```

## Pull image
```ShellSession
docker compose pull
```

## Start new Postgres container (version 16)
```ShellSession
docker compose up -d db
```

## Import database dump
```ShellSession
cat dump.sql | docker exec -i paperless-db-1 psql -U paperless
```

## Shutdown Postgres container
```ShellSession
docker compose down
```

## Start entire Paperless stack
```ShellSession
docker compose up
```
