### DISCUSSION TITLE
Consuming all (txt, png, html, odt, doc, docx ) but html

### DISCUSSION THREAD

**Discussion by dmenne** [paperless-ngx/paperless-ngx#6700] [Support] [answered]
_I had posted this on the gotenberg forum as https://github.com/gotenberg/gotenberg/discussions/875; on suggestion of @guilien, I have transferred it to this forum._

Running paperless with [Docker image](https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml) on Synology

* REST using PUT with Insomnia (Postman alternative) to API:9998 with txt, png, **html**, odt, doc, docx gives correct responses.
* All extensions except html work
```
[paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Atemtes1t.html: Unknown file extension.
[paperless.management.consumer] Not consuming file /usr/src/paperless/consume/Atemtes1t.htm: Unknown file extension.

// Renamed html to txt
[paperless.consumer] Consuming Atemtes1t.txt

// Correctly identified as html in disguise
[paperless.consumer] Detected mime type: text/html
[paperless.consumer] Unsupported mime type text/html
```
I suspect some Chromium problem, but how to debug?

```
...
            PAPERLESS_TIKA_ENABLED: 1
...
    gotenberg:
        container_name: paperless-gotenberg
        image: gotenberg/gotenberg:8
        restart: unless-stopped
        command:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"
            - "--api-timeout=300s"
    tika:
        container_name: paperless-tika
        image: apache/tika:2.9.2.0-full
        ports:
            - 9998:9998
        restart: unless-stopped

```
