### DISCUSSION TITLE
Issue with Custom Field Search Request via API

### DISCUSSION THREAD

**Discussion by tural-ali** [paperless-ngx/paperless-ngx#6743] [Support] [answered]
### Description

I am installing Paperless using the following Docker Compose script. I created a custom "tagged" field in Paperless. One of the services, Doclytics, periodically sends the following GET request (with the auth token as in headers) to the Paperless API:

`/api/documents/?query=NOT%20tagged=true`

However, every time this request is made, Paperless returns the following error message:

`Error listing search results, check logs for more detail.`
I tried to manually send this request using Postman. The same result.

What am I doing wrong?

Below is the Docker Compose configuration I am using:

 
```
version: '3.8'
services:
  broker:
    image: redis
    container_name: Paperless-NGX-REDIS
    restart: always
    volumes:
      - /volume1/docker/paperless/redis:/data
      
  doclytics:
    image: bjoern5urban/doclytics:v1.1.3
    container_name: doclytics
    environment:
      PAPERLESS_BASE_URL: http://192.168.68.59:8001
      PAPERLESS_TOKEN: your-paperless-token
      LOG_LEVEL: DEBUG
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
      OLLAMA_MODEL: llama3
    volumes:
      - /volume1/docker/paperless/doclytics:/app/data
    depends_on:
      - ollama
      - webserver
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - /volume1/docker/paperless/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
 
  db:
    image: postgres
    container_name: Paperless-NGX-DB
    restart: always
    volumes:
      - /volume1/docker/paperless/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: your-postgres-user
      POSTGRES_PASSWORD: your-postgres-password

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: Paperless-NGX
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - 8001:8000
    volumes:
      - /volume1/docker/paperless/data:/usr/src/paperless/data
      - /volume1/docker/paperless/media:/usr/src/paperless/media
      - /volume1/docker/paperless/export:/usr/src/paperless/export
      - /volume1/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_SECRET_KEY: your-secret-key
      PAPERLESS_ADMIN_USER: your-admin-user
      PAPERLESS_ADMIN_PASSWORD: your-admin-password
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBPORT: 5432
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: your-db-user
      PAPERLESS_DBPASS: your-db-password
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
      PAPERLESS_OCR_LANGUAGE: "ces+tur+aze+deu+eng+rus"
      PAPERLESS_OCR_LANGUAGES: "ces tur aze deu eng rus"
      PAPERLESS_URL: http://192.168.68.59:8001
      PAPERLESS_ALLOWED_HOSTS: "http://192.168.68.59:8001,localhost,127.0.0.1,192.168.68.59:8001,synology.local:8001"
      PAPERLESS_CORS_ALLOWED_HOSTS: "http://192.168.68.59:8001"
      PAPERLESS_CSRF_TRUSTED_ORIGINS: "http://192.168.68.59:8001"
      PAPERLESS_DEBUG: false

```

### Steps to reproduce

1. Create a custom Boolean field "tagged"
2. Send an API request: http://<ip>:<port>/api/documents/?query=NOT%20tagged=true
3. Result: "Error listing search results, check logs for more detail."

### Webserver logs

```bash
[2024-05-16 01:05:51,577] [WARNING] [paperless.api] An error occurred listing search results: Document matching query does not exist.
[2024-05-16 01:05:51,578] [WARNING] [django.request] Bad Request: /api/documents/
```

### Paperless-ngx version

2.8.6

### Host OS

Synology DSM 7.2

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
