### DISCUSSION TITLE
Password reset loading for long time and end up with error 500

### DISCUSSION THREAD

**Discussion by annoying-default-user** [paperless-ngx/paperless-ngx#6766] [Support] [answered]
I've setup Paperless-ngx on my NAS at home using the Docker Compose path, the host system is Proxmox and Docker is running in an LXC. I've taken the [compose example for PostgreSQL with Tika](https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml) and changed it for my usecase (using a different PostgreSQL database). I like to use an external mail server, from a paid hosting service.
It seems everything is working, except sending emails for password recovery. I enter the address and click on "Send instructions" and the page going in "loading mode" (the browser shows a loading circle on the tab). After a long time, maybe 10 or 20 or 30 minutes, I'am landing on a default error 500 page. The time it takes is feeling very long.
I found [this on stackoverflow](https://stackoverflow.com/questions/67948226/django-exception-templatedoesnotexist-at), but it is nothing in my hand. So, what can I check or change to get the password reset working?

And additional question, is that correct, that all fields of the OCR settings on the administration page are empty? On the public demo, I saw the same behavior today.

In the logs, I found:
``` bash
webserver-1  | [2024-05-18 17:04:41,663] [ERROR] [django.request] Internal Server Error: /accounts/password/reset/
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
webserver-1  |     raise exc_info[1]
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
webserver-1  |     response = await get_response(request)
webserver-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
webserver-1  |     raise exc_info[1]
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
webserver-1  |     response = await wrapped_callback(
webserver-1  |                ^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
webserver-1  |     ret = await asyncio.shield(exec_coro)
webserver-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
webserver-1  |     result = self.fn(*self.args, **self.kwargs)
webserver-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
webserver-1  |     return func(*args, **kwargs)
webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
webserver-1  |     return self.dispatch(request, *args, **kwargs)
webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
webserver-1  |     return handler(request, *args, **kwargs)
webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/allauth/account/mixins.py", line 69, in post
webserver-1  |     response = self.form_valid(form)
webserver-1  |                ^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/allauth/account/views.py", line 576, in form_valid
webserver-1  |     r429 = ratelimit.consume_or_429(
webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/allauth/core/ratelimit.py", line 134, in consume_or_429
webserver-1  |     return handler429(request)
webserver-1  |            ^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/allauth/core/ratelimit.py", line 124, in _handler429
webserver-1  |     return render(request, "429." + app_settings.TEMPLATE_EXTENSION, status=429)
webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
webserver-1  |     content = loader.render_to_string(template_name, context, request, using=using)
webserver-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
webserver-1  |     template = get_template(template_name, using=using)
webserver-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
webserver-1  |     raise TemplateDoesNotExist(template_name, chain=chain)
webserver-1  | django.template.exceptions.TemplateDoesNotExist: 429.html
```

My compose file:
``` yaml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

#  db:
#    image: docker.io/library/postgres:16
#    restart: unless-stopped
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: paperless
#      POSTGRES_USER: paperless
#      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
#      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /share/data/export:/usr/src/paperless/export
      - /fastshare/data/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBHOST: 192.168.168.168
      PAPERLESS_DBPORT: 5432
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: pprlss
      PAPERLESS_DBPASS_FILE: /run/secrets/db_passwd
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    secrets:
      - db_passwd
      - smtp_passwd

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
#  pgdata:
  redisdata:

secrets:
  db_passwd:
    file: ./passwd_db.txt
```

My environment file:
``` dotenv
PAPERLESS_SECRET_KEY = coolrandomstring
PAPERLESS_TIME_ZONE = Europe/Berlin
PAPERLESS_OCR_OUTPUT_TYPE = pdfa-2
PAPERLESS_OCR_LANGUAGE = deu
PAPERLESS_OCR_LANGUAGES = pol ces
PAPERLESS_EMAIL_HOST = mail.example.com
PAPERLESS_EMAIL_PORT = 465
PAPERLESS_EMAIL_HOST_USER = server@example.com
PAPERLESS_EMAIL_FROM = Paperless-ngx Archiv
PAPERLESS_EMAIL_HOST_PASSWORD = coolrandompasswd
PAPERLESS_EMAIL_USE_TLS = 1
```
