### DISCUSSION TITLE
Help needed before migrating from linuxserver.io docker container paperless-ngx to paperless-ngx (by paperless-ngx)

### DISCUSSION THREAD

**Discussion by queen4me** [paperless-ngx/paperless-ngx#6870] [Support] [answered]
I'm no Linux-/Docker-Pro but would like to migrate.

My previous docker-compose.yml (with sql as DB):

```
version: "2.1"
services:
  paperless-ngx:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless-ngx
    volumes:
      - /home/johndoe/docker/paperless-ngx:/config
      - /mnt/nas/paperless-ngx:/data
    env_file: docker-compose.env
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8601:8000
    restart: unless-stopped
```
and this is the docker-compose.env:

```
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_CONSUMER_POLLING=60
DOCKER_MODS=linuxserver/mods:papermerge-multilangocr
OCRLANG=deu
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{title}
```

I would now use the following new docker-compose.yml:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /home/johndoe/docker/paperless-ngx/redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8601:8000
    volumes:
      - /home/johndoe/docker/paperless-ngx:/data
      - /mnt/nas/paperless-ngx/media:/media
      - /mnt/nas/paperless-ngx/export:/usr/src/paperless/export
      - /mnt/nas/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
```

with the following new docker-compose.env:

```
USERMAP_UID=1000
USERMAP_GID=1000
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{title}
```

Could someone please take a look and give me feedback?

Do I have to create a new admin-user or will this account be migrated too?

Thanks a lot for helping!
