### DISCUSSION TITLE
Problem with Restore/ Migrate through export/ import

### DISCUSSION THREAD

**Discussion by knebb** [paperless-ngx/paperless-ngx#6997] [Support]
Hi,

I have a running instance through Docker with MySQL. Now I wanted to migrate to a better hardware and switch to PostgreSQL.
I donwloaded [docker-compose.postgres-tika.yml](https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml) and started my new Paperless instance from scratch without configuring it.
So I did `docker compose up -d` and can connect to the new instance (but not login as no admin user is created). Fine so far.

On the other host I shut down paperless, did an update by `docker compose pull`, started it by `docker compose up -d` followed by backing it up with `docker compose exec webserver document_exporter ../export -d -p`.

Then I transferred the export directory through `rsync -avz`to the new instance.

On the new instance I am importing through `docker compose exec webserver document_importer ../export `. Unfotunately I am getting errors:
```
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.DataError: Problem installing fixture '/usr/src/paperless/export/manifest.json': Could not load auditlog.LogEntry(pk=1000): unsupported Unicode escape sequence
LINE 1: ..., "action" = 2, "changes_text" = '', "changes" =  E'{"share_...
                                                             ^
DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: ...00e4ge", "None"], "content": ["\ufffd\ufffd\u0000...

```

When I use the .yml file from my MySQL installation the import runs fine....

Is migration between databases noch supported?

Thank!

/KNEBB

**Comment by stumpylog** [comment]
You'll have to manually correct the values.  The databases are clearly configured differently in how they treat Unicode.  Make sure you are using utf8 for both sides

**Comment by knebb** [comment]
Hmmm.... I did not create the containers on my own. 
So which of the two databases is not UTF-8 compliant? Is it MySQL or is it PostgreSQL? I guess it is the MySQL one?

How can I verify it is fine?

/KNEBB

**Comment by knebb** [comment]
Hi, 
this is the *.yml for MySQL:
```
  db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
     - ./volumes/database:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
```
I am currently evaluating which charset the database uses...
