### DISCUSSION TITLE
Help with cleaning up my Compose file

### DISCUSSION THREAD

**Discussion by BoBBer446** [paperless-ngx/paperless-ngx#7046] [Support] [answered]
Hey guys, I have a pretty bloated compose file over time and from the beginning. I would like to clean it up. However, I'm not sure if and where or how best to start because I don't know how much changes to it will affect the integrity of the data.

The second point is that I am not sure which ENVs I actually need for smooth operation.

Based on the compose file, I think you can see that I would like to use OCR for German and English.
But I don't know exactly which ENVs are now obsolete and which are still useful.

So I would be happy if someone could give me some feedback :)

```yml
# Angepasste Compose File für Paperless-NGX (zweite Instanz) - Rene
# https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres-tika.yml
services:
  broker_rene:
    image: docker.io/library/redis:7
    restart: always
    volumes:
      - /home/docker-projects/paperless-ngx/rene/volumes/redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rene_paperless_netzwerk

  db_rene:
    image: docker.io/library/postgres:15
    restart: always
    volumes:
      - /home/docker-projects/paperless-ngx/rene/volumes/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless -d paperless"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rene_paperless_netzwerk

  webserver_rene:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    # user: 1000:1000 #uid und gid des container benutzers ist gleich die des users "rene"
    restart: always
    depends_on:
      - db_rene
      - broker_rene
      - tika_rene
      - gotenberg_rene
    ports:
      - "8002:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/nas/NasHome/Dokumente-Paperless-Consume:/usr/src/paperless/consume
      - /home/docker-projects/paperless-ngx/rene/volumes/data:/usr/src/paperless/data
      - /home/docker-projects/paperless-ngx/rene/volumes/media:/usr/src/paperless/media
      - /home/docker-projects/paperless-ngx/rene/volumes/export:/usr/src/paperless/export
      - /home/docker-projects/paperless-ngx/rene/volumes/pre_scripte:/scripts:ro
    environment:
      PAPERLESS_TASK_WORKERS: 3
      PAPERLESS_THREADS_PER_WORKER: 3
      PAPERLESS_WORKER_TIMEOUT: 3600
      PAPERLESS_ALLOWED_HOSTS: "192.168.178.36"
      PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://paperless.chuwi.local"
      PAPERLESS_REDIS: redis://broker_rene:6379
      PAPERLESS_DBHOST: db_rene
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBSSLMODE: prefer
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_CONVERT_DENSITY: 600
      PAPERLESS_CONVERT_IMAGE_DPI: 600
      PAPERLESS_CONVERT_IMAGE_QUALITY: 100
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_SECRET_KEY: 4566673454356887
      PAPERLESS_URL: http://192.168.178.36:8002
      PAPERLESS_CORS_ALLOWED_HOSTS: http://192.168.178.36
      PAPERLESS_FORGIVING_OCR: "true"
      # PAPERLESS_PRE_CONSUME_SCRIPT: /scripts/pre-consume.sh
      PAPERLESS_TIKA_ENABLED: "1"
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg_rene:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika_rene:9998
      # USERMAP_UID: 1000
      # USERMAP_GID: 100
      PAPERLESS_CONSUMER_POLLING: 5
      PAPERLESS_CONSUMER_POLLING_RETRY_COUNT: 5
      PAPERLESS_CONSUMER_POLLING_DELAY: 5
      PAPERLESS_CONSUMER_INOTIFY_DELAY: 0.5
      # PAPERLESS_EMAIL_TASK_CRON: "*/10 * * * *"
    networks:
      - rene_paperless_netzwerk

  tika_rene:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: always

    networks:
      - rene_paperless_netzwerk

  gotenberg_rene:
    #image: thecodingmachine/gotenberg:7.9.1
    image: docker.io/gotenberg/gotenberg:7.10
    restart: always
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--api-timeout=600s"
      - "--uno-listener-start-timeout=120s"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rene_paperless_netzwerk

networks:
  rene_paperless_netzwerk:
    driver: bridge

volumes:
  data_rene:
  media_rene:
  pgdata_rene:
  redisdata_rene:
```
