### DISCUSSION TITLE
[Feature Request] Selectively disable inverted colors for dark mode

### DISCUSSION THREAD

**Discussion by moritztim** [paperless-ngx/paperless-ngx#7058] [Feature Requests]
### Description

![image](https://github.com/paperless-ngx/paperless-ngx/assets/90388353/dc787e27-ae5e-4977-8b20-2b98937c2347)
Some documents just don't need their colors inverted.

**Comment by sbrunner** [comment]
Personally, I use this filer in place of inverted colors:
```css
    filter: sepia(50%) brightness(50%);
```
Full style:
```css
html body img.card-img {
    filter: sepia(50%) brightness(50%) !important;
}
```
