### DISCUSSION TITLE
Paperless data migration without exporter / importer option (after power failure)

### DISCUSSION THREAD

**Discussion by georgy62** [paperless-ngx/paperless-ngx#7140] [Support] [answered]
Hello everyone,

In brief: 10 minutes of power failure, after which the raspi5 no longer starts up, the connected SSD seems to be broken. Connected to a second raspi, I was able to "rescue" the "docker-volumes" directory with the command:

tar -czvf docker-volumes.tar.gz -C /home/[user]/docker-volumes

In the meantime, I was able to reinstall docker / paperless-ngx on the Raspberry PI and install docker / paperless-ngx, among other things. Now my question:

Is there a way to make the data from the saved tar archive accessible to the new installation of paperless-ngx? Simply copying and renaming the directories (paperless_ngx_bak_old / paperless_ngx_new > alternating in paperless_ngx) didn't work.

I would be very grateful for some good advice
Regards, georgyboy

**Comment by limdul79** [comment]
You are missing the volume for the database. If you look at https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.postgres.yml, you need all volumes (perhaps redis can be skipped, don't know).

But with a power failure it might that the databse is corrupted. In that case, your solution would be re-import all Documents (they should be in in the data volume as originals). 

The normal way in such a case would be to install it from a backup with the import feature.

**Comment by georgy62** [comment]
OK, thank you very much. Here is the relevant section from my "docker-compose.yml". Perhaps you could look through it and give me a hint as to where the database volume is located: I read from it that it is in ./volumes/paperlessngx/db, i.e. next to the other data. So it is there and in the right place. However, it is not recognized and integrated by the new paperless-ngx installation. I am at a loss and hope that there is some way before I start re-reading around 600 documents.

```
services:
  paperless_broker:
    image: docker.io/library/redis:7
    container_name: paperless_broker
    restart: unless-stopped

  paperless_db:
    image: docker.io/library/mariadb:10
    container_name: paperless_db
    restart: unless-stopped
    volumes:
      - ./volumes/paperlessngx/db:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless


  paperless_web:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless_web
    restart: unless-stopped
    depends_on:
      - paperless_db
      - paperless_broker
    ports:
      - 2226:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./volumes/paperlessngx/data:/usr/src/paperless/data
      - /././././mnt/nfs_paperless/media:/usr/src/paperless/media
      - ./volumes/paperlessngx/export:/usr/src/paperless/export
      - ./volumes/paperlessngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_CONSUMER_POLLING: 1 
      PAPERLESS_REDIS: redis://paperless_broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: paperless_db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIME_ZONE: Europe/Berlin
      # PAPERLESS_SECRET_KEY: Passcode
      # PAPERLESS_ADMIN_USER: user
      # PAPERLESS_ADMIN_PASSWORD: Passcode
```

Best regards
georgy62
