### DISCUSSION TITLE
Workflow if ASN is present

### DISCUSSION THREAD

**Discussion by mholti** [paperless-ngx/paperless-ngx#7252] [Support] [answered]
Hi,
i apply the ASN to my documents via QR-sticker. But not all documents get an ASN, because some are sent to trah after scan...
Is it possible to filter the presence of an ASN in a workflow, e.g. to apply a certain tag to documents with ASN and another to those without?
Thanks in advance
Michael

**Comment by ignoreigor** [comment]
Hi,
I think this is not easy in one step. But have a look at PAPERLESS_CONSUMER_ENABLE_TAG_BARCODE and PAPERLESS_CONSUMER_TAG_BARCODE_MAPPING (https://docs.paperless-ngx.com/configuration/#PAPERLESS_CONSUMER_TAG_BARCODE_MAPPING) *. 

You can automatically add tags if a barcode is detected. Afterwards you can use this tags to define your workflows - if still needed at all.

(*) By the way: Thanks to the paperless-ngx team for this great feature

**Comment by mholti** [comment]
Thanks for this suggestion. I'll give it a try with the next incoming invoice

**Comment by mholti** [comment]
Hi,
one problem raises the next...
I'm unable to add the needed values to my docker-compose.yml
Here's what my environment-lines looks like:
```
paperless-ngx:
  image: ${PAPERX_IMAGE}
  container_name: paperless-ngx
  environment:
    - USERMAP_UID=1026
    - USERMAP_GID=100
    - PAPERLESS_TIME_ZONE=Europe/Berlin
    - PAPERLESS_OCR_LANGUAGE=deu
    - PAPERLESS_FILENAME_FORMAT={added_year}/{added_month}/{tag_list}/{asn}-{title}
    - PAPERLESS_REDIS=redis://paperless-ngx-broker:6379
    - PAPERLESS_ADMIN_USER=userxy
    - PAPERLESS_ADMIN_PASSWORD=pwxy
    - PAPERLESS_ENABLE_UPDATE_CHECK=TRUE
    - PAPERLESS_URL=https://url
    - PAPERLESS_CONSUMER_ENABLE_BARCODES=TRUE
    - PAPERLESS_CONSUMER_BARCODE_SCANNER=ZXING
    - PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true
    - PAPERLESS_CONSUMER_TAG_BARCODE_MAPPING= "ASN0.*":"tag name"
```
   I tried several formats, none of these are working. What am i doing wrong?
