### DISCUSSION TITLE
CSRF verification failed Paperless

### DISCUSSION THREAD

**Discussion by ProEsizal** [paperless-ngx/paperless-ngx#7257] [Support] [answered]
### **Hello guys,

I've read up on it a bit but I'm still getting the error message that when I try to log into Paperless with DDNS (it works via the local IP) I get the error message. What I don't understand is that I have the URL correct because I get the login window asking me to sign up for Paperless.**

**My env file looks like this:**

```
-The UID and GID of the user used to run paperless in the container. Set this
-to your UID and GID on the host so that you have write access to the
-consumption directory.
USERMAP_UID=1026
USERMAP_GID=100

-Additional languages to install for text recognition, separated by a
-whitespace. Note that this is
-different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
-language used for OCR.
-The container installs English, German, Italian, Spanish and French by
-default.
-See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
-for available languages.
PAPERLESS_OCR_LANGUAGES=eng slk

-###############################################################################
-# Paperless-specific settings                                                 #
-###############################################################################

-All settings defined in the paperless.conf.example can be used here. The
-Docker setup does not use the configuration file.
-A few commonly adjusted settings are provided below.

-Adjust this key if you plan to make paperless available publicly. It should
-be a very long sequence of random characters. You don't need to remember it.
PAPERLESS_SECRET_KEY=xxxxxxxxxxxxxx

-This is required if you will be exposing Paperless-ngx on a public domain
-(if doing so please consider security measures such as reverse proxy)
PAPERLESS_URL= https://paperless.xxxxx.synology.me
PAPERLESS_CSRF_TRUSTED_ORIGINS= https://paperless.xxxxx.synology.me
PAPERLESS_ALLOWED_HOSTS=paperless.xxxxx.synology.me
PAPERLESS_CORS_ALLOWED_HOSTS=https://paperless.xxxxx.synology.me

-Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=Europe/Berlin

-The default language to use for OCR. Set this to the language most of your
-documents are written in.
PAPERLESS_OCR_LANGUAGE=deu

-Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx
-#PAPERLESS_FORCE_SCRIPT_NAME=/PATHPREFIX
-#PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # trailing slash required

-Recursive parsing of consumption directory
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true

-OCR Mode
PAPERLESS_OCR_MODE=skip
PAPERLESS_OCR_DESKEW=true
PAPERLESS_OCR_ROTATE_PAGES=true

-Search for updates automatically
PAPERLESS_ENABLE_UPDATE_CHECK=true

-Filename handling
PAPERLESS_FILENAME_FORMAT={titel}/{creatde_year}
```

**Here is a picture of my proxy server**

**Here is the docker-compose.yml file**

```yaml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless-ngx/redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8877:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume1/docker/paperless-ngx/data:/usr/src/paperless/data
      - /volume1/docker/paperless-ngx/media:/usr/src/paperless/media
      - /volume1/docker/paperless-ngx/export:/usr/src/paperless/export
      - /volume1/docker/paperless-ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_SECRET_KEY: super11geheim
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: 123456
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      USERMAP_UID: 0
      USERMAP_GID: 0  

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  redisdata:
```

**Does anyone have an idea why it doesn't work for me?? I don't know...**
