### DISCUSSION TITLE
Fresh docker install with install script - error connecting to broker:6379. No route to host

### DISCUSSION THREAD

**Discussion by Peter-Ries** [paperless-ngx/paperless-ngx#7300] [Support] [answered]
Hello everybody, I hope you can help me finding the cause of my error here. Googleing more than two days did not help yet.

I have a BananaPi M1 (ARMV7l, 32bit; fresh armbian install with just docker and docker-compose-plugin) and was looking for a way to let it do sth useful. I came around paperless-ngx.

After I played around with the installer and manifest errors I found a way to modify the installer to make use of version paperless-ngx:1.17.4 - the last one supporting 32bit. With that change the image now get pulled by "docker compose pull" called in the script. All good IMHO. 
But the next step when the installer tries to "docker compose run -rm webserver createsuperuser..." it starts "Waiting for Redis..." and fails with Error 113 connecting to broker:6379. No route to host. And Failed to connect to redis using environment variable PAPERLESS_REDIS.

Now here are my 3 configs created by the script

.env
`COMPOSE_PROJECT_NAME=paperless`

docker-compose.yml
```yml
# Docker Compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# SQLite is used as the database. The SQLite file is stored in the data volume.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.17.4
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /exports/documents/Scanarchiv:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  redisdata:

```

docker-compose.env
```yml
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY='...MySecretKeyHere...'
```

script ouput:
```bash
peter@bananas:~/paperless-ngx$ docker compose pull
[+] Pulling 4/4
 ✔ gotenberg Pulled                                                                                                                                                            1.9s 
 ✔ tika Pulled                                                                                                                                                                 1.9s 
 ✔ broker Pulled                                                                                                                                                               2.0s 
 ✔ webserver Pulled                                                                                                                                                            1.7s 
peter@bananas:~/paperless-ngx$ docker compose run --rm webserver createsuperuser
[+] Creating 3/0
 ✔ Container paperless-tika-1       Running                                                                                                                                    0.0s 
 ✔ Container paperless-gotenberg-1  Running                                                                                                                                    0.0s 
 ✔ Container paperless-broker-1     Running                                                                                                                                    0.0s 
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Redis ping #0 failed.
Error: Error 113 connecting to broker:6379. No route to host..
Waiting 5s
Redis ping #1 failed.
Error: Error 113 connecting to broker:6379. No route to host..
Waiting 5s
Redis ping #2 failed.
Error: Error 113 connecting to broker:6379. No route to host..
Waiting 5s
Redis ping #3 failed.
Error: Error 113 connecting to broker:6379. No route to host..
Waiting 5s
Redis ping #4 failed.
Error: Error 113 connecting to broker:6379. No route to host..
Waiting 5s
Failed to connect to redis using environment variable PAPERLESS_REDIS.

```

some docker command outputs (of which I hope it helps):
```bash
peter@bananas:~/paperless-ngx$ docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS      NAMES
c33d8037dea9   gotenberg/gotenberg:8.7   "/usr/bin/tini -- go…"   21 minutes ago   Up 21 minutes   3000/tcp   paperless-gotenberg-1
be37eec188e6   apache/tika:latest        "/bin/sh -c 'exec ja…"   21 minutes ago   Up 21 minutes   9998/tcp   paperless-tika-1
a96e12339429   redis:7                   "docker-entrypoint.s…"   21 minutes ago   Up 21 minutes   6379/tcp   paperless-broker-1

peter@bananas:~/paperless-ngx$ docker volume ls
DRIVER    VOLUME NAME
local     paperless_data
local     paperless_media
local     paperless_redisdata

peter@bananas:~/paperless-ngx$ docker container ls
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS      NAMES
c33d8037dea9   gotenberg/gotenberg:8.7   "/usr/bin/tini -- go…"   22 minutes ago   Up 22 minutes   3000/tcp   paperless-gotenberg-1
be37eec188e6   apache/tika:latest        "/bin/sh -c 'exec ja…"   22 minutes ago   Up 22 minutes   9998/tcp   paperless-tika-1
a96e12339429   redis:7                   "docker-entrypoint.s…"   22 minutes ago   Up 22 minutes   6379/tcp   paperless-broker-1

peter@bananas:~/paperless-ngx$ docker image ls
REPOSITORY                            TAG       IMAGE ID       CREATED         SIZE
gotenberg/gotenberg                   8.7       44999e4c7b03   5 weeks ago     1.48GB
redis                                 7         c07497cc8f33   2 months ago    93.1MB
apache/tika                           latest    aade8562ccae   2 months ago    293MB
postgres                              16        4ca73b6ec246   2 months ago    366MB
ghcr.io/paperless-ngx/paperless-ngx   1.17.4    c1612702ab40   10 months ago   1.28GB

peter@bananas:~/paperless-ngx$ docker network ls
NETWORK ID     NAME                DRIVER    SCOPE
880f4af0462f   bridge              bridge    local
a9f7adf00c6d   host                host      local
1497729183d6   none                null      local
8e32810ea38c   paperless_default   bridge    local


###########
# redis contailer logs...
1:C 23 Jul 2024 06:45:50.262 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 23 Jul 2024 06:45:50.263 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 23 Jul 2024 06:45:50.263 * Redis version=7.2.5, bits=32, commit=00000000, modified=0, pid=1, just started
1:C 23 Jul 2024 06:45:50.263 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 23 Jul 2024 06:45:50.268 * monotonic clock: POSIX clock_gettime
1:M 23 Jul 2024 06:45:50.270 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
1:M 23 Jul 2024 06:45:50.275 * Running mode=standalone, port=6379.
1:M 23 Jul 2024 06:45:50.283 * Server initialized
1:M 23 Jul 2024 06:45:50.287 * Ready to accept connections tcp

```

iptables:
```
peter@bananas:~/paperless-ngx$ sudo iptables -L
[sudo] Passwort für peter: 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (2 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere    
```

As this is a fresh install of Armbian and no ufw or iptables have been set up by me I wonder why paperless-container struggles to reach redis. I'm clueless ATM. Any ideas or help? (I'm quite new to docker and only know some basics)

Thanks, Peter
