### DISCUSSION TITLE
Mail Fetcher does not automatically run on CRON schedule

### DISCUSSION THREAD

**Discussion by skellycode** [paperless-ngx/paperless-ngx#7347] [Support] [answered]
### Description

`v2.11.2`
Brand new, clean paperless-ngx installation using docker-compose.  Consumes files via consume folder and web folder without issue.
Connects to mail server without issue.
Mail Rule defined.
Mail_Fetcher does not run on the default CRON schedule of every 10mins.

I can trigger a manual run (which executes flawlessly and as expected) via the method below:
```
docker exec -it webserver bash
su - paperless
cd /usr/src/paperless/src
python3 manage.py mail_fetcher
```

I have also attempted to export the installation, delete all files, and re-import the installation to a clean docker with clean datasets - yet the issue persists. (you may notice the `latest_migration` in the system status below.  This was after I tried the export/import trick.  The issue exists for both clean, and post-export/import installations)

### Steps to reproduce

1) Start with a fresh installation following the docker-compose example from GitHub.
2) Set up a mail account and verify connection.
3) Set up a mail rule.
4) Observe that the CRON task does not run.

### Webserver logs

```bash
As the task does not run, there are no logs.  Literally nothing in the output at all.
Logs are produced as normal when manually running `python3 manage.py mail_fetcher`.
```

### Paperless-ngx version

v2.11.2

### Host OS

TrueNAS (Debian?) x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-6.6.32-production+truenas-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 3931833237504,
        "available": 3774811734016
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://paperless_redis:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-07-30T14:56:22.640159+09:30",
        "index_error": null,
        "classifier_status": "WARNING",
        "classifier_last_trained": null,
        "classifier_error": "Classifier file does not exist (yet). Re-training may be pending."
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Mail fetching has worked for years and has not changed, I doubt its suddenly broken.

Please provide your config and the logs, entirely.

**Comment by skellycode** [comment]
Thanks @shamoon.  I find it strange that it works when invoked manually, yet not on schedule (whether the CRON is left as default, or defined in the docker compose).  On a purely clean installation as well, so it feels less like a config issue - although I'll happily be proven wrong! 😄 

docker-compose:
```
paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    depends_on:
      - paperless_redis
    volumes:
      - /mnt/Apps/docker-data/paperless-ngx/data:/usr/src/paperless/data:rw
      - /mnt/tank/Filing/Documents/Paperless-ngx:/usr/src/paperless/media:rw
      - /mnt/tank/Transfer/Paperless-Export:/usr/src/paperless/export:rw
      - /mnt/tank/Transfer/Paperless-Consume:/usr/src/paperless/consume:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      USERMAP_UID: 1125
      USERMAP_GID: 1125
      PAPERLESS_REDIS: redis://paperless_redis:6379
      PAPERLESS_SECRET_KEY: REDACTED
      PAPERLESS_URL: https://paperless.REDACTED.com
      PAPERLESS_USE_X_FORWARD_HOST: true
      PAPERLESS_USE_X_FORWARD_PORT: true
      PAPERLESS_EMAIL_TASK_CRON: '*/10 * * * *' # every 10mins
      PAPERLESS_TIME_ZONE: REDACTED
  paperless_redis:
    image: docker.io/library/redis:7
    container_name: paperless_redis
    user: 1125:1125 # paperless:paperless
    volumes:
      - /mnt/Apps/docker-data/paperless-ngx/redis:/data:rw
      - /etc/localtime:/etc/localtime:ro
```

As mentioned in the post, there is literally no logs regarding the email AT ALL when left by itself, given that it does not run on the CRON schedule.  However if invoked manually, I get this in the mail.log:

```
[2024-07-30 15:22:51,557] [DEBUG] [paperless_mail] Processing mail account REDACTED
[2024-07-30 15:22:51,584] [DEBUG] [paperless_mail] GMAIL Label Support: False
[2024-07-30 15:22:51,585] [DEBUG] [paperless_mail] AUTH=PLAIN Support: False
[2024-07-30 15:22:51,631] [DEBUG] [paperless_mail] Account REDACTED: Processing 1 rule(s)
[2024-07-30 15:22:51,634] [DEBUG] [paperless_mail] Rule REDACTED.Inbox: Selecting folder INBOX
[2024-07-30 15:22:51,680] [DEBUG] [paperless_mail] Rule REDACTED.Inbox: Searching folder with criteria (SINCE 31-Jul-2023 UNFLAGGED)
[2024-07-30 15:22:51,683] [DEBUG] [paperless_mail] Rule REDACTED.Inbox: Processed 0 matching mail(s)
```

I have tried adjusting the search folders/etc with the rule to put emails into scope, and again, when triggered manually they are consumed correctly.  It just doesn't run in the background every 10mins... 🤷
