### DISCUSSION TITLE
Unable to connect redis to paperless

### DISCUSSION THREAD

**Discussion by netsho** [paperless-ngx/paperless-ngx#7377] [Support] [answered]
Hello community,

I'm stuck and i need your help.

I'm trying to install paperless using docker compose file. I copied the official docker-compose.postgresql-tika.yml to my host, while making some minor modifications :
- Remove PostgreSQL db container as i already have postgre installed as daemon (The connection is successful).
- Configured the containers to run on a custom network (this network was created for nginx reverse proxy).
- Limited the memory usage and cpus.

The gotenberg, tika and redis containers are working as expected, but the paperless container isn't.

**Paperless container logs:**
```
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Redis ping #0 failed.
Error: Error 111 connecting to localhost:6379. Connection refused..
Waiting 5s
Redis ping #1 failed.
Error: Error 111 connecting to localhost:6379. Connection refused..
Waiting 5s
Redis ping #2 failed.
Error: Error 111 connecting to localhost:6379. Connection refused..
Waiting 5s
Redis ping #3 failed.
Error: Error 111 connecting to localhost:6379. Connection refused..
Waiting 5s
Redis ping #4 failed.
Error: Error 111 connecting to localhost:6379. Connection refused..
Waiting 5s
Failed to connect to redis using environment variable PAPERLESS_REDIS.
```

**Redis container logs:**
```
1:C 02 Aug 2024 11:43:57.788 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 02 Aug 2024 11:43:57.871 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 02 Aug 2024 11:43:57.872 * Redis version=7.4.0, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 02 Aug 2024 11:43:57.872 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 02 Aug 2024 11:43:57.874 * monotonic clock: POSIX clock_gettime
1:M 02 Aug 2024 11:43:57.879 * Running mode=standalone, port=6379.
1:M 02 Aug 2024 11:43:57.881 * Server initialized
1:M 02 Aug 2024 11:43:57.881 * Loading RDB produced by version 7.4.0
1:M 02 Aug 2024 11:43:57.881 * RDB age 14 seconds
1:M 02 Aug 2024 11:43:57.881 * RDB memory usage when created 0.93 Mb
1:M 02 Aug 2024 11:43:57.881 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 02 Aug 2024 11:43:57.881 * DB loaded from disk: 0.001 seconds
1:M 02 Aug 2024 11:43:57.881 * Ready to accept connections tcp
```

**Here is the compose file i'm using:**
```
services:
  broker:
    image: docker.io/library/redis:7.4.0
    restart: unless-stopped
    container_name: paperless-redis
    networks:
      - nginx-proxy-net
    volumes:
      - /etc/paperless-ngx/redisdata:/data
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"

  webserver:
    image: docker.io/paperlessngx/paperless-ngx:2.11
    restart: unless-stopped
    container_name: paperlessngx
    networks:
      - nginx-proxy-net
    depends_on:
      - broker
      - gotenberg
      - tika
    volumes:
      - /etc/paperless-ngx/data:/usr/src/paperless/data
      - /etc/paperless-ngx/media:/usr/src/paperless/media
      - /etc/paperless-ngx/export:/usr/src/paperless/export
      - /etc/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: podman-compose.env
    environment:
      PAPERLESS_REDIS: redis://localhost:6379
      PAPERLESS_DBHOST: localhost:5432
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless_admin
      PAPERLESS_DBPASS: l3eZZkh€D5mBlP5perL€sS
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      VIRTUAL_HOST: paperless.rock64.com
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.9.0
    restart: unless-stopped
    container_name: paperless-gotenberg
    networks:
      - nginx-proxy-net
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:2.9.2.1
    restart: unless-stopped
    container_name: paperless-tika
    networks:
      - nginx-proxy-net
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.25"

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  nginx-proxy-net:
     external: true
```

In the compose file, i have tried multiple values for PAPERLESS_REDIS env variable:
* redis://broker:6379 -> Error -5: Can't resolve hostname
* redis://paperless-redis:6379 -> Error -2: Name or service not known
* redis://localhost:6379 -> Error 111: Connection refused
* redis://<host-ip>:6379 -> Error 111: Connection refused

Does anyone have any idea how to solve this ?

I have been for awhile searching a solution on the net but couldn't find anything.

Thank you in advance
