### DISCUSSION TITLE
Problems with permissions and ownership when deploying paperless-ngx

### DISCUSSION THREAD

**Discussion by T3CHN3W** [paperless-ngx/paperless-ngx#7386] [Support]
Hello, I would like to get Paperless-ngx running on my Raspi-Pi in Docker. Since I don't want to flood the SD cards with data, I would like to store all services and media on an external SSD hard disk (exFat). However, I get the following error message when deploying the broker, db-1 and webserver-1  _**"chown: changing ownership of '.': Operation not permitted"**_

I proceeded as follows:

1. give the user "admin" ownership of the SSD and assign permissions

> sudo chown -R admin:admin /dev/sda2
> sudo chmod u=rwx,g=rwx,o= /dev/sda2
> ls -l /dev/sda2
Output: brwxrwx--- 1 admin admin 8, ... /dev/sda2

2. Mounting the SSD with permissions for the user "admin" (uid=1000(admin) gid=1000(admin) groups=1000(admin))
> sudo mount -o rw,user,uid=1000,umask=007,exec /dev/sda2 /media/externSSD/
> ls -l /media/
Output: drwxrwx--- 11 admin root 131072 ... externSSD

As I understand it, the user "Admin" now has read, write and execute rights for the mounted hard disk.

I also see that the SSD is mounted:
```
> lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda           8:0    0 465.8G  0 disk 
├─sda1        8:1    0   200M  0 part 
└─sda2        8:2    0 465.6G  0 part /media/externSSD
```

The Docker-Compose file looks like this:

```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /media/externSSD/redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - /media/externSSD/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    volumes:
      - /media/externSSD/data:/usr/src/paperless/data
      - /media/externSSD/media:/usr/src/paperless/media
      - /media/externSSD/export:/usr/src/paperless/export
      - /media/externSSD/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_SECRET_KEY: test_key
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: test_admin
      PAPERLESS_OCR_LANGUAGE: deu+eng

      USERMAP_UID: 1000
      USERMAP_GID: 1000


volumes:
  data:
  media:
  pgdata:
  redisdata:
```

The broker returns the following message:

> chown: changing ownership of '.': Operation not permitted

db-1 returns the following message:

> chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted

The webserver returns the following message:
```
chown: changing ownership of '/usr/src/paperless/media/documents': Operation not permitted
chown: changing ownership of '/usr/src/paperless/media/documents/originals': Operation not permitted
chown: changing ownership of '/usr/src/paperless/media/documents/thumbnails': Operation not permitted
chown: changing ownership of '/usr/src/paperless/consume': Operation not permitted
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Redis ping #0 failed.
Error: Error -2 connecting to broker:6379. Name or service not known..
Waiting 5s
```
I don't understand why I get these error messages when the user Admin has all rights and I set the UID and GID to the Admin user (1000).

Unfortunately I am very new to the Linux world and hope that you can help me here.

I would be very grateful.

Best regards
