### DISCUSSION TITLE
Documents folder

### DISCUSSION THREAD

**Discussion by icvdok** [paperless-ngx/paperless-ngx#7416] [Support]
Hello, just start to setup my paperless in a docker environment via docker-compose on a ubuntu server. I'm using nfs volumes where the filesystem is located on a QNAP NAS. I've created three folders to map (documenti, data and consume) , the folder "documenti" is used as media and it's in Italian.
Question:
When paperless start, it creates a folder structure documents (archive, originals and thumbnails as subfolders) within the folder "documenti" previously created as nfs mount. There is a way to avoid the documents folder creation ad keep the subfolders directly on the "documenti" folder?

**Comment by stumpylog** [comment]
Sounds like a path mapping issue, but you've given no details on your setup

**Reply by Herve-M** [reply]
Got the same question, it seems that paperless create a `documents` folder inside `/usr/src/paperless/media` which at the send end like: `/usr/src/paperless/media/documents/{archive, originals, thumbnails}`

**Comment by icvdok** [comment]
Sorry for the missing info, let me explain better the diagram here explain what i get from the setup:
![image](https://github.com/user-attachments/assets/a24af76f-9e6d-4c8f-b4a0-0f64adce859a)

**Comment by icvdok** [comment]
This is what I would like to achieve:
![image](https://github.com/user-attachments/assets/59a60228-e00c-47d5-88a5-234181ea0b85)

**Comment by icvdok** [comment]
this is the docker-compose file:

```
services:
  broker:
    image: docker.io/library/redis:7
    container_name: _paperless_redis 
    restart: unless-stopped
    networks:
      docmgmt:
        ipv4_address: 170.22.0.2
    volumes:
      - ppl_redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: _paperless_web
    restart: unless-stopped
    depends_on:
      - broker
    networks:
      docmgmt:
        ipv4_address: 170.22.0.4
    ports:
      - "8880:8000"
    volumes:
      - ppl_data:/usr/src/paperless/data
      - ppl_media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ppl_consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: xxx.xxx.xxx.xxx
      PAPERLESS_URL: https://xxxxxxxxxxxxxxxx
      PAPERLESS_APPS: xxxxxxxxxxxxxxxx
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: xxxxxxxxxxxxxxxxxx
      PAPERLESS_FILENAME_FORMAT: xxxxxxxxxxxxxxxxxxxxxxx 
volumes:
  ppl_data:
    name: nfs_paperless_data
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=qnap.lan,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      device: ":_docker/_paperless/data"  
  ppl_media:
     name: nfs_paperless_media
     driver: local
     driver_opts:
       type: "nfs"
       o: "addr=qnap.lan,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
       device: ":_docker/_paperless/__documenti"
  ppl_consume:
     name: nfs_paperless_consume
     driver: local
     driver_opts:
       type: "nfs"
       o: "addr=qnap.lan,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
       device: ":_docker/_paperless/consume"
  ppl_redisdata:
     name: nfs_paperless_redis
     driver: local
     driver_opts:
       type: "nfs"
       o: "addr=qnap.lan,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
       device: ":_docker/_paperless/redis"

networks:
  docmgmt:
    name: net_paperless
    ipam:
      config:
        - subnet: 170.22.0.0/24
          gateway: 170.22.0.1
```
