### DISCUSSION TITLE
Using Paperless-NGX with Authelia OIDC

### DISCUSSION THREAD

**Discussion by poperigby** [paperless-ngx/paperless-ngx#7560] [Support] [answered]
I'm trying to setup paperless-ngx with Authelia OIDC, but a button for logging in with OIDC isn't showing up on the login page. I'm using version 2.11.4. Here's my config:

```env
PAPERLESS_DBHOST="/run/postgresql"
PAPERLESS_APPS="allauth.socialaccount.providers.openid_connect"
PAPERLESS_SOCIALACCOUNT_PROVIDERS_FILE=<path>
```

This is what I have in the file at that path:

```json
{
    "openid_connect": {
        "SCOPE": [
            "openid",
            "profile",
            "email"
        ],
        "OAUTH_PKCE_ENABLED": true,
        "APPS": [
            {
                "provider_id": "authelia",
                "name": "Authelia",
                "client_id": "REDACTED",
                "secret": "REDACTED",
                "settings": {
                    "server_url": "https://auth.haddock.cc",
                    "token_auth_method": "client_secret_basic"
                }
            }
        ]
    }
}
```

I also have this in my Authelia config:

```yaml
- client_name: 'Paperless'
  client_id: {{ secret "/run/secrets/paperless-oidc-client-id_authelia" | mindent 10 "|" | msquote }}
  client_secret: {{ secret "/run/secrets/paperless-oidc-client-secret_authelia" | mindent 10 "|" | msquote }}
  public: false
  authorization_policy: 'one_factor'
  require_pkce: true
  pkce_challenge_method: 'S256'
  redirect_uris:
    - 'https://paper.haddock.cc/accounts/oidc/authelia/login/callback/'
  scopes:
    - 'openid'
    - 'profile'
    - 'email'
    - 'groups'
  userinfo_signed_response_alg: 'none'
  token_endpoint_auth_method: 'client_secret_basic'
```

Navigating to https://paper.haddock.cc/accounts/oidc/authelia/login/callback/ gives me a page with `Server Error (500)`
