### DISCUSSION TITLE
Mapping network folder to consume directory

### DISCUSSION THREAD

**Discussion by thisIsLiving** [paperless-ngx/paperless-ngx#774] [Support] [answered]
I've got paperless-ngx running fine in Windows Docker but I can't seem to map a SMB network folder to the the consume directory. I've tried the below docker-compose.yml

```
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - //192.168.1.40/scans:/usr/src/paperless/consume
```
What do I need to do to make this work?

**Comment by thisIsLiving** [comment, marked as answer]
Looks like I just had to mount it via a different way. Config ended up being:

```
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - scans:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
  media:
  pgdata:
  scans:
    driver_opts:
      type: cifs
      o: username=<user>,password=<password>,uid=1000,gid=1000,vers=1.0,rw
      device: //192.168.1.40/scans
```
