### DISCUSSION TITLE
Bug that was announced to been fixed, still present issue #7438

### DISCUSSION THREAD

**Discussion by SaFi2266** [paperless-ngx/paperless-ngx#7745] [Support]
Hi, ALL

Regard to issue "initial upload message not being dismissed"

I preferred to report this here rather than bug report, because I am not sure whether it's an effect on all or not.

My Setup
- paperless-ngx version: 2.12.1
- Environment: container (Docker) latest images from docker hub
- Host: Ubuntu 24.04
- Reverse proxy: openlitespeed

My docker-compose file like below
```
name: paperless-ngx
services:
  broker:
    image: docker.io/library/redis:latest #redis:latest
    restart: unless-stopped
    volumes:
      - ./redis-data:/data

  db:
    image: docker.io/library/postgres:16 #postgres:latest
    restart: unless-stopped
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  web:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest #paperlessngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8050:8000"
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7 #gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest #apache/tika:latest 
    restart: unless-stopped
```
the docker-compose.env is
```
USERMAP_UID=1000
USERMAP_GID=1000

PAPERLESS_OCR_LANGUAGES=ara
PAPERLESS_TIME_ZONE=Asia/Baghdad
PAPERLESS_OCR_LANGUAGE=eng+ara

PAPERLESS_DEBUG=true

PAPERLESS_URL=https://paperless.iqnethub.com
PAPERLESS_CSRF_TRUSTED_ORIGINS=https://paperless.iqnethub.com # can be set using PAPERLESS_URL
PAPERLESS_ALLOWED_HOSTS=paperless.iqnethub.com # can be set using PAPERLESS_URL
PAPERLESS_CORS_ALLOWED_HOSTS=https://localhost:8050,https://paperless.iqnethub.com # can be set using PAPERLESS_URL
PAPERLESS_USE_X_FORWARD_HOST=true
PAPERLESS_USE_X_FORWARD_PORT=true

PAPERLESS_OCR_DESKEW=true
PAPERLESS_OCR_ROTATE_PAGES=true

PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini"]
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
PAPERLESS_CONSUMER_ENABLE_BARCODES=true
PAPERLESS_CONSUMER_BARCODE_STRING=PATCHT
PAPERLESS_CONSUMER_BARCODE_UPSCALE=1.5
PAPERLESS_CONSUMER_BARCODE_DPI=600
PAPERLESS_CONSUMER_ENABLE_TAG_BARCODE=true
PAPERLESS_CONSUMER_TAG_BARCODE_MAPPING={"NFT": "نفط", "TYB": "طبية", "KHR": "كهرباء", "MKN": "ميكانيك", "SYR": "سيارات", "MDN": "معادن", "TBR": "تبريد", "NJR": "نجارة", "NSJ": "نسيج"}

PAPERLESS_FILENAME_FORMAT={created_year}/{created_month}/{created_day}/{title}({original_name})-{doc_pk}
PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=true

PAPERLESS_CONVERT_BINARY=/usr/bin/convert
PAPERLESS_GS_BINARY=/usr/bin/gs
```
So, every time I upload a document to pngx web interface, the progress of uploading stay present till to reload the webpage.

I am asking for any suggestions to digging about this issue or trying to correct it?

Note: _my server is on local network without incoming from Internet access._
