### DISCUSSION TITLE
No documents after restore of docker volumes

### DISCUSSION THREAD

**Discussion by eric72777** [paperless-ngx/paperless-ngx#7772] [Support]
After my system went down, I needed to reinstall the system and restore from backups of docker volumes. All of my other services are working fine except paperless. It looks like all files exist on the host and I am able to log in using my paperless account, but no documents are shown in the paperless UI. Do I need to be on the same image number for the documents to properly show up? If so, is there a way to see the image number from my backups? Is there a way to re-import the documents/metadata from the existing documents in the folder?

My docker compose is below:
```
services:
  paperless_broker:
    image: docker.io/library/redis:7
    container_name: paperless_broker
    restart: unless-stopped
    volumes:
      - /mnt/data/paperless/redisdata:/data
  paperless_db:
    image: docker.io/library/postgres:15
    container_name: paperless_db
    restart: unless-stopped
    volumes:
      - /mnt/data/paperless/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  paperless_webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless_webserver
    restart: unless-stopped
    depends_on:
      - paperless_db
      - paperless_broker
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/data/paperless/data:/usr/src/paperless/data
      - /mnt/data/paperless/media:/usr/src/paperless/media
      - /mnt/data/paperless/export:/usr/src/paperless/export
      - /mnt/data/paperless/consume:/usr/src/paperless/consume
    env_file: paperless.env
    environment:
      PAPERLESS_REDIS: redis://paperless_broker:6379
      PAPERLESS_DBHOST: paperless_db
```

In the future, I now know that I should have been performing backups using document exporter.
