### DISCUSSION TITLE
KeyError: 'getpwuid(): uid not found: 1033'

### DISCUSSION THREAD

**Discussion by BoBBer446** [paperless-ngx/paperless-ngx#7793] [Support] [answered]
Hello, one of my servers is broken, so I have made a backup on another server. 

I have two paperless instances. Mine works, my girlfriend's doesn't. I get this error:

```ini
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
mkdir: created directory '/tmp/paperless'
Adjusting permissions of paperless files. This may take a while.
changed ownership of '/usr/src/paperless/consume' from 1033:users to paperless:paperless
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  No migrations to apply.
Running Django checks
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless/checks.py", line 35, in path_check
    with open(test_file, "w"):
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/consume/__paperless_write_test_57__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/check.py", line 76, in handle
    self.check(
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/paperless/checks.py", line 67, in paths_check
    + path_check("PAPERLESS_CONSUMPTION_DIR", settings.CONSUMPTION_DIR)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/paperless/checks.py", line 40, in path_check
    dir_owner = pwd.getpwuid(dir_stat.st_uid).pw_name
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'getpwuid(): uid not found: 1033'
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
changed ownership of '/usr/src/paperless/consume' from 1033:users to paperless:paperless
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  No migrations to apply.
Running Django checks
```

`/usr/src/paperless/consume` is located on the host system:
` - /home/nas/JulianeNas/paperless-ngx/consume:/usr/src/paperless/consume`

This folder is integrated via fstab:
`//192.168.178.146/homes /home/nas/ cifs credentials=/etc/samba/credentials,iocharset=utf8,vers=3.0,uid=1033,gid=100,file_mode=0775,dir_mode=0775 0 0`
uid=1033,gid=100 is the id from nas user im using here to mount:
```bash
sudo id nipogi_paperless_rene
uid=1033(nipogi_paperless_rene) gid=100(users) groups=100(users),101(administrators)
```
The folder on the Nas also belongs to the user
![image](https://github.com/user-attachments/assets/ff0da46d-d9f0-4e6a-9f97-9319d4fe091f)

I hope someone can help me to solve the problem.

The alternative would probably just be to start again, right?
The original ones are here
/home/rene/docker-projects/paperless/juliane/volumes/media/documents/originals

```yml
services:
  broker_juliane:
    image: docker.io/library/redis:7
    restart: always
    volumes:
      - /home/rene/docker-projects/paperless/juliane/volumes/redisdata:/data
    networks:
      - juliane_paperless_netzwerk

  db_juliane:
    image: docker.io/library/postgres:15
    restart: always
    volumes:
      - /home/rene/docker-projects/paperless/juliane/volumes/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - juliane_paperless_netzwerk

  webserver_juliane:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    #user: 1033:100 #uid und gid des Besitzers des Odners und per fstab eingemountet
    restart: always
    depends_on:
      - db_juliane
      - broker_juliane
      - tika_juliane
      - gotenberg_juliane
    ports:
      - "8001:8000"
    volumes:
      - /home/nas/JulianeNas/paperless-ngx/consume:/usr/src/paperless/consume
      - /home/rene/docker-projects/paperless/juliane/volumes/data:/usr/src/paperless/data
      - /home/rene/docker-projects/paperless/juliane/volumes/media:/usr/src/paperless/media
      - /home/rene/docker-projects/paperless/juliane/volumes/export:/usr/src/paperless/export
      - /home/rene/docker-projects/paperless/juliane/volumes/pre_scripte:/scripts:ro
    env_file:
      - stack.env  # Hier wird die env-Datei referenziert
    networks:
      - juliane_paperless_netzwerk

  tika_juliane:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: always

    networks:
      - juliane_paperless_netzwerk

  gotenberg_juliane:
    image: thecodingmachine/gotenberg:8.7
    restart: always
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--api-timeout=600s"
      - "--uno-listener-start-timeout=120s"
    networks:
      - juliane_paperless_netzwerk

networks:
  juliane_paperless_netzwerk:
    driver: bridge

volumes:
  data_juliane:
  media_juliane:
  pgdata_juliane:
  redisdata_juliane:
```
