### DISCUSSION TITLE
docker setup ran, then: /sbin/docker-prepare.sh: line 42: /dev/tcp/db/3306: Connection refused

### DISCUSSION THREAD

**Discussion by Kugeleis** [paperless-ngx/paperless-ngx#7837] [Support] [answered]
I run paperless-ngx on a ubuntu server with docker. It ran for weeks flawlessly. Now I see `/sbin/docker-prepare.sh: line 42: /dev/tcp/db/3306: Connection refused` in the paperless log. I did not change anyting. What can be the reason?

In the docker-network for paperless are only paperless, redis and mariadb.

<details>

<summary>compose.yaml</summary>

```yaml
version: "3.8"
name: paperless-ngx
services:
  broker:
    container_name: paperless_redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /data/paperless/volumes/redis:/data

  db:
    container_name: paperless_mariadb
    image: docker.io/library/mariadb:11
    restart: unless-stopped
    volumes:
     - /data/paperless/volumes/database:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  webserver:
    container_name: paperless_server
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8888:8000"
    volumes:
      - /data/paperless/volumes/data:/usr/src/paperless/data
      - /data/paperless/volumes/media:/usr/src/paperless/media
      - /data/paperless/volumes/export:/usr/src/paperless/export
      - /data/paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBPORT: 3306
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'

```

</details>
<details>
<summary>docker-compose.env</summary>

```yaml
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.

USERMAP_UID=1004
USERMAP_GID=100

# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.

PAPERLESS_OCR_LANGUAGES=deu

###############################################################################
# Paperless-specific settings
###############################################################################

# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.
# This is required if you will be exposing Paperless-ngx on a public domain
# (if doing so please consider security measures such as reverse proxy)
#PAPERLESS_URL=https://paperless.example.com
# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
PAPERLESS_SECRET_KEY=myverylongandverysecretkey
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.

PAPERLESS_TIME_ZONE=Europe/Berlin

# The default language to use for OCR. Set this to the language most of your
# documents are written in.

PAPERLESS_OCR_LANGUAGE=deu

# Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx

#PAPERLESS_FORCE_SCRIPT_NAME=/PATHPREFIX
#PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # trailing slash required
#PAPERLESS_CONSUMER_POLLING=30

PAPERLESS_CONSUMER_ASN_BARCODE_PREFIX=HOME
PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true
PAPERLESS_CONSUMER_ENABLE_BARCODES=true
PAPERLESS_CONSUMER_BARCODE_SCANNER=ZXING

```

</details>

<details>

<summary>mariadb error logs</summary>

```
2024-10-02 16:13:52 0 [ERROR] InnoDB: Unable to lock ./ibdata1 error: 11
2024-10-02 16:13:52 0 [Note] InnoDB: Check that you do not already have another mariadbd process using the same InnoDB data or log files.
2024-10-02 16:13:52 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2024-10-02 16:13:52 0 [Note] InnoDB: Starting shutdown...
2024-10-02 16:13:52 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-10-02 16:13:52 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-10-02 16:13:52 0 [Note] Plugin 'wsrep-provider' is disabled.
2024-10-02 16:13:52 0 [ERROR] Could not open mysql.plugin table: "Unknown storage engine 'Aria'". Some plugins may be not loaded
2024-10-02 16:13:52 0 [ERROR] Failed to initialize plugins.
2024-10-02 16:13:52 0 [ERROR] Aborting
```

</details>
