### DISCUSSION TITLE
PAPERLESS_CONSUMER_POLLING won't work

### DISCUSSION THREAD

**Discussion by SgtHater** [paperless-ngx/paperless-ngx#7937] [Support] [answered]
Hello, I'm pretty new to paperless-ngx and docker so I'm trying to give as much info as I can. 

I installed paperless-ngx as a docker container on a windows laptop and I seems like everything works. 
But paperless won't recognize new documents. Only after I restart the container. 

At the path "C:\Users\User\Documents\Paperless" I have the docker-compose.env and the docker-compose.yml file. 
my docker-compose.env file is unchanged. 

And my yaml looks like this. 
```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./import:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379

volumes:
  data:
  media:
  redisdata:
```
In the documentation it says that when paperless won't consume  new documents, I have to add f.e. PAPERLESS_CONSUMER_POLLING=10 into my docker-compose.env. I did that, restarted the container, added some files to the import folder, waited a minute and nothing happened, restarted container and then the files are consumed.

i tried the add the setting also in the yml under environment: like 
```
environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_CONSUMER_POLLING=10
```
and retried but it didn't help. 
Am I doing something wrong? Sorry if I'm completely stupid.
