### DISCUSSION TITLE
Connection Error with PostgreSQL after Paperless-NGX Update

### DISCUSSION THREAD

**Discussion by robertobasile84** [paperless-ngx/paperless-ngx#8164] [Support] [answered]
Hello everyone,

After the latest update (from 2.12.1 to 2.13.3), I’m experiencing a connection error with my Paperless-NGX setup. The system was working perfectly before, but now, after updating, I receive the following error when starting the `paperless-ngx` container:

> psycopg.OperationalError: [Errno -2] Name or service not known 
> django.db.utils.OperationalError: [Errno -2] Name or service not known

The Paperless-NGX container appears unable to connect to the PostgreSQL database, suggesting a hostname resolution issue.

### Stack Details

Here’s the `docker-compose` configuration file I’m using in Portainer:

```yaml
version: "3.6"
services:
  broker:
    image: redis
    container_name: Paperless-NGX-REDIS
    restart: always
    volumes:
      - /volume1/docker/paperlessngx/redis:/data

  db:
    image: postgres
    container_name: Paperless-NGX-DB
    restart: always
    volumes:
      - /volume1/docker/paperlessngx/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: paperlessngx/paperless-ngx:latest
    container_name: Paperless-NGX
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - 8777:8000
    volumes:
      - /volume1/docker/paperlessngx/data:/usr/src/paperless/data
      - /volume1/docker/paperlessngx/media:/usr/src/paperless/media
      - /volume1/docker/paperlessngx/export:/usr/src/paperless/export
      - /volume1/docker/paperlessngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1026
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: America/Detroit
      PAPERLESS_ADMIN_USER: ff8mania
      PAPERLESS_ADMIN_PASSWORD: xxxxxx
      PAPERLESS_OCR_LANGUAGE: ita+eng
```

### Downgraded to the previous working version: 
I reverted to the last known working version (2.12.1), but the issue persists.

### Rebuilt containers and cleared Docker cache: 
I restarted everything, including clearing Docker volumes, but it failed.

### Used Portainer: 
I am managing this stack through Portainer, which has previously worked without issues.

## Request
I'd appreciate any help from anyone who has experienced similar issues or has insights into potential solutions. 
Could this be related to recent Paperless-NGX changes that affect network or database configurations?
