### DISCUSSION TITLE
Persistent Gotenberg errors 404 and 503 - no suggested solution made it work

### DISCUSSION THREAD

**Discussion by MrNo4Name** [paperless-ngx/paperless-ngx#8187] [Support]
Hello everyone,
I tried almost every solution that is suggested in other threads here but Gotenberg is not working with .eml files for me. I can import mails with attachements but mails withouth attachement don't work.

When I use the following config in docker, I receive an error 503. When I upgrade to "latest" it is error 404. 

```
  gotenberg:
    image: gotenberg/gotenberg:8.7
    container_name: PaperlessNGX-GOTENBERG
    hostname: gotenberg
    
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--api-timeout=600s"
      - "--libreoffice-disable-routes=false"
      - "--libreoffice-auto-start=true"
    restart: on-failure:5
```
I even tried removing all commands exept the javascript one and allow-list. It is still error 503. Downgrading to different versions of 7.x didn't work either. In this case, the logs show that the container crashes immediately. Interestingly the cpu usage of the host didn't go up. Additionally I tried to add start-timeouts as someone in a different thread stated, but it didn't work.

The rest of my ppl-ngx configuration is a basic docker compose file running on a Synology DS1621+. It works like a charme except Gotenberg when it should convert single .eml files. 

I am pretty sure it is not a DNS or other network routing mistake because gotenberg is working for e-mails with attachements.

Since the last threads with reasonable suggestions to fix this problem is from mid 2023 (and didn't worked out for me), I hoped that there are newer fixes. I just couldn't find any.
Does anyone has a working solution with Gotenberg?

**Comment by Atomique** [comment]
No, I also have the same problem here. I tried so many combinations, but everytime the response is a 404.

**Comment by OverDodo** [comment]
This is the setup i run currently and I dont have any issues - import of attachments and/or import of eml works fine. 

Maybe its one you havent tried and it works for you as well?

```yml
gotenberg:
    image: gotenberg/gotenberg:8.7
    container_name: Paperless-NGX-GOTENBERG
    hostname: gotenberg
    security_opt:
      - no-new-privileges:true
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-auto-start=true"
      - "--api-timeout=300s"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--libreoffice-auto-start=true"
      - "--libreoffice-restart-after=0"
    restart: on-failure:5
```

**Reply by MrNo4Name** [reply]
Thanks for the help, but...
Your code worked for at least a minute and one E-Mail before it did not work again. I have still no clue what is causing this unpredictable behaviour.

**Reply by OverDodo** [reply]
Odd, can you share the gotenberg logs?

**Reply by MrNo4Name** [reply]
Sure. I restarted the stack to get a shorter log. Interestingly the processing all .eml file suddenly worked without errors. Let's see how long it will stay like that

**Reply by OverDodo** [reply]
Sounds good, maybe you didnt properly recreate the container after making the changes to the compose? Had people test this compose on multiple different setups so it should work out

**Comment by janaxhell** [comment]
I am running Paperless NGX on Open Media Vault 7/Docker. Tried every solution suggested in maaaany posts, changed several versions of Gotenberg, none of them ever worked. My Paperless NGX can only ingest correctly PDF attachments, but never ever converts .eml to PDF, not even with --api-timeout=600s. Posting this just to add OMV7 feedback.

EDIT It was not asked to me, but I will paste here my gotenberg log anyway:

```
  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/
A Docker-powered stateless API for PDF files.
Version: 8.7.0
-------------------------------------------------------
[SYSTEM] modules: api chromium exiftool libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] prometheus: collecting metrics
[SYSTEM] pdfengines: exiftool libreoffice-pdfengine pdfcpu pdftk qpdf
[SYSTEM] chromium: Chromium automatically started
[SYSTEM] libreoffice-api: LibreOffice automatically started
[SYSTEM] api: server listening on port 3000
ERR ts=1734699008.6597674 logger=api msg=code=404, message=Not Found trace=0582f53f-1837-4929-8953-df48db9e7033 remote_ip=172.29.0.1 host=192.168.1.164:3002 uri=/forms/chromium/convert/html method=POST path=/forms/chromium/convert/html referer= user_agent=python-httpx/0.27.2 status=404 latency=31401 latency_human=31.401µs bytes_in=14037 bytes_out=9
ERR ts=1734699608.6576972 logger=api msg=code=404, message=Not Found trace=0139d728-c8d8-472c-bc52-1ae11faf0a93 remote_ip=172.29.0.1 host=192.168.1.164:3002 uri=/forms/chromium/convert/html method=POST path=/forms/chromium/convert/html referer= user_agent=python-httpx/0.27.2 status=404 latency=43921 latency_human=43.921µs bytes_in=96407 bytes_out=9
```

**Reply by OverDodo** [reply]
And what compose did you use for that?

**Reply by janaxhell** [reply]
Here. Ports 3000 and 8000 are already taken by other services, so I deviated them.
EDIT
[wrong compose, check reply below]

**Reply by OverDodo** [reply]
You seem to be missing the PAPERLESS_GOTENBERG_ENDPOINT env variable. And can you also try with the gotenberg compose i posted in the other reply?

**Reply by janaxhell** [reply]
No, sorry, it's there, but I had removed all the lines containing a "#" and there were a couple that should have not been removed. This is the real full compose. What do you mean by trying yours? Replacing the commands in mine with yours?

```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/paperless-ngx/redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/paperless-ngx/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /srv/dev-disk-by-uuid-8998116d-e145-4319-8c9f-41609747f657/Configs/paperless-ngx/data:/usr/src/paperless/data
      - /srv/dev-disk-by-uuid-ba4514c7-4c36-4c08-9827-3f3f584ab6b0/data/paperless/media:/usr/src/paperless/media
      - /srv/dev-disk-by-uuid-ba4514c7-4c36-4c08-9827-3f3f584ab6b0/data/paperless/export:/usr/src/paperless/export
      - /srv/dev-disk-by-uuid-ba4514c7-4c36-4c08-9827-3f3f584ab6b0/data/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_URL: https://paperless.janaxhell.com
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
      PAPERLESS_FILENAME_FORMAT: '{created_year}/{correspondent}/{document_type}/{created_year}-{created_month}-{created_day} - {title} [{asn}]'
      USERMAP_UID: 998
      USERMAP_GID: 100
      PAPERLESS_OCR_LANGUAGES: ita eng 
      PAPERLESS_TIME_ZONE: Europe/Rome
      PAPERLESS_OCR_LANGUAGE: ita+eng
      PAPERLESS_OCR_ROTATE_PAGES: true
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://192.168.1.164:3002 #/forms/chromium/convert/html  #/forms/libreoffice/convert#/forms/libreoffice/convert
      PAPERLESS_TIKA_ENDPOINT: http://192.168.1.164:9998
      PAPERLESS_WORKER_TIMEOUT: 3600
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true
      PAPERLESS_CONSUMER_ASN_BARCODE_PREFIX: 00
      PAPERLESS_CONSUMER_ENABLE_BARCODES: false
  gotenberg:
    container_name: paperless-gotenberg
    image: gotenberg/gotenberg:8.7 # :latest = 8.14.1
    restart: unless-stopped
    ports:
      - 3002:3000

    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
      - "--chromium-restart-after=5"
      - "--chromium-auto-start=true"
      - "--libreoffice-disable-routes=false"
      - "--libreoffice-auto-start=true"
      - "--libreoffice-restart-after=0" # prima era 5
      - "--chromium-ignore-certificate-errors=true"
      - "--chromium-disable-web-security=true"
      - "--chromium-allow-insecure-localhost=true"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--chromium-start-timeout=30s"
      - "--api-timeout=600s"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: tika
    ports:
      - 9998:9998
    restart: unless-stopped
```
