### DISCUSSION TITLE
Consumption Directory Not Processing Files in Paperless-ngx

### DISCUSSION THREAD

**Discussion by DockLoco** [paperless-ngx/paperless-ngx#8239] [Support] [answered]
**Description of the Problem:**

I’ve set up Paperless-ngx using Docker Compose, and everything is working except for the consumption directory. Files placed in the designated consume directory are not being processed, despite confirming configuration and permissions.

Environment Details:

- 	System: QNAP NAS QTS 5.2.1.2930 (Docker running in a Linux environment)
- 	Docker Compose Version: Compose version v2.29.1-qnap1
- 	Paperless-ngx Version: latest from GitHub Container Registry
- 	Database: MariaDB 10

**Configuration Files and Settings:**

Below is my docker-compose.yml file, with sensitive information anonymized:

```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./volumes/redis:/data

  db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - ./volumes/database:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: ******** # Hidden
      MARIADB_ROOT_PASSWORD: ******** # Hidden

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/data:/usr/src/paperless/data
      - ./volumes/media:/usr/src/paperless/media
      - ./volumes/export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume  # Directory mapped for document consumption
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: ******** # Hidden
      PAPERLESS_DBPORT: 3306
      PAPERLESS_CONSUMER_POLLING: 5  # Polling enabled for network file system
```

Troubleshooting Steps Taken:
1.	Directory Verification: Confirmed that ./consume exists in the same directory as docker-compose.yml and has the correct permissions (read and write access).

2.	Polling Configuration: Added PAPERLESS_CONSUMER_POLLING: 5 in docker-compose.yml to enable periodic polling, given that the consumption directory is on a network file system.

3.	Permissions Check: Set permissions on ./consume to ensure Docker has access:

```
sudo chmod -R 755 ./consume
sudo chown -R $(whoami):$(whoami) ./consume
```

4. Log Monitoring: Checked docker compose logs -f webserver for any messages related to file consumption. The logs show that Paperless-ngx is running normally, but there’s no indication of new files being processed when they’re placed in the consume folder.

5. Tested with Local Directory: Tried mapping a local directory directly (instead of the network directory) and placed a test PDF, but still no processing.

6. Configuration Checks: Verified that only supported file types (PDF) are being placed in consume to avoid format-related issues.

Problem Persistence:
Despite these attempts, Paperless-ngx does not detect or process files in the consume directory. I suspect it could be an issue specific to the NAS environment or the Docker configuration, but I’m unable to pinpoint the root cause.

Request for Help:
Any insights or suggestions would be greatly appreciated, especially regarding additional configuration options, NAS-related issues, or any known workarounds.
