### DISCUSSION TITLE
Use Nas as main storage

### DISCUSSION THREAD

**Discussion by jbulmers** [paperless-ngx/paperless-ngx#8253] [Support]
Hello,

I've recently installed Paperless-ngx on a NUC where i have proxmox installed. The problem is that i don't have a lot of storage on that NUC, and therefore i need to use my NAS as the storage for the documents.

I have not found the information on how to configure a network share for paperless-ngx in order for it to have the paperless-ngx database and the document all on the NAS instead of the NUC drive. 

Is it possible to do so ? If yes, would it be possible to help me out ?

Thank you for your help

**Comment by mquade** [comment]
Hi, you may specify it in the docker-compose.yml. 
This is an *example* (!!) out of my file:
```
    webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
[...]
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - paperless-ngx_consume-nfs:/usr/src/paperless/consume <-- !! THIS is a shared NFS on a separate server !!
      - /home/paperless-ngx/export:/usr/src/paperless/export  
#      - /home/paperless-ngx/consume:/usr/src/paperless/consume
```


You also need to specify the volume in the compose file:
```volumes:
  data:
  media:
  pgdata:
  redisdata:
  paperless-ngx_consume-nfs:
    external: true
```
Either you import it on the host with standard linux tools (fstab, mount etc) or you[ create a dedicated nfs-volume.](https://phoenixnap.com/kb/nfs-docker-volumes)
