### DISCUSSION TITLE
Paperless is not consuming files

### DISCUSSION THREAD

**Discussion by jmcanedoa** [paperless-ngx/paperless-ngx#8382] [Support] [answered]
Hi all:
After many configuration tests, I have not been able to get Paperless to consume documents from my consumer folder.

My docker compose:

```yaml
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8005:8000"
    volumes:
      - $DOCKERDIR/paperless/data:/usr/src/paperless/data
      - $DOCKERDIR/paperless/media:/usr/src/paperless/media
      - $DOCKERDIR/paperless/export:/usr/src/paperless/export
      - $DOCKERDIR/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_DEBUG: true
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: 0
      USERMAP_GID: 0
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: ${PG_USER} # only needed if non-default username
      PAPERLESS_DBPASS: ${PG_PASS} # only needed if non-default password
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMPTION_DIR: /home/jose/docker/paperless/consume
      PAPERLESS_CONSUMER_RECURSIVE: 1
      PAPERLESS_URL: https://paperless.canedocolon.duckdns.org
      PAPERLESS_TIME_ZONE: Europe/Madrid
      PAPERLESS_OCR_LANGUAGE: spa
      PAPERLESS_OCR_LANGUAGES: eng
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: 1
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
      # PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: 1
      # PAPERLESS_OCR_MODE: skip
      PAPERLESS_CONSUMER_IGNORE_PATTERNS: '[".DS_STORE/*", "._*", ".stfolder/*","@eaDir/*"]'
```

And the log:

````
[2024-11-29 20:45:34,741] [DEBUG] [paperless.management.consumer] Consumer exiting.
[2024-11-29 20:46:24,078] [INFO] [paperless.management.consumer] Polling directory for changes: /home/jose/docker/paperless/consume
[2024-11-29 20:48:30,768] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
````

And nothing happens when I move a pdf document in /home/jose/docker/paperless/consume

I have tried different options with 
      PAPERLESS_CONSUMER_POLLING: 60
My directory uses samba/cifs.

If anybody has any idea, please, let me know to try it.

Thanks in advance!
