### DISCUSSION TITLE
Docker compose webserver container not using USERMAP_UID when writing to media

### DISCUSSION THREAD

**Discussion by benlinton** [paperless-ngx/paperless-ngx#8434] [Support] [answered]
### Description

It seems the `webserver` docker container does not use the mapped `USERMAP_UID` and `USERMAP_GID` when writing to `media`, `consume` (e.g. creating the folder on initial build), and the likes. 

- When the `webserver` container is initializing directories (`media`, `consume`, etc) on `docker compose up` build, it seems like it's using the `root` user instead of the mapped user.
- If I create the necessary directories for paperless in order to bypass the directory creation issues, the logs still complain that the container is unable to write to `media` after successfully booting
- When I jump into the container `docker compose exec webserver bash` and switch users `su - paperless` without modifying the webserver container, I can write to `media` container without any permission issues

I'm using this docker-compose file https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.postgres-tika.yml

### Steps to reproduce

Verify the `media` folder on the host has the correct permissions and the `paperless` user can write to it.
    
    useradd -u 2104 paperless
    chown -R paperless:paperless /mnt/nfs/services-paperless
    chmod -R 775 /mnt/nfs/services-paperless
    su - paperless
    touch test

Fire up the official docker compose with the UID and GID mapped to `2014`

The webserver container use the mapped UID and GID when creating directories or writing to `media`.

### Webserver logs

```bash
webserver-1  | Paperless-ngx docker container starting...
webserver-1  | Mapping UID and GID for paperless:paperless to 2104:2104
webserver-1  | Creating directory /usr/src/paperless/media/documents
webserver-1  | mkdir: cannot create directory ‘/usr/src/paperless/media/documents’: Permission denied
```

### Paperless-ngx version

v2.13.5 (latest)

### Host OS

Debian (Proxmox)

### Installation method

Docker - official image

### Browser

Chrome

## docker-compose.yml

```
services:

  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - /mnt/nfs/services-paperless/media:/usr/src/paperless/media
      - /mnt/nfs/services-paperless/export:/usr/src/paperless/export
      - /mnt/nfs/services-paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  data:
  pgdata:
  redisdata:

```

## docker-compose.env

```
###############################################################################
# Paperless-ngx settings                                                      
###############################################################################

# See http://docs.paperless-ngx.com/configuration/ for all available options.

# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=2104
USERMAP_GID=2104
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
