### DISCUSSION TITLE
[Feature Request] API to get current Paperless-NGX version

### DISCUSSION THREAD

**Discussion by dannytsang** [paperless-ngx/paperless-ngx#8491] [Feature Requests] [answered]
### Description

I would like to use [Release Argus](https://release-argus.io/) to monitor deployed version against the latest version. An API end point to get this information would facilitate this.

### Other

Nice to have tbh.

**Comment by stumpylog** [comment, marked as answer]
System status includes the version

**Reply by dannytsang** [reply]
What's the end point? I'm look at this part of the documentation and can't see a system status: https://docs.paperless-ngx.com/api/

**Reply by stumpylog** [reply]
/api/status probably. The builtin browser will show it

**Comment by github-actions** [comment]
This discussion has been automatically closed because it was marked as answered. Please see our [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/dev/CONTRIBUTING.md#automatic-repository-maintenance) for more details.

**Comment by thickconfusion** [comment]
I desire this exact functionality and don't see how using the Settings>System Status modal dialog works with Release Argus. @dannytsang did you get this working? I believe an API endpoint, even if it should be authenticated, would be a great feature.

**Reply by dannytsang** [reply]
I did. Make sure your account is an admin:
![image](https://github.com/user-attachments/assets/e8524107-a0e6-4c52-aa3a-97f999f241a3)

Replace the square brackets and contents **[]** with your info.
```
service:
  paperless-ngx/paperless-ngx:
    latest_version:
      type: github
      url: paperless-ngx/paperless-ngx
    deployed_version:
      method: GET
      url: http://[IP/URL]:[port]/api/status/?format=json
      basic_auth:
        username: [username - change me]
        password: [password - change me]
      regex: "[0-9].+"
      json: pngx_version
    notify:
      slack:
        params:
          icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/refs/heads/dev/resources/logo/web/svg/square.svg
    dashboard:
      icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/refs/heads/dev/resources/logo/web/svg/square.svg
      web_url: https://github.com/paperless-ngx/paperless-ngx/releases
```
