### DISCUSSION TITLE
Store documents on NAS.

### DISCUSSION THREAD

**Discussion by Skhoooler** [paperless-ngx/paperless-ngx#8496] [Support]
I'd like for Paperless to store my documents on my NAS. The server I have doesn't have much space, all of my other data is on the NAS (named Cerberus). I've looked up a lot of resources, both Paperless-ngx-specific, and docker-compose specific about how to mount a NAS to a docker container, but It doesn't seem to have worked, since I don't see any of the documents I've uploaded at the location I specified in the NAS.

I'll attach my docker-compose.yml and docker-compse.env

![yml](https://github.com/user-attachments/assets/85460b9a-899a-4da6-b30a-c200aa365532)
![env](https://github.com/user-attachments/assets/2a0444b2-c8fe-45e1-98cf-c4c93ae2862b)

Thanks for all of your help!

**Comment by stumpylog** [comment]
It looks generally correct.  Are there errors?  You have re-created the container?  Maybe re-created the volumes too?

**Reply by Skhoooler** [reply]
Thanks for replying! I'm not getting any errors. I guess what I'm looking for is confirmation that the documents are being saved on the NAS as opposed to the server. I'm relatively new to docker/compose, so I'm not sure how it works, but I'd expect to be able to see the documents I've uploaded in the NAS folder, and I don't.

Is there any way you know of to confirm that they're being saved in the right place?

**Reply by stumpylog** [reply]
Since you changed the definitions of the volumes, have you run `docker compose down && docker compose up`?  Maybe try `docker volume inspect` against one and see what it outputs?

**Reply by Skhoooler** [reply]
Yes, I've run down and up so these are the settings the container will be running. But I'll try testing that volume when I get home tonight. Thanks!

**Reply by luisr-ca** [reply]
@Skhoooler Which NAS are you using ?   We have paperless saving documents to a shared folder on a Synology NAS.  I can have our technologist provide some details on how we made that work, if it helps.  I DO know that we 

- Created a separate Paperless shared folder, and
- Created a local user "paperless" with full read/write permissions to the shared folder.
   _(no humans have direct access to the shared folder)_

Does your _paperless-user_ have full read/write permissions to your folders?

**Reply by Skhoooler** [reply]
I use an Asustor NAS. The NAS is mounted to my Linux server already, and I can read and write from it. And I added the NAS to the docker compose yml file the same way so it should have read and write permissions just like the Linux server. 

I wonder if docker changes the IP address it says it's from. In my NAS I only allowed server's IP to read from it.

**Reply by HiranChaudhuri** [reply]
- You could test that effect by temporarily removing the IP filter.
- Another way would be to find out the source IP for your connections, like described here:
https://unix.stackexchange.com/questions/634247/figure-out-client-ip-used
- And then you could on purpose use the wrong password and see how docker and paperless behave.

**Comment by Skhoooler** [comment]
I inspected the container like @stumpylog suggested, and it looks like it didn't use the correct source for the volume. Is there a setting that I may need to set in the docker-compose.env file maybe?
![image](https://github.com/user-attachments/assets/c41b3bbe-f794-41c5-a73e-b857e10b914b)

**Reply by Skhoooler** [reply]
I changed the the docker-compose.yml so that I avoid using the named volume, and the inspect shows the correct Source, but when I uploaded a document, I still don't see it in my NAS for some reason.

![image](https://github.com/user-attachments/assets/192bdb00-0603-4516-a87c-a105fbc52616)

**Comment by ProgTiger** [comment]
Hi, 
I'm also using my NAS as Doc-Storage. Here is my volumes config from docker-compose.yml. Don't forget "iocharset=utf8" costs me a lot of trouble ;-)

```
services:
  paperless:
    [...]
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
[...]

volumes:
  [...]
  data:   
  consume:
    # driver: local
    driver_opts:
      type: cifs 
      o: "username=<mySmbUser>,password=<mySecretPassword>,iocharset=utf8,uid=1000,gid=1000,vers=3.0"
      device: "//<myNasIP>/dms/consume"  
  export:
    # driver: local
    driver_opts:
      type: cifs 
      o: "username=<mySmbUser>,password=<mySecretPassword>,iocharset=utf8,uid=1000,gid=1000,vers=3.0"
      device: "//<myNasIP>/dms/export"
  media:
    # driver: local
    driver_opts:
      type: cifs 
      o: "username=<mySmbUser>,password=<mySecretPassword>,iocharset=utf8,uid=1000,gid=1000,vers=3.0"
      device: "//<myNasIP>/dms/media"
```
