### DISCUSSION TITLE
Change File Path for Documents

### DISCUSSION THREAD

**Discussion by KenjiUchiha** [paperless-ngx/paperless-ngx#8530] [Support]
Hey there!

I am trying to change the file path for Paperless Files. As it is, I have it set up for auto email uploads and it works perfectly. However, my new issue is getting it to change the path/folder where files are uploaded to.

For context, I am running paperless on Ubuntu 22.04. I have a wireless synology drive I want the files to upload to. I have been doing searches for being able to do this and I find the instructions a bit unclear or I run into odd issues. I can access the drive via the file folder but I have issues mounting the drive, stating the following "mount: /mnt/paperless_smb: mount(2) system call failed: No route to host."

I just feel I need to make sure I have my steps correct. Any advise is apprecated, Thanks

**Comment by stumpylog** [comment]
Assuming you are using Docker Compose, showing your relevant configuration would be helpful

**Reply by KenjiUchiha** [reply]
```yaml
services:
  broker:
    image: docker.io/library/redis:7
    restart: always
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 5

  db:
    image: docker.io/library/postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: ********
      POSTGRES_PASSWORD: ***********
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ****** -d paperless"]
      interval: 30s
      retries: 5


  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8080:8000"
    volumes:
      - data:/usr/src/paperless/data
      - /home/*****/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/*****/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: ********** 
      PAPERLESS_DBPASS: **********
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: always

      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: always

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

I've censored more private things
