### DISCUSSION TITLE
media folder - some folders are missing in archive

### DISCUSSION THREAD

**Discussion by Puffo19** [paperless-ngx/paperless-ngx#8567] [Support]
### Description

The folder structure of the media folder ist not equal. Some folders are missing and the files within. Folder pathes are used for the structure. 

In some rare cases, the "orginals" folder looks like expected, and the "archive" folder is not in sync. 

There are differences in the folder structure between:
```
/media/documents/archive/
/media/documents/originals/

```
I tried to change the date, the name, the storage path. Noting had an affect to the "archive" folder. If I change the names of the "synched" files, everything works as expected. 

### Steps to reproduce

can not reproduce. 

### Webserver logs

```bash
there are no logs related to the bug.
```

### Browser logs

```bash
not relevant
```

### Paperless-ngx version

 2.13.5

### Host OS

OpenMediaFault x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.5",
    "server_os": "Linux-6.1.0-28-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 3936687546368,
        "available": 1883806875648
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0028_alter_mailaccount_password_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-12-29T23:40:52.488977+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-12-29T22:05:24.314940Z",
        "classifier_error": null
    }
}
```

### Browser

Chroma

### Configuration changes

```
version: "3.6"
services:
  broker:
    image: redis:6.2
    restart: always
    volumes:
      - /srv/<custom>/paperedis:/data

  db:
    image: postgres:14
    restart: always
    volumes:
      - /srv/<custom>/paperdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: <pwd<

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - 8777:8000
    volumes:
      - /srv/<custom>/paperlessngx/data:/usr/src/paperless/data
      - /srv/<custom>/paperlessngx/media:/usr/src/paperless/media
      - /srv/<custom>/paperlessngx/export:/usr/src/paperless/export
      - /srv/<custom>/paperlessngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: <pwd>
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
