### DISCUSSION TITLE
Media on NFS

### DISCUSSION THREAD

**Discussion by tyler5136** [paperless-ngx/paperless-ngx#8640] [Support]
Before I get started I'm sure that the issues I'm having are a side effect of me being new to the software.  As the configuration I'm trying to make happen is not what you would call normal. I don't think these are actual issues so much as I'm misconfiguring something vague.

I spun up paperless-ngx in a container using compose. The system is working great. I've done a few things with it that I would have thought needed more moving parts. 

I am having a couple hiccups though with storage. I've already got other systems using an existing NFS share we'll call this 'media'. And I've got users scanning files directly into a 'ScanIn' folder. Ideally the ScanIn folder would function as the consumption folder. I found some documentation about workarounds with NFS consumption and will give that a go after my container is done with it's current workload. The primary issue I'm having though is media storage. Ideally all the media will be stored in the NFS share. However as of now the media directory is bound to the default. I'm hesitant to change this mount since I dont know what relationships exist int he pgsql db that may be pointing to where the originals/archives live. I've consumed a few thousand documents and I dont relish the idea of having to redo that workload. I'd like to migrate the existing media to the root of the NFS share 'media'. I've set up the storage paths following the advanced documentation. This is working great following my existing schema with the exception that it's storing them in the 'media' >> originals >> (storage path)

Below is my existing compose file. If someone could give me some guidance on how to migrate the existing data to the share without breaking the system or redoing the workloads I'd be extremely grateful. I also plan on moving the pg db to my existing cluster at some point. 

```
services:
  broker:
    container_name: paperless-redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
    networks:
      paperless:
  db:
    container_name: paperless-pg
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      paperless:

  webserver:
    container_name: paperless-app
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    networks:
      frontend:
      paperless:
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    volumes:
      #- ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - imp-share:/Imp
      - imp-share:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      - scanin-share:/ScanIn
      #- scanin-share:/usr/src/paperless/consume
      - ./scripts:/usr/src/paperless/scripts
    labels:
      <traefik labels>
    env_file: ./.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_CONSUME_DIR: /usr/src/paperless/consume/consume
      #PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless/scripts/example.sh
      PAPERLESS_FILENAME_FORMAT: "{{ correspondent }}/{{ title }}/{{ created_year }}"
      PAPERLESS_AUTO_CONSUME_INTERVAL: 60
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "Authentik",
                "client_id": <redact>,
                "secret": <redact>,
                "settings": {
                  "server_url": "https://<url>/application/o/paperless/.well-known/openid-configuration"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
  gotenberg:
    container_name: paperless-gotenberg
    image: docker.io/gotenberg/gotenberg:latest
    restart: unless-stopped
    networks:
      paperless:
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    container_name: paperless-tika
    image: docker.io/apache/tika:latest
    networks:
      paperless:
    restart: unless-stopped

networks:
  frontend:
    external: true
  paperless:

volumes:
  scanin-share:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<ip>,rw
      device: ":/volume1/ScanIn"
  imp-share:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<ip>,rw
      device: ":/volume1/Imp"
```
