### DISCUSSION TITLE
New paperless-ngx image gives fatal error

### DISCUSSION THREAD

**Discussion by nlgunther** [paperless-ngx/paperless-ngx#8648] [Support] [answered]
When I started my paperless-ngx container today, the container failed and I started getting this error:

PostgreSQL Database directory appears to contain a database; Skipping initialization
2025-01-07 13:40:18 db-1         | 
2025-01-07 13:40:18 db-1         | 2025-01-07 21:40:18.682 UTC [1] FATAL:  database files are incompatible with server
2025-01-07 13:40:18 db-1         | 2025-01-07 21:40:18.682 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 15.10 (Debian 15.10-1.pgdg120+1).
2025-01-07 13:41:10 db-1         | 
2025-01-07 13:41:10 db-1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
2025-01-07 13:41:10 db-1         | 
2025-01-07 13:41:10 db-1         | 2025-01-07 21:41:10.184 UTC [1] FATAL:  database files are incompatible with server
2025-01-07 13:41:10 db-1         | 2025-01-07 21:41:10.184 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 15.10 (Debian 15.10-1.pgdg120+1).

It seems a new image is based on PostgresSQL version 16, while my existing data is contained in PostgresSQL version 15.  Is there anything I can do to get my paperless-ngx back?
Thank you!

**Comment by stumpylog** [comment, marked as answer]
You can change back to the Postgres v15 image tag.  Don't use latest or leave the tag off for a database.

**Reply by nlgunther** [reply]
That is super helpful and very prompt.  How do I do that now that I have pulled the latest paperless-ngx image?
Sorry to be so ignorant!  I love paperless-ngx and am recommending it to all an sundry, but I'm a newbie on docker.

**Reply by stumpylog** [reply]
I don't fully understand the question.  The paperless image version and the database image version are independent.  If you have `:2.13`, that's the latest for now

**Reply by nlgunther** [reply]
I'm more ignorant that you expect.  Very sorry!  Could you write the docker command to "change back to the postrgres v15 image tag"?  I expect it's one line containing the world "pull".
Again, I'm very sorry for my ignorance on this matter.

**Reply by stumpylog** [reply]
Are you using Docker Compose?  If yes, post the file contents.  Or if using just `docker run`, that command

**Reply by nlgunther** [reply]
As requested:

docker-compose.env
====
```
PAPERLESS_URL=
Note
PAPERLESS_TIME_ZONE=America/Los_Angeles
PAPERLESS_OCR_LANGUAGE=eng
PAPERLESS_SECRET_KEY=*******
```

=======================

docker-compose.yml
```yaml
# Docker Compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

# version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/nlgunther/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:
```
