### DISCUSSION TITLE
Two Instances with docker - thumbnails created on both

### DISCUSSION THREAD

**Discussion by thomaswwp** [paperless-ngx/paperless-ngx#8777] [Support] [answered]
I thought I had this working but find that the thumbnails are cross-posting. I am running two instances: filing.mydomain.com and paperless.mydomain.com with caddy reverse proxy to ports 8010 and 8011. The main documents are fine, but the thumbnails cross post to both servers, so I certainly have something wrong in my system.

My setup is a second database ("filing"), two webserver in my yaml and separate redis with /0 and /1 on the end for different databases.

I am clearly not understanding something fundamental, because any thumbnail is being created on both servers. I can recreate them using `document_thumbnails --document {doc_number}` but I have to choose which one to keep!

I will lay off adding to the second instance and hope someone can put me right.

My files:
### docker-compose.yaml
```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8010:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379/0
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  webserver-fil:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8011:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export-filing:/usr/src/paperless/export
      - ./consume-filing:/usr/src/paperless/consume
    env_file: docker-compose-fil.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379/1
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

### docker-compose.env
```
PAPERLESS_URL=https://paperless.mydomain.com
PAPERLESS_TIMEZONE=Europe/London
PAPERLESS_SECRET_KEY=blah
PAPERLESS_REVERSE_PROXY_AUTH=true
PAPERLESS_DEBUG=false
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".deleted", ".DS_Store", ".DS_STORE", "._", ".stfolder/", ".stversions/", ".localized/", "desktop.ini", "@eaDir/*", "Thumbs.db"]
PAPERLESS_DBNAME=paperless
```

## docker-compose-fil.env
```
PAPERLESS_URL=https://filing.mydomain.com
PAPERLESS_TIMEZONE=Europe/London
PAPERLESS_SECRET_KEY=blahblah
PAPERLESS_REVERSE_PROXY_AUTH=true
PAPERLESS_DEBUG=false
#PAPERLESS_CONSUMER_RECURSIVE=true
#PAPERLESS_CONSUMER_IGNORE_PATTERNS=\.deleted
PAPERLESS_DBNAME=filing
```
