### DISCUSSION TITLE
Is it possible to make OpenID users superuser if they are in a group?

### DISCUSSION THREAD

**Discussion by silmarine** [paperless-ngx/paperless-ngx#8931] [Support] [answered]
I just set up paperless-ngx with authelia for openid. I disabled the default login from the start as well. It seems to create my user and everything but I keep getting this error:
```
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":403,"statusText":"OK","url":"https://paperless-ngx.example.com/api/ui_settings/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://paperless-ngx.example.com/api/ui_settings/: 403 OK","error":{"detail":"You do not have permission to perform this action."}}
```
When searching around for this I kept seeing people needing to log into their admin/superuser account. Can I set up paperless-ngx where it make a user a superuser if they are in the "admin" group in authelia? I can't seem to find any documentation for this.

**Comment by silmarine** [comment]
Forgot to add my config.
Authelia client:
```
    - client_id: 'paperless-ngx'
      client_name: 'Paperless-ngx'
      client_secret: 'secret'
      public: false
      authorization_policy: 'admin_policy'
      consent_mode: 'implicit'
      scopes:
        - 'openid'
        - 'groups'
        - 'email'
        - 'profile'
      require_pkce: true
      pkce_challenge_method: 'S256'
      redirect_uris:
        - 'https://paperless-ngx.example.com/accounts/oidc/authelia/login/callback/'
      userinfo_signed_response_alg: 'none'
      token_endpoint_auth_method: 'client_secret_basic'
```
Paperless-ngx openid variables:
```
      - PAPERLESS_DISABLE_REGULAR_LOGIN=True
      - PAPERLESS_REDIRECT_LOGIN_TO_SSO=True
      - 'PAPERLESS_SOCIALACCOUNT_PROVIDERS={"openid_connect": {"SCOPE": ["openid", "profile", "email", "groups"],"OAUTH_PKCE_ENABLED": true,"APPS": [{"provider_id": "authelia","name": "Authelia","client_id": "paperless-ngx","secret": "secret","settings": { "server_url": "https://auth.example.com", "token_auth_method": "client_secret_basic"}}]}}'
      - PAPERLESS_SOCIAL_AUTO_SIGNUP=true
      - LOGOUT_REDIRECT_URL=https://auth.example.com/logout
      - PAPERLESS_APPS=allauth.socialaccount.providers.openid_connect
