### DISCUSSION TITLE
New deployment via portainer, all containers up & running but webserver seems stuck in a loop

### DISCUSSION THREAD

**Discussion by nzbtuxnews** [paperless-ngx/paperless-ngx#8954] [Support] [answered]
New deployment via portainer, all containers up & running but webserver seems stuck in a loop.

PGSQL server has an account and DB already created but there's no tables in it.

webserver container says "Connected to PostgreSQL" but I doubt it since I dont see connections in the DB server...

WebUI errors out with "Unable to connect" (basically a 404)

```
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 1004:1004
Creating directory scratch directory /tmp/paperless
mkdir: created directory '/tmp/paperless'
Adjusting permissions of paperless files. This may take a while.
changed ownership of '/usr/src/paperless/export' from paperless:1000 to paperless:paperless
changed ownership of '/usr/src/paperless/data' from paperless:1000 to paperless:paperless
changed ownership of '/usr/src/paperless/data/index' from paperless:1000 to paperless:paperless
changed ownership of '/usr/src/paperless/data/migration_lock' from paperless:1000 to paperless:paperless
changed ownership of '/usr/src/paperless/media' from paperless:1000 to paperless:paperless
changed ownership of '/usr/src/paperless/media/documents' from paperless:1000 to paperless:paperless
changed ownership of '/usr/src/paperless/media/documents/thumbnails' from paperless:1000 to paperless:paperless
changed ownership of '/usr/src/paperless/media/documents/originals' from paperless:1000 to paperless:paperless
changed ownership of '/usr/src/paperless/consume' from paperless:1000 to paperless:paperless
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Connected to Redis broker.
flock: 200: No locks available
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Connected to Redis broker.
flock: 200: No locks available
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Connected to Redis broker.
flock: 200: No locks available
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Connected to Redis broker.
flock: 200: No locks available
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Connected to PostgreSQL
Waiting for Redis...
Connected to Redis broker.
```
broker logs:
```
1:C 29 Jan 2025 22:37:26.715 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 29 Jan 2025 22:37:26.715 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 29 Jan 2025 22:37:26.715 * Redis version=7.4.2, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 29 Jan 2025 22:37:26.715 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 29 Jan 2025 22:37:26.716 * monotonic clock: POSIX clock_gettime
1:M 29 Jan 2025 22:37:26.717 * Running mode=standalone, port=6379.
1:M 29 Jan 2025 22:37:26.717 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 29 Jan 2025 22:37:26.718 * Server initialized
1:M 29 Jan 2025 22:37:26.745 * Loading RDB produced by version 7.4.2
1:M 29 Jan 2025 22:37:26.745 * RDB age 3972 seconds
1:M 29 Jan 2025 22:37:26.745 * RDB memory usage when created 0.95 Mb
1:M 29 Jan 2025 22:37:26.745 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 29 Jan 2025 22:37:26.745 * DB loaded from disk: 0.028 seconds
1:M 29 Jan 2025 22:37:26.745 * Ready to accept connections tcp
```

Gotenberg logs
```
  _____     __           __               
 / ___/__  / /____ ___  / /  ___ _______ _
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / 
                                   /___/
A Docker-powered stateless API for PDF files.
Version: 8.7.0
-------------------------------------------------------
[SYSTEM] modules: api chromium exiftool libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] chromium: Chromium ready to start
[SYSTEM] libreoffice-api: LibreOffice ready to start
[SYSTEM] prometheus: collecting metrics
[SYSTEM] pdfengines: exiftool libreoffice-pdfengine pdfcpu pdftk qpdf
[SYSTEM] api: server listening on port 3000
```

tika logs:
```
INFO  [main] 22:37:31,130 org.apache.tika.server.core.TikaServerProcess Starting Apache Tika 3.0.0 server
INFO  [main] 22:37:33,510 org.apache.tika.server.core.TikaServerProcess loading resource from SPI: class org.apache.tika.server.standard.resource.XMPMetadataResource
Jan 29, 2025 10:37:34 PM org.apache.cxf.endpoint.ServerImpl initDestination
INFO: Setting the server's publish address to be http://0.0.0.0:9998/
INFO  [main] 22:37:34,321 org.eclipse.jetty.server.Server jetty-11.0.24; built: 2024-08-26T18:11:22.448Z; git: 5dfc59a691b748796f922208956bd1f2794bcd16; jvm 21.0.4+7-Ubuntu-1ubuntu224.04
INFO  [main] 22:37:34,457 org.eclipse.jetty.server.AbstractConnector Started ServerConnector@6831d8fd{HTTP/1.1, (http/1.1)}{0.0.0.0:9998}
INFO  [main] 22:37:34,462 org.eclipse.jetty.server.Server Started Server@5b69fd74{STARTING}[11.0.24,sto=0] @4903ms
INFO  [main] 22:37:34,572 org.eclipse.jetty.server.handler.ContextHandler Started o.a.c.t.h.JettyContextHandler@1d269ed7{/,null,AVAILABLE}
INFO  [main] 22:37:34,604 org.apache.tika.server.core.TikaServerProcess Started Apache Tika server 63da0510-8d87-4a90-993a-d9277a9840c9 at http://0.0.0.0:9998/
```

Docker compose

```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8088:8000"
    volumes:
      - /mnt/data/paperless-ngx/data:/usr/src/paperless/data
      - /mnt/data/paperless-ngx/media:/usr/src/paperless/media
      - /mnt/data/paperless-ngx/export:/usr/src/paperless/export
      - /mnt/data/paperless-ngx/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: dbserver
      PAPERLESS_DBUSER: paperless-ngx
      PAPERLESS_DBPASS: *****************
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      USERMAP_UID: 1004
      USERMAP_GID: 1004
      PAPERLESS_TIME_ZONE: America/Toronto
      PAPERLESS_OCR_LANGUAGE: eng

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  redisdata:
```

Docker version 26.1.3, build b72abbb
Rocky Linux 8
Portainer 2.21.5
