### DISCUSSION TITLE
How to change gotenberg's default port number

### DISCUSSION THREAD

**Discussion by ghost** [paperless-ngx/paperless-ngx#917] [Support] [answered]
Dear all,

because of a port number conflict with other services I'd like to change the ports that paperless-ngx & co. is using. For `paperless-ngx` itself, that's (described and) easily done inside the `docker-compose.yml` file. However, for `gotenberg` it seems that I cannot accomplish this.

I tried:
```
...
services:

...

 gotenberg:
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--api-port=30300"
...
```
but gotenberg stubbornly stays with 3000, however that's what I deduce from the output of `docker container ls --no-trunc` in the `PORTS` column. I have no idea whether this is a meanigful approach whatsoever.

Any help is greatly appreciated.

Thanks a lot in advance!

**Comment by Profex** [comment, marked as answer]
Your compose sysntax should be ok, it's inline with the [gotenberg documentation](https://gotenberg.dev/docs/modules/api) for this
Just tested it with my gotenberg installation and I could successfully change the API port using this syntax

>   gotenberg:
>       image: gotenberg/gotenberg:7
>       restart: unless-stopped
>       command:
>         - "gotenberg"
>         - "--api-port=30300"   

I get the follow log output after starting the container (log output retrieved using command `docker logs containername`)

> [SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook
> [SYSTEM] gc: application started
> **[SYSTEM] api: server listening on port 30300**
> [SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
> [SYSTEM] prometheus: collecting metrics
> [SYSTEM] uno: long-running LibreOffice listener ready to start

Do you maybe also have this in your compose file?

>       ports:
>         - 3000:3000  

After changing the API port you maybe want to change this to below, to expose the new API port 30300 to the outside using the same port number

>       ports:
>         - 30300:30300

**Reply by ghost** [reply]
yes, thank you. I can confirm this. To be clear and as there are other place where port numbers go in let me put my complete `docker-compose.yml` here for further confirmation:

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    # image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 18001:8000
      - 30300:30300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18001"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mypath/data:/usr/src/paperless/data
      - /mypath/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mypath/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:30300
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--api-port=30300"

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
```
however, a `docker container ls` still lists port 3000 for gotenberg.
