### DISCUSSION TITLE
How to setup a second paperless docker instance on one machine?

### DISCUSSION THREAD

**Discussion by bread-on-toast** [paperless-ngx/paperless-ngx#9265] [Support]
Hi all,
I am using paperless now for a while for my personal documents and now would like to have a clean seperation from my business documents. For that I think the cleanest solution would be a seperate instance but I do not know how to do this alongside the existing one. can someone give me advice?

**Comment by stumpylog** [comment]
With the little information here, no one can really say..  Have you tried anything?  How are you installing?  The easiest way would be just another Compose file

**Comment by wduda** [comment]
You want to make sure that you have all components of paperless present a second time and the two sets of components isolated from each other. That means making a copy of your compose file (assuming you used that, changing container names, ports and netwroking settings so they do not try and talk to each other, change the mounted volumes so they do not clash and so on. Then you can run both setups in parallel using the two compose files.

**Reply by HiranChaudhuri** [reply]
I would separate out the components that need to be duplicated and keep the others.

Components that carry state and thus need to be duplicated:
- filesystem to host files
- Redis as it hosts the queue
- (Postgres|MariaDB) database to host the metadata about documents
- the webserver (paperless instance) so it connects to the duplicated documents

Components to be kept the same (they are stateless webservices for parsing/rendering the documents)
- Tika
- Gotenberg

**Reply by wduda** [reply]
While this is a good approach to save ressources, it requires more knowledge and sophistication in maintaining the setup. Either through a more complex Compose file, or running a separate stack for Tika and Gotenberg. 

So multiple things can be true at the same time:
- the setup is good because it saves on compute resources
- the setup is also a bit trickier to maintain for a less experienced user

I would have someone start with a full copy and then learn to optimize. Hard for me to see where an optimization of one less tika an one less gotenberg instance makes or breaks the cost and availability in a home user environment.

**Reply by nklamann** [reply]
> * Redis as it hosts the queue

How exactly can redis be duplicated, given that both docker instances share the same external network for connection to the proxy.

I tried:
```
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
    ports:
      - "46379:6379"
```
and 

```
  webserver:
...
    environment:
      PAPERLESS_REDIS: redis://broker:46379
```

but got at startup:
```
loc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
broker-1     | 1:C 13 Mar 2025 09:04:17.320 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
broker-1     | 1:C 13 Mar 2025 09:04:17.320 * Redis version=7.4.2, bits=64, commit=00000000, modified=0, pid=1, just started
broker-1     | 1:C 13 Mar 2025 09:04:17.320 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
broker-1     | 1:M 13 Mar 2025 09:04:17.321 * monotonic clock: POSIX clock_gettime
broker-1     | 1:M 13 Mar 2025 09:04:17.322 * Running mode=standalone, port=6379.

....

webserver-1  | Waiting for Redis...
webserver-1  | Redis ping #0 failed.
webserver-1  | Error: Error 111 connecting to broker:46379. Connection refused..
webserver-1  | Waiting 5s
```

**Reply by wduda** [reply]
> > * Redis as it hosts the queue
> 
> How exactly can redis be duplicated, given that both docker instances share the same external network for connection to the proxy.
> 
Something seems off with that setup. Either you have the same network and then a broker1 and broker2 which are really distinct instances which are being talked to separately on the same network, or you make a copy of the whole stack including a copy of the network and then you have two networks with distinct names and tenants which never intersect.

So on the same network something like this just for two brokers:
```
brokerA:
    container_name: paperless-redis-a
    image: docker.io/library/redis:7
    networks:
      - paperless-net
    volumes:
      - /paperless-docs/redis-a:/redis
    restart: unless-stopped
brokerB:
    container_name: paperless-redis-b
    image: docker.io/library/redis:7
    networks:
      - paperless-net
    volumes:
      - /paperless-docs/redis-b:/redis
    restart: unless-stopped
```

then you need two copies of paperless, two copies of db, and copy A of paperless depends on copy A of redis and copy A of DB and so on, and `PAPERLESS_REDIS: redis://brokerA:6379` for the first and `PAPERLESS_REDIS: redis://brokerB:6379` for the second.
