### DISCUSSION TITLE
Forbidden (403) CSRF verification failed

### DISCUSSION THREAD

**Discussion by smooth-baking-powder** [paperless-ngx/paperless-ngx#9301] [Support] [answered]
Hey,

i need help, cause i didnt find a solution for this Issue i have: https://github.com/paperless-ngx/paperless-ngx/issues/670

Its the same like in the Bug Report
![2025-03-05_10-06](https://github.com/user-attachments/assets/60a64962-1fa0-4df2-b387-c20cdccd2c8a)

I tried all Solutions in the Issue, nothing did it.

I use Paperless in a Ansible Playbook, the problem also exist with docker-compose test after reboot paperless container or Reverse proxy.

I hope anybody can help me here.

Thanks in forward

Playbook part with the containers:
```
    - name: Deploy the updated Paperless Broker
      community.docker.docker_container:
        name: paperless_broker
        image: docker.io/library/redis:7
        state: started
        restart_policy: always
        volumes:
          - paperless_redisdata:/data
        networks:
          - name: "{{ docker_network }}"

    - name: Deploy the updated Paperless DB
      community.docker.docker_container:
        name: paperless_db
        image: docker.io/library/postgres:16
        state: started
        restart_policy: always
        volumes:
          - paperless_dbdata:/var/lib/postgresql/data
        env:
          POSTGRES_DB: paperless_db
          POSTGRES_USER: paperless
          POSTGRES_PASSWORD: "{{ paperless_password }}"
        networks:
          - name: "{{ docker_network }}"

    - name: Pause for 10 seconds to let Redis fully start
      pause:
        seconds: 10

    - name: Deploy the updated Paperless Webserver
      community.docker.docker_container:
        name: paperless_webserver
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        state: started
        restart_policy: always
        ports:
          - "12001:8000"
        volumes:
          - paperless_data:/usr/src/paperless/data
          - paperless_media:/usr/src/paperless/media
          - "{{ export_dir }}:/usr/src/paperless/export"
          - "{{ consume_dir }}:/usr/src/paperless/consume"
        env:
          PAPERLESS_REDIS: redis://paperless_broker:6379
          PAPERLESS_URL: https://paperless.domain.tld
          PAPERLESS_TRUSTED_PROXIES: 10.0.0.31
          PAPERLESS_DBHOST: paperless_db
          PAPERLESS_DBNAME: paperless_db
          PAPERLESS_DBUSER: paperless # only needed if non-default username
          PAPERLESS_DBPASS: "{{ paperless_password }}" # only needed if non-default password
          CSRF_TRUSTED_ORIGINS: 'https://paperless.domain.tld'
          PAPERLESS_CORS_ALLOWED_HOSTS: 'https://paperless.domain.tld'
          PAPERLESS_ALLOWED_HOSTS: 'https://paperless.domain.tld,10.0.0.31,localhost'
          PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperless.domain.tld
        networks:
          - name: "{{ docker_network }}"
```

Caddy Reverse Proxy:
```
# Paperless
paperless.domain.tld {
    # Reverse Proxy zu der IP-Adresse und Port
    reverse_proxy 10.0.0.36:12001 {
    	header_up Host {host}
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
	}
    
    # CSRF Trusted Origins setzen
    @csrf {
        method POST
        path /api/
    }
    header @csrf Access-Control-Allow-Origin https://paperless.domain.tld
    
    # Let's Encrypt Zertifikat (automatisch)
    tls admin@domain.tld

    # Optional: Logging
    log {
        output file /var/log/caddy/access.log
        format json
    }
}
```

**Comment by shamoon** [comment]
> reboot paperless container

Just to clarify if you mean restart or re-create (e.g.` compose down` then `up`). The difference being that restarting does not change environment variables, recreating does, thats a docker thing. Also I would take out all of the settings besides the PAPERLESS_URL to see, and I dont use caddy but your settings look quite suspicious compared to the example in the wiki: https://github.com/paperless-ngx/paperless-ngx/wiki/Using-a-Reverse-Proxy-with-Paperless-ngx#caddy

**Reply by smooth-baking-powder** [reply]
I mean re-create. My Ansible Playbook check for a new update of the image and if its happen, it pull the image and updates the container.
That also happen with my Reverse proxy automatically in a specific time in the night.
After this (daily or weekly doesnt matter) i get the error. 

The Caddy Settings i tested from the issue and other issues or threads about paperless-ng. 
I now got the settings of your link. Tomorrow i can tell, if its work with only PAPERLESS_URL

Thanks

**Reply by smooth-baking-powder** [reply]
Today.
The changes didnt help :/
![2025-03-06_20-34](https://github.com/user-attachments/assets/1d302e7e-3b2b-4aef-b195-a2b4fe2d0e87)

**Reply by shamoon** [reply]
You should use process of elimination. My next guess would be your caddy configuration as I mentioned. Since this isnt an issue that others are experiencing you need to figure out which piece of your setup is to blame

**Reply by smooth-baking-powder** [reply]
> You should use process of elimination. My next guess would be your caddy configuration as I mentioned. Since this isnt an issue that others are experiencing you need to figure out which piece of your setup is to blame

i already disabled caddy update over night. Its Paperless after re-create container the Error comes.
I now disabled also paperless update and tomorrow morning i will check logs with manual update.

**Reply by smooth-baking-powder** [reply]
okay without any re-creat i have this error after some hours....

Log of Paperless Webserver:
[2025-03-14 06:24:45,471] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://paperless.domain.tld does not match any trusted origins.): /accounts/login/
[2025-03-14 06:24:57,729] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://paperless.domain.tld does not match any trusted origins.): /accounts/login/

**Reply by smooth-baking-powder** [reply]
So, with this errors out of the logs i was looking for solutions and found this for the webserver-container.
```
          CSRF_TRUSTED_ORIGINS: 'https://paperless.domain.tld/'
          ALLOWED_HOSTS: 'paperless.domain.tld'
```

But this didnt help. 
Again the Error.

Its frustrating.

**Comment by HiranChaudhuri** [comment]
That error is quite generic. Not per se, but the way Django uses it.
It could even mean you are posting to the wrong URL on the api. I went through a number of such constellations when developing my own client and was searching for issues in the server configuration. If you are using a reliable client (e.g. the paperless UI) that can be ruled out though.

**Reply by smooth-baking-powder** [reply]
i still have no idea to solve this problem. i tried all i found with AI, documentations, environments and so on. every day i have this error again and i dont know why.

**Comment by smooth-baking-powder** [comment]
Hey, could it be, that the problem may is a missing settings.py?

I was looking for the settings.py, but i dont have one in /usr/src/paperless or other places.
I only have some environments in my compose, but maybe this could be a problem?

**Reply by shamoon** [reply]
Even if youre running a 'bare metal' installation, you should not need to edit the source files, I assure you it is there if you are using docker (which I think you are, ultimately). 

So, what is the output if you shell into the docker container and run `printenv` (or do that via docker exec)?

**Reply by smooth-baking-powder** [reply]
> So, what is the output if you shell into the docker container and run `printenv` (or do that via docker exec)?

the correct Adresses. I masked the domain with domain.tld, but there are all correct.

```
root@6b01c342e935:/usr/src/paperless/src# printenv
PYTHONUNBUFFERED=1
PAPERLESS_REDIS=redis://paperless_broker:6379
HOSTNAME=6b01c342e935
PYTHON_VERSION=3.11.10
PAPERLESS_CSRF_TRUSTED_ORIGINS=https://paperless.domain.tld
ALLOWED_HOSTS=paperless.domain.tld
PWD=/usr/src/paperless/src
PAPERLESS_DBPASS=***masked***
PAPERLESS_DBUSER=paperless
HOME=/root
LANG=C.UTF-8
GPG_KEY=***masked***
PAPERLESS_DBNAME=paperless_db
CSRF_TRUSTED_ORIGINS=https://paperless.domain.tld
TERM=xterm-256color
PAPERLESS_ALLOWED_HOSTS=paperless.domain.tld,10.0.0.31,localhost,127.0.0.1
SHLVL=1
PYTHONDONTWRITEBYTECODE=1
LC_ALL=C.UTF-8
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PAPERLESS_URL=https://paperless.domain.tld
PNGX_CONTAINERIZED=1
PYTHONWARNINGS=ignore:::django.http.response:517
PAPERLESS_DBHOST=paperless_db
_=/usr/bin/printenv
root@6b01c342e935:/usr/src/paperless/src# 
```

**Reply by UlrichThiess** [reply]
It should be ```PAPERLESS_CSRF_TRUSTED_ORIGINS``` 

And please set ```PAPERLESS_DEBUG=true``` and restart.

Then you would see wich domain you set to ```PAPERLESS_CSRF_TRUSTED_ORIGINS```

```domain.tld``` ist not correct

**Reply by smooth-baking-powder** [reply]
> It should be `PAPERLESS_CSRF_TRUSTED_ORIGINS`
> 
> And please set `PAPERLESS_DEBUG=true` and restart.
> 
> Then you would see wich domain you set to `PAPERLESS_CSRF_TRUSTED_ORIGINS`
> 
> `domain.tld` ist not correct

i wrote i masked the toplevel domain part with domain.tld. the addresses was before all correct.
in the past i got many ddos attacks some minutes after posting domain address, so i try to mask it.

**Comment by UlrichThiess** [comment]
Did you try to set ```PAPERLESS_DEBUG=true``` in ```paperless.conf``` or ```PAPERLESS_DEBUG: 'true'``` in the ```docker-compose.yml``` in the enviroment section?

**Reply by smooth-baking-powder** [reply]
I did,

now the message is bigger:

``` 
Verboten (403)
CSRF-Verifizierung fehlgeschlagen. Anfrage abgebrochen.

Help
Reason given for failure:

    CSRF token missing.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when [Django’s CSRF mechanism](https://docs.djangoproject.com/en/4.2/ref/csrf/) has not been used correctly. For POST forms, you need to ensure:

Your browser is accepting cookies.
The view function passes a request to the template’s [render](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render) method.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.
You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.
``` 

In Webserver log is not more than before:
```
Forbidden (CSRF token missing.): /accounts/login/
[2025-04-10 14:36:33,627] [WARNING] [django.security.csrf] Forbidden (CSRF token missing.): /accounts/login/
Forbidden (CSRF token missing.): /accounts/login/
[2025-04-10 14:37:21,636] [WARNING] [django.security.csrf] Forbidden (CSRF token missing.): /accounts/login/
Forbidden (CSRF token missing.): /accounts/login/
[2025-04-10 14:37:23,628] [WARNING] [django.security.csrf] Forbidden (CSRF token missing.): /accounts/login/
```

**Reply by UlrichThiess** [reply]
If i set ```PAPERLESS_DEBUG=true``` i see the domainname. You see ```CSRF token missing```
maybe there's something wrong with you caddy conf-file?
i could not find anything except you should write ```/api/*```

**Reply by UlrichThiess** [reply]
Could you try nginx?

**Reply by smooth-baking-powder** [reply]
> Could you try nginx?

i already did, same problem

**Reply by smooth-baking-powder** [reply]
> If i set `PAPERLESS_DEBUG=true` i see the domainname. You see `CSRF token missing` maybe there's something wrong with you caddy conf-file? i could not find anything except you should write `/api/*`

Caddy config is very simple (i masked the domain for security reasons. its accessable from outside)
```
paperless.domain.tld {
    # Reverse Proxy zu der IP-Adresse und Port
    reverse_proxy 10.0.0.36:12001
    
    # Let's Encrypt Zertifikat (automatisch)
    tls admin@domain.tld

    # Optional: Logging
    log {
        output file /var/log/caddy/access.log
        format json
    }
}
```

**Reply by UlrichThiess** [reply]
Here is a part of my PowerShell-Skript to install Paperless-ngx on a Windows-Server. That's why there are some PS-Variables and some `
Don't use paste and copy only. Maybe that gives you a hint?

#### ```docker-compose.yml```
```
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "$($nginxHttpPortLocal):$($nginxHttpPortGlobal)"
      - "$($nginxHttpsPortLocal):$($nginxHttpsPortGlobal)"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - paperless
```

#### ```conf.d/paperless.conf```
```
server {
    listen 80;
    server_name _;

    access_log off;
    error_log /var/log/nginx/error.log;

    return 301 https://`$host`$request_uri;
}

server {
    listen 443 ssl;
    server_name $($paperlessUrl);

    access_log off;
    error_log /var/log/nginx/error.log;

    ssl_certificate /etc/nginx/certs/$($paperlessUrl).crt.pem;
    ssl_certificate_key /etc/nginx/certs/$($paperlessUrl).key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    gzip off;

    location / {
        proxy_pass http://paperless:8000;
        proxy_set_header Host `$host;
        proxy_set_header X-Real-IP `$remote_addr;
        proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|svg)$ {
        expires 7d;
        gzip on;
        gzip_types text/css application/javascript image/svg+xml;
        gzip_min_length 256;
    }
}

server {
    listen 443 ssl;
    server_name $($pgAdminUrl);

    access_log off;
    error_log /var/log/nginx/error.log;

    ssl_certificate /etc/nginx/certs/$($pgAdminUrl).crt.pem;
    ssl_certificate_key /etc/nginx/certs/$($pgAdminUrl).key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    gzip off;

    location / {
        proxy_pass http://pgadmin:80;
        proxy_set_header Host `$host;
        proxy_set_header X-Real-IP `$remote_addr;
        proxy_set_header X-Forwarded-For `$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff|woff2|ttf|svg)$ {
        expires 7d;
        gzip on;
        gzip_types text/css application/javascript image/svg+xml;
        gzip_min_length 256;
    }
}
```
