### DISCUSSION TITLE
Files in consume directory not consumed

### DISCUSSION THREAD

**Discussion by SteveDevDev** [paperless-ngx/paperless-ngx#9318] [Support] [answered]
I've had this issues since paperless-ng and it still persists with paperless-ngx.  I'm using the latest 2.14.7.  When I drop files in the directory, they don't get consumed automatically.  However if I restart the paperless containers then they get consumed on startup.  Here is my docker compose file.

```
services:
  broker:
    container_name: paperless-ng-redis
    image: redis:6.0
    restart: unless-stopped

  db:
    container_name: paperless-ng-db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: xxxxxxxx

  webserver:
    container_name: paperless-ng-webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8088:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/media/paperless-ng/data:/usr/src/paperless/data
      - /mnt/media/paperless-ng/media:/usr/src/paperless/media
      - /mnt/backup/paperless-ng/export:/usr/src/paperless/export
      - /mnt/media/paperless-ng/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
```
