### DISCUSSION TITLE
adding custom parser

### DISCUSSION THREAD

**Discussion by waselias** [paperless-ngx/paperless-ngx#9385] [Support]
Hey Guys,

since a few days i'm trying to add a custom parser to my paperless in docker compose. I have a parser-file (py), a init-file (also py) to announce the parser. Both are in a mounted custom_parser - Directory. But everytime i try to import a .notebook-file, wich is the parser for, i get the following error in the logs: 

> [WARNING] [django.request] Bad Request: /api/documents/post_document/

Here ist my Yaml-Configuration:
```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8010:8000"
    volumes:
      - /volume1/docker/paperless-ngx2/data:/usr/src/paperless/data
      - /volume1/docker/paperless-ngx2/media:/usr/src/paperless/media
      - /volume1/docker/paperless-ngx2/export:/usr/src/paperless/export
      - /volume1/docker/paperless-ngx2/consume:/usr/src/paperless/consume
      - /volume1/docker/paperless-ngx2/custom_parsers:/usr/src/paperless/custom_parsers  # Custom Parser Mount
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_SECRET_KEY: geheim
      PAPERLESS_ADMIN_USER: XXX
      PAPERLESS_ADMIN_PASSWORD: XXX
      PAPERLESS_OCR_LANGUAGE: eng + deu
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CUSTOM_PARSERS: /usr/src/paperless/custom_parsers  # Hier wird das Custom Parser Verzeichnis angegeben

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  data: 
  media: 
  pgdata: 
  redisdata: 

```
Here my custom parser:
```
import os
import zipfile
import xml.etree.ElementTree as ET
from paperless.parsers import DocumentParser, ParseError
from PIL import Image

class NotebookParser(DocumentParser):
    """Custom Parser für .notebook-Dateien in Paperless-NGX"""

    SUPPORTED_MIME_TYPES = ["application/x-notebook", "application/zip"]
    SUPPORTED_FILE_EXTENSIONS = [".notebook"]

    def parse(self, document_path):
        """Extrahiert den Text aus der .notebook-Datei"""
        extracted_dir = self.extract_zip(document_path)
        if not extracted_dir:
            raise ParseError(f" Konnte .notebook-Datei {document_path} nicht entpacken")

        text_content = self.extract_text_from_svg(extracted_dir)
        metadata = self.extract_metadata(extracted_dir)

        return {"text": text_content, "date": metadata.get("created_date")}

    def get_thumbnail(self, document_path):
        """Erstellt eine Vorschau aus preview.png"""
        extracted_dir = self.extract_zip(document_path)
        preview_path = os.path.join(extracted_dir, "preview.png")

        if os.path.exists(preview_path):
            thumb_dest = os.path.join(self.create_tempdir(), "thumb.webp")
            with Image.open(preview_path) as img:
                img.thumbnail((300, 300))
                img.save(thumb_dest, "WEBP")
            return thumb_dest
        else:
            raise ParseError("Keine Vorschau gefunden.")

    def extract_zip(self, file_path):
        """Entpackt die .notebook ZIP-Datei in ein temporäres Verzeichnis"""
        temp_dir = self.create_tempdir()

        if not zipfile.is_zipfile(file_path):
            raise ParseError(f" {file_path} ist keine gültige ZIP-Datei")

        try:
            with zipfile.ZipFile(file_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)
        except zipfile.BadZipFile:
            raise ParseError(f" Konnte ZIP-Datei {file_path} nicht entpacken")

        return temp_dir

    def extract_text_from_svg(self, extracted_dir):
        """Liest den Text aus SVG-Dateien"""
        text_content = []
        for file in sorted(os.listdir(extracted_dir)):
            if file.endswith(".svg"):
                svg_path = os.path.join(extracted_dir, file)
                text = self.extract_text_from_svg_file(svg_path)
                if text:
                    text_content.append(text)

        return "\n".join(text_content)

    def extract_text_from_svg_file(self, svg_path):
        """Extrahiert Text aus einer SVG-Datei"""
        try:
            # SVG-Namespace definieren
            NS = {"svg": "http://www.w3.org/2000/svg"}
            ET.register_namespace("", NS["svg"])

            tree = ET.parse(svg_path)
            root = tree.getroot()

            # Suche nach allen <text>-Elementen innerhalb des SVG-Namespace
            text_elements = [elem.text for elem in root.findall(".//svg:text", NS) if elem.text]

            return " ".join(text_elements) if text_elements else ""
        except Exception as e:
            return f"[ Fehler beim Verarbeiten von {svg_path}: {e}]"

    def extract_metadata(self, extracted_dir):
        """Liest Metadaten aus metadata.xml und imsmanifest.xml"""
        metadata_info = {}

        metadata_path = os.path.join(extracted_dir, "metadata.xml")
        manifest_path = os.path.join(extracted_dir, "imsmanifest.xml")

        if os.path.exists(metadata_path):
            metadata_info.update(self.parse_xml(metadata_path))

        if os.path.exists(manifest_path):
            metadata_info.update(self.parse_xml(manifest_path))

        return metadata_info

    def parse_xml(self, xml_path):
        """Parst eine XML-Datei und extrahiert relevante Informationen"""
        try:
            tree = ET.parse(xml_path)
            root = tree.getroot()
            data = {child.tag: child.text for child in root}
            return data
        except Exception as e:
            return {f" Fehler in {xml_path}": str(e)}

```

And My announcement:
```
from django.dispatch import receiver
from paperless.signals import document_consumer_declaration
from .notebook_parser import NotebookParser

logger = logging.getLogger(__name__)
logger.info("Notebook Parser wird registriert...")

@receiver(document_consumer_declaration)
def notebook_parser_declaration(sender, **kwargs):
    return {
        "parser": NotebookParser,
        "weight": 100,
        "mime_types": {
            "application/x-notebook": ".notebook",
            "application/zip": ".notebook"  # Fügt Unterstützung für ZIP hinzu!
        },
    }
```
Did i miss something?
