### DISCUSSION TITLE
django.db.utils.operationalerror: connection failed:  fatal: password authentication failed for user paperless

### DISCUSSION THREAD

**Discussion by alero63** [paperless-ngx/paperless-ngx#9419] [Support]
HI, i try to install paperless ngx. The installation runs with error code 0. After starting the services Paperless-ngx. starts and stop all the time.
Protocol of paperless-ngx: django.db.utils.operationalerror: connection failed: connection to server at 172.20.0.5 , port 5432 failed: fatal: password authentication failed for user paperless.

My Docker-compose.env:

````
USERMAP_UID=1026
USERMAP_GID=100
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_SECRET_KEY=geheim-2025
PAPERLESS_ADMIN_USER: admin
PAPERLESS_ADMIN_PASSWORD: admin
````

My docker-compse.yml:

````
services:
  broker:
    image: redis:7
    container_name: paperless-ngx-redis
    restart: unless-stopped
    volumes:
      - /volume2/docker/paperless-ngx/redis:/data

  db:
    image: postgres
    container_name: paperless-ngx-db:16
    restart: unless-stopped
    volumes:
    - /volume2/docker/paperless-ngx/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
    - db
    - broker
    - gotenberg
    - tika
    ports:
      - "8090:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8090"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume2/docker/paperless-ngx/data:/usr/src/paperless/data
      - /volume2/docker/paperless-ngx/media:/usr/src/paperless/media
      - /volume2/docker/paperless-ngx/export:/usr/src/paperless/export
      - /volume2/docker/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    container_name: paperless-ngx-gotenberg
    restart: unless-stopped

     # The gotenberg chromium route is used to convert .eml files. We do not
     # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    container_name: paperless-ngx-tika
    restart: unless-stopped 
````

it looks like paperless db dont know the user paperless. How can i change it?what is wrong?
I also found a post with nearly the same Error, but i dont know what to do.
