### DISCUSSION TITLE
On Editing view, create an custom field, add this and fill it, on save an Errormessage with

### DISCUSSION THREAD

**Discussion by svalcken** [paperless-ngx/paperless-ngx#9505] [Support] [answered]
### Description

In the view edit, create an custom field, add this field, fill it and try to save,
an Error appears: This field may not be null.

Copy from Errormessage Dialog:
Error Message (German, "This field may not be null."):
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://paperless:8001/api/documents/6/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://paperless:8001/api/documents/6/: 400 Bad Request","error":{"custom_fields":[{"field":["Dieses Feld darf nicht null sein."]},{}]}}

### Steps to reproduce

1. Go in the edit view
2. create an custom field. I have used an textfield.
3. Add this field.
4. Insert any value in this field
5. try to save.
6. Errormessage appears: This field may not be null. / German: Diese Feld darf nicht leer sein.

### Webserver logs

```bash
Don't know where the log.
```

### Browser logs

```bash

```

### Paperless-ngx version

2.14.7

### Host OS

In Docker: Debian GNU/Linux 12 (bookworm) x86_64, Host from Docker: Ubuntu 24.04.2 LTS x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.14.7",
    "server_os": "Linux-6.8.8-4-pve-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 26241896448,
        "available": 24663322624
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0001_initial_squashed_0009_mailrule_assign_tags",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2025-03-27T00:57:24.277689+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2025-03-27T08:05:00.167690Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome 134.0.6998.166

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Ah my bad, I see the part about creating the field on the document page and that does seem to do it. Apologies, this is reproducible. I’ll sort it out.

**Comment by shamoon** [comment]
Well now Im a bit confused, I cant actually reproduce this in our `beta`, can you?


https://github.com/user-attachments/assets/1abf0c38-eb2d-42be-b24f-30a1796622f6

**Reply by svalcken** [reply]
Sorry. i have seen a this moment.
The way is the same.

i can reproduce always in the 2.14.7. The current Beta are 2.15, if a see it right. This version have i not installed.
i must show in my docker, how can i install the 2.15.

My Environment ist installed as Docker with an script for everything. One difference is the current language. I try with english and show if the Error disappears.
But i have change to English and the same Error comes up.

I also an difference seen to your video. The Custom field will not add automatical after creation.

**Reply by shamoon** [reply]
Hmm, I cannot think of any reason why the language would make a difference, and indeed even when testing a different language I cannot reproduce this in our `beta` version. Note that the beta is not installed by the script, if thats what you are using, thats why I was asking specifically about the beta version which we will be releasing in the next week or two (if you do want to test it you can change the docker image to `ghcr.io/paperless-ngx/paperless-ngx:beta`, you might want to test separate from your real data, just in case)

Perhaps if you are still seeing this you can provide a video or more information? Maybe there is a set of requirements needed to reproduce that I cannot find.

Another video (again, from our beta version):


https://github.com/user-attachments/assets/0123dcde-9bfe-4a38-b8c7-2c27a527ad0b

**Reply by svalcken** [reply]
Language ist not the Problem.
The same issue on 2.15. (Beta).

i use the image from ghcr.io/paperless-ngx/paperless-ngx:beta in docker-compose. bevor was :latest (2.14.7).

Addtional Service Redis:7, postgres:16, gotenberg:8.8, tika:latest.
must i change any images also?

In your video, i see, the custom field will directy added after creation.
In my installation is this not, possible i must change an configuration entry to automatic adding the field?

**Reply by shamoon** [reply]
> In my installation is this not, possible i must change an configuration entry to automatic adding the field?

No, you shouldn't need to. Can you provide a screen cap video? Also can you check if there is anything in the browser console as well as checking the browser network tab?

**Reply by svalcken** [reply]
i am on working to create the video.
i have a short webm  video, but a little bit too big. (15MB). and allowed to upload are 10MB.
i try to compress and convert with ffmpeg. ist current not installeld on my macos.

**Comment by svalcken** [comment]
https://github.com/user-attachments/assets/56a0e7c3-a429-4f1c-bd8f-ba5718258764

**Reply by shamoon** [reply]
Ok thanks, yea I cant tell exactly what's happening. Is there anything in the browser console? (like an error?)

I do have one idea though Im not certain if it's the issue. If you would like to test this out a docker image is being built with the tag `fix-9505-maybe`, which should take a [few more minutes to complete](https://github.com/paperless-ngx/paperless-ngx/actions/runs/14223504129).

**Reply by svalcken** [reply]
Here are my Docker-Compsose (Only Credentials/Urls are cloaked)

```
services:
 broker:

   image: redis:7
   container_name: broker
   restart: unless-stopped
   volumes:
     - /drv/paperless/redis/_data:/data

 db:
   image: postgres:16
   container_name: db
   restart: unless-stopped
   volumes:
     - /drv/paperless/postgresql/_data:/var/lib/postgresql/data
   environment:
     POSTGRES_DB: <db>
     POSTGRES_USER: <dbuser>
     POSTGRES_PASSWORD: <dbpasswd>

 webserver:
   image: ghcr.io/paperless-ngx/paperless-ngx:beta
   container_name: webserver
   restart: unless-stopped
   depends_on:
     - db
     - broker
     - gotenberg
     - tika
   ports:
     - "8001:8000"
   volumes:
     - /drv/paperless/consume:/usr/src/paperless/consume
     - /drv/paperless/data:/usr/src/paperless/data
     - /drv/paperless/media:/usr/src/paperless/media
     - /drv/paperless/export:/usr/src/paperless/export
   environment:
     PAPERLESS_ADMIN_USER: <adminuser>
     PAPERLESS_ADMIN_PASSWORD: <adminpassword>
     PAPERLESS_REDIS: redis://broker:6379
     PAPERLESS_DBHOST: db
     PAPERLESS_TIKA_ENABLED: 1
     PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
     PAPERLESS_TIKA_ENDPOINT: http://tika:9998
     PAPERLESS_OCR_LANGUAGE: deu
     PAPERLESS_TIME_ZONE: Europe/Berlin
     PAPERLESS_CONSUMER_ENABLE_BARCODES: "true"
     PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: "true"
     PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING
     PAPERLESS_EMAIL_TASK_CRON: '*/10 * * * *'
     PAPERLESS_URL: https://<paperlessURL>:8088
     USERMAP_UID: "1002"
     USERMAP_GID: "1002"

 gotenberg:
   image: gotenberg/gotenberg:8.8
   restart: unless-stopped
   command:
     - "gotenberg"
     - "--chromium-disable-javascript=false"
     - "--chromium-allow-list=.*"

 tika:
   image: ghcr.io/paperless-ngx/tika:latest
   container_name: tika
   restart: unless-stopped
```
