### DISCUSSION TITLE
NGINX/Paperless - Forbidden (403) CSRF

### DISCUSSION THREAD

**Discussion by wesseli01** [paperless-ngx/paperless-ngx#9528] [Support]
### Description

PP Site (https://paperless2.XXXX.XXXX.de/accounts/login/?next=/ )

<img width="740" alt="image" src="https://github.com/user-attachments/assets/641ee1cb-8775-41b9-91e9-4435e269e1fa" />

Error:

<img width="578" alt="image" src="https://github.com/user-attachments/assets/25f76ab9-4917-49b7-b04e-f8a95255cb33" />

Check/Answer in Nginx Terminal (curl -L https://paperless2.XXXX.XXXX.de/)
<img width="984" alt="image" src="https://github.com/user-attachments/assets/313bebbe-6223-429e-abcd-02150e3355b2" />

npm connection:
<img width="786" alt="image" src="https://github.com/user-attachments/assets/7a1fbb16-56ff-4ef1-9f9e-caa522e37c83" />

### Steps to reproduce

I used the docker compose installation script (bash -c "$(curl --location --silent --show-error https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)") in two proxmos container (1x pp + 1x nginx). I checked the connection with curl -L https://paperless.doxxxxx.xxxx.de or curl -L http://PP-IP:8000 in ngix terminal container. Redirection to pp container works fine. I received the  pp site information in ngix terminal. I entered the access data on pp site (accessing the website via npm) but I get the 403 error. I didn't get the pp access. The user rights were given. It is the bug? The PAPERLESS_URL=paperless.doxxxxx.xxxx.de was/were set in compose env file  or yml (PAPERLESS_URL: https://paperless.doxxxxx.xxxx.de) file or both. 

### Webserver logs

```bash
dito
```

### Browser logs

```bash

```

### Paperless-ngx version

2.14.7

### Host OS

Proxmox Debian 12

### Installation method

Docker - official image

### System status

```json

```

### Browser

Chrome

## docker-compose.env
```
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY='*aaI9O%A5p^[$3v5fnrSAao;0oSDeP`Evn89KwiVTl$A}h.OO.dio53F!C7NKfTI'
PAPERLESS_URL=https://paperless2.homenet1.ddnss.de
#PAPERLESS_CSRF_TRUSTED_ORIGINS=https://paperless2.XXXX.XXXXX.de
PAPERLESS_CONSUMER_POLLING=1
#PAPERLESS_DEBUG=true
PAPERLESS_USE_X_FORWARD_HOST=true
PAPERLESS_USE_X_FORWARD_PORT=true
PAPERLESS_PROXY_SSL_HEADER='["HTTP_X_FORWARDED_PROTO", "https"]'
```

## docker-compose.yml
```yaml
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - /paperlesshdd/paperless/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /paperlesshdd/paperless/data:/usr/src/paperless/data
      - /paperlesshdd/paperless/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /paperlesshdd/paperless/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
```

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
