### DISCUSSION TITLE
File not found during consumption

### DISCUSSION THREAD

**Discussion by thomwiggers** [paperless-ngx/paperless-ngx#9614] [Support] [answered]
### Description

When I upload a file, I get "File Not Found" errors 75% of the time — not every time. This seem to be happening since 2.15.0; updating to 2.15.1 does not seem to help.

### Steps to reproduce

1. Drag file on user interface OR put it into the consume folder
2. Most of the time, consumption will fail. 

### Webserver logs

```bash
[2025-04-10 17:05:56,742] [ERROR] [paperless.consumer] Cannot consume /tmp/paperless/tmpn_3ue08e/10 - Revisie svw_Heijmans 43 won Fase 2_aanleg Blok H + I.pdf: File not found.
[2025-04-10 17:05:56,742] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: filename.pdf: Cannot consume /tmp/paperless/tmpn_3ue08e/filename.pdf: File not found.
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/tasks.py", line 179, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/consumer.py", line 373, in run
    self.pre_check_file_exists()
  File "/usr/src/paperless/src/documents/consumer.py", line 163, in pre_check_file_exists
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 152, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: filename.pdf: Cannot consume /tmp/paperless/tmpn_3ue08e/filename.pdf: File not found.
```

### Browser logs

```bash

```

### Paperless-ngx version

1.15.1

### Host OS

Arch Linux, AMD64

### Installation method

Docker - official image

### System status

```json

```

### Browser

Safari

### Configuration changes

I tried setting `PAPERLESS_CONSUMER_INOTIFY_DELAY=5` but that seems to have no effect.

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Consumption is not just broken.  I have moved this to a discussion as such.

There are multiple knobs to tune the timing of consumption.  You will need to investigate and test what works for your system, scanner, network, etc.

**Reply by thomwiggers** [reply]
Everything has been working for months, yet this installation has stopped working.

**Comment by thomwiggers** [comment]
I agree that something fishy is going on — copying my exact configuration into a new folder, spinning up this separate installation, and just dumping on a bunch of files seems to be working. So something in the state of the old-continuously-updated paperless installation seems to have gotten corrupted.

**Comment by thomwiggers** [comment]
Okay I tracked this down to https://github.com/paperless-ngx/paperless-ngx/commit/9c68100dc0f5fd48d765a66214a8cf28386e4e58; which changes how the containers interact with `manage.py`. I am running an additional container that periodically runs `manage.py document_export` for a backup job, and this has started interacting with the webserver instance.

**Reply by thomwiggers** [reply]
May also be related to https://github.com/paperless-ngx/paperless-ngx/commit/880f08599ad7534fb99828bd0d695463fccb9810

**Reply by stumpylog** [reply]
You should run `document_exporter` not `python3 manage.py document_exporter` directly.

**Comment by thomwiggers** [comment, marked as answer]
To run a periodic export job in a docker container, I have the following additional container in my `docker-compose.yml`. Since the switch to `s6`, just overriding the `CMD` is no longer sufficient to make sure Paperless isn't actually started. So note the `empty:` container mounts over a few folders in `/etc/s6-overlay/rc.d` to make sure there are no competing webservers started: 

```yaml

  export_job:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    volumes:
      - ./paperless/data:/usr/src/paperless/data
      - ./paperless/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./empty:/etc/s6-overlay/s6-rc.d/user/contents.d:ro
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

    command: ["/bin/sh", "-c", "whoami; while true; do date; /usr/local/bin/document_exporter --verbosity 2 --no-progress-bar --passphrase secret --no-color --compare-checksums --delete ../export; echo -n done; date; sleep 600; done"]
```

`./empty` is simply an empty folder.

If anyone has a good suggestion to run the document exporter periodically *in a self-contained way* (ie. without relying on host `cron`), in a less hacky way, let me know.
