### DISCUSSION TITLE
Can't seem to use a Synology SMB share as the consume folder

### DISCUSSION THREAD

**Discussion by xbmcnut** [paperless-ngx/paperless-ngx#9787] [Support] [answered]
Hi. Loving pngx and have it working great using the following compose file on my RS820+. I have however tried to change the consume path to` /volume1/paperless/consume`, a shared folder I set up for my WF-3640 scanner to send to and when I do that, I get this error `?: PAPERLESS_CONSUMPTION_DIR is not writeable` 

The shared folder has permissions set to user 1026, the same user ID specified in the .env file. Everything is working swell except for that little glitch.

Anyone got any tips for me?

DSM 7.2.2-72806 Update 3
paperless-ngx version v2.15.3

```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./redis:/data
  db:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: xxxxxxx
      POSTGRES_PASSWORD: xxxxxxx
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8004:8000"
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume:rw
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.19
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
volumes:
  data:
  media:
  redis:
  db:
```

**Comment by xbmcnut** [comment]
I just found this read https://github.com/paperless-ngx/paperless-ngx/discussions/3669#discussioncomment-6271326 but there is no detail on step 5 and I'm at a loss as to why that would be needed when the permissions are set when you create the shared folder.

> I changed the read/write permissions and ownership for the shared folder paperlessConsume so it can be accessed and written to by the user paperless-ngx (via SSH)

**Comment by kernie** [comment]
I have entries like `user: 1026:100` in the supporting services and `USERMAP_UID` and `USERMAP_GID` set as env variables with paperless service:
```
services:
  redis:
    image: redis:7
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redispass
    container_name: PaperlessNGX-REDIS
    hostname: paper-redis
    read_only: true
    user: 1026:100
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/paperlessngx/redis:/data:rw
    environment:
      TZ: Europe/Berlin
    restart: on-failure:5
    .
    .
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: PaperlessNGX-GOTENBERG
    hostname: gotenberg
    user: 1026:100
    .
    .
  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: PaperlessNGX-TIKA
    hostname: tika
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    restart: on-failure:5
    .
    .
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: PaperlessNGX
    hostname: paperless-ngx
    environment:
      USERMAP_UID: 1026
      USERMAP_GID: 100
    .
    .
```
where 1026 is my userid and 100 my groupid. You have to check that the folder as write permissions for that user.

Maybe it helps?

**Reply by xbmcnut** [reply]
Thank you for the tip. I modified my environment for the paperlesss webserver below but sadly the container reboots after 30s again.
```
ports:
      - "8004:8000"
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /volume1/paperless/consume:/usr/src/paperless/consume:rw
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      USERMAP_UID: 1026
      USERMAP_GID: 100  
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.19
    restart: unless-stopped

```
Here is the log
```
2025/04/25 13:42:40 | stdout | Waiting for Redis...
-- | -- | --
2025/04/25 13:42:38 | stdout | [init-folders] Running with root privileges, adjusting directories and permissions
2025/04/25 13:42:38 | stdout | [init-user] No GID changes for paperless
2025/04/25 13:42:38 | stdout | [init-user] No UID changes for paperless
2025/04/25 13:42:38 | stdout | [init-redis-wait] Waiting for Redis to report ready
2025/04/25 13:42:38 | stdout | [init-db-wait] Waiting for PostgreSQL to start...
2025/04/25 13:42:38 | stdout | [init-db-wait] Waiting for postgresql to report ready
2025/04/25 13:42:38 | stdout | [init-tesseract-langs] No additional installs requested
2025/04/25 13:42:38 | stdout | [init-tesseract-langs] Checking if additional teseract languages needed
2025/04/25 13:42:38 | stdout | [env-init] No *_FILE environment found
2025/04/25 13:42:38 | stdout | [env-init] Checking for environment from files
2025/04/25 13:42:38 | stdout | [init-start]  paperless-ngx docker container starting init as root
2025/04/25 13:42:38 | stdout | [init-start] paperless-ngx docker container starting...
2025/04/25 13:42:34 | stderr | /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
2025/04/25 13:42:34 | stderr | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
2025/04/25 13:42:34 | stderr | s6-rc: warning: unable to start service init-system-checks: command exited 1
2025/04/25 13:42:33 | stderr | System check identified 1 issue (0 silenced).
2025/04/25 13:42:33 | stderr |  
2025/04/25 13:42:33 | stderr | to be writeable by the user running the Paperless services
2025/04/25 13:42:33 | stderr | d--------- paperless users /usr/src/paperless/consume
2025/04/25 13:42:33 | stderr | HINT: Set the permissions of
2025/04/25 13:42:33 | stderr | ?: PAPERLESS_CONSUMPTION_DIR is not writeable
2025/04/25 13:42:33 | stderr | ERRORS:
2025/04/25 13:42:33 | stderr |  
2025/04/25 13:42:33 | stderr | SystemCheckError: System check identified some issues:
2025/04/25 13:42:20 | stdout | [init-checks] Running Django checks
2025/04/25 13:42:20 | stdout | [init-superuser] Not creating superuser
2025/04/25 13:42:19 | stdout | No migrations to apply.
```
![image](https://github.com/user-attachments/assets/3a0a44f0-140d-4907-9712-65f4ff9c474f)
