### DISCUSSION TITLE
configuration for traefik reverse proxy // CSRF - Origin checking failed

### DISCUSSION THREAD

**Discussion by egabosh** [paperless-ngx/paperless-ngx#980] [Support] [answered]
Moin,

I'm trying to setup paperless-ngx behind a traefik reverse proxy.
Loginpage comes up but when I try to login I'm getting the following error:

```
Verboten (403)

CSRF-Verifizierung fehlgeschlagen. Anfrage abgebrochen.
Help

Reason given for failure:

    Origin checking failed - null does not match any trusted origins.
    

In general, this can occur when there is a genuine Cross Site Request Forgery, or when [Django’s CSRF mechanism](https://docs.djangoproject.com/en/4.0/ref/csrf/) has not been used correctly. For POST forms, you need to ensure:

    Your browser is accepting cookies.
    The view function passes a request to the template’s [render](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render) method.
    In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
    If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
    The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.

You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.
```
I set the PAPERLESS_URL to the URL I'm using via webbrowser:
PAPERLESS_URL=https://mydomain.org

Here my docker-compose.yml:
```
version: '3.6'
services:
  mydomain.org:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    depends_on:
      - mydomain.org--broker
    env_file: docker-compose.env
    environment:
      - PAPERLESS_REDIS=redis://mydomain.org--broker:6379
      - PAPERLESS_FILENAME_FORMAT={correspondent}/{created}-{title}
      - PAPERLESS_TASK_WORKERS=1
      - PAPERLESS_THREADS_PER_WORKER=1
      - PAPERLESS_OCR_MODE=skip_noarchive
      - PAPERLESS_WEBSERVER_WORKERS=1
      - PAPERLESS_OCR_LANGUAGE=deu
      - PAPERLESS_TIME_ZONE=Europe/Berlin
      - PAPERLESS_URL=https://mydomain.org
      - PAPERLESS_DEBUG=true
    networks:
      - mydomain.org--network
      - traefik
    labels:
      - traefik.enable=true
      # HTTPS
      - traefik.http.routers.paperless.rule=Host(`mydomain.org`)
      - traefik.http.routers.paperless.entrypoints=https
      - traefik.http.routers.paperless.tls=true
      # Proxy to service-port
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      - traefik.http.routers.paperless.service=paperless
      # cert via letsencrypt
      - traefik.http.routers.paperless.tls.certresolver=letsencrypt
      # Traefik network
      - traefik.docker.network=traefik
      # activate secHeaders@file
      - traefik.http.routers.paperless.middlewares=secHeaders@file
  
  mydomain.org--broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
    networks:
      - mydomain.org--network

networks:
  mydomain.org--network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-paperless
  traefik:
    external: true
```
Here my traefik-setup:
```
version: '3.6'
services:
  traefik:
    image: traefik:latest
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    command:
      # Try to enable this if something isn't working.
      # Chances are, Traefik will tell you why.
      # Be careful in production as it exposes the traffic you might not want to expose.
      - --log.level=INFO
      # http -> https redirect
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --entrypoints.https.address=:443
      # Docker
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      # Traefik
      - --api=true
      - --api.dashboard=true
      - --api.insecure=false
      # LetsEncrypt 
      # Staging Server - uncomment when testing
      #- --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.letsencrypt.acme.email=ssl@mydomain.org
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # non-docker services
      - --providers.file=true
      - --providers.file.directory=/etc/traefik/providers.local
      - --providers.file.watch=true
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      traefik:
        ipv4_address: XXX.XXX.XXX.XXX
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./providers:/etc/traefik/providers.local
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.mydomain.org`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.middlewares=secHeaders@file,auth
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.middlewares.to-https.redirectscheme.scheme=https
      # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
      - traefik.http.middlewares.auth.basicauth.users=admin:XXXXXXXXXXXXXXXXXXXXXXXXX
networks:
  traefik:
    external: true
```
```
---
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
http:
  middlewares:
    secHeaders:
      compress: false
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "no-referrer"
        # HSTS Configuration
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        hostsProxyHeaders: ["X-CSRFToken"]
```
Played and searched already around a but with "hostsProxyHeaders: ["X-CSRFToken"]" but didn't find a way to get it working.
Anyone an idea whats going wrong?

Regards,
olli
