### DISCUSSION TITLE
High RAM usage after processing/browsing files. (7GB after 1 file).

### DISCUSSION THREAD

**Discussion by diminDDL** [paperless-ngx/paperless-ngx#9914] [Support]
Today after a fresh restart of my server I uploaded a 20MB scanned document to my paperless-ngx instance running in a docker container. After it got processed and I opened it to check the OCR, assign tags and downloaded the pdf with the OCR. Then I closed the tab and forgot about it. Now several hours later the container still sits at ~7GB of RAM usage.
![image](https://github.com/user-attachments/assets/7f06bc77-ead3-47b8-9477-ff6daa363ef3)

In particular the granian process seems to be hogging up most of that memory:
![image](https://github.com/user-attachments/assets/3f7122e6-78c3-4e3b-b42a-ede2dd04d296)

Is this behavior expected? Can I limit the RAM to this container to prevent it from doing this? Are there any other ways to limit RAM usage to something reasonable?

My configurations:
`docker-compose.yml`
```yaml
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./paperless-data/redisdata:/data

  db:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    volumes:
      - ./paperless-data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8010:8000"
    volumes:
      - ./paperless-data/data:/usr/src/paperless/data
      - ./paperless-data/media:/usr/src/paperless/media
      - ./paperless-data/export:/usr/src/paperless/export
      - ./paperless-data/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.19
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
```

`docker-compose.env`

```
###############################################################################
# Paperless-ngx settings                                                      #
###############################################################################

# See http://docs.paperless-ngx.com/configuration/ for all available options.

# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
#USERMAP_UID=1000
#USERMAP_GID=1000

# See the documentation linked above for all options. A few commonly adjusted settings
# are provided below.

# This is required if you will be exposing Paperless-ngx on a public domain
# (if doing so please consider security measures such as reverse proxy)
#PAPERLESS_URL=https://paperless.example.com

# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
PAPERLESS_SECRET_KEY=<key>

# Use this variable to set a timezone for the Paperless Docker containers. Defaults to UTC.
PAPERLESS_TIME_ZONE=Europe/Warsaw

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=eng

# Additional languages to install for text recognition, separated by a whitespace.
# Note that this is different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines
# the language used for OCR.
# The container installs English, German, Italian, Spanish and French by default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
PAPERLESS_OCR_LANGUAGES=ukr pol deu
```

Note:
I've seen some other reports of "high" memory usage but in those cases it was either temporary or went down over time, I am fine with that. But in my case it stays at this level constantly unless I restart the container.

Thank you.

**Comment by shamoon** [comment]
You can limit docker memory with e.g.

```
services:
  webserver:
    deploy:
      resources:
        limits:
          memory: 2g
```

As you noted this is coming from granian, not a lot we can do here as granian is likely holding onto memory that other server setups (e.g., pre-fork workers in Gunicorn) might eventually release via worker recycling. Memory allocated by Python is not always returned to the OS, even if the objects are freed inside Python. This is standard CPython behavior, not specific to granian.
