### DISCUSSION TITLE
Change PAPERLESS_LOGGING_DIR for docker compose image

### DISCUSSION THREAD

**Discussion by datenmuell** [paperless-ngx/paperless-ngx#9918] [Support]
Hi there, 

#### issue
Changing the PAPERLESS_LOGGING_DIR is not working as expected for me.

- Added mount point in compose file
- Added PAPERLESS_LOGGING_DIR env_variable to point to that mount point
- Logs are still written to 'paperless/data/log'

#### Setup

I set up paperless with docker compose and portainer in a proxmox LXC container according to the installation guide and included some bind mounts

#### compose file

```
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: DB_User
      POSTGRES_PASSWORD: DB_Pass

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - /home/$USER/paperless/NAS/data:/usr/src/paperless/data
      - /home/$USER/paperless/NAS/media:/usr/src/paperless/media
      - /home/$USER/paperless/NAS/export:/usr/src/paperless/export
      - /home/$USER/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  pgdata:
  redisdata:
```
I am using these bind mounts to store the data on my NAS while keeping the consume-directory locally.

In general everything was running as expected, but then I discovered that writing the logs on "paperless/data/log" keeps my NAS-Disks spinning all the time, therefore I also tried moving the log-folder to a local directory and added the following mount (just below the line "- /home/$USER/paperless/consume:/usr/src/paperless/consume" )
```
- /home/$USER/paperless/logs:/usr/src/paperless/logs`
```

As I am using portainer I just added a environment variable according to the documentation:
```
PAPERLESS_LOGGING_DIR=/usr/src/paperless/logs/
```

But after restarting the logs are still written to 'paperless/data/log'

I also tried defining different directories in the environment variable "PAPERLESS_LOGGING_DIR" (e. g. only 'logs/' or 'paperless/logs'; all variants with or without starting with a slash) none of it changed the behaviour (and I also got no error messages I could find)

Actually I am not to deep into docker and therefore I am not sure if I am addressing the mounted directory correctly, or whether my mistake might be somewhere else. 

Hence any help would be highly appreciated (or any idea for what logfiles I should inspect)

P.S.:
Just as I am writing this it comes to my mind that I do not know whether I have to somehow create the mount point "/usr/src/paperless/logs" in advance (as I said I am little clueless with docker yet)

P.P.S:
The directory '/home/$USER/paperless/logs' exists and is writeable for $USER (and for testing purposes I made it writeable for everyone)
