### ISSUE TITLE
[BUG] Seeing granian exceptions after upgrading to 2.16.2

### ISSUE THREAD

**Issue by a2hill** [paperless-ngx/paperless-ngx#10097]
### Description

Just upgraded from 2.12.1 to 2.16.2 (running on docker) and started seeing the following exceptions in the logs on application startup. I can't actually determine what might be broken as a result, but figured I would report it here. 

### Steps to reproduce

docker compose up

### Webserver logs

```bash
[2025-06-01 10:02:36,593] [INFO] [_granian.asgi.serve] Started worker-1
[2025-06-01 10:02:36,594] [INFO] [_granian.asgi.serve] Started worker-1 runtime-1
[2025-06-01 10:03:09,345] [ERROR] [_granian.utils] Application callable raised an exception

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/granian/_futures.py", line 15, in future_watcher

    await inner(watcher.scope, watcher.proto)

  File "/usr/local/lib/python3.12/site-packages/channels/routing.py", line 48, in __call__

    return await application(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/channels/sessions.py", line 44, in __call__

    return await self.inner(dict(scope, cookies=cookies), receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/channels/sessions.py", line 261, in __call__

    return await self.inner(wrapper.scope, receive, wrapper.send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/channels/auth.py", line 185, in __call__

    return await super().__call__(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/channels/middleware.py", line 24, in __call__

    return await self.inner(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/channels/routing.py", line 136, in __call__

    raise ValueError("No route found for path %r." % path)

ValueError: No route found for path 'ws/status/'.
```

### Browser logs

```bash

```

### Paperless-ngx version

2.16.2

### Host OS

Ubuntu 24.04.2 LTS

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.16.2",
    "server_os": "Linux-6.8.0-56-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 490577010688,
        "available": 157639847936
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0029_mailrule_pdf_layout",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "celery_url": "celery@d1af1ce17beb",
        "celery_error": null,
        "index_status": "OK",
        "index_last_modified": "2025-06-01T09:41:51.693769-07:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2025-06-01T17:05:51.572304Z",
        "classifier_error": null,
        "sanity_check_status": "WARNING",
        "sanity_check_last_run": null,
        "sanity_check_error": "No sanity check tasks found"
    }
}
```

### Browser

Firefox

### Configuration changes

docker compose
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    networks:
      - proxy-network

  bridge:
    image: protonmail-bridge-docker_bridge:latest #    build: ./protonmail-bridge-docker/deb/
    restart: unless-stopped
    ports:
      - 1025:25
      - 1143:443
    volumes:
      - bridge:/root
    networks:
      - proxy-network

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
      - bridge
    networks:
      - proxy-network
    ports:
      - 8000:8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - bridge:/bridge:ro
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      - ./scripts:/usr/src/paperless/scripts
    env_file:
      - docker-compose.env
      - .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless/scripts/post-consume/post-consume.sh
      PAPERLESS_SCRIPT_ROOT: /usr/src/paperless/scripts
 extra_hosts:
      - host.docker.internal:host-gateway

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - proxy-network

  tika:
    image: apache/tika
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  # Allows nginx to call web-server
  proxy-network:
    external: true
    name: proxy-network

volumes:
  data:
  media:
  bridge:
```

docker compose env
```
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=America/Los_Angeles

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=eng

# Tells paperless to use unpaper to clean any input document before sending it to tesseract.
# This uses more resources, but generally results in better OCR results.
PAPERLESS_OCR_CLEAN=clean-final

# Paperless will try to determine the document creation date from its contents.
# Specify the date format Paperless should expect to see within your documents.
# This option defaults to DMY which translates to day first, month second, and
# year last order. Characters D, M, or Y can be shuffled to meet the required order.
PAPERLESS_DATE_ORDER=MDY

# Host paperless on a sub-path
PAPERLESS_FORCE_SCRIPT_NAME=/paperless
PAPERLESS_STATIC_URL=/paperless/static/
PAPERLESS_URL=https://paperless.apps.nitsua.org

# Barcode support
PAPERLESS_CONSUMER_ENABLE_BARCODES=true
PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT=true
PAPERLESS_CONSUMER_BARCODE_STRING="PATCHT"

# Processing
PAPERLESS_TASK_WORKERS=4
```

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
