### ISSUE TITLE
[BUG] Web Server not working with docker secrets and struggling to connect to redis container.

### ISSUE THREAD

**Issue by ArcherCentauri** [paperless-ngx/paperless-ngx#10128]
### Description

When using the following docker compose on the latest version of Paperless, the web server no longer starts.

```
services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.16.2
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "7777:8000"
    volumes:
      - /mnt/docker/swarm/paperless/export:/usr/src/paperless/export
      - /mnt/docker/swarm/paperless/data:/usr/src/paperless/data
      - /mnt/docker/swarm/paperless/media:/usr/src/paperless/media
      - /mnt/docker/swarm/paperless/consume:/usr/src/paperless/consume
    secrets:
      - pngx_db_user
      - pngx_db_pass
    environment:
      USERMAP_UID: 0
      USERMAP_GID: 0
      PAPERLESS_URL: https://paperless.example.com
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBUSER_FILE: /run/secrets/pngx_db_user
      PAPERLESS_DBPASS_FILE: /run/secrets/pngx_db_pass
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
    networks:
      - swarm-proxy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mariadb:10
    volumes:
      - /mnt/docker/swarm/paperless/mysql:/var/lib/mysql
    secrets:
      - pngx_db_user
      - pngx_db_pass
    environment:
      MARIADB_DATABASE: paperless
      MARIADB_USER_FILE: /run/secrets/pngx_db_user
      MARIADB_PASSWORD_FILE: /run/secrets/pngx_db_pass
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/pngx_db_pass
    networks:
      - swarm-proxy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  broker:
    image: redis:7
    volumes:
      - /mnt/docker/swarm/paperless/redis:/data
    networks:
      - swarm-proxy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  gotenberg:
    image: gotenberg/gotenberg:7.8
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - swarm-proxy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    networks:
      - swarm-proxy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  swarm-proxy:
    external: true

secrets:
  pngx_db_user:
    external: true
  pngx_db_pass:
    external: true
```
My first though based on the error log was that there was something wrong with the docker secrets and connecting to the redis container, even though they worked before I deleted them and recreated the docker secrets to be sure. Still the web server would not start. I also docker exec -it into the database container and confirmed the secrets were indeed correct. 

I have confirmed that the Redis container is part of the stage with the expected name.

When I remove the docker secrets and change back to just using the credentials in the compose file the container starts as expected and everything works.

### Steps to reproduce

1. Create bind mounts
2. Create docker secrets
3. Create compose file
4. Start docker stack

### Webserver logs

```bash
[init-start] paperless-ngx docker container starting...
[init-start]  paperless-ngx docker container starting init as root
[env-init] Checking for environment from files
[env-init] Your secret: PAPERLESS_DBPASS_FILE contains a trailing newline and may not work as expected
[env-init] PAPERLESS_DBPASS set from PAPERLESS_DBPASS_FILE
[env-init] Your secret: PAPERLESS_DBUSER_FILE contains a trailing newline and may not work as expected
[env-init] PAPERLESS_DBUSER set from PAPERLESS_DBUSER_FILE
[init-db-wait] Waiting for MariaDB to report ready
[init-db-wait] Waiting for MariaDB to start...
[init-redis-wait] Waiting for Redis to report ready
[init-tesseract-langs] Checking if additional teseract languages needed
[init-tesseract-langs] No additional installs requested
[init-user] Mapping UID for paperless to 0
Waiting for Redis...
[init-user] Mapping GID for paperless to 0
[init-folders] Running with root privileges, adjusting directories and permissions
mkdir: created directory '/tmp/paperless'
/etc/s6-overlay/s6-rc.d/init-wait-for-db/run: connect: Connection timed out
/etc/s6-overlay/s6-rc.d/init-wait-for-db/run: line 46: /dev/tcp/db/3306: Connection timed out
[init-db-wait] Attempt 1 failed! Trying again in 5 seconds...
Redis ping #0 failed.
Error: Timeout connecting to server.
Waiting 5s
```

### Browser logs

```bash

```

### Paperless-ngx version

2.16.2

### Host OS

Debian 12 (Via Docker)

### Installation method

Docker - official image

### System status

```json

```

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
