### ISSUE TITLE
[BUG] Docker container errors with PAPERLESS_CONSUMPTION_DIR is not writeable when using NFS

### ISSUE THREAD

**Issue by kfriede** [paperless-ngx/paperless-ngx#1109]
### Description

I'm using paperless-ngx with docker and a mounted NFS share via a docker bind mount. I had previously had this working with paperless-ng, and in the upgrade this has stopped working. 

Exact error received is listed in webserver logs.  

Steps attempted:
- Removing PUID/PGID. No success.
- Omitting "PAPERLESS_CONSUMPTION_DIR" and mounting NFS to /usr/src/paperless/consume.  No success
- Running `docker exec -it paperless chown -R $(id -u):$(id -g) /consume`. Command does not return error, but paperless won't start still.
- Running `docker exec -it paperless touch /consume/testfile`.  WORKS, file appears in NFS.

NFS has no user mapping applied. Files appear as 777 with user 1000:1000 when mounted via linux host.  

Docker compose file is:
```
version: "3.4"
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_CONSUMPTION_DIR=/consume
    volumes:
      - /home/docker/paperless/data/media:/usr/src/paperless/media
      - /home/docker/paperless/data:/usr/src/paperless/data
      - paperless-inbox:/consume
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - paperless
    command: tail -f /dev/null

  paperless-redis:
    image: redis:6.0
    container_name: paperless-redis
    hostname: broker
    restart: unless-stopped
    volumes:
      - /home/docker/paperless/redis:/data
    networks:
      - paperless

volumes:
  paperless-inbox:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.example.com,rw
      device: ":/volume1/DAV/"


networks:
  paperless:

```

### Steps to reproduce

Run compose file as listed

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis: redis://broker:6379
Connected to Redis broker: redis://broker:6379
Apply database migrations...
SystemCheckError: System check identified some issues:

ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is not writeable
	HINT: Set the permissions of
dr-xr-xr-x /consume
 to be writeable by the user running the Paperless services
```

### Paperless-ngx version

latest

### Host OS

Docker

### Installation method

Docker

### Configuration changes

SEE DESCRIPTION
