### ISSUE TITLE
[BUG] createsuperuser throws usermod error when USERMAP_UID is set

### ISSUE THREAD

**Issue by CharlesSchimmel** [paperless-ngx/paperless-ngx#1229]
### Description

I'm following the docker-compose instructions for the sqlite-tika configuration. On the host machine I've created a user `paperlessd` with a UID of 123. When I set `USERMAP_UID=123` in the `docker-compose.env` file and run `docker-compose run --rm webserver createsuperuser` docker creates tika, gotenberg, and redis successfully but halts while creating paperless-web with the output:

```
Mapping UID and GID for paperless:paperless to 123:123
usermod: Failed to change ownership of the home directory%
```

It succeeds if only `USERMAP_GID` is set and if both are unset. This only occurs while running the `createsuperuser` script although the same error message is output as a warning when starting paperless-web so it seems it can be worked around by commenting out `USERMAP_UID` before running the script.

### Steps to reproduce

1. set `USERMAP_UID` to the UID of a valid host user
2. run `docker-compose run --rm webserver createsuperuser`

### Paperless-ngx version

latest

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Configuration changes

USERMAP_UID=123

**Comment by qcasey** [comment]
Hmm, I can't replicate this. Do you mind posting your `docker-compose.yml`?

**Comment by CharlesSchimmel** [comment]
For sure, I've added it as a gist here: https://gist.github.com/CharlesSchimmel/bcf5dcb4c3d4b7b85668e31fda946532. The only things I've changed from `docker-compose.sqlite-tika.yml` is port, container names, and mounts.

**Comment by stumpylog** [comment]
I'm also not able to reproduce this.  I tried with all the combination of set/not set and never saw this.  Tried a few other system user IDs as well to no avail.

**Comment by Z0pyrus** [comment]
I have a similar Issue: I want to run paperless-ngx on my Raspberry Pi 4 (8gb), Ubuntu 22.04.01 LTS, Docker version 20.10.17, build 100c701 **Rootless**.

When I try to start it (also without createsuperuser first), I'll get:

```
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 1002:1002
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
```
yml file:
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    user: "1002"
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8100:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8100"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  redisdata:
```

Trying to run createsuperuser and normal run command without or with uid leads to this:
(In the yml file `user: "1002"` was removed, with this the error is the same as above)
The weird thing is, that after running it, the export dir was changed (owner...) to paperless (232073)
```
user@ubuntu:~/dockervolumes/paperless-ngx$ docker-compose run --rm webserver createsuperuser
Creating paperless_gotenberg_1 ... done
Creating paperless_tika_1      ... done
Creating paperless_broker_1    ... done
Creating paperless_webserver_run ... done
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 1000:1002
usermod: no changes
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis: redis://broker:6379
Connected to Redis broker: redis://broker:6379
Apply database migrations...
SystemCheckError: System check identified some issues:

ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is not writeable
	HINT: Set the permissions of 
drwxrwxr-x /usr/src/paperless/consume
 to be writeable by the user running the Paperless services
ERROR: 1
```
Quick fix: After running `chmod 777 consume/`, it works now.
