### ISSUE TITLE
[Other] Problem starting docker container

### ISSUE THREAD

**Issue by Tockra** [paperless-ngx/paperless-ngx#152]
Hi,

I am currently using following docker image: `jonaswinkler/paperless-ng:latest`
Now I wanted to replace it by an selfbuild image from this repo.
I changed my docker-compose.yaml to following:
```yaml
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    build: ./build
    restart: unless-stopped
    depends_on:
      - db
      - broker
    expose:
        - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db
      - VIRTUAL_HOST=mydomain
      - LETSENCRYPT_HOST=mydomain
      - LETSENCRYPT_EMAIL=mymail
      - VIRTUAL_PORT=8000
      - HTTPS_METHOD=redirect
    networks:
      - proxy-tier
      - default

networks:
    proxy-tier:
        external:
            name: proxy-tier
```

But after I started this setup, I get following message (with the docker hub image it runs):
Web-Browser:
![image](https://user-images.githubusercontent.com/1353859/155707181-e0d174d2-6941-4f87-9a9c-4cc518a9c4e4.png)

Console: 
```
webserver_1  | 12:22:56 [Q] INFO Q Cluster orange-massachusetts-foxtrot-william starting.
webserver_1  | 12:22:56 [Q] INFO Process-1:1 ready for work at 61
webserver_1  | 12:22:56 [Q] INFO Process-1:2 ready for work at 62
webserver_1  | 12:22:56 [Q] INFO Process-1:3 monitoring at 63
webserver_1  | 12:22:56 [Q] INFO Process-1 guarding cluster orange-massachusetts-foxtrot-william
webserver_1  | 12:22:56 [Q] INFO Process-1:4 pushing tasks at 64
webserver_1  | 12:22:56 [Q] INFO Q Cluster orange-massachusetts-foxtrot-william running.
webserver_1  | 2022-02-25 11:22:57,541 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | 2022-02-25 11:22:57,541 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | 2022-02-25 11:22:57,542 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

T
