### ISSUE TITLE
[Docker] Database gone 

### ISSUE THREAD

**Issue by henfri** [paperless-ngx/paperless-ngx#153]
Hello,

I re-created my setup, which uses the docker image, because of a filesystem corruption of the drive that contained my Images.
As on this drive I only have my docker images, I did not have a backup - and I think that was a right choice.
So, I created the image newly by running docker-compose up -d

But unfortunately, all documents are gone now. 
I think, this is due to:
```
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

```
So the database is stored only in a docker volume and not stored where I have my other docker-data stored.
Is this a wise choice?
Would it not be better to remark in the documentation, in addition to:
```
Replace the part BEFORE the colon with a local directory of your choice:

- /home/jonaswinkler/paperless-inbox:/usr/src/paperless/consume
```

To do the same for the database?

Any recommendations how to start over now?
Would I just move all files from paperless_ng_media\documents\archive to consume?

Best regards,
Hendrik

Best regards,
Hendrik

**Comment by qcasey** [comment]
Hello Hendrik,

I'm sorry about your recent data loss. That's always a headache.

> So the database is stored only in a docker volume and not stored where I have my other docker-data stored.

Yes, the database is a docker volume but the media files are as well. Where is your "other docker-data" stored?

```yaml
volumes:
  data:
  media:
  pgdata:
```

The consume/export directories are ephemeral. Paperless will only remove or add files (respectively) to those directories. They're only host mounts because FTP scanners and samba shares can't be mapped to a docker volume. 

>  Would it not be better to remark in the documentation ... To do the same for the database?

This is really a personal preference IMO. Some people really like all their data in docker volumes. I personally use host mounts for everything so I can backup `~/` and be done with it.

> Would I just move all files from paperless_ng_media\documents\archive to consume?

I hate to say it, but are you sure `paperless_ng_media\documents\archive` exists? If it was a docker volume and you lost your DB volume to corruption, I'd expect the media volume is also corrupted. Perhaps I do not understand your setup though.

If you can, back up whatever documents/volumes you can to another disk (corrupted or not). Then yes, moving documents to the `consume` directory would be an easy way to re-import.

-Quinn

**Comment by schnuffle** [comment]
The advantage of setting a simple docker volume as default is that it works without adoption.

I prefer having a contained env for a service, so my folder tree always looks like:
/docker/servicename/
Docker-compose.yml
./data
./data/firstcontainer
./data/secondcontainer


Though it might be a good idea to point out that storage/backup setup should be "ChangeMe"

**Comment by henfri** [comment]
Hello,

thanks for your reply.
Here my docker-compose.yml:
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: xxxxx

  webserver:
#    image: jonaswinkler/paperless-ng:latest
    image: ghcr.io/paperless-ngx/paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /srv/Daten/dockerconfig/paperless/data:/usr/src/paperless/data
      - /srv/DataPool/Paperless/paperless_ng_media:/usr/src/paperless/media
      - /srv/DataPool/Paperless/export:/usr/src/paperless/export
      - /srv/DataPool/Paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
```

As you can see:
```
      - /srv/Daten/dockerconfig/paperless/data:/usr/src/paperless/data
      - /srv/DataPool/Paperless/paperless_ng_media:/usr/src/paperless/media
      - /srv/DataPool/Paperless/export:/usr/src/paperless/export
      - /srv/DataPool/Paperless/consume:/usr/src/paperless/consume
```
I mount all relevant folders to the Host - and I thought that the database would be under `/srv/Daten/dockerconfig/paperless/data` - obviously only, as I did not pay enough attention.

@schnuffle Yes, but it is dangerous, as one can easily lose his database. 

Furthermore, I find it a bit inconsistent. Why is `/usr/src/paperless/data` not a volume, but mounted to the host - opposed to the database?

I suggest to make that consistent. And if keeping the database in a volume, I suggest to make it clear in the documentation, that it is important to backup that volume.

Best regards,
Hendrik

**Comment by qcasey** [comment]
I see. Thank you for the `docker-compose.yml` that is helpful. Luckily it looks like you still have your original documents.

> Furthermore, I find it a bit inconsistent. Why is /usr/src/paperless/data not a volume, but mounted to the host - opposed to the database?

I'm confused, `/usr/src/paperless/data` is a volume [by default](https://github.com/paperless-ngx/paperless-ngx/blob/630cdaf08f0adce283c364c9dc6f0035a63e7786/docker/compose/docker-compose.postgres-tika.yml#L65). I don't think it suggests changing that default anywhere in the documentation. Please correct me if I'm wrong, though.

Perhaps what added confusion was the [Configuration section](https://paperless-ngx.readthedocs.io/en/latest/configuration.html?highlight=%2Fusr%2Fsrc%2Fpaperless%2Fdata#paths-and-folders), which says

> ### PAPERLESS_DATA_DIR=<path>
> 
>     This is where paperless stores all its data (search index, SQLite database, classification model, etc).
> 
>     Defaults to “../data/”, relative to the “src” directory.

**all its data** is technically incorrect on postgres installs. Mentioning SQLite without commenting on `pgdata` is also misleading. We will fix that. 

After the 1.6.0 release we plan to review and update our documentation. I agree that the backup strategies should be clearer, emphasized as important, and featured in the install guides. Please let me know if you found anything else that can improved for future users.

Thanks,
Quinn

**Comment by qcasey** [comment]
Oh okay I get it now, the volume was changed during the `install-paperless-ng.sh` script... I'm not sure if that is ideal or not. Will review.

**Comment by henfri** [comment]
Yes, the install-script changes the `data`-folder, but not the `database ` folder.
Combined with

> This is where paperless stores all its data (search index, SQLite database, classification model, etc).

This is quite dangerous, as I had to find out.

I propose to change the docker-compose*yml and the install-script accordingly.

Best regards,
Hendrik

**Comment by qcasey** [comment]
> I propose to change the docker-compose*yml and the install-script accordingly.

I completely agree, thank you for bringing this up.

**Comment by schnuffle** [comment]
@[henfri](https://github.com/henfri)
Not in my setup as it will be stored under ./data/postgressql. I store everything in the data folder, paperless data and db data of course as well.

Regards

Schnuffle

**Comment by henfri** [comment]
Hello,
I suggest to change the docker-compose.yml like this:
https://github.com/paperless-ngx/paperless-ngx/compare/main...henfri:patch-1

People use this container on ther NAS or similar and have no clue how to backup the data/media/pgdata folders.

Greetings,
Hendrik

**Comment by qcasey** [comment]
Hello, thank you for the example compose file.

> People use this container on ther NAS or similar and have no clue how to backup the data/media/pgdata folders.

Our docs already address [how to backup data stored in docker volumes](https://paperless-ngx.readthedocs.io/en/latest/administration.html#making-backups). 

I still think this host mount vs docker volume debate is a personal preference. You and I both use host mounts because that's what we prefer to backup, but others would use docker volumes because it fits in their backup plan. If you're running everything on a single disk anyway (many people do, think Raspberry Pis), host mounts are just an unnecessary complication that causes permissions issues. This is why the docker volumes are our default in the compose files.

I do agree that the choice should be consistent, hence #173. But I don't think we should recommend host mounts by default.

**Comment by henfri** [comment]
In the end, I am an example who lost data due to the combination of this choice and me not reading to the guidance how to backup (hm... maybe I am a good example of the majority :-) )
It is clearly my fault, and I did not use the install-script (which you are fixing), but I think that this default is also encouraging this problem.
Ok for me, even if my choice would be different :-)

**Comment by qcasey** [comment]
>  It is clearly my fault, and I did not use the install-script (which you are fixing), but I think that this default is also encouraging this problem.

I see, I thought you used the script. I'm not trying to discredit your negative install experience at all here.

We intend to modify the docs for readability, and add emphasis on the difference between the `consume` mount and `data` volume. Another section can be added (and linked to) explaining why a user might prefer host mounts.

**Comment by qcasey** [comment]
By the way, I've nearly shot myself in the foot the exact same way with other programs, but what's saved me is actually removing the docker volumes by deleting that entire block

```yml
volumes:
  data:
  media:
  pgdata:
  redisdata:
```

After that, if I accidentally leave `pgdata:/var/lib/postgresql/data` in the file, `docker-compose` will refuse to start. Just a tip, apologies if you already know.
