### ISSUE TITLE
[BUG] Getting "ZoneInfo keys must be normalized relative paths" on files in consume folder

### ISSUE THREAD

**Issue by stefanrybacki** [paperless-ngx/paperless-ngx#1547]
### Description

I copied all my pdf documents to the docker-compose setup consume folder.
Paperless recognizes them but issues the following error over and over:

```
webserver_1  | 06:35:35 [Q] ERROR Failed [FOOBAR.pdf] - FOOBAR.pdf: The following error occurred while consuming FOOBAR.pdf: ZoneInfo keys must be normalized relative paths, got:  : Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 280, in main_wrap
webserver_1  |     raise exc_info[1]
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 351, in try_consume_file
webserver_1  |     document = self._store(text=text, date=date, mime_type=mime_type)
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 452, in _store
webserver_1  |     create_date = timezone.make_aware(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 272, in make_aware
webserver_1  |     timezone = get_current_timezone()
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 84, in get_current_timezone
webserver_1  |     return getattr(_active, "value", get_default_timezone())
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 70, in get_default_timezone
webserver_1  |     return zoneinfo.ZoneInfo(settings.TIME_ZONE)
webserver_1  |   File "/usr/local/lib/python3.9/zoneinfo/_tzpath.py", line 67, in find_tzfile
webserver_1  |     _validate_tzfile_path(key)
webserver_1  |   File "/usr/local/lib/python3.9/zoneinfo/_tzpath.py", line 91, in _validate_tzfile_path
webserver_1  |     raise ValueError(
webserver_1  | ValueError: ZoneInfo keys must be normalized relative paths, got:
webserver_1  |
webserver_1  | During handling of the above exception, another exception occurred:
webserver_1  |
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/docker/src/django-q/django_q/cluster.py", line 434, in worker
webserver_1  |     res = f(*task["args"], **task["kwargs"])
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 162, in consume_file
webserver_1  |     document = Consumer().try_consume_file(
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 413, in try_consume_file
webserver_1  |     self._fail(
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 84, in _fail
webserver_1  |     raise ConsumerError(f"{self.filename}: {log_message or message}")
webserver_1  | documents.consumer.ConsumerError: FOOBAR.pdf: The following error occurred while consuming FOOBAR.pdf: ZoneInfo keys must be normalized relative paths, got:
webserver_1  |
```

So documents show up on the progress page, but never in the documents section.
Any idea on how to fix this? Do I have wrong settings?

Docker compose file looks like this:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8888:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      USERMAP_UID: 1000
      USERMAP_GID: 1000

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
```

Thanks in advance.

### Steps to reproduce

1. start paperless ngx with docker-compose with default settings
2. copy pdf file to consume folder linked in docker-compose.yml
3. see error in log

### Webserver logs

```bash
webserver_1  | 06:35:35 [Q] ERROR Failed [FOOBAR.pdf] - FOOBAR.pdf: The following error occurred while consuming FOOBAR.pdf: ZoneInfo keys must be normalized relative paths, got:  : Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 280, in main_wrap
webserver_1  |     raise exc_info[1]
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 351, in try_consume_file
webserver_1  |     document = self._store(text=text, date=date, mime_type=mime_type)
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 452, in _store
webserver_1  |     create_date = timezone.make_aware(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 272, in make_aware
webserver_1  |     timezone = get_current_timezone()
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 84, in get_current_timezone
webserver_1  |     return getattr(_active, "value", get_default_timezone())
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/timezone.py", line 70, in get_default_timezone
webserver_1  |     return zoneinfo.ZoneInfo(settings.TIME_ZONE)
webserver_1  |   File "/usr/local/lib/python3.9/zoneinfo/_tzpath.py", line 67, in find_tzfile
webserver_1  |     _validate_tzfile_path(key)
webserver_1  |   File "/usr/local/lib/python3.9/zoneinfo/_tzpath.py", line 91, in _validate_tzfile_path
webserver_1  |     raise ValueError(
webserver_1  | ValueError: ZoneInfo keys must be normalized relative paths, got:
webserver_1  |
webserver_1  | During handling of the above exception, another exception occurred:
webserver_1  |
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/docker/src/django-q/django_q/cluster.py", line 434, in worker
webserver_1  |     res = f(*task["args"], **task["kwargs"])
webserver_1  |   File "/usr/src/paperless/src/documents/tasks.py", line 162, in consume_file
webserver_1  |     document = Consumer().try_consume_file(
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 413, in try_consume_file
webserver_1  |     self._fail(
webserver_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 84, in _fail
webserver_1  |     raise ConsumerError(f"{self.filename}: {log_message or message}")
webserver_1  | documents.consumer.ConsumerError: FOOBAR.pdf: The following error occurred while consuming FOOBAR.pdf: ZoneInfo keys must be normalized relative paths, got:
webserver_1  |
```

### Paperless-ngx version

1.8.0

### Host OS

Docker

### Installation method

Docker - official image

### Browser

Chrome
