### ISSUE TITLE
[BUG] MariaDB doesnt accept custom password

### ISSUE THREAD

**Issue by Sblop** [paperless-ngx/paperless-ngx#1660]
### Description

Problems using my own mariaDB server.

### Steps to reproduce

I have been trying all day to get mariaDB to connect. DB logs shows access denied. After checking the code I found: 
```
    DATABASES["default"] = {
        "HOST": os.getenv("PAPERLESS_DBHOST"),
        "NAME": os.getenv("PAPERLESS_DBNAME", "paperless"),
        "USER": os.getenv("PAPERLESS_DBUSER", "paperless"),
        "PASSWORD": os.getenv("PAPERLESS_DBPASS", "paperless"),
        "OPTIONS": {},
    }
```
My db host = mariadb, set in env. Works.
db name = paperless, same as my own, works.
db password = unique.... Didnt work.

From composer:
```
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: mariadb
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASSWORD: REDACTED
      PAPERLESS_DBPORT: 3306
```
I believe the code overwrites the unique  dbname, dbuser and dbpassword with paperless... Or am I wrong?

**Problem were solved by changing       PAPERLESS_DBPASSWORD to "paperless".** However I believe the code overwrites several env with paperless?

### Webserver logs

```bash
09/27/2022 12:37:22 PM
2022-09-27 12:37:22 3922 [Warning] Access denied for user 'paperless'@'192.168.18.25' (using password: YES)
09/27/2022 12:37:23 PM
2022-09-27 12:37:23 3923 [Warning] Access denied for user 'paperless'@'192.168.18.25' (using password: YES)
09/27/2022 1:43:58 PM
2022-09-27 13:43:58 4790 [Warning] Access denied for user 'paperless'@'192.168.18.11' (using password: YES)
09/27/2022 1:43:59 PM
2022-09-27 13:43:59 4791 [Warning] Access denied for user 'paperless'@'192.168.18.11' (using password: YES)
09/27/2022 1:44:12 PM
2022-09-27 13:44:12 4801 [Warning] Access denied for user 'paperless'@'192.168.18.11' (using password: YES)
09/27/2022 1:44:14 PM
2022-09-27 13:44:14 4802 [Warning] Access denied for user 'paperless'@'192.168.18.11' (using password: YES)
```

### Paperless-ngx version

1.9.1

### Host OS

docker

### Installation method

Docker - official image

### Browser

firefox

**Comment by stumpylog** [comment]
So `os.getenv` isn't going to overwrite anything, it just allows a default to be returned in the case of the environment not containing the specified key.

I was able to set a custom password with `MARIADB_PASSWORD: paperless-very-secure` set in the db container and `PAPERLESS_DBPASS: paperless-very-secure` on the webserver.

Did you ever start with a different password maybe?

**Comment by Venem** [comment]
You've correctly identified the code that deals with environment variables.

I think it's pretty clear what happened here:
`"PASSWORD": os.getenv("PAPERLESS_DBPASS", "paperless"),`
`PAPERLESS_DBPASSWORD: REDACTED`

Notice how paperless checks `PAPERLESS_DBPASS`, which you have not set.

**Comment by shamoon** [comment]
Thanks for pointing that out @Venem , it looks like the mariadb compose files include `PAPERLESS_DBPASSWORD`: https://github.com/paperless-ngx/paperless-ngx/blob/8feada6907a616c16956646810342dca11e18a02/docker/compose/docker-compose.mariadb.yml#L75 / https://github.com/paperless-ngx/paperless-ngx/blob/8feada6907a616c16956646810342dca11e18a02/docker/compose/docker-compose.mariadb-tika.yml#L81

so that may be the source of confusion. I think that should be changed, unless Im misunderstanding?

**Comment by stumpylog** [comment]
Ah, there's the issue.  `PAPERLESS_DBPASS` != `PAPERLESS_DBPASSWORD`.  I just changed my existing compose around, so had the correct naming.

**Comment by thebream** [comment]
FWIW, this thread helped me solve a similar problem with using a custom dbname.

I.e. I set MARIADB_DATABASE to "**paperlessprod**", and was getting following error:

> Error in log "Access denied for user 'paperless'@'%' to database '**paperless**'")"

To fix, I needed to add "**PAPERLESS_DBNAME: paperlessprod**" in webserver section.

**Comment by andreapx** [comment]
I have this problem too, but with the original docker-compose:
````
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-ngx-redis
    restart: unless-stopped
    volumes:
      - /var/docker/paperless-ngx/redisdata:/data
    networks:
      internal_bridge:
          ipv4_address: "172.20.0.63"

  db:
    image: docker.io/library/mariadb:10
    container_name: paperless-ngx-db
    restart: unless-stopped
    volumes:
      - /var/docker/paperless-ngx/dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
    networks:
      internal_bridge:
          ipv4_address: "172.20.0.62"

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx-app
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "127.0.0.1:8004:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /var/docker/paperless-ngx/data:/usr/src/paperless/data
      - /var/docker/paperless-ngx/media:/usr/src/paperless/media
      - /var/docker/paperless-ngx/export:/usr/src/paperless/export
      - /var/docker/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
    networks:
      internal_bridge:
          ipv4_address: "172.20.0.61"

networks:
  internal_bridge:
    external: true
````
The error is: `django.db.utils.OperationalError: (1045, "Access denied for user 'paperless'@'172.20.0.61' (using password: YES)")`
