### ISSUE TITLE
[BUG] Error during processing

### ISSUE THREAD

**Issue by jpoggi** [paperless-ngx/paperless-ngx#1697]
### Description

Hello,

I'm using Paperless-ngx with a docker compose stack with PostgreSQL 14.5 and Redis 7.0.5.

Everything is working fine, except with three particular PDF from Lego, like this one

https://www.lego.com/fr-fr/service/buildinginstructions/42103

Choose the 42103_X_Hot Rod.pdf one.

Here is the error:

```
paperless        | [2022-10-01 16:16:39,481] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
paperless        | 16:17:09 [Q] ERROR reincarnated worker Process-1:31 after death
paperless        | 2022-10-01 16:17:09,408 INFO reaped unknown pid 6219 (terminated by SIGPIPE)
paperless        | 2022-10-01 16:17:09,411 INFO reaped unknown pid 6220 (terminated by SIGPIPE)
paperless        | 16:17:09 [Q] INFO Process-1:32 ready for work at 6223
paperless        | 2022-10-01 16:17:10,414 INFO reaped unknown pid 6221 (terminated by SIGPIPE)
paperless        | 2022-10-01 16:17:10,414 INFO reaped unknown pid 6222 (exit status 0)
paperless        | 16:22:59 [Q] INFO Enqueued 1
paperless        | 16:22:59 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
paperless        | 16:22:59 [Q] INFO Process-1:32 processing [charlie-october-cat-seven]
paperless        | 16:23:00 [Q] INFO Process-1:32 stopped doing work
paperless        | 16:23:00 [Q] INFO Processed [charlie-october-cat-seven]
paperless        | 16:23:04 [Q] INFO recycled worker Process-1:32
paperless        | 16:23:04 [Q] INFO Process-1:33 ready for work at 6506
```

PDF files keep hanging on the process documents.

Here is my docker-compose file:

```
services:
  redis:
    container_name: redis
    image: redis:7.0.5
    restart: unless-stopped
    mem_limit: 512m
    environment:
      TZ: Europe/Paris
      PUID: 1000
      PGID: 1000
      REDIS_DATABASES: 1
    volumes:
      - /srv/paperless/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 30s

  postgres:
    container_name: postgres
    image: postgres:14.5
    restart: unless-stopped
    mem_limit: 512m
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: password
    volumes:
      - /srv/paperless/db_01:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "paperless", "-U", "paperless" ]
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 30s

  paperless:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:1.9.2
    restart: unless-stopped
    mem_limit: 1024m
    ports:
      - 8000:8000
    environment:
      PAPERLESS_URL: https://paperless.local
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: password
      PAPERLESS_DBNAME: paperless
      PAPERLESS_ADMIN_USER: user
      PAPERLESS_ADMIN_PASSWORD: password
      PAPERLESS_ADMIN_MAIL: contact@local.fr
    volumes:
      - /srv/paperless/vol_01:/usr/src/paperless/data
      - /srv/paperless/vol_02:/usr/src/paperless/media
      - /srv/paperless/vol_03:/usr/src/paperless/export
      - /srv/paperless/vol_04:/usr/src/paperless/consume
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
      - redis
```

Do you have any idea of what is causing that issue ?

Cheers.

### Steps to reproduce

1. Go to dashboard.
2. Upload the PDF.
3. Endless wait, and PDF keep being process without success.

### Paperless-ngx version

1.9.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Browser

Firefox
