### ISSUE TITLE
[BUG] django.db.utils.OperationalError: FATAL: sorry, too many clients already

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1797]
### Description

I’m trying to pinpoint exactly when/how this occurs and so far it seems to be whenever I add a folder full of files into the consume directory. (I’m using docker and have all paperless folders mapped to host locations)

![CE8DA1FF-653B-49E5-BBD8-30FA23B0DDC1](https://user-images.githubusercontent.com/4349292/195807969-5206ff16-b1e2-47ad-a5a9-f425b0320d0f.jpeg)

This then results in a Server 500 error, initially visible via the UI

![E2800070-1334-4ACC-896E-24FA4792743C](https://user-images.githubusercontent.com/4349292/195808473-8b08cce3-ed1f-4e7b-8548-6f799eae445b.jpeg)

But upon refresh, and trying to access paperless again, it simple returns the error on its own.

![6BAB8078-347B-411B-B1D6-6B2790F8BCAA](https://user-images.githubusercontent.com/4349292/195808585-19793f30-115c-4a1d-b906-e1ba20702d86.jpeg)

### Steps to reproduce

I added a folder approx 29 mb in size into the consume folder.

My Docker compose is as follows..

````
version: "3.6"
services:
  redis:
    image: redis:6.2
    container_name: paperless-redis
    restart: always
    volumes:
      - /share/Container/paperlessredis:/data

  db:
    image: postgres:14
    container_name: paperless-db
    restart: always
    volumes:
      - /share/Container/paperlessdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx
    container_name: paperlessngx
    restart: always
    privileged: true
    depends_on:
      - db
      - redis
      - gotenberg
      - tika
    ports:
      - 8777:8000
    volumes:
      - /share/Container/paperless/data:/usr/src/paperless/data
      - /share/Container/paperless/media:/usr/src/paperless/media
      - /share/Container/paperless/export:/usr/src/paperless/export
      - /share/Container/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1005
      USERMAP_GID: 1000
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_ADMIN_USER: chris
      PAPERLESS_ADMIN_PASSWORD: chrishosting
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      PAPERLESS_CONSUMER_POLLING: 5
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIKA_ENABLED: 1
      #PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/forms/libreoffice/convert#
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: gotenberg/gotenberg
    restart: always
    container_name: gotenberg
    ports:
      - 3044:3000
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
  
  tika:
    image: ghcr.io/paperless-ngx/tika
    container_name: tika
    ports:
      - 9998:9998
    restart: always
    ````

### Paperless-ngx version

Latest

### Host OS

QNAP linux 

### Installation method

Docker - linuxserver.io image

### Browser

Safari

### Configuration changes

Provided above in steps to reproduce
