### ISSUE TITLE
Setting PAPERLESS_TRASH_DIR is not working.

### ISSUE THREAD

**Issue by apoorv569** [paperless-ngx/paperless-ngx#2130]
### Description

I have set the variable `PAPERLESS_TRASH_DIR` in `docker-compose.env` but when I start the container, in the logs I see this error message mentioned below under `"Webserver logs",

Here is the relevant part of the `docker-compose.env`
```yaml
# Paths and folders
#PAPERLESS_CONSUMPTION_DIR=../consume
#PAPERLESS_DATA_DIR=../data
PAPERLESS_TRASH_DIR=/mnt/documents/trash
#PAPERLESS_MEDIA_ROOT=../media
#PAPERLESS_STATICDIR=../static
#PAPERLESS_FILENAME_FORMAT=
#PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=
```

`/mnt/documents` is a `NFS` mount, I have my `media`, `consume` and `export` direct set to the same directory and they all are fine with it. Permissions are good as well.

```yaml
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 80:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
#     - data:/usr/src/paperless/data
#     - media:/usr/src/paperless/media
      - ./appdata/paperless-ngx/data:/usr/src/paperless/data
      - /mnt/documents/media:/usr/src/paperless/media
      - /mnt/documents/export:/usr/src/paperless/export
      - /mnt/documents/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
```
```ls
apoorv@paperless:~/dc$ ls -la /mnt/documents/
total 4
drwxrws---+ 1 apoorv users   46 Dec  5 15:42 .
drwxr-xr-x  3 root   root  4096 Dec  5 15:50 ..
drwxrwx---+ 1 apoorv users    0 Dec  6 03:18 consume
drwxrwx---+ 1 apoorv users    0 Dec  5 15:42 export
drwxrwx---+ 1 apoorv users   38 Dec  6 03:18 media
drwxrws---+ 1 apoorv users    0 Dec  5 15:42 trash
```

I manually created the `trash` directory but that doesn't help either.

### Steps to reproduce

1. Set `PAPERLESS_TRASH_DIR` variable to `/mnt/documents/trash`
2. Start the container
3. Check logs
4. See the error

### Webserver logs

```bash
webserver_1  | SystemCheckError: System check identified some issues:
webserver_1  |
webserver_1  | ERRORS:
webserver_1  | ?: PAPERLESS_TRASH_DIR is set but doesn't exist.
webserver_1  |  HINT: Create a directory at /mnt/documents/trash
```
```


### Browser logs

_No response_

### Paperless-ngx version

1.10.2

### Host OS

Ubuntu 22.04 LTS

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

_No response_

### Other

_No response_
