### ISSUE TITLE
[BUG] ERROR:  relation "documents_document" does not exist at character 625

### ISSUE THREAD

**Issue by stepanov1975** [paperless-ngx/paperless-ngx#2182]
### Description

Fresh installation using docker-compose

### Steps to reproduce

Gerring error:
paperless-ngx-postgres | 2022-12-14 19:21:49.834 UTC [68] ERROR:  relation "documents_document" does not exist at character 625

### Webserver logs

```bash
paperless-ngx | Apply database migrations...
paperless-ngx-postgres | 2022-12-14 19:21:49.834 UTC [68] ERROR:  relation "documents_document" does not exist at character 625
paperless-ngx-postgres | 2022-12-14 19:21:49.834 UTC [68] STATEMENT:  SELECT "documents_document"."id", "documents_document"."correspondent_id", "documents_document"."storage_path_id", "documents_document"."title", "documents_document"."document_type_id", "documents_document"."content", "documents_document"."mime_type", "documents_document"."checksum", "documents_document"."archive_checksum", "documents_document"."created", "documents_document"."modified", "documents_document"."storage_type", "documents_document"."added", "documents_document"."filename", "documents_document"."archive_filename", "documents_document"."original_filename", "documents_document"."archive_serial_number" FROM "documents_document" WHERE "documents_document"."storage_type" = 'gpg' ORDER BY "documents_document"."created" DESC LIMIT 1
```

### Paperless-ngx version

latest

### Host OS

docker on Fedora

### Installation method

Docker - official image

### Configuration changes

```
version: "3.4"
services:

  broker:
    image: redis:latest
    restart: unless-stopped
    container_name: paperless-ngx-redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 3s
      retries: 5

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - broker
      - db
    ports:
      - 8888:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

  db:
    image: docker.io/library/postgres:latest
    restart: unless-stopped
    container_name: paperless-ngx-postgres
    security_opt:
      - no-new-privileges:true
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker_installs/paperless-ngx/data
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker_installs/paperless-ngx/media
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker_installs/paperless-ngx/redis_data
  pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker_installs/paperless-ngx/pg_data
```
