### ISSUE TITLE
[Enhancement] Split docker image build into base image and application image

### ISSUE THREAD

**Issue by schnuffle** [paperless-ngx/paperless-ngx#222]
For the moment, the job build-docker-image in ci.yml takes some hours. 
### The reason:
- The whole container is rebuild everytime it runs
- The 2 components jbig2enc and pikepdf ( only arm ) get rebuild for every new build, though there're no changes

### A possible Solution:
Seperate the docker build into 2 stages:
- Build the base image with all deps only when there has been changes
- Base the final image on the base image

I've started a POC in my fork and will report if there's any progress

Regards

Schnuffle

**Comment by schnuffle** [comment]
I started with some test and had another idea. For now I have defined 3 workflows:

1. Build a nodejs base image, that should be triggered on changing files package.json and package-json.lock
2. Build a ngx base image, that should be triggered on any python dep changes
3. Build the ngx image using thise two others

I need to sort out how exactly the directive works and if I can it combine with tags:


```
on:
  push:
    tags: 
      - ngx-base-nodejs*
    paths:
      - 'example.c'
    branches-ignore:
      - 'translations**'
```
