### ISSUE TITLE
[BUG] Migration crashes while upgrading to Paperless-ngx 1.10.x

### ISSUE THREAD

**Issue by DasFaultier** [paperless-ngx/paperless-ngx#2269]
### Description

I am currently running docker-compose based Paperless-ngx 1.9.2 with Postgres, Tika and Gotenberg:
```
$ docker image ls
REPOSITORY                            TAG       IMAGE ID       CREATED         SIZE
redis                                 7         3358aea34e8c   6 weeks ago     117MB
postgres                              13        a4d5977013bf   6 weeks ago     373MB
apache/tika                           latest    2fe4f732c2cf   7 weeks ago     437MB
ghcr.io/paperless-ngx/paperless-ngx   1.9.2     18e744af92a1   3 months ago    1.35GB
gotenberg/gotenberg                   7.4       7e1884a8553c   11 months ago   1.51GB
```

When upgrading to Paperless-ngx 1.10.x, I run into problems. Paperless tries to run migrations on the database, but crashes while doing so (see logs below).

The `docker-compose.yml` looks like this:
```yaml
version: "3.4"
services:
  broker:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /opt/paperless/db/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: {{ db_name }}
      POSTGRES_USER: {{ db_user }}
      POSTGRES_PASSWORD: {{ db_password }}

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 80:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /opt/paperless/data/:/usr/src/paperless/data
      - /opt/paperless/media/:/usr/src/paperless/media
      - /opt/paperless/export:/usr/src/paperless/export
      - /opt/paperless/consume/:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    restart: unless-stopped
    environment:
      CHROMIUM_DISABLE_ROUTES: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:
```
Iirc, this is based on the Compose file i found in the Paperless-ngx GitHub repo somewhere during version 1.8, so probably nothing too extraordinary.

If you have any questions, I'll be happy to try and provide more details as needed.

### Steps to reproduce

1. Install Paperless-ngx 1.9.2 using docker-compose
2. Shut down existing containers (`docker-compose -p paperless down`)
3. Get latest Docker images (`docker-compose -p paperless pull`)
4. Startup with fresh containers (`docker-compose -p paperless up -d`)
5. Monitor logs and state of Paperless container.

### Webserver logs

```bash
# docker-compose -p paperless logs
(...)
db_1         | 2022-12-30 13:23:37.631 UTC [1] LOG:  database system is ready to accept connections
db_1         | 2022-12-30 13:23:46.867 UTC [35] ERROR:  tuple concurrently updated
db_1         | 2022-12-30 13:23:46.867 UTC [35] STATEMENT:  DROP TABLE IF EXISTS django_q_schedule
(...)
webserver_1  | Paperless-ngx docker container starting...
webserver_1  | Installing languages...
webserver_1  | Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
webserver_1  | Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
webserver_1  | Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
webserver_1  | Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
webserver_1  | Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [210 kB]
webserver_1  | Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
webserver_1  | Fetched 8616 kB in 4s (2253 kB/s)
webserver_1  | Reading package lists...
webserver_1  | Package tesseract-ocr-deu already installed!
webserver_1  | Creating directory /tmp/paperless
webserver_1  | Adjusting permissions of paperless files. This may take a while.
webserver_1  | Waiting for PostgreSQL to start...
webserver_1  | Waiting for Redis...
webserver_1  | Connected to Redis broker.
webserver_1  | Apply database migrations...
webserver_1  | Operations to perform:
webserver_1  |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, paperless_mail, sessions
webserver_1  | Running migrations:
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
webserver_1  |     return self.cursor.execute(sql)
webserver_1  | psycopg2.errors.InternalError_: tuple concurrently updated
webserver_1  |
webserver_1  |
webserver_1  | The above exception was the direct cause of the following exception:
webserver_1  |
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/manage.py", line 11, in <module>
webserver_1  |     execute_from_command_line(sys.argv)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
webserver_1  |     utility.execute()
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
webserver_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
webserver_1  |     self.execute(*args, **cmd_options)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
webserver_1  |     output = self.handle(*args, **options)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
webserver_1  |     res = handle_func(*args, **kwargs)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 349, in handle
webserver_1  |     post_migrate_state = executor.migrate(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
webserver_1  |     state = self._migrate_all_forwards(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
webserver_1  |     state = self.apply_migration(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
webserver_1  |     state = migration.apply(state, schema_editor)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 130, in apply
webserver_1  |     operation.database_forwards(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 106, in database_forwards
webserver_1  |     self._run_sql(schema_editor, self.sql)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 133, in _run_sql
webserver_1  |     schema_editor.execute(statement, params=None)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 199, in execute
webserver_1  |     cursor.execute(sql, params)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
webserver_1  |     return self._execute_with_wrappers(
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
webserver_1  |     return executor(sql, params, many, context)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
webserver_1  |     return self.cursor.execute(sql, params)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
webserver_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
webserver_1  |     return self.cursor.execute(sql)
webserver_1  | django.db.utils.InternalError: tuple concurrently updated
```

### Paperless-ngx version

1.10.2

### Host OS

Ubuntu 22.04.1

### Installation method

Docker - official image
