### ISSUE TITLE
Upgrade to 1.6.0 breaks Kubernetes installations (Error: 'tcp' is not a valid port number.)

### ISSUE THREAD

**Issue by morremeyer** [paperless-ngx/paperless-ngx#264]
ℹ️ This serves as a note to everyone running their installation in a Kubernetes cluster and upgrading to 1.6.0.

You **must** set the environment variable `PAPERLESS_PORT` **if** your Service resource is named `paperless`.

If you do not do this before upgrading, you will get the following error logged by paperless: `Error: 'tcp' is not a valid port number.`

This will affect you if you use the following setup methods (this list is definitely incomplete):

* [k8s-at-home/paperless](https://github.com/k8s-at-home/charts/tree/master/charts/stable/paperless), PR: https://github.com/k8s-at-home/charts/pull/1450

**Background information**:

#124 introduced the environment variable `PAPERLESS_PORT`. 

However, Kubernetes automatically creates a variable named `${serviceName}_PORT` in the paperless container (as the service matches that pod). See https://kubernetes.io/docs/concepts/containers/container-environment/ for details.

**Comment by qcasey** [comment]
Thanks. Is this something we can fix by setting a default?

**Comment by morremeyer** [comment]
That’s a good question. Let me experiment with that, I like the idea. I’ll report back here.
If it works, I’ll open a PR.

If not, I'll close this issue anyway. I initially opened it to have this documented for others who might run into the same problem, not with the expectation that we could actually fix it. Would be great if we can :)

**Comment by ikaruswill** [comment]
I just ran into the same issue and saw your post here. You can fix this without setting the `PAPERLESS_PORT` environment variable, and instead, disable service links (which is useless in most contexts) by setting `enableServiceLinks: false` in the pod spec.

Example:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paperless
    spec:
      enableServiceLinks: false
```
