### ISSUE TITLE
[BUG]  Error: Error 110 connecting to paperless-redis:6379. Connection timed out

### ISSUE THREAD

**Issue by Hack4Life** [paperless-ngx/paperless-ngx#3533]
### Description

I am trying to setup paperless-ngx via a Portainer (running on my Synology) Stack.

This is my stack file:
```
services:
  redis:
    image: redis
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
      - /volume2/docker/paperless/redisdata:/usr/local/etc/redis

  db:
    image: docker.io/library/postgres:13
    container_name: paperless-postgres
    restart: unless-stopped
    volumes:
      - /volume2/docker/paperless/pqdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperlessngx
    restart: unless-stopped
    depends_on:
      - redis
      - gotenberg
      - tika
    ports:
      - 6969:8000
    volumes:
      - /volume2/docker/paperless/data:/usr/src/paperless/data
      - /volume2/docker/paperless/media:/usr/src/paperless/media
      - /volume3/homes/paperless/paperless/export:/usr/src/paperless/export
      - /volume3/homes/paperless/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PUID: 1024
      PGID: 100
      USERMAP_UID: 1024
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_DBHOST: db
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: mysecretpw
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998

  gotenberg:
    image: gotenberg/gotenberg
    restart: unless-stopped
    container_name: paperless-gotenberg
    ports:
      - 3044:3000
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika
    container_name: paperless-tika
    ports:
      - 9998:9998
    restart: unless-stopped
```

Once I try to start the stack all containers spin up correctly and appear to be running:
<img width="1142" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/11788789/893c9532-fcee-41ab-99a6-5bf248f63040">

Nevertheless it looks like paperlessngx cannot connect to redis (all log output below). What am I doing wrong here?

Log from `paperlessngx`:
```
Paperless-ngx docker container starting...,
Mapping UID and GID for paperless:paperless to 1024:100,
Creating directory /tmp/paperless,
Adjusting permissions of paperless files. This may take a while.,
Waiting for PostgreSQL to start...,
Waiting for Redis...,
Redis ping #0 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Redis ping #1 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Redis ping #2 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Redis ping #3 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Redis ping #4 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Failed to connect to redis using environment variable PAPERLESS_REDIS.,
Paperless-ngx docker container starting...,
Creating directory /tmp/paperless,
Adjusting permissions of paperless files. This may take a while.,
Waiting for PostgreSQL to start...,
Waiting for Redis...,
Redis ping #0 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s
```

Log output from `paperless-redis`:
```
1:C 04 Jun 2023 14:37:44.099 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo,
1:C 04 Jun 2023 14:37:44.099 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started,
1:C 04 Jun 2023 14:37:44.099 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf,
1:M 04 Jun 2023 14:37:44.100 * monotonic clock: POSIX clock_gettime,
1:M 04 Jun 2023 14:37:44.101 * Running mode=standalone, port=6379.,
1:M 04 Jun 2023 14:37:44.101 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.,
1:M 04 Jun 2023 14:37:44.101 # Server initialized,
1:M 04 Jun 2023 14:37:44.101 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.,
1:M 04 Jun 2023 14:37:44.102 * Ready to accept connections
```

Log from `paperless-postgres`:
```
,
PostgreSQL Database directory appears to contain a database; Skipping initialization,
,
2023-06-04 14:37:44.006 UTC [1] LOG:  starting PostgreSQL 13.11 (Debian 13.11-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit,
2023-06-04 14:37:44.018 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432,
2023-06-04 14:37:44.018 UTC [1] LOG:  listening on IPv6 address "::", port 5432,
2023-06-04 14:37:44.673 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432",
2023-06-04 14:37:45.536 UTC [27] LOG:  database system was shut down at 2023-06-04 14:35:03 UTC,
2023-06-04 14:37:45.848 UTC [1] LOG:  database system is ready to accept connections
```

Log from `paperless-tika`:
```
INFO  [main] 14:38:02,447 org.apache.tika.server.core.TikaServerProcess Starting Apache Tika 2.7.0 server,
INFO  [main] 14:38:04,188 org.apache.tika.server.core.TikaServerProcess loading resource from SPI: class org.apache.tika.server.standard.resource.XMPMetadataResource,
Jun 04, 2023 2:38:06 PM org.apache.cxf.endpoint.ServerImpl initDestination,
INFO: Setting the server's publish address to be http://0.0.0.0:9998/,
INFO  [main] 14:38:06,348 org.eclipse.jetty.util.log Logging initialized @10104ms to org.eclipse.jetty.util.log.Slf4jLog,
INFO  [main] 14:38:06,510 org.eclipse.jetty.server.Server jetty-9.4.50.v20221201; built: 2022-12-01T22:07:03.915Z; git: da9a0b30691a45daf90a9f17b5defa2f1434f882; jvm 17.0.7+7-Ubuntu-0ubuntu122.04.2,
INFO  [main] 14:38:07,049 org.eclipse.jetty.server.AbstractConnector Started ServerConnector@241a0c3a{HTTP/1.1, (http/1.1)}{0.0.0.0:9998},
INFO  [main] 14:38:07,049 org.eclipse.jetty.server.Server Started @10808ms,
WARN  [main] 14:38:07,062 org.eclipse.jetty.server.handler.ContextHandler Empty contextPath,
INFO  [main] 14:38:07,087 org.eclipse.jetty.server.handler.ContextHandler Started o.e.j.s.h.ContextHandler@3ff57625{/,null,AVAILABLE},
INFO  [main] 14:38:07,372 org.apache.tika.server.core.TikaServerProcess Started Apache Tika server e05206bd-2b73-4b8a-b58a-b0e0df02231a at http://0.0.0.0:9998/
```

Log from `paperless-gotenberg`:
```
,
  _____     __           __               ,
 / ___/__  / /____ ___  / /  ___ _______ _,
/ (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/,
\___/\___/\__/\__/_//_/_.__/\__/_/  \_, / ,
                                   /___/,
,
A Docker-powered stateless API for PDF files.,
Version: 7.8.3,
-------------------------------------------------------,
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook ,
[SYSTEM] prometheus: collecting metrics,
[SYSTEM] api: server listening on port 3000,
[SYSTEM] gc: application started,
[SYSTEM] uno: long-running LibreOffice listener ready to start,
[SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
```

### Steps to reproduce

1. Use the stack file from the post
2. Try to start the stack
3. open the paperlessngx container logs to see the error

### Webserver logs

```bash
Paperless-ngx docker container starting...,
Mapping UID and GID for paperless:paperless to 1024:100,
Creating directory /tmp/paperless,
Adjusting permissions of paperless files. This may take a while.,
Waiting for PostgreSQL to start...,
Waiting for Redis...,
Redis ping #0 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Redis ping #1 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Redis ping #2 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Redis ping #3 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Redis ping #4 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s,
Failed to connect to redis using environment variable PAPERLESS_REDIS.,
Paperless-ngx docker container starting...,
Creating directory /tmp/paperless,
Adjusting permissions of paperless files. This may take a while.,
Waiting for PostgreSQL to start...,
Waiting for Redis...,
Redis ping #0 failed.,
Error: Error 110 connecting to paperless-redis:6379. Connection timed out..,
Waiting 5s
```

### Paperless-ngx version

1.15.1

### Host OS

Synology NAS / x86_64

### Installation method

Other (please describe above)

### Browser

docker-compose.portainer.yml
