### ISSUE TITLE
Right on a document not applied by the API

### ISSUE THREAD

**Issue by Philippe-M** [paperless-ngx/paperless-ngx#3705]
### Description

Hi,

I re-open a bug ticket because the previous one was transformed into discussion and everything was closed because my request was not clear.

With a PAPERLESS_POST_CONSUME_SCRIPT I try to update the access rights to a document.I largely inspired myself with documentation: https://github.com/paperless-ngx/paperless-ngx/wiki/post-consume-script-examples

My python script:

```
#!/usr/bin/env python3

import os
import requests

def _set_auth_tokens(paperless_url: str, timeout: float, session: requests.Session):
    credentials = {"username": "mysuperuser", "password": "mypassword"}
    response = sess.get(paperless_url, timeout=timeout)
    response.raise_for_status()
    csrf_token = response.cookies["csrftoken"]

    response = sess.post(
        paperless_url + "/api/token/",
        data=credentials,
        headers={"X-CSRFToken": csrf_token},
        timeout=timeout,
    )
    response.raise_for_status()

    api_token = response.json()["token"]

    session.headers.update(
        {"Authorization": f"Token {api_token}", f"X-CSRFToken": csrf_token}
    )

def get_info(paperless_url: str, timeout: float, session: requests.Session, doc_pk):
    doc_info_resp = sess.get(
        paperless_url + f"/api/documents/{doc_pk}/?full_perms=true", timeout = timeout
    )
    doc_info_resp.raise_for_status()
    doc_info = doc_info_resp.json()

    print("permissions : " + str(doc_info["permissions"]))

if __name__ == "__main__":
    paperless_url = "http://localhost:8000"
    timeout = 5.0

    with requests.Session() as sess:
        _set_auth_tokens(paperless_url, timeout, sess)

        #doc_pk = int(os.environ["DOCUMENT_ID"])
        doc_pk = 62
        get_info(paperless_url, timeout, sess, doc_pk)

        resp = sess.patch(
            paperless_url + f"/api/documents/{doc_pk}/",
            data =
                {
                    "owner": 4,
                    "permissions": {
                        "view": {
                            "users": [1], 
                            "groups": [1]
                        },
                        "change": {
                            "users": [1],
                            "groups": [3]
                        }
                    },
                    "set_permissions": {
                        "view": {
                            "users": [1], 
                            "groups": [1]
                        },
                        "change": {
                            "users": [1],
                            "groups": [3]
                        }
                    }
                },
            timeout = timeout,
        )
        resp.raise_for_status()

        get_info(paperless_url, timeout, sess, doc_pk)

```        

For my tests, I first display the rights assigned to the document (ID 62 here), I apply changes and I show rights again.Results The old ones have been deleted and the new not applied.

I tried several structures for the data variable (line 48) to ultimately reproduce that obtained when using the interface.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/03a9c943-e702-4d51-baf3-abcd245ba4da)

For my tests I use docker and paperless-ngx with sqlite

Docker-compose.yml (with a modification to add tabula)

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./consume:/usr/src/paperless/consume
      # Use for PAPERLESS_POST_CONSUME_SCRIPT
      - ./export:/usr/src/paperless/export      
      - ./scripts:/usr/src/paperless/scripts
      # -------------------------------------
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless/scripts/post_script.py
      PAPERLESS_OCR_LANGUAGE: fra
      PAPERLESS_TIME_ZONE: Europe/Paris
      PAPERLESS_URL: http://localhost:8000
      CSRF_TRUSTED_ORIGINS: http://localhost:8000

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

  tabula:
    build: ./
    volumes:
    # Same source of PAPERLESS_POST_CONSUME_SCRIPT
      - ./export:/export
      - ./scripts:/scripts
      
volumes:
  data:
  media:
  redisdata:
```

### Steps to reproduce

- Assign reading and writing rights by the web interface;
- Save the document;
- Launch the script by adapting the Doc_PK variable and the IDs of users and groups if necessary.
- Recharge the document from the web interface.

### Webserver logs

```bash
none
```

### Paperless-ngx version

1.16.4

### Host OS

Fedora 37 / Linux 6.3.5-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 30 15:43:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

Docker - official image

### Configuration changes

docker-compose.yml
