### ISSUE TITLE
[BUG] Polish Diacritics don't work in the Content section of the document

### ISSUE THREAD

**Issue by life8853** [paperless-ngx/paperless-ngx#3718]
### Description

Currently polish diacritics don't seem to work for me in the content tab as well as in search:
`SCownie: sze[dziesit osiem PLN 94/100`, when it should be `Słownie: sześćdziesiąt osiem PLN 94/100`

### Steps to reproduce

1. Install paperless using the postgress tika docker-compose.yml
2. Set PAPERLESS_OCR_LANGUAGES=pol and PAPERLESS_OCR_LANGUAGE=pol+eng in docker-compose.env
3. Enter a pdf with letters like "Ą,Ę,Ć,Ś" - Ó and Ł seem to work
4. Look in the content tab of a document.

Was able to reproduce on brand new install of Ubuntu 23.04 in a VM (x64)
It's not a db configuration problem, cause it is able to store and than display those symbols when i manually inserted them into a row.

### Webserver logs

```bash
2023-06-29 19:04:18,648] [INFO] [paperless.consumer] Consuming FS_6005_KRI_22.pdf

[2023-06-29 19:04:18,653] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-06-29 19:04:18,655] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-06-29 19:04:18,667] [DEBUG] [paperless.consumer] Parsing FS_6005_KRI_22.pdf...

[2023-06-29 19:04:18,867] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxkoprn3jy/FS_6005_KRI_22.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-whfkekmm/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'pol', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-whfkekmm/sidecar.txt')}

[2023-06-29 19:04:19,822] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2023-06-29 19:04:19,888] [DEBUG] [paperless.consumer] Generating thumbnail for FS_6005_KRI_22.pdf...

[2023-06-29 19:04:19,904] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-whfkekmm/archive.pdf[0] /tmp/paperless/paperless-whfkekmm/convert.webp

[2023-06-29 19:04:21,949] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2023-06-29 19:04:21,960] [DEBUG] [paperless.consumer] Saving record to database

[2023-06-29 19:04:21,961] [DEBUG] [paperless.consumer] Creation date from parse_date: 1978-01-01 00:00:00+01:00

[2023-06-29 19:04:22,094] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxkoprn3jy/FS_6005_KRI_22.pdf

[2023-06-29 19:04:22,099] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-whfkekmm
```
```


### Browser logs

_No response_

### Paperless-ngx version

1.16.5

### Host OS

Armbian (based of ubuntu 22.04)/ aarch64

### Installation method

Docker - official image

### Browser

Brave - chromium based

### Configuration changes

_No response_

### Other

_No response_

**Comment by shamoon** [comment]
What database and collation are you using?

**Comment by life8853** [comment]
I am using postgres (docker-compose-tika-postgres.yml file that you provide) and I didn't change anything about collation so whatever is set in the image by default, that's what I'm using.

**Comment by life8853** [comment]
I did some testing and it happens for mariadb also, so i don't think it is database's fault.

**Comment by solarssk** [comment]
Hmmm... in my paper I don't have that issue

<img width="157" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/83293863/2ed2e022-4652-4da3-a2d9-3793b8d4a5f2">

**Comment by life8853** [comment]
@solarssk Could you try for example this? https://cloud-a.edupage.org/cloud/H7_Napoleon_Bonaparte_zadanie.pdf?z%3AEw%2BQiEgCTISbAzzbKVhohsce6AYRCkBGsHTCUEmMu5Ivahl6EhYhe8seVa24YQGL  This is the one that i tried.

**Comment by solarssk** [comment]
<img width="1468" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/83293863/71103e43-9146-4c44-98aa-6bdbbee487ec">
everything I see is ok.

**Comment by life8853** [comment]
That's weird, you mind sharing your config files, and installation method that you are using?

**Comment by solarssk** [comment]
Docker on Synology:

`version: "3.6"
services:
  broker:
    image: redis
    container_name: paperless_redis
    hostname: paperless-redis
    restart: always
    sysctls:
      - net.core.somaxconn=511
    networks:
      - paperless_network
      - grafana_network
    volumes:
      - XXX:/data

  db:
    image: postgres:13
    container_name: paperless_postgres
    hostname: paperless-postgre
    restart: always
    networks:
      - paperless_network
      - grafana_network
    volumes:
      - XXX:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: XXX
      POSTGRES_USER: XXX
      POSTGRES_PASSWORD: XXX

  gotenberg:
    image: gotenberg/gotenberg:7.8.0
    restart: always
    container_name: paperless_gotenberg
    networks:
      - paperless_network
    #ports:
    #  - 3002:3000
    command:
      - 'gotenberg'
      - '--log-level=debug'
      - '--api-timeout=600s'
      - '--uno-listener-start-timeout=180s'
      - '--chromium-disable-javascript=true'
      - '--chromium-allow-list=file:///tmp/.*'
  
  tika:
    image: ghcr.io/paperless-ngx/tika
    container_name: paperless_tika
    networks:
      - paperless_network
    #ports:
    #  - 9998:9998
    restart: always
    
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.15.1
    restart: always
    container_name: paperless_server
    networks:
      - paperless_network
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8777:8000
    volumes:
      - XXX:/usr/src/paperless/data
      - XXX:/usr/src/paperless/media
      - XXX:/usr/src/paperless/export
      - XXX:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: XXX
      USERMAP_GID: XXX
      PAPERLESS_TIME_ZONE: Europe/Warsaw
      PAPERLESS_ADMIN_USER: XXX
      PAPERLESS_ADMIN_PASSWORD: XXX
      PAPERLESS_ADMIN_MAIL: XXX
      PAPERLESS_URL: https://XXX
      PAPERLESS_ALLOWED_HOSTS: XXX
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{created} {title}"
      PAPERLESS_LOGOUT_REDIRECT_URL: https://XXX
      PAPERLESS_ENABLE_UPDATE_CHECK: enable
      PAPERLESS_OCR_LANGUAGES: pol
      PAPERLESS_OCR_LANGUAGE: pol
      PAPERLESS_ENABLE_HTTP_REMOTE_USER: "TRUE"
      PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTHENTIK_USERNAME
      #PAPERLESS_CONVERT_MEMORY_LIMIT: 128
      PAPERLESS_OPTIMIZE_THUMBNAILS: "false"
      #PAPERLESS_WEBSERVER_WORKERS: 1
      #PAPERLESS_OCR_THREADS: 1
      PAPERLESS_TASK_WORKERS: 1
      PAPERLESS_THREADS_PER_WORKER: 2
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/forms/libreoffice/convert#
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      
networks:
  grafana_network:
    external: true
  paperless_network:
    name: paperless_network
    ipam:
      config:
        - subnet: XXX
`

**Comment by life8853** [comment]
Hmm i don't see anything that would be different from mine

Docker-compose.yml
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:


networks:
  default:
    external: true
    name: homenetwork
```

Docker-compose.env file
```
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=XXX
USERMAP_GID=XXX

# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
PAPERLESS_OCR_LANGUAGES=pol

###############################################################################
# Paperless-specific settings                                                 #
###############################################################################

# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.

# This is required if you will be exposing Paperless-ngx on a public domain
# (if doing so please consider security measures such as reverse proxy)
PAPERLESS_URL=XXX

# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
PAPERLESS_SECRET_KEY=XXX

# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=Europe/Warsaw

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=pol+eng

# Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx
#PAPERLESS_FORCE_SCRIPT_NAME=/PATHPREFIX
#PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # trailing slash required

PAPERLESS_TIKA_ENABLED=true


PAPERLESS_TASK_WORKERS=2
```
