### ISSUE TITLE
[BUG] Migration from ng TypeError: argument of type 'EmailAddress' is not iterable

### ISSUE THREAD

**Issue by stepanov1975** [paperless-ngx/paperless-ngx#377]
Hi.

Just migrated from ng by replacing the image and see the following errors in the log:

```
paperless-ng | [2022-03-15 15:48:40,811] [ERROR] [paperless_mail] Rule Alex Gmail.Alex mailbox: Error while processing mail 137569: argument of type 'EmailAddress' is not iterable
paperless-ng | Traceback (most recent call last):
paperless-ng |   File "/usr/src/paperless/src/paperless_mail/mail.py", line 222, in handle_mail_rule
paperless-ng |     processed_files = self.handle_message(message, rule)
paperless-ng |   File "/usr/src/paperless/src/paperless_mail/mail.py", line 266, in handle_message
paperless-ng |     correspondent = self.get_correspondent(message, rule)
paperless-ng |   File "/usr/src/paperless/src/paperless_mail/mail.py", line 138, in get_correspondent
paperless-ng |     and "name" in message.from_values
paperless-ng | TypeError: argument of type 'EmailAddress' is not iterable
```

docker-compose file:
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    container_name: paperless-redis
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ng
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8008:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
```

docker-compose.env
```
USERMAP_UID=1000
USERMAP_GID=1000

PAPERLESS_OCR_LANGUAGES=eng heb

PAPERLESS_SECRET_KEY=edited

PAPERLESS_TIME_ZONE=Asia/Jerusalem

PAPERLESS_OCR_LANGUAGE=heb
PAPERLESS_FILENAME_FORMAT={document_type}/{created_year}/{created_month}/{title}
```
