### ISSUE TITLE
[BUG] Database half? gone

### ISSUE THREAD

**Issue by Grummeltier** [paperless-ngx/paperless-ngx#418]
**Describe the bug**
I installed 1.6.0-RC1 with docker compose and updated to 1.6.0 and everything went super. I filled my paperless with documents and everything was ok. I have restarted the docker container and the host machine and this was also ok, but yesterday I shut down my host machine and now after booting and starting of the containers, my documents can't be found in paperless.

The item ist there with all details, the OCR and most of the Metadata, but no thumbnail and no document. I can't open or download the document.

I have my data and media folder on an smb-share on the host machine, which is on my NAS. All documents are on my NAS, but paperless can't find them. When I open a document I get a website from the Django REST framework and the message 

```
GET /api/documents/232/preview/

HTTP 404 Not Found
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Nicht gefunden."
}
```
In the docker log I get 
```
paperless-webserver-1  | [2022-03-17 09:18:42,461] [WARNING] [django.request] Not Found: /api/documents/232/thumb/
```

**Webserver logs**
```
If available, post any logs from the web server related to your issue.
```

**Relevant information**
 - Host OS of the machine running paperless: debian 11
 - Browser firefox
 - Version 1.6.0
 - Installation method: docker (20.10.12) with compose (2.1.1)

docker-compose.yml
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 80:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/dms/paperless-ngx/data:/usr/src/paperless/data
      - /mnt/dms/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  data:
  media:
  pgdata: 
 ```
 docker-compose.env
```
USERMAP_GID=1003
PAPERLESS_SECRET_KEY="SuperSecretPassword"
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
```
