### ISSUE TITLE
[BUG] Rootless Docker installation results in permission issues

### ISSUE THREAD

**Issue by MxtOUT** [paperless-ngx/paperless-ngx#4191]
### Description

Setting up paperless with the rootless Docker installation method fails at `docker compose run --rm webserver createsuperuser`:

```shell
[+] Creating 4/4
 ✔ Network paperless_default        Created                                                                                                                                              0.2s 
 ✔ Container paperless-tika-1       Created                                                                                                                                              0.2s 
 ✔ Container paperless-gotenberg-1  Created                                                                                                                                              0.3s 
 ✔ Container paperless-broker-1     Created                                                                                                                                              0.3s 
[+] Running 3/3
 ✔ Container paperless-gotenberg-1  Started                                                                                                                                              1.2s 
 ✔ Container paperless-broker-1     Started                                                                                                                                              1.3s 
 ✔ Container paperless-tika-1       Started                                                                                                                                              1.3s 
Paperless-ngx docker container starting...
Creating directory /usr/src/paperless/media/documents
mkdir: cannot create directory ‘/usr/src/paperless/media/documents’: Permission denied
```

There was [another issue](https://github.com/paperless-ngx/paperless-ngx/issues/3751) with the same symptoms but it was just transferred to a [discussion](https://github.com/paperless-ngx/paperless-ngx/discussions/3752).
In this discussion, [a user might have discovered](https://github.com/paperless-ngx/paperless-ngx/discussions/3752#discussioncomment-6764645) the cause for the issue:
The `consume/`, `export/`, and `media/` directories in the image are owned by the root user.
I can replicate the exact same situation on my device with both the `latest` and `dev` tags.

Trying to trace it down, I can't seem to make out where exactly the ownership of these directories is changed:

1. Ownership of `/usr/src/paperless/` is [recursively being transferred](https://github.com/paperless-ngx/paperless-ngx/blob/5ee9ad3e4f9e4cb1aeca2063c5246bbb4ef908f2/Dockerfile#L233) to the `paperless` user and group.
2. [Django collects static resources and translations](https://github.com/paperless-ngx/paperless-ngx/blob/5ee9ad3e4f9e4cb1aeca2063c5246bbb4ef908f2/Dockerfile#L234C3-L235C54), but already running under the `paperless` user.
3. [Volumes are declared](https://github.com/paperless-ngx/paperless-ngx/blob/5ee9ad3e4f9e4cb1aeca2063c5246bbb4ef908f2/Dockerfile#L237C1-L240C37]) (coincidence that the first volume has correct permissions and the other three don't?)
4. At runtime, the entrypoint script [tries to create some directories](https://github.com/paperless-ngx/paperless-ngx/blob/5ee9ad3e4f9e4cb1aeca2063c5246bbb4ef908f2/docker/docker-entrypoint.sh#L82C2-L91C6) and fails at creating `"${MEDIA_ROOT_DIR}/documents"` (probably due to the changed permissions)

### Steps to reproduce

Follow the installation steps for a rootless Docker installation using the official Docker image.

`docker-compose.yml`:
```yml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    user: 1000:1000
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  redisdata:
```

`docker-compose.env`:
```
USERMAP_UID=1000
USERMAP_GID=1000
```

`.env`:
```
COMPOSE_PROJECT_NAME=paperless
```

### Webserver logs

```bash
Doesn't start
```

### Paperless-ngx version

1.17.4

### Host OS

Raspberry Pi `arm64`

### Installation method

Docker - official image
