### ISSUE TITLE
[BUG] Images in HTML mails doesn't get processed

### ISSUE THREAD

**Issue by hspe98** [paperless-ngx/paperless-ngx#4195]
### Description

When I let paperless consume an email with html content, the image-tag with external urls (e.g. https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg) only appears as placeholder in the final pdf file.

The content of an example .eml file looks like this:

```
From: sender@domain.de
Return-Path: <sender@domain.de>
X-Spam-Checker-Version: SpamAssassin 3.4.4 (2020-01-24) on
 mail.domain.de
X-Spam-Level: **
X-Spam-Status: No, score=2.6 required=7.0 tests=ALL_TRUSTED,DKIM_SIGNED,
	DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,EMPTY_MESSAGE,
	HTML_IMAGE_ONLY_04,HTML_MESSAGE,IMG_ONLY_FM_DOM_INFO,MIME_HTML_ONLY,
	SPF_PASS,TVD_SPACE_RATIO,T_REMOTE_IMAGE autolearn=no
	autolearn_force=no version=3.4.4
X-Original-To: consume@domain.de
Delivered-To: consume@domain.de
Received: from webmail.domain.de (localhost [IPv6:::1])
	by mail.domain.de (Postfix) with ESMTPSA id 99A188CAD;
	Sat, 16 Sep 2023 22:13:24 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=domain.de;
	s=default; t=1694895204;
	bh=CcmMK+7uGLsdfgnsdfkjlfnbkljadfnbkjdfgnasfasndkfjhbaksjdffbgvdnafghfgdfghdMA=
Authentication-Results: mail.domain.de;
	dmarc=pass (p=NONE sp=NONE) smtp.from=domain.de header.from=domain.de;
	dkim=pass header.d=domain.de;
        spf=pass (sender IP is ::1) smtp.mailfrom=sender@domain.de
 smtp.helo=webmail.domain.de
Received-SPF: pass (mail.domain.de: connection is authenticated)
MIME-Version: 1.0
Date: Sat, 16 Sep 2023 22:13:24 +0200
To: consume@domain.de, sender@domain.de
Subject: TESTMAIL2
Message-ID: <78cc7407ab8edf35f70c250fc0b42683@domain.de>
X-Sender: sender@domain.de
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<p><img src=3D"https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg" =
alt=3D"" width=3D"500" height=3D"540" /></p>
</body></html>
```

The pdf file generated by paperless:

[2023-09-16 TESTMAIL2_geschwärzt.pdf](https://github.com/paperless-ngx/paperless-ngx/files/12641514/2023-09-16.TESTMAIL2_geschwarzt.pdf)

The gotenberg config in the docker-compose.yml is
```
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--api-timeout=1000s"
      - "--chromium-disable-web-security=true"
      - "--chromium-ignore-certificate-errors=true"

```

### Steps to reproduce

1. Let paperless-ngx consume an .eml file with valid html and at least one <img> tag
2. View final pdf

### Webserver logs

```bash
-
```

### Browser logs

```bash
-
```

### Paperless-ngx version

1.17.4

### Host OS

Raspbian 10 on Raspberry Pi4 arm64

### Installation method

Docker - official image

### Configuration changes

-

### Other

-
