### ISSUE TITLE
[BUG] Insufficient permissions when using bind mounts with rootless Docker installation

### ISSUE THREAD

**Issue by MxtOUT** [paperless-ngx/paperless-ngx#4242]
### Description

Setting up paperless with the rootless Docker installation method and using bind mounts instead of volumes fails at `docker compose run --rm webserver createsuperuser`:

```shell
[+] Creating 3/3
 ✔ Container paperless-gotenberg-1  Created                                                                                                                                              0.3s 
 ✔ Container paperless-broker-1     Created                                                                                                                                              0.3s 
 ✔ Container paperless-tika-1       Created                                                                                                                                              0.2s 
[+] Running 3/3
 ✔ Container paperless-tika-1       Started                                                                                                                                              1.3s 
 ✔ Container paperless-gotenberg-1  Started                                                                                                                                              1.3s 
 ✔ Container paperless-broker-1     Started                                                                                                                                              1.3s 
Paperless-ngx docker container starting...
Creating directory /usr/src/paperless/data/index
mkdir: cannot create directory ‘/usr/src/paperless/data/index’: Permission denied
```

This is a follow-up issue to #4191, where a similar bug, that was encountered when using volumes, was reported.
The fix of this issue in #4225 doesn't appear to affect bind mounts though, only volumes.

I made sure that I have the proper permissions in the directory where I  bind mount directories, as an `ls -al` shows:
```
total 20
drwxr-xr-x 2 pi pi 4096 Sep 22 21:42 .
drwxr-xr-x 8 pi pi 4096 Sep 22 21:42 ..
-rw-r--r-- 1 pi pi  408 Sep 22 21:23 docker-compose.env
-rw-r--r-- 1 pi pi 2825 Sep 22 21:37 docker-compose.yml
-rw-r--r-- 1 pi pi   31 Sep 15 15:38 .env
```

`id -u pi` and `id -g pi` are both `1000` and "pi" is also the currently logged in user.

I tried to trace down the issue, but couldn't locally replicate the GitHub action that builds the Docker image due to `npm` (inside the image) not finding a Python installation.

### Steps to reproduce

1. Follow the installation steps for a rootless Docker installation using the official Docker image with files at the end of this post.
2. At `docker compose run --rm webserver createsuperuser`, the aforementioned error is being thrown.
3. Observe that the directories `consume/`, `data/`, `/export`, and `/media` are being created in the correct location with the correct permissions, but they are empty.

`docker-compose.yml` (I removed the volume declarations under `volumes` and replaced them with bind mounts under `services.webserver.volumes`. Also, I checked with the `dev` paperless image, same result):
```yml
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    user: 1000:1000
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
```

`docker-compose.env`:
```
USERMAP_UID=1000
USERMAP_GID=1000
```

`.env`:
```
COMPOSE_PROJECT_NAME=paperless
```

### Webserver logs

```bash
Doesn't start
```

### Paperless-ngx version

1.17.4

### Host OS

Raspberry Pi `arm64`

### Installation method

Docker - official image

### Configuration changes

Changed volumes to bind mounts
