### ISSUE TITLE
[BUG] API token request unusable when using PAPERLESS_AUTO_LOGIN_USERNAME

### ISSUE THREAD

**Issue by plu** [paperless-ngx/paperless-ngx#5090]
### Description

When I enable the auto login feature, some of the requests to the API return 403 with `{"detail":"CSRF Failed: CSRF cookie not set."}`. I cannot say for sure, but if feels like any request that would modify data fails this way.

### Steps to reproduce

`docker-compose.yml`
```yaml
version: "3.4"
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.1.3
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      PAPERLESS_ADMIN_MAIL: johannes@plunien.com
      PAPERLESS_ADMIN_PASSWORD: secret
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_AUTO_LOGIN_USERNAME: admin
    ports:
      - "8000:8000"
  redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
```

Steps to reproduce:
```shell
# SUCCESS
curl 'http://localhost:8000/api/correspondents/'
# FAILURE
curl -XPOST -H "Content-Type: application/json" --data-binary '{"matching_algorithm": 6, "name": "Test"}' 'http://localhost:8000/api/correspondents/'
```

### Webserver logs

```bash
[2023-12-23 09:42:45,270] [WARNING] [django.request] Forbidden: /api/correspondents/
```

### Paperless-ngx version

2.1.3

### Host OS

docker

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
