### ISSUE TITLE
[BUG] External Auth for API is enabled by default even in 2.4.3

### ISSUE THREAD

**Issue by andi0b** [paperless-ngx/paperless-ngx#5651]
### Description

Currently paperless-ngx (2.4.3) accepts external authentication also on API requests.

I've seen this was an issue in 2.4.0 and was supposedly fixed in 2.4.1, but I can still reproduce this behaviour.

In my case paperless runs behind a reverse proxy with external authentication and some paths are whitelisted from authentication (/api/, /share/ and /favicon.ico).

It would be really great if external authentication for API endpoints would be an opt-in and not enabled by default.

I'm now looking into removing the headers from the reverse proxy, to also prevent issues like that in the future. But for now I think this is a bug that should be investigated. Especially because the release notes for 2.4.1 say that this behaviour was changed.

edit: I'm running `ghcr.io/paperless-ngx/paperless-ngx:2.4.3`, I hope this is the "official image".
edit2: exact image reference: `ghcr.io/paperless-ngx/paperless-ngx@sha256:839cabc0c5859a844c72940468e700f668bb59c16743fd9e81d5e21845488a85`
edit3: it's running on ARM64, maybe this is relevant
edit4: it's all 2.4.x versions, I accidentally wrote 1.4.x

### Steps to reproduce

1. Set env vars:
```yaml
  - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
    value: "true"
  - name: PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME
    value: "HTTP_X_AUTH_REQUEST_EMAIL"
```

2. HTTP request to paperless
```
curl https://paperless/api/correspondents/ --header "x-auth-request-email: valid-user@example.com"

{"count":22,"next":null,"previous":null,"all":[18,12,19,10,9,4,5,20,21,1 ....
```

### Webserver logs

```bash
nothing in logs regarding this issue
```

### Paperless-ngx version

2.4.3

### Host OS

openSUSE MicroOS ARM64

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by andi0b** [comment]
Maybe useful for other people using nginx or ingress-nginx, that's how I could block the headers leaking though:

My external auth header is `X-Auth-Request-User`, replace it with your header

set this in location: 
```
proxy_set_header X-Auth-Request-Email "";
```
<details>
  <summary>full example for the unauthenticated kubernetes ingress:</summary>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unauthenticated
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Auth-Request-User "";
      proxy_set_header X-Auth-Request-Email "";
spec:
  rules:
    - host: paperless.example.com
      http:
        paths:
          - path: /favicon.ico
            pathType: Exact
            backend:
              service:
                name: paperless-main
                port:
                  number: 8000
          - path: /share/
            pathType: Prefix
            backend:
              service:
                name: paperless-main
                port:
                  number: 8000
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: paperless-main
                port:
                  number: 8000
  tls:
    - hosts:
        - paperless.example.com
      secretName: paperless-tls
```
</details>
