### ISSUE TITLE
[BUG] CSRF Issue for API-POST-Requests on http://localhost

### ISSUE THREAD

**Issue by hahrens** [paperless-ngx/paperless-ngx#5827]
### Description

I'm unable to use the Paperless-API on localhost; think that's a bug. I've installed/started a fresh container and still get the CSRF error. I already played with [PAPERLESS_CSRF_TRUSTED_ORIGINS](https://docs.paperless-ngx.com/configuration/#PAPERLESS_CSRF_TRUSTED_ORIGINS) and [PAPERLESS_ALLOWED_HOSTS](https://docs.paperless-ngx.com/configuration/#PAPERLESS_ALLOWED_HOSTS) trying some values, but no success.

I also tried to use port 80 instead of 8000 and fake-map a domain (/etc/hosts) with the same error.

I dont know if thats a problem that affects live instances with real domain-mappings and/or https. But i think http://localhost should work too. 

### Steps to reproduce

To Reproduce:
I use the Install-Script on my local machine with this settings (Copy+Pasted from the Install-Script-Summary).
`bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"`

-----

Target folder: paperless-api-test
Consume folder: paperless-api-test/consume
Media folder: Managed by docker
Data folder: Managed by docker
Database folder: Managed by docker

URL: http://localhost:8000
Port: 8000
Database: postgres
Tika enabled: no
OCR language: deu
User id: 501
Group id: 20

Paperless username: admin
Paperless email: admin@localhost

-----

After that i start the container with 
`cd paperless-api-test`
`docker compose up`

Then, for any reason, my created user does not work. So i had to create a new one
`docker compose run --rm webserver createsuperuser`

Now login with this user (or the created one from install script) and create an api token (top right -> user-icon -> profile).

Use an API-Client or CURL to send a POST-Request:
```
curl --request POST \
  --url http://localhost:8000/api/document_types \
  --header 'Accept: application/json' \
  --header 'Authorization: Token <YOUR_TOKEN_HERE>' \
  --header 'Content-Type: application/json' \
  --data '{
    "name": "test-doc",
    "match": "",
    "matching_algorithm": 0,
    "is_insensitive": false,
    "is_inbox_tag": false,
    "set_permissions": {
       "view": {
         "users": [1],
         "groups": []
       },
       "change": {
         "users": [1],
         "groups": []
       }
    }
}'
```

-----

Just for documentation, here the contents of my install-script-generated docker-compose.env:
```
PAPERLESS_URL=http://localhost:8000
USERMAP_UID=501
USERMAP_GID=20
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY=<SOME_RANDOM_CODE>
```

docker-compose.yml
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

### Webserver logs

```bash
paperless-webserver-1  | [2024-02-19 23:25:25,531] [WARNING] [django.security.csrf] Forbidden (CSRF cookie not set.): /api/document_types
```

### Paperless-ngx version

2.5.3

### Host OS

MacOS / Docker Container

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
