### ISSUE TITLE
[BUG] Importing Thousands of PDFs with 20 Workers, Redis Flushdb Fixes Issue?

### ISSUE THREAD

**Issue by cmoski** [paperless-ngx/paperless-ngx#6508]
### Description

First off, love this project! I've been using it for personal use for a long time, and spun it up for an absolutely crazy request that a client of mine ran into..

We had a requirement to import around 1.8 million PDFs into Paperless. Crazy, I know. I ran into an issue where ingesting PDFs would come to a stop, all existing jobs would fail (saying that they couldn't find the PDF) and it would just continue to fail for a long time. The only fix was to docker-compose down, rm dump.rdb and docker-compose up to get everything started again.

I believe this bug may be a threading issue or race condition, with different worker schedules the same file multiple times, as when everything fell apart the files that it claimed didn't exist were already processed. There was just so many failures that it couldn't get through them all -- around 2-3k.

Edit: The other thing after filing I thought of that may be relevant was that I had APERLESS_CONSUMER_RECURSIVE set to True, so there could be some interaction there.

**Here are all the gory details:** 

So, to furnish this I configured an Ubuntu machine running: 

- [docker-compose.postgres-tika.yml](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.postgres-tika.yml)
- Latest version on docker hub as of this writing

I set the following environment variables, after creating a 48 core VM with around 24 GB of RAM. I wanted to reduce file duplication as there were 1.8 mil, so I set PAPERLESS_OCR_SKIP_ARCHIVE_FILE and speed up processing, so I increased the worker count to a level where processor usage was just about 70%.

docker-compose.env:
```
COMPOSE_PROJECT_NAME=paperless
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_OCR_LANGAUGE=eng
PAPERLESS_TASK_WORKERS=20
PAPERLESS_OCR_SKIP_ARCHIVE_FILE=with_text
```
docker-compose.yml:
```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /home/administrator/paperless-ngx/redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - /home/administrator/paperless-ngx/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /home/administrator/paperless-ngx/data:/usr/src/paperless/data
      - /home/administrator/paperless-ngx/media:/usr/src/paperless/media
      - /home/administrator/paperless-ngx/export:/usr/src/paperless/export
      - /home/administrator/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    logging:
      options:
        max-size: "4k"

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    logging:
      options:
        max-size: "4k"
  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
    logging:
      options:
        max-size: "4k"

```

I set up all of the directories to mount to the filesystem, and I exposed /home/administrator/paperless-ngx/consume via an SMB share so that I could drop my 1.8 million PDF files directly into the system.

I had to make one change to the postgres config, and that was:
`max_connections = 1000 `

Otherwise, during the 20 worker import, postgres would fail with too many connections.

I started ingesting my files, and I had a rate of around 222 per minute. When I hit around file 5k or so I noticed that all of the file transfers started failing and the rate dropped to 0.

After some "hulk smash no code debugging", the only thing that solved the issue  was downing the container and removing dump.rdb. After that, although the fails were still there, the files started processing again successfully. Dismissing the errors cleared out all the thousands of failures on the UI.

Script to do that dropped on Crontab every 30 minutes successfully worked around the problem:
```
#!/bin/bash

# Set the PATH explicitly to ensure all command locations are known
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Define the log file where all outputs will be directed
LOGFILE=/home/administrator/paperless-ngx/cron/log/restart-container.log

# Redirect all output and errors to the logfile
exec > $LOGFILE 2>&1

# Function to add a timestamp to log messages
log() {
    echo "$(date +"%Y-%m-%d %T") - $1"
}

# Exit immediately if a command exits with a non-zero status.
set -e

# Change to the directory containing the Docker Compose file
log "Changing to the directory containing the Docker Compose file."
cd /home/administrator/paperless-ngx

# Stop and remove containers, networks, images, and volumes
log "Shutting down Docker Compose services..."
docker compose down

# Check if the Redis dump file exists and remove it
REDIS_DUMP_FILE="/home/administrator/paperless-ngx/redisdata/dump.rdb"
if [ -f "$REDIS_DUMP_FILE" ]; then
    log "Removing Redis data file at $REDIS_DUMP_FILE..."
    rm "$REDIS_DUMP_FILE"
else
    log "No Redis dump file found at $REDIS_DUMP_FILE."
fi

# Start the Docker Compose services
log "Starting Docker Compose services..."
docker compose up -d

log "Operations completed successfully."
```

### Steps to reproduce

1. Set up a docker-compose instance
2. Share out the consume directory via samba
3. Set the worker count to 20
4. Set the Postgres Max connection count to 1000 (doesn't need to be this high, but hey.. why not?)
6. Dump in around 60,000 PDFs (realistically a few thousand would do.. we only got to 60k before the problem started, and only 5k were ingested..)
7. Observe all jobs start failing around 5,000 files ingested
8. Tear down the docker-compose, remove the redis dump, and restart.. Things start working again!
9. During the import operation the web interface became totally unusable

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

Latest

### Host OS

Ubuntu 24.04

### Installation method

Docker - official image

### Configuration changes

```
COMPOSE_PROJECT_NAME=paperless
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_OCR_LANGAUGE=eng
PAPERLESS_TASK_WORKERS=20
PAPERLESS_OCR_SKIP_ARCHIVE_FILE=with_text
```
Postgres:
`max_connections = 1000 
`

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
