### ISSUE TITLE
Paperless-ngx and IPV6

### ISSUE THREAD

**Issue by Johnnie390** [paperless-ngx/paperless-ngx#6546]
### Description

Excerpt from docker ps
cde26c0dab4f   ghcr.io/paperless-ngx/paperless-ngx:latest   "/sbin/docker-entryp…"   2 hours ago   Up 22 minutes (unhealthy)   0.0.0.0:8000->8000/tcp 
The above happens when IPV6 is specifically disabled.
When IPV6 is enabled, paperless-ngx works, i.e. I can access paperless-ngx from localhost:8000.
I am running Debian with a 6.8.x kernel.
I do NOT want IPV6 on my system.
I have read previous posts related to the abovementioned problem, but am none the wiser.

### Steps to reproduce

paperless-ngx installed via - 
bash -c "$(curl --location --silent --show-error https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"

### Webserver logs

```bash
.
.
.
2024-05-02 07:37:01,448 WARN exited: gunicorn (exit status 1; not expected)
2024-05-02 07:37:02,451 INFO spawned: 'gunicorn' with pid 7668
[2024-05-02 09:37:03 +0200] [7668] [INFO] Starting gunicorn 21.2.0
[2024-05-02 09:37:03 +0200] [7668] [ERROR] Retrying in 1 second.
2024-05-02 07:37:04,311 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2024-05-02 09:37:04 +0200] [7668] [ERROR] Retrying in 1 second.
[2024-05-02 09:37:05 +0200] [7668] [ERROR] Retrying in 1 second.
[2024-05-02 09:37:06 +0200] [7668] [ERROR] Retrying in 1 second.
[2024-05-02 09:37:07 +0200] [7668] [ERROR] Retrying in 1 second.
[2024-05-02 09:37:08 +0200] [7668] [ERROR] Can't connect to ('::', 8000)
2024-05-02 07:37:08,489 WARN exited: gunicorn (exit status 1; not expected)
2024-05-02 07:37:09,493 INFO spawned: 'gunicorn' with pid 7706
[2024-05-02 09:37:10 +0200] [7706] [INFO] Starting gunicorn 21.2.0
[2024-05-02 09:37:10 +0200] [7706] [ERROR] Retrying in 1 second.
.
.
```

### Paperless-ngx version

The latest, as pulled by docker - 2.7.2

### Host OS

Debian

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by ignoreigor** [comment]
Hi,

have a look in the manual: https://docs.paperless-ngx.com/configuration/#docker 
[PAPERLESS_BIND_ADDR](https://docs.paperless-ngx.com/configuration/#PAPERLESS_BIND_ADDR) defaults to [::], any IP-address including IPv6. You'll have to set the bind address to 

`PAPERLESS_BIND_ADDR: 0.0.0.0`

or any other specific ipv4.

**Comment by Johnnie390** [comment]
Tried what you suggested.
With IPV6 disabled and my docker-compose.env looking like this - 

USERMAP_UID=1001
USERMAP_GID=1001
PAPERLESS_TIME_ZONE=Europe/Brussels
PAPERLESS_OCR_LANGUAGE=eng
PAPERLESS_SECRET_KEY='COOd^x>xPX.oNWAfU1@8,!<i~#(]xaWeJbrA}6S@He.dDf{7$,LiXO<fm&sbb}/*'
PAPERLESS_BIND_ADDR=0.0.0.0
It is not working => 
 ghcr.io/paperless-ngx/paperless-ngx:latest   "/sbin/docker-entryp…"   4 hours ago   Up 2 minutes (unhealthy)   0.0.0.0:8000->8000/tcp   paperless-webserver-1

**Comment by ignoreigor** [comment]
I did it in the yaml-file:
```
webserver:
  environment:
    PAPERLESS_BIND_ADDR: 0.0.0.0
```

**Comment by stumpylog** [comment]
This is exactly what the bond address configuration exists for, as stated above and is not a bug with paperless.

**Comment by Johnnie390** [comment]
@ ignoreigor  Could you please post your docker-compose.yaml file here.
I have PAPERLESS_BIND_ADDR**=**0.0.0.0 as per the documentation.
Now I am confused as to the _EXACT_ syntax of this statement.
I am travelling at the moment and will not be able to verify all of this until tomorrow afternoon.

**Comment by Johnnie390** [comment]
It would seem BOLD text is not working.
Here is my statement as coded in the yaml file again - PAPERLESS_BIND_ADDR=

**Comment by ignoreigor** [comment]
You'll have to use colons instead of equals

```
...
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
        - "8001:8000"
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_BIND_ADDR: 0.0.0.0
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
...

```
