### ISSUE TITLE
[BUG] Webserver won't start after update with PAPERLESS_OCR_LANGUAGES

### ISSUE THREAD

**Issue by petarmarj** [paperless-ngx/paperless-ngx#6591]
### Description

Having these two env variables in docker-compose.yml for webserver causes issues after updating to 2.8.0:

```
      PAPERLESS_OCR_LANGUAGE: deu fra eng
      LC_ALL: de_CH.UTF-8
```

Problem disappeared after I removed these two lines. My docker-compose.yml now looks like this:

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./redisdata:/data

  db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    ports:
      - "33060:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.8.1
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8765:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIME_ZONE: Europe/Zurich

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
     # - "--chromium-disable-javascript=true"
     # - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
```

### Steps to reproduce

1. Have the mentioned env variables in webservices part of docker-compose
2. Change version manually from `image: ghcr.io/paperless-ngx/paperless-ngx:2.7.1` to `image: ghcr.io/paperless-ngx/paperless-ngx:2.8.0`
3. Compose up

### Webserver logs

```bash
System check identified 1 issue (0 silenced).
bash: warning: setlocale: LC_ALL: cannot change locale (de_CH.UTF-8)
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
bash: warning: setlocale: LC_ALL: cannot change locale (de_CH.UTF-8)
Waiting for MariaDB to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  No migrations to apply.
Running Django checks
SystemCheckError: System check identified some issues:

ERRORS:
?: The selected ocr language deu fra eng is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.

System check identified 1 issue (0 silenced).
```
```


### Browser logs

_No response_

### Paperless-ngx version

2.8.0

### Host OS

x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

docker-compose.yml

### Other

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
