### ISSUE TITLE
[BUG] Healthcheck error with 1.7.0-rc1

### ISSUE THREAD

**Issue by Profex** [paperless-ngx/paperless-ngx#696]
### Description

After upgrade to 1.7.0-rc1 the docker healthcheck is no longer working

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]

I assume this is connected to https://github.com/paperless-ngx/paperless-ngx/pull/674

### Expected behavior

Healthcheck working, to see that container is alive

### Steps to reproduce

Update to 1.7.0-rc1 using healthcheck as documented in https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.portainer.yml

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

### Webserver logs

```bash
[2022-04-12 10:36:56,641] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
[2022-04-12 10:36:56,673] [WARNING] [django.request] Bad Request: /
```

### Paperless-ngx version

1.7.0-rc1

### Host OS

Synology DSM 7.1

### Installation method

Docker

### Browser

Edge

### Configuration changes

No changes in docker compose regarding healthcheck, using standard healthcheck configuration as documented

**Comment by gador** [comment]
Cannot reproduce. 

docker-compose.env:
```
PAPERLESS_DEBUG=true
PAPERLESS_CONSUMER_ENABLE_BARCODES=True
```
docker-compose.yml:
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:beta
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379

volumes:
  data:
  media:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
```
Notice: The network is due to OpenVPN and overlapping subnets. Shoudn't have any influence on the healthcheck.

Output of docker ps:
```
docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                   PORTS                                       NAMES
71a1cc80155e   ghcr.io/paperless-ngx/paperless-ngx:beta   "/sbin/docker-entryp…"   3 minutes ago   Up 3 minutes (healthy)   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   paperless-webserver-1
e73a6f385a98   redis:6.0                                  "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes             6379/tcp                                    paperless-broker-1
```

Maybe you have `PAPERLESS_URL`, `PAPERLESS_CSRF_TRUSTED_ORIGINS`, `PAPERLESS_CORS_ALLOWED_HOSTS` or `PAPERLESS_ALLOWED_HOSTS` set somewhere?
