### ISSUE TITLE
[BUG] Error with OIDC authentification via Authentik

### ISSUE THREAD

**Issue by JannikWilhelm** [paperless-ngx/paperless-ngx#7484]
### Description

Trying to create an external SSO using Authentik with these tutorials:
- https://chochol.io/en/software/authentik-single-sign-on-configuration-for-paperless-ngx/
- https://docs.goauthentik.io/integrations/services/paperless-ngx/
However, when trying to login to Paperless using the SSO (either in the Login screen or in the account settings to connect an existing account), the process errors out.
The authentik site loads, but on the redirect to paperless an error Page is shown: 
![grafik](https://github.com/user-attachments/assets/0e62d4d1-9b07-4bcb-ab42-4e6ed4996286)

### Steps to reproduce

1. create authentik provider and application
2. create Settings for paperless in docker-compose.env File
3.  docker-compose.env file contents: 
```yaml

PAPERLESS_URL=https://paperless.mydomain.de
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY='[redacted]'

environment:
    PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect": {"APPS": [{"provider_id": "authentik","name": "Authentik SSO","client_id": "[redacted]","secret": "[redacted]","settings": { "server_url": "https://auth.mydomain.de/application/o/paperless/.well-known/openid-configuration"}}],  "OAUTH_PKCE_ENABLED": "True"}}'

``` 

Redirect URL in authentik: https://paperless.mydomain.de/accounts/oidc/authentik/login/callback/

<details><summary>docker-compose.yml contents</summary>

```yaml
# Docker Compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - /home/paperless-ngx/paperless-ngx/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /home/paperless-ngx/paperless-ngx/data:/usr/src/paperless/data
      - /home/paperless-ngx/paperless-ngx/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/paperless-ngx/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=[redacted]

volumes:
  redisdata:
``` 

<p>

</p>
</details> 

### Webserver logs

```bash
no related log entries. after error occurred, the latest log entry was from about 2 minutes prior:

webserver-1         | [2024-08-17 19:10:00,018] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
webserver-1         | [2024-08-17 19:10:00,027] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[ab8eb0d0-7ec0-4364-afd9-187712854402] received
webserver-1         | [2024-08-17 19:10:00,173] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[ab8eb0d0-7ec0-4364-afd9-187712854402] succeeded in 0.13831543084234s: 'No new documents were added.'
```

### Paperless-ngx version

2.11.4

### Host OS

Docker-Compose on Alpine x86_64

### Installation method

Docker - official image

### Browser

Firefox, Chrome

### Configuration changes

docker-compose.yml and docker-compose.env already above. Changes in docker-compose.yml: added cloudflare tunnel for global access. Changes in docker-compose.env: added OIDC config

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
