### ISSUE TITLE
[BUG] Login fails due to CSRF issue - (Origin checking failed - null does not match any trusted origins.)

### ISSUE THREAD

**Issue by cjd** [paperless-ngx/paperless-ngx#817]
### Description

This is likely related to bug #712 but slightly different.
After setting up PAPERLESS_URL login is failing with "CSRF verification failed. Request aborted."
Looking at the log output from paperless I see:
[2022-04-27 08:37:27,580] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - null does not match any trusted origins.): /paperless/accounts/login/

Note that it is reporting 'null' as the host rather than the actual hostname (or server_name)
I am running paperless-ngx from within docker but on a different docker stack than my reverse proxy so proxy is via host interface IP rather than via localhost

== relevant section from  docker-compose.yml section ==
```
    environment:
      LANG: en_AU.UTF-8
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_TIME_ZONE: Australia/Sydney
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_FORCE_SCRIPT_NAME: /paperless
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_FILENAME_FORMAT: "{correspondent}/{created_year}/{created_year}-{created_month}-{created_day}_{correspondent}-{title}"
      PAPERLESS_SECRET_KEY: thisisnottherealsecretimnotthatsilly
      PAPERLESS_FILENAME_DATE_ORDER: YMD
      PAPERLESS_DATE_ORDER: DMY
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
      PAPERLESS_URL: https://home.xxxxxxxxx.com
```
== end docker-compose.yml ==

== relevant nginx reverse-proxy section ==
```
location /paperless/ {
    proxy_pass http://192.168.0.10:8000/;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_redirect off;
    proxy_read_timeout 86400;

    # Websocket
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    client_max_body_size 50M;
```
== end nginx config ==

### Steps to reproduce

1. Upgrade to 1.7.0
2. Add PAPERLESS_URL
3. Attempt login

### Webserver logs

```bash
[2022-04-27 08:37:27,580] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - null does not match any trusted origins.): /paperless/accounts/login/
```

### Paperless-ngx version

1.7.0

### Host OS

debian 11

### Installation method

Docker

### Browser

Chrome
