### ISSUE TITLE
[BUG] Session authentication to API from Web UI not working when behind reverse proxy 

### ISSUE THREAD

**Issue by SriRamanujam** [paperless-ngx/paperless-ngx#846]
### Description

When Paperless is configured to sit behind an authenticating reverse proxy, Django is not accepting the browser's session cookie as proper authorization for `/api` requests. It then tries to fall back to basic auth, but even entering credentials there does not work.

### Steps to reproduce

1. Configure authenticating reverse proxy in front of paperless that uses a header like `X-Forwarded-User` to send the username to the backend.
2. Configure paperless-ng as follows to enable integration with authenticating reverse proxy (environment variables):
  ```yaml
              - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
                value: 'True'
              - name: PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME
                value: HTTP_X_FORWARDED_USER
              - name: PAPERLESS_URL
                value: 'https://paperless-ng.example.com'
              - name: PAPERLESS_ALLOWED_HOSTS
                value: '192.168.11.3,localhost'
  ```
3. Browse to `https://paperless-ng.example.com` and login via the authenticating reverse proxy
4. Observe that the browser's basic auth dialog pops up. Whatever credentials you enter, the browser will not accept them. If you click cancel, observe that the requests to all `/api` endpoints made result in 401 Unauthorized.

### Webserver logs

```bash
[2022-04-29 22:22:04,522] [WARNING] [django.request] Unauthorized: /api/saved_views/
[2022-04-29 22:22:04,530] [WARNING] [django.request] Unauthorized: /api/remote_version/
[2022-04-29 22:22:04,544] [WARNING] [django.request] Unauthorized: /api/statistics/
```

### Paperless-ngx version

1.7.0

### Host OS

Container host is Fedora 35. But it's the Docker image, so.

### Installation method

Docker

### Other

I already had a pre-existing user with a valid username and password configured prior to trying this authenticated reverse proxy configuration. I have everything set up such that the usernames are the same between the paperless internal user and the username passed in via `X-Forwarded-User`. I'm not sure if this is tripping up some edge case logic in the session auth flow.
