### ISSUE TITLE
[BUG] Problem with method PATCH

### ISSUE THREAD

**Issue by dar-tal** [paperless-ngx/paperless-ngx#9108]
### Description

Hello! 

I have two Paperless instances [same paperless versions - aligned by pull, same docker version on servers, yml files almost identical, also same OS - Debian 12], and on one server 'PATCH' API method doesn't work. I get timeout as shown in the log file. Although when I enter URL via browser, I get: "HTTP 200 OK Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS". Where could be the problem? GET and another methods works.

[log.txt](https://github.com/user-attachments/files/18795276/log.txt)

### Steps to reproduce

1. Install Paperless from official docker images
2. Check the problem ;-)

### Webserver logs

```bash
[2025-02-14 03:05:03,975] [DEBUG] [paperless.tasks] Training data unchanged.
[2025-02-14 04:05:00,408] [DEBUG] [paperless.classifier] Gathering data from database...
[2025-02-14 04:05:04,192] [INFO] [paperless.classifier] No updates since last training
[2025-02-14 04:05:04,194] [DEBUG] [paperless.tasks] Training data unchanged.
[2025-02-14 05:05:00,107] [DEBUG] [paperless.classifier] Gathering data from database...
[2025-02-14 05:05:03,881] [INFO] [paperless.classifier] No updates since last training
[2025-02-14 05:05:03,884] [DEBUG] [paperless.tasks] Training data unchanged.
[2025-02-14 06:05:00,412] [DEBUG] [paperless.classifier] Gathering data from database...
[2025-02-14 06:05:04,196] [INFO] [paperless.classifier] No updates since last training
[2025-02-14 06:05:04,199] [DEBUG] [paperless.tasks] Training data unchanged.
[2025-02-14 07:05:00,117] [DEBUG] [paperless.classifier] Gathering data from database...
[2025-02-14 07:05:03,989] [INFO] [paperless.classifier] No updates since last training
[2025-02-14 07:05:03,992] [DEBUG] [paperless.tasks] Training data unchanged.
#
```

### Browser logs

```bash

```

### Paperless-ngx version

2.14.7

### Host OS

Debian 12

### Installation method

Docker - official image

### System status

```json

```

### Browser

Curl / Chrome

### Configuration changes

# docker-compose.yml on a not working paperless

```
services:
  broker:
    image: docker.io/library/redis:7
    restart: always
    volumes:
      - ./redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: UzXXXXXXXXXXX3

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "80:8000"
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      - ./scripts:/usr/src/paperless/scripts
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: UzXXXXXXXXXXXX3
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless/scripts/post-consumption.sh
      PAPERLESS_APP_LOGO: /logo/logo_btn.svg

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: always

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: always

```

# docker-compose.yml on a **working paperless**

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: EtXXXXXXXXXXXXXXXG

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "80:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      - ./scripts:/usr/src/paperless/scripts
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPASS: EtXXXXXXXXXXXXXXXG
      PAPERLESS_DBUSER: paperless
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless/scripts/post-consumption.sh
      ###PAPERLESS_APPS: allauth.socialaccount.providers.google
      #PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"google": {"APP": {"client_id": "660428396416-n8vXXXXXXXXXXXXXXXXXXXntent.com", "secret": "GOXXXXXXXXXXXXV"}, "SCOPE": ["openid", "email", "profile"]}}'
      ###PAPERLESS_SOCIAL_AUTO_SIGNUP: false
      ###PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: false
      ###PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: false

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
  redisdata:

```

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
