### ISSUE TITLE
[BUG] docker-entrypoint.sh: no such file or directory: unknown on Synology NAS since 2.14.2

### ISSUE THREAD

**Issue by Riza-Aslan** [paperless-ngx/paperless-ngx#9206]
### Description

I've tried to deploy the docker-compose stack via portainer on my Synology NAS (DS3622xs+, x86). First i've tried it with the latest-tag but I got this issue when starting up the paperless container:

`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/sbin/docker-entrypoint.sh": stat /sbin/docker-entrypoint.sh: no such file or directory: unknown`

The other container startet without an issue. Then I tried to use v. 2.13 and it worked. Now i've tried every version and it worked until 2.14.1. With Version 2.14.2 the issue began.

### Steps to reproduce

Use my docker-compose.yml on a Synology NAS (DS3622xs+, x86) via portainer

### Webserver logs

```bash
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/sbin/docker-entrypoint.sh": stat /sbin/docker-entrypoint.sh: no such file or directory: unknown
```

### Browser logs

```bash

```

### Paperless-ngx version

2.14.2

### Host OS

Synology NAS (DS3622xs+, x86)

### Installation method

Docker - official image

### System status

```json

```

### Browser

Chrome 133.0.6943.127

### Configuration changes

```
services:
    broker:
        container_name: paperless-redis
        image: redis:7
        volumes:
            - /volume3/docker/Paperless/redisdata:/data
        restart: unless-stopped
        user: "0:0"
        sysctls:
            - net.core.somaxconn=511
        cap_add:
            - SYS_RESOURCE
        deploy:
            resources:
                limits:
                    memory: 256M
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 5s
            retries: 3

    db:
        container_name: paperless-db
        image: postgres:16
        # Do not simply upgrade or downgrade, as the database will not load anymore.
        restart: unless-stopped
        volumes:
            - /volume3/docker/Paperless/pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: paperless
            POSTGRES_USER: paperless
            POSTGRES_PASSWORD: my_PW
        deploy:
            resources:
                limits:
                    memory: 512M
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "paperless"]
            interval: 30s
            timeout: 5s
            retries: 3
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"

    webserver:
        container_name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:2.14.2
        restart: unless-stopped
        depends_on:
            - db
            - broker
            - gotenberg
            - tika
        ports:
            - 8010:8000
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - /volume3/docker/Paperless/data:/usr/src/paperless/data
            - /volume3/docker/Paperless/media:/usr/src/paperless/media
            - /volume3/docker/Paperless/export:/usr/src/paperless/export
            - /volume3/docker/Paperless/consume:/usr/src/paperless/consume
        environment:
            PAPERLESS_REDIS: redis://broker:6379
            PAPERLESS_DBHOST: db
            #PAPERLESS_DBUSER: paperless
            PAPERLESS_DBPASS: my_PW
            USERMAP_UID: 0
            USERMAP_GID: 0
            PAPERLESS_OCR_LANGUAGES: deu eng
            PAPERLESS_SECRET_KEY: random_KEY
            PAPERLESS_ALLOWED_HOSTS: "localhost,my_PROXY"
            PAPERLESS_TRUSTED_PROXIES: my_PROXIES
            PAPERLESS_TIME_ZONE: Europe/Berlin
            PAPERLESS_OCR_LANGUAGE: deu
            PAPERLESS_FILENAME_FORMAT: "{{ created_year }}/{{ correspondent }}/{{ title }}"
            PAPERLESS_TIKA_ENABLED: 1
            PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000/
            PAPERLESS_TIKA_ENDPOINT: http://tika:9998
            PAPERLESS_URL: "https://my_PROXY"
            PAPERLESS_EMAIL_HOST: my_MAILSERVER
            PAPERLESS_EMAIL_PORT: 587
            PAPERLESS_EMAIL_HOST_USER: my_USER
            PAPERLESS_EMAIL_FROM: my_MAIL
            PAPERLESS_EMAIL_HOST_PASSWORD: my_PW
            PAPERLESS_EMAIL_USE_TLS: true
            PAPERLESS_EMAIL_USE_SSL: true
        deploy:
            resources:
                limits:
                    memory: 2048M
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"

    db-backup:
        container_name: paperless-db-backup
        image: postgres:16
        volumes:
            - /volume3/docker/Paperless/db-backup:/dump
            - /etc/localtime:/etc/localtime:ro
        environment:
            PGHOST: db
            PGDATABASE: paperless
            PGUSER: paperless
            PGPASSWORD: my_PW
            BACKUP_NUM_KEEP: 10
            BACKUP_FREQUENCY: 7d
        entrypoint: |
            bash -c 'bash -s <<EOF
            trap "break;exit" SIGHUP SIGINT SIGTERM
            sleep 2m
            while /bin/true; do
              pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
              (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
              sleep $$BACKUP_FREQUENCY
            done
            EOF'
        deploy:
            resources:
                limits:
                    memory: 256M
    gotenberg:
        container_name: paperless-gotenberg
        image: gotenberg/gotenberg:8.7
        restart: unless-stopped
        environment:
            CHROMIUM_DISABLE_ROUTES: 1
        command:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"
        deploy:
            resources:
                limits:
                    memory: 512M
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 30s
            timeout: 5s
            retries: 3

    tika:
        container_name: paperless-tika
        image: apache/tika:latest
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 512M

    paperless-ai:
        image: clusterzx/paperless-ai
        container_name: paperless-ai
        restart: unless-stopped
        cap_drop:
        - ALL
        security_opt:
        - no-new-privileges=true
        environment:
        - PUID=0
        - PGID=0
        - PAPERLESS_PORT=${PAPERLESS_PORT:-3000}
        ports:
        - "3000:${PAPERLESS_PORT:-3000}"
        volumes:
        - /volume3/docker/Paperless/ai:/app/data
```

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
