### ISSUE TITLE
[BUG] CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by truthsword** [paperless-ngx/paperless-ngx#9299]
### Description

Logging in with secure HTTPS domain yields: `Forbidden (403) CSRF verification failed. Request aborted.`

Using Nginx Proxy Manager with LE cert for *.charto.one

Searched this site and see similar postings but no clear answer. Thank you for your help.

### Steps to reproduce

1. Docker compose up
2. Enter URL (https://paperless.charto.one) [this URL is not exposed outside my LAN]
3. Enter login credentials

### Webserver logs

```bash
`[2025-03-04 16:34:44,833] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://paperless.charto.one does not match any trusted origins.): /accounts/login/
`
```

### Browser logs

```bash

```

### Paperless-ngx version

2.14.7

### Host OS

Debian Bookworm

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.14.7",
    "server_os": "Linux-6.1.0-31-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 900682375168,
        "available": 699951284224
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1061_workflowactionwebhook_as_json",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://paperless-redis:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2025-03-04T00:00:00.692818-05:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2025-03-04T21:05:00.224340Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox

### Configuration changes

```
# 20250228

# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.

services:
  paperless-redis:
    image: docker.io/library/redis:7
    container_name: paperless-redis
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges=true
    networks:
      - paperless
    volumes:
      - redisdata:/data

  paperless-postgres:
    image: docker.io/library/postgres:15
    container_name: paperless-postgres
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - FOWNER
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges=true
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - paperless
    volumes:
      - pgdata:/var/lib/postgresql/data

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges=true
    env_file: .env
    depends_on:
      - paperless-postgres
      - paperless-redis
      - paperless-gotenberg
      - paperless-tika
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-postgres
      PAPERLESS_DATE_ORDER: MDY
      PAPERLESS_FILENAME_DATE_ORDER: YMD
      PAPERLESS_OCR_MODE: skip_noarchive
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_URL: https://paperless.local.karphos.net # required for reverse proxy
    networks:
      - paperless
    ports:
      - "8204:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume

  paperless-gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    container_name: paperless-gotenberg
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless

  paperless-tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: paperless-tika
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    networks:
      - paperless

networks:
  paperless:

volumes:
  data:
  media:
  pgdata:
  redisdata:
```

```
# 20250304
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=1000
USERMAP_GID=1000

# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
#PAPERLESS_OCR_LANGUAGES=tur ces

###############################################################################
# Paperless-specific settings                                                 #
###############################################################################

# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.

# This is required if you will be exposing Paperless-ngx on a public domain
# (if doing so please consider security measures such as reverse proxy)
PAPERLESS_URL=https://paperless.charto.one

# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
#PAPERLESS_SECRET_KEY=change-me

# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=America/New_York

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=eng

# Set if accessing paperless via a domain subpath e.g. https://domain.com/PATHPREFIX and using a reverse-proxy like traefik or nginx
#PAPERLESS_FORCE_SCRIPT_NAME=/PATHPREFIX
#PAPERLESS_STATIC_URL=/PATHPREFIX/static/ # trailing slash required
```

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
