### ISSUE TITLE
[BUG] SyntaxWarnings from whoosh in logs

### ISSUE THREAD

**Issue by petarmarj** [paperless-ngx/paperless-ngx#9477]
### Description

While debugging my reverse proxy setup for Paperless-NGX, I noticed repeated `SyntaxWarning` messages in the container logs. They originate from the `whoosh` package used by Paperless. These warnings do not currently break anything.

I'm not proficient in Python, so I cannot evaluate if this leads to functional problems, but I wanted to report it for awareness.

System status shows everything is running fine otherwise.

**docker-compose.env**
```env
USERMAP_UID=501
USERMAP_GID=20
PAPERLESS_TIME_ZONE=Europe/Zurich
PAPERLESS_OCR_LANGUAGE=deu 
PAPERLESS_SECRET_KEY=****
DOCKER_MODS=linuxserver/mods:papermerge-multilangocr
PAPERLESS_FILENAME_FORMAT={{ created_year }}/{{ correspondent }}/{{ title }}
PAPERLESS_CONSUMER_ENABLE_BARCODES=true
PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true # enable setting ASN by ASN barcodes
PAPERLESS_CONSUMER_BARCODE_SCANNER=ZXING # switch from pyzbar to zxing for better recognition
PAPERLESS_OCR_MODE=force
PAPERLESS_OCR_CLEAN=clean
PAPERLESS_OCR_DESKEW=true
PAPERLESS_CONSUMER_POLLING=60
PAPERLESS_TASK_WORKERS=2
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
PAPERLESS_OCR_USER_ARGS={"invalidate_digital_signatures": true}
PAPERLESS_URL=https://*****.****.**
```

**docker-compose.yml**
```yml
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ./redisdata:/data

  db:
    image: docker.io/library/mariadb:11
    restart: unless-stopped
    ports:
      - "33060:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:beta
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8765:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      - ./tmp:/tmp/paperless
      - ./tmp2:/tmp
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIME_ZONE: Europe/Zurich
      PAPERLESS_CONSUMER_ENABLE_TAG_BARCODE: 1
      PAPERLESS_CONSUMER_TAG_BARCODE_MAPPING: '{"TAG:(.*)": "\\g<1>"}'
      PAPERLESS_OCR_LANGUAGES: deu 
      

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
```

### Steps to reproduce

1. Install Paperless-NGX using the official Docker setup (see docker-compose setup below).
2. Start the stack with docker compose up.
3. Observe the logs of the paperless-ngx container (docker compose logs paperless-ngx).
4. SyntaxWarnings will appear related to invalid escape sequences in the whoosh package.

### Webserver logs

```bash
paperless-ngx-1  | System check identified no issues (0 silenced).
paperless-ngx-1  | [custom-init] /custom-cont-init.d doesn't exist, nothing to do
paperless-ngx-1  | [init-complete] paperless-ngx docker container init completed in 22 seconds
paperless-ngx-1  | [init-complete] Starting services
paperless-ngx-1  | [svc-flower] Checking if we should start flower...
paperless-ngx-1  | [svc-flower] Not starting flower
paperless-ngx-1  | [INFO] Starting granian (main PID: 189)
paperless-ngx-1  | [INFO] Listening at: http://:::8000
paperless-ngx-1  | [INFO] Spawning worker-1 with PID: 213
paperless-ngx-1  | celery beat v5.4.0 (opalescent) is starting.
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/filters.py:50: SyntaxWarning: invalid escape sequence '\w'
paperless-ngx-1  |   url_pattern = rcompile("""
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/filters.py:148: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Interleaves the results of two or more filters (or filter chains).
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:37: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Given a set of words (or any object with a ``__contains__`` method),
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:224: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Splits words into subwords and performs optional transformations on
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:285: SyntaxWarning: invalid escape sequence '\|'
paperless-ngx-1  |   def __init__(self, delims=u("-_'\"()!@#$%^&*[]{}<>\|;:,./?`~=+"),
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/filters.py:50: SyntaxWarning: invalid escape sequence '\w'
paperless-ngx-1  |   url_pattern = rcompile("""
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/filters.py:148: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Interleaves the results of two or more filters (or filter chains).
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:37: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Given a set of words (or any object with a ``__contains__`` method),
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:224: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Splits words into subwords and performs optional transformations on
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:285: SyntaxWarning: invalid escape sequence '\|'
paperless-ngx-1  |   def __init__(self, delims=u("-_'\"()!@#$%^&*[]{}<>\|;:,./?`~=+"),
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/filters.py:50: SyntaxWarning: invalid escape sequence '\w'
paperless-ngx-1  |   url_pattern = rcompile("""
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/filters.py:148: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Interleaves the results of two or more filters (or filter chains).
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:37: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Given a set of words (or any object with a ``__contains__`` method),
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:224: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Splits words into subwords and performs optional transformations on
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:285: SyntaxWarning: invalid escape sequence '\|'
paperless-ngx-1  |   def __init__(self, delims=u("-_'\"()!@#$%^&*[]{}<>\|;:,./?`~=+"),
paperless-ngx-1  | [2025-03-24 11:02:56,285] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/consume
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/filters.py:50: SyntaxWarning: invalid escape sequence '\w'
paperless-ngx-1  |   url_pattern = rcompile("""
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/filters.py:148: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Interleaves the results of two or more filters (or filter chains).
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:37: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Given a set of words (or any object with a ``__contains__`` method),
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:224: SyntaxWarning: invalid escape sequence '\S'
paperless-ngx-1  |   """Splits words into subwords and performs optional transformations on
paperless-ngx-1  | /usr/local/lib/python3.12/site-packages/whoosh/analysis/intraword.py:285: SyntaxWarning: invalid escape sequence '\|'
paperless-ngx-1  |   def __init__(self, delims=u("-_'\"()!@#$%^&*[]{}<>\|;:,./?`~=+"),
```

### Paperless-ngx version

2.15.0 (beta)

### Host OS

MacOS, x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.15.0",
    "server_os": "Linux-6.10.14-linuxkit-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 2121312247808,
        "available": 1133935968256
    },
    "database": {
        "type": "mysql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0029_mailrule_pdf_layout",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "celery_url": "celery@df24f3637eeb",
        "celery_error": null,
        "index_status": "OK",
        "index_last_modified": "2025-03-24T10:15:16.075630+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2025-03-24T10:05:05.675280Z",
        "classifier_error": null,
        "sanity_check_status": "OK",
        "sanity_check_last_run": "2025-03-24T10:11:53.292054Z",
        "sanity_check_error": null
    }
}
```

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
