### ISSUE TITLE
[BUG] Running container as nonroot in kubernetes fails

### ISSUE THREAD

**Issue by bolsblue** [paperless-ngx/paperless-ngx#9609]
### Description

When running paperless in docker as a nonroot container, startup fails.

This did work in versions below 2.15.0, I guess it has something to do with the switch to s6.

I wonder how one is supposed to run the container without root now?

### Steps to reproduce

```
securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 38580
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

### Webserver logs

```bash
/package/admin/s6-overlay/libexec/preinit: fatal: /run belongs to uid 0 instead of 1000 and we're lacking the privileges to fix it.
s6-overlay-suexec: fatal: child failed with exit code 100
```

### Browser logs

```bash

```

### Paperless-ngx version

2.15.0, 2.15.1

### Host OS

Fedora CoreOS 41.20250315.3.0, kubernetes v1.32.3+k3s1

### Installation method

Docker - official image

### System status

```json

```

### Configuration changes

USERMAP_UID=1000
USERMAP_GID=38580

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.
