### ISSUE TITLE
[BUG] unable to envdir /run/s6/container_environment: No such file or directory

### ISSUE THREAD

**Issue by morremeyer** [paperless-ngx/paperless-ngx#9631]
### Description

I run regular exports of my paperless instance with 

```shell
/usr/local/bin/document_exporter ../export
```

in a Kubernetes CronJob that is otherwise configured exactly as the running paperless instance. 

Since version 2.15.1, this fails with

```
s6-envdir: fatal: unable to envdir /run/s6/container_environment: No such file or directory
```

## Run the container

```shell
docker run --rm -it --entrypoint /bin/bash ghcr.io/paperless-ngx/paperless-ngx:2.15.1
```

## Run the document_exporter in the container

```shell
root@514bc017422d:/usr/src/paperless/src# /usr/local/bin/document_exporter
s6-envdir: fatal: unable to envdir /run/s6/container_environment: No such file or directory
```

### Webserver logs

```bash
Not applicable
```

### Browser logs

```bash
Not applicable
```

### Paperless-ngx version

2.15.0+

### Host OS

Ubuntu 22.04, Podman Machine VM on macOS Sequoia

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.15.0",
    "server_os": "Linux-5.4.0-196-generic-x86_64-with-glibc2.36",
    "install_type": "kubernetes",
    "storage": {
        "total": 4919772684288,
        "available": 903416827904
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0029_mailrule_pdf_layout",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://paperless-redis-headless.paperless.svc.cluster.local:None",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "celery_url": "celery@paperless-78d64c4556-h7fxh",
        "celery_error": null,
        "index_status": "OK",
        "index_last_modified": "2025-04-12T08:00:12.604930+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2025-04-12T06:05:05.979025Z",
        "classifier_error": null,
        "sanity_check_status": "WARNING",
        "sanity_check_last_run": null,
        "sanity_check_error": "No sanity check tasks found"
    }
}
```

### Configuration changes

None

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
You are overriding the entry point.  That's not supported.  Just docker exec document_exporter.

**Comment by morremeyer** [comment]
@stumpylog Thanks for that info! I wasn't aware that is unsupported. My setup runs in Kubernetes, and so far it just worked, so I never bothered to check if it were actually supported.

That being said, there is no way to run a `docker exec`-style command with a Kubernetes CronJob, since any CronJob will start a new container.

Does this mean I have to switch to backing up all volumes explicitly or is there any other way to run the document_exporter that does not require running it manually or from the host?

**Comment by shamoon** [comment]
ChatGPT says:

> ### What are your options?
> 
> #### ✅ **Recommended**: Run a purpose-built one-shot exporter container
> 
> Instead of changing the entrypoint, you can define a CronJob that starts a container **with the default entrypoint**, but adds a command override like this:
> 
> ```yaml
> command: ["/usr/local/bin/document_exporter"]
> ```
> 
> This keeps the s6 init in place but runs your command cleanly. The container will still follow the correct startup sequence.
> 
> Here’s an example `spec` snippet for the Kubernetes CronJob:
> 
> ```yaml
> spec:
>   containers:
>   - name: paperless-export
>     image: ghcr.io/paperless-ngx/paperless-ngx:2.15.1
>     command: ["/usr/local/bin/document_exporter"]
> ```
> 
> This approach ensures s6 is happy, and you still get to run your export logic in a clean, idiomatic way for Kubernetes.
> 
> #### 🛑 Avoid this: Backing up volumes directly
> 
> Backing up volumes may sound like a workaround, but it’s generally brittle and misses app-level logic or cleanup that tools like `document_exporter` perform. Only go this route if all else fails (and it rarely should).

**Comment by morremeyer** [comment]
@shamoon Thanks for checking in! ChatGPT is wrong, unsurprisingly 🤷 

What it proposes is exactly how my CronJob is configured, and what broke with 2.15.0. I could have added that to the initial report, sorry about that. Full config is below.

I already tested all possible configurations of setting the `command` or `args`, but none work, they all either just start paperless (when using `args`), or fail with the error mentioned in the issue (when using `command`, e.g. when executing `manage.py document_exporter ../export`) 

I can happily build my own image for the exporter if there is no supported way to get this to run without a manual exec, but I think ideally that wouldn't be necessary. 

<details>
<summary>Kubernetes CronJob</summary>

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-export-cronjob
  namespace: paperless
spec:
  jobTemplate:
    spec:
      backoffLimit: 6
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: paperless
                    app.kubernetes.io/name: paperless
                topologyKey: kubernetes.io/hostname
          containers:
          - command:
            - /usr/local/bin/document_exporter
            - ../export
            env:
            - name: PAPERLESS_CONSUMER_BARCODE_SCANNER
              value: ZXING
            - name: PAPERLESS_CONSUMER_ENABLE_BARCODES
              value: "true"
            - name: PAPERLESS_CONSUMER_RECURSIVE
              value: "true"
            - name: PAPERLESS_DBHOST
              value: postgres-postgresql.postgres.svc.cluster.local.
            - name: PAPERLESS_DBSSLMODE
              value: disable
            - name: PAPERLESS_ENABLE_NLTK
              value: "false"
            - name: PAPERLESS_FILENAME_FORMAT
              value: '{{ owner_username }}/{{ created_year }}/{{ created_month }}/{{ created }}-{{ correspondent }}-{{ title }}'
            - name: PAPERLESS_OCR_LANGUAGE
              value: deu
            - name: PAPERLESS_OCR_USER_ARGS
              value: '{"invalidate_digital_signatures": true}'
            - name: PAPERLESS_REDIS
              value: redis://paperless-redis-headless.paperless.svc.cluster.local
            - name: PAPERLESS_TIME_ZONE
              value: Europe/Berlin
            - name: PAPERLESS_URL
              value: https://paperless.example.com
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: paperless-secrets
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: paperless-secrets
            image: ghcr.io/paperless-ngx/paperless-ngx:2.15.1
            name: cronjob
            volumeMounts:
            - mountPath: /usr/src/paperless/consume
              name: consume
            - mountPath: /usr/src/paperless/data
              name: data
            - mountPath: /usr/src/paperless/export
              name: export
            - mountPath: /usr/src/paperless/media
              name: media
          terminationGracePeriodSeconds: 30
          volumes:
          - name: consume
            persistentVolumeClaim:
              claimName: paperless-consume
          - name: data
            persistentVolumeClaim:
              claimName: paperless-data
          - name: export
            persistentVolumeClaim:
              claimName: paperless-export
          - name: media
            persistentVolumeClaim:
              claimName: paperless-media
  schedule: 24 1 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
```

</details>
